### ISSUE TITLE
Game UI suddenly vanishes and appear back beyond all reason

### ISSUE THREAD

**Issue by Nikuksis** [beyond-all-reason/Beyond-All-Reason#1003]
UI in game: health/progress bars, marker lines/dots (text remains visible), areas when using area orders are disapearing from time to time in game without any settings being changed.
Healthbar widget/ luaui reload doesnt help.

I assume it begins after enabling devmode and tweaking some map-related settings  (in separate game before).

I guess removing springsettings.cfg (see reset to deault) helped resolve the problem, but im not sure about it.

**Comment by SethDGamre** [comment]
ancient issue, I haven't seen it any time during my time playing BAR. I suggest closing issue.
