### ISSUE TITLE
AMD/Linux specific map extension issue, a gap in left side

### ISSUE THREAD

**Issue by MooseOnTheLoose** [beyond-all-reason/Beyond-All-Reason#1008]
https://cdn.discordapp.com/attachments/554307356360441876/982345882966056970/screen00061.png
https://cdn.discordapp.com/attachments/554307356360441876/982346662129320006/screen00062.png
https://cdn.discordapp.com/attachments/554307356360441876/982347156818116648/screen00063.png

This issue can be reproduced on Twin Lakes Park Redux 1.0 https://springfiles.springrts.com/index.html?type=2&filter=447cd03fadc6018138d524dc38ec9304

It has been tested on an AMD/Linux system (mine) with consistent reproduction, and a Nvidia/Windows system that could not reproduce the error.

The gap can be changed by adjusting gridsize but can not be eliminated. 

The widget is here: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/map_edge_extension2.lua

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8836107/infolog.txt)

**Comment by Beherith** [comment]
On screen61, does it also happen on the right of the map?
And on any other maps too?

**Comment by The-Yak** [comment]
Can't seem to be on the right side on the map, but by going into the map extension widget and changing gridsize I can move the gap to the bottom.

I have seen this on one or two other maps but don't remember which.

**Comment by Beherith** [comment]
file:///home/deck/.var/app/info.beyondallreason.bar/data/screenshots/screen00015.png
file:///home/deck/.var/app/info.beyondallreason.bar/data/screenshots/screen00015.png

![image](https://user-images.githubusercontent.com/109391/193139283-37a68daf-bc0d-431c-acd6-bcfa5d0ffa89.png)

**Comment by Beherith** [comment]
ok the triangles are def culling
![image](https://user-images.githubusercontent.com/109391/193139605-7b7e964d-2699-4e14-9b80-8c0933cbdc3c.png)

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/193139698-54e8f1c4-c3fb-4367-9e50-818f5e6aba4c.png)

**Comment by Beherith** [comment]
it only happens on maps that are taller than wide, like quicksilver
