### ISSUE TITLE
Transparant Smoke

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/Beyond-All-Reason#101]
I know it's an engine thing, but i would really like to see transparant smoke-shadows, if smoke particle also get more transparent.

**Comment by Beherith** [comment]
Shadows are from binary stencil buffer. So cantdo, you can make smoke shadows not be there by spawning two identical particles with alpha >0.5.

**Comment by lhog** [comment]
Probably doable with some engine changes, but certainly not something we can do in the near future.

**Comment by icexuick** [comment]
Fixed/mitigated by redoing smoke textures to have more varied alpha and texture, now showing better fadeouts on smoke.
