### ISSUE TITLE
No cell in STAI localization

### ISSUE THREAD

**Issue by pandaro** [beyond-all-reason/Beyond-All-Reason#1022]
probably a unit outside of the map, (plane or a unit hit by a explosion) cause trouble in assign it on map
floris report with

error and replay

**Comment by pandaro** [comment]
error
[t=00:11:24.760190][f=0014294] [Game::ClientReadNet][LOGMSG] sender="[RZ]Jarkozpl" string="[Internal Lua error: Call failure] [string "luarules/gadgets/ai/STAI/targethst.lua"]:467: attempt to index field '?' (a nil value)
stack traceback:
    [string "luarules/gadgets/ai/STAI/targethst.lua"]:467: in function 'AddBadPosition'
    [string "luarules/gadgets/ai/STAI/targethst.lua"]:444: in function 'UnitDamaged'
    [string "luarules/gadgets/ai/shard_runtime/shardai.l..."]:179: in function 'UnitDamaged'
    [string "LuaRules/Gadgets/ailoader.lua"]:218: in function 'UnitDamaged'
    [string "LuaRules/gadgets.lua"]:1404: in function <[string "LuaRules/gadgets.lua"]:1391>
    (tail call): ?"
[t=00:11:26.337445][f=0014342] 13, STAI, TargetHST, Warning:, no cell, 13, 0, nil, nil
[t=00:11:28.702983][f=0014413] 13, STAI, TargetHST, Warning:, no cell, 13, 0, nil, nil

**Comment by pandaro** [comment]
replay
https://www.beyondallreason.info/replays?gameId=2c3a9b62f7582df9fb29f21394b64f60

**Comment by SethDGamre** [comment]
Ancient issue too old to be relevant.
