### ISSUE TITLE
STAI varius minor bugreport checklist

### ISSUE THREAD

**Issue by Sovgut** [beyond-all-reason/Beyond-All-Reason#1029]
- he build torpedo air on no water map
- he don't build any air defense
- he have 0/0 stockpile on nuke and anti-nuke

[20220616_180234_Valles Marineris 2_105.1.1-941-g941148f BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8921630/20220616_180234_Valles.Marineris.2_105.1.1-941-g941148f.BAR105.zip)

@pandaro

**Comment by pandaro** [comment]
Call failure] [string "luarules/gadgets/ai/STAI/taskqueuebst.lua"]:111: attempt to index field 'constructing' (a boolean value)
stack traceback:
	[string "luarules/gadgets/ai/STAI/taskqueuebst.lua"]:111: in function 'ConstructionComplete'
	[string "luarules/gadgets/ai/STAI/buildsitehst.lua"]:582: in function 'UnitDead'
	[string "luarules/gadgets/ai/shard_runtime/shardai.l..."]:148: in function 'UnitDead'
	[string "LuaRules/Gadgets/ailoader.lua"]:281: in function 'UnitDestroyed'
	[string "LuaRules/gadgets.lua"]:1324: in function <[string "LuaRules/gadgets.lua"]:1321>
	(tail call): ?
[t=00:31:02.038588][f=0062814] armnanotc, 12927, nil position
[t=00:31:03.632839][f=0062870] armnanotc, 12927, nil position

**Comment by Sovgut** [comment]
Currently STAI have some issues:

- Does not build air defense
- Does not use a nuclear installation
- Sometimes his anti-nuclear installation does not work
- Sometimes he makes a lot of units but does nothing with them (and does not attack or defend with them)
- Can't capture neutral buildings
- Can't capture loot boxes

**Comment by Sovgut** [comment]
he tries to send these units to a place where they cannot reach

https://user-images.githubusercontent.com/26426861/186615469-bf0e698d-4bcc-4b5a-8158-35d86edd6499.mp4

**Comment by pandaro** [comment]
thank you for the first and about the second can happend sometime, im working on a side total different atm. so maybe i can try a workaround... but nothing more specific.

**Comment by SethDGamre** [comment]
This is ancient and no longer relevant. 
Closing.
