### ISSUE TITLE
Lag spike after selecting unit with build options

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1033]
Lag spike happening after select particular unit with build options for first time in the game (Build menu widget lag it).
https://youtu.be/VIL1Ia6O-7o

**Comment by Damgam** [comment]
That is quite likely related to loading lots of uniticons from the disk. Could be solved with preload probably.

**Comment by MasterBel2** [comment]
Would agree, seems to only trigger when loading from my HD, and not when loading from my SSD

**Comment by 6AKU66** [comment]
Well, i'm using SSD and it's happening to me. But my SSD not so super fast.

**Comment by Ruwetuin** [comment]
applied unit icon caching
