### ISSUE TITLE
Revert Fix capslock selecting group9  on next engine release

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#1045]
[Fix capslock selecting group9 ](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1042)

] badosu: If a new engine is released while I'm away I'd appreciate if someone could take care of reverting this: https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1042

**Comment by badosu** [comment]
Thank you, I'll look into that

**Comment by badosu** [comment]
Can be closed as soon as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1198 is merged
