### ISSUE TITLE
Map edge extension doesnt not work on lava maps

### ISSUE THREAD

**Issue by Nikuksis** [beyond-all-reason/Beyond-All-Reason#1047]
![image](https://user-images.githubusercontent.com/54234096/176302986-01895640-6d97-4332-ba07-3f9eb7c13275.png)

**Comment by Damgam** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/map_edge_extension2.lua#L282-L285
