### ISSUE TITLE
Tombstone option is not working

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1067]
![изображение_2022-07-10_135812](https://user-images.githubusercontent.com/89547444/178142025-62fa4123-c4be-4d1d-8ce1-ed1ce5680211.png)
https://www.youtube.com/watch?v=sebkqn1vMWk

**Comment by Ruwetuin** [comment]
i removed the toggle for now here: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/10b9ec8c3c40e2dc343366aaaaa71131df8fc305

hoping for beherith being able to reintroduce it later
