### ISSUE TITLE
Antinuke rocket missing when weapon range multiplier is 2

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1068]
https://www.youtube.com/watch?v=6tgIl2qFY0k

**Comment by Ruwetuin** [comment]
i've made it affect starburst launcher flighttime less

possibly circumvented in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f5045cbe0599e2e9e4c7b1f76ca3044fe988e358
