### ISSUE TITLE
Ready button for 1v1s and FFA games pre-game

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/Beyond-All-Reason#107]
Let's add a Ready button as well when startpostype=fixed or random. 

It is annoying that the game loads and starts immediately, sometimes you get bored with looking at the loading screen and want to do other stuff, but it forces you to pay attention as the game may start any time. Another big issue connected to it is that you are not able to chose a faction in-game, so ppl using current lobby will always default to ARM, since no lobby-side faction picker either.

**Comment by icexuick** [comment]
3 sec countdown was added.
