### ISSUE TITLE
Only one player can pick starting position with same ID (shared control)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1070]
Reproduce: Start game with same ID and same ally with another player.
Result: Only one player can pick starting position.
Example: https://www.beyondallreason.info/replays?gameId=a7ef8f622b538e98aec59a5d4e94d5c9

**Comment by SethDGamre** [comment]
is this a feature we want to support? There's been talk of Archon mode but nobody's seriously trying to take it on so far.

**Comment by SethDGamre** [comment]
Per GDT decision, this is an unplanned and unsupported feature for the foreseeable future. Closing as unplanned.
