### ISSUE TITLE
Game autopause itself when player enter menu if all players have same ID and same ally

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1071]
Reproduce: Start game with same ID and same ally with another player.
Result: If someone enter in menu, game pause itself.
Example: https://www.beyondallreason.info/replays?gameId=a7ef8f622b538e98aec59a5d4e94d5c9

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/7f447c3101a9c677d07d1c782fc6026c958a74c5
