### ISSUE TITLE
Music track title is not updating

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1073]
Floating bug, steps to reproduce unknown.
https://youtu.be/iMFGv6Um6zw

**Comment by Damgam** [comment]
This one is not a "sometimes"
It's only updated for the first time the tooltip shows up, and gets stuck forever.

**Comment by 6AKU66** [comment]
Ok, i will change name of ticket

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/112e4c375ddc413b8ed68189c3e5aab0e73911fb
