### ISSUE TITLE
Otago issue 2: Forest fires are insignificant in damage

### ISSUE THREAD

**Issue by ghost** [beyond-all-reason/Beyond-All-Reason#1076]
Some time spent with the Otago remake has revealed 2 game issues that make it and maps like it suboptimal.

Forest fires only do 1 damage per frame, making them visually impressive but ultimately insignificant. The treefeller_gfx.lua gadget which controls this refers to weapondefs for tree fires but doesn't seem to respect the damage specified in them, with that only visibly changing screen shake.

A value should be decided upon of some significance in the tree feller gadget. If it is decided that map makers should have control of this value then I assume the simplest approach should be to respect weapons/treefire.lua damage value.

**Comment by SethDGamre** [comment]
this hasn't been touched in two years and sounds like it belongs in the suggestions discord channel.
I'd suggest closing this issue and trying suggestions.
