### ISSUE TITLE
Placement grid indication bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1083]
Reproduce:
1. Start to build 2x2 buildings.
2. When building have been started drop it and order new 1 single building somewhere else.
3. Grid indication bugged now.

Unbug:
1. Press shift when you in buildmode.

https://youtu.be/wPXQ7VSbwEU
![изображение_2022-07-13_100642](https://user-images.githubusercontent.com/89547444/178672197-e48b3f29-c4c1-4df2-bfcd-ded4828b2c10.png)

**Comment by hihoman23** [comment]
Seems to be fixed
