### ISSUE TITLE
Flatpak version of the Game Crashes on Wayland but not on x11 when trying to start a skirmish or load one.

### ISSUE THREAD

**Issue by Dark-Aeon** [beyond-all-reason/Beyond-All-Reason#1088]
I have installed the Game as Flatpak from flathub. While on X11 I can start a skirmish or load one from a save file just fine.

I switched to wayland a couple days ago. I can still start the game just fine but when trying to start a skirmish or load a save game the game Crashes and takes most of my other programs with it and I cannot start them again only a restart fixes that. KDE Programs like Konsole and Kate where fine.

To get some Log files i started the game from the terminal and got this output:

[bar-terminal-output.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9116505/bar-terminal-output.log)

and this error log: [bar-error.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9116516/bar-error.log)

I noticed the DBUS Erros and checked with Flatseal and the game did not had access to the DBUS stuff I gave it permission and tried again.
The terminal output after fixing the permissions in flatseal:  [bar-terminal-output-2.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9116524/bar-terminal-output-2.log)

and here is the Error log: [bar-error-2.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9116526/bar-error-2.log)

Also My System info:
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.5
Kernel Version: 5.18.7-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600X 6-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT

I have 3 Monitors: one 2560x1440  (32") and two 1920x1200 (24")

This is the first time I report a bug  :-) If you need any more log files or infos please let me know.

Edit: output of the DBUS_SESSION_BUS_ADDRESS env variable:
![Screenshot_2022-07-15_003](https://user-images.githubusercontent.com/20175257/179214857-0062f105-e701-42f6-bee7-0db6cab3c8a5.png)

I was advised to also add the output of inxi -Fa:
[inxi-Fa.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9120509/inxi-Fa.log)

**Comment by dpanter** [comment]
Unable to reproduce the issue on Siduction, KDE 5.25, Wayland, 6900XT.
Game works on first install, completed first scenario and played a skirmish map. Did not use Flatseal.
My inxi -Fa output: [siduction-inxi.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9120923/siduction-inxi.log)

**Comment by Dark-Aeon** [comment]
I now also have tried the appimage version of the game. it also crashed when seemingly on the same position when loading a skirmish game is nearly finished.

here is the Terminal output: 
[appimage-terminal-output.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9122211/appimage-terminal-output.log)

and the Logfile 
[appimage-error.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9122214/appimage-error.log)

**Comment by lhog** [comment]
```
[t=00:00:00.086176] [GR::LogVersionInfo]
[t=00:00:00.086187] 	SDL version : 2.0.22 (linked) / 2.0.8 (compiled)
[t=00:00:00.086191] 	GL version  : 4.6 (Compatibility Profile) Mesa 22.1.2
[t=00:00:00.086194] 	GL vendor   : AMD
[t=00:00:00.086196] 	GL renderer : AMD Radeon RX 5700 XT (navi10, LLVM 13.0.1, DRM 3.46, 5.18.7-1-MANJARO)
[t=00:00:00.086199] 	GLSL version: 4.60
[t=00:00:00.086202] 	GLEW version: 2.2.0
[t=00:00:00.086204] 	GPU memory  : 15122MB (total) / 15122MB (available)
[t=00:00:00.086228] 	SDL swap-int: -1
[t=00:00:00.086231] 	SDL driver  : x11
```

Somehow SDL thinks it's running X11 driver while this value should be Wayland I think.
Can you try running it on X11.
Also try to run `./spring` from the engine dir natively (you won't need to run the game itself, just send the logs)

**Comment by dpanter** [comment]
For an additional data point: I tested the AppImage in KDE Wayland, same system as earlier.
Forcing `SDL_VIDEODRIVER` to either X11 or Wayland - both work without issues. Verified in terminal output that the proper SDL driver is used and checked with KWin debug console that the game window is using native Wayland when forced.
Let me know if you want logs.

**Comment by lhog** [comment]
Interesting, so if you force the `SDL_VIDEODRIVER` everything works just fine?
In theory we could set `SDL_VIDEODRIVER`, if I know how to detect if it's running Wayland, but generally this would look very situational and SDL folks should better fix it rather than us.

**Comment by lhog** [comment]
Can you send the output for:
```
echo $XDG_SESSION_TYPE
echo $WAYLAND_DISPLAY
echo $SDL_VIDEODRIVER
```
In your vanilla setup (i.e. when `SDL_VIDEODRIVER` is not overridden)

**Comment by Dark-Aeon** [comment]
> Somehow SDL thinks it's running X11 driver while this value should be Wayland I think. Can you try running it on X11. Also try to run `./spring` from the engine dir natively (you won't need to run the game itself, just send the logs)

Here are the logs when running the game on X11:

Terminla output: 
[bar-terminal-output-x11.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9127929/bar-terminal-output-x11.log)

error log:
[bar-error-x11.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9127932/bar-error-x11.log)

running `./spring` from the engine directory, how do I do that? in `./spring` is only a *.pem file. where do i find the engine directory?
I tried googling it but could not find an answer

**Comment by lhog** [comment]
Don't see any errors here. So how about: https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1088#issuecomment-1186297437 ?

**Comment by Dark-Aeon** [comment]
```
[a@b ~]$ echo $XDG_SESSION_TYPE
wayland
[a@b ~]$ echo $WAYLAND_DISPLAY
wayland-0
[a@b ~]$ echo $SDL_VIDEODRIVER

[a@b ~]$ 
```
interesting. looks like the last variable is empty on my system.

should i try to put in x11 or wayland into it?

**Comment by dpanter** [comment]
Last comment from me then (maybe) ;)
SDL_VIDEODRIVER isn't set on my system and as previously mentioned, both Flatpak and AppImage work properly without it set. Both also work properly when forcing either X11 or Wayland. It's curious how Manjaro KDE Wayland apparently needs it set to X11.

**Comment by ripper81** [comment]
I had the same problem with KDE Plasma Wayland. However after updating from Plasma 5.24 to 5.25 the issue was gone. I don't know why though.

**Comment by SethDGamre** [comment]
Issue is very old.
