### ISSUE TITLE
CAN I adjust the game speed ? now is too slooooow

### ISSUE THREAD

**Issue by woodgreat** [beyond-all-reason/Beyond-All-Reason#1094]
the game speed is too slow ,Can I adjust it? maybe add this feature is nice idea, less fast X2 at most ,and I can set speed low at game setting in starting .

**Comment by WatchTheFort** [comment]
Press Alt and Numpad - or + to adjust game speed.

**Comment by woodgreat** [comment]
Thanks , by the way ,Is there a button for speed adjustion or what?

**Comment by woodgreat** [comment]
ok,I  tried and fond that true ,How about we add the button !
