### ISSUE TITLE
Another update point ,Is there have “Economic architecture”？

### ISSUE THREAD

**Issue by woodgreat** [beyond-all-reason/Beyond-All-Reason#1101]
Economic architecture ，we know in SC1 or SC1a ,the economic building have bonus ，like power plant and power storage side around, Can we do it in BAR ?

**Comment by sprunk** [comment]
There is no adjacency bonus, but having a good base layout is still important because economic buildings tend to explode, to make it easier for your own units to path, and to make it harder for the enemy to raid.

**Comment by woodgreat** [comment]
Can we keep and add this "bonus" feature in BAR? maybe ,it's a good idea .
