### ISSUE TITLE
Mouse can't move camera

### ISSUE THREAD

**Issue by JackCarterSmith** [beyond-all-reason/Beyond-All-Reason#111]
Hi,

I'm on byar-14688 and I've got a problem with the mouse cam control:
The mouse can't move the camera, the option is not enabled by default on the config. When I enabled it and restart a session (not the full game), the camera work.
But when I do a full restart of the game, the config is overriden and the camera is lock again.

Maybe byar-chobby rewrite the config file with default value everytime it's launch?

**Comment by Ruwetuin** [comment]
re-added edge move as default, however know you toggle this ingame at: Settings > Control > Screen edge moves camera

**Comment by JackCarterSmith** [comment]
Okay thanks, I know the option in settings but it's normal that the modification in the settings is not saved on restart?

**Comment by Ruwetuin** [comment]
no, the default settings only should be loaded on first load. Maybe they are loaded more than once.... or.... it cant save settings? maybe permission problem?

**Comment by JackCarterSmith** [comment]
The permission in user AppData is normally without problems?
I've made a fresh re-install and same problem.

Can I try to launch BAR with admin rights?

**Comment by JackCarterSmith** [comment]
Okay I've found the problem:

- First clean launch -> generate new springsettings.cfg with FullscreenEdgeMove=0
- Launch new skirmish -> read 0 value and play without mouse control
- Close game and edit the file manually to value 1 -> game running with mouse controle support
- Edit the settings directly in game -> FullscreenEdgeMode variable disappear from file

I think isn't normal yep?

**Comment by gajop** [comment]
A server outage was preventing @Ruwetuin changes from being applied (https://spring-launcher.firebaseapp.com/repo/beyond-all-reason/BYAR-Chobby)

This has now been fixed.
