### ISSUE TITLE
Crashing often code 3221225477

### ISSUE THREAD

**Issue by segatrade** [beyond-all-reason/Beyond-All-Reason#1119]
https://bar-infologs.s3.eu-central-1.amazonaws.com/spring-launcher_1658813305799.log

https://bar-infologs.s3.eu-central-1.amazonaws.com/spring-launcher_1658809532597.log

Spring has crashed:
  Access violation.
  
  This stacktrace indicates a problem with a skirmish AI.
  
  bar\AI\Skirmish\BARb\stable\SkirmishAI.dll
  
  p.s.
  https://bar-infologs.s3.amazonaws.com/spring-launcher_1658913525074.log code 3
  https://bar-infologs.s3.eu-central-1.amazonaws.com/spring-launcher_1658921359598.log

**Comment by pandaro** [comment]
Related with stai or barbarian? Do we have a distinguish?

**Comment by segatrade** [comment]
It's question to me or colleague?
I experienced it in Scenario Where NeoEurope map and start as England. It started happen often after minute 14 approx

**Comment by sanderstad** [comment]
I have this problem whenever I hit the Settings menu anywhere in a game

**Comment by SethDGamre** [comment]
> I have this problem whenever I hit the Settings menu anywhere in a game

This sounds unrelated to AI crash. 

This issue is too old to be recreated and too difficult to theorize possible causes.
Closing for this reason.

**Comment by paulsolovyov** [comment]
> > I have this problem whenever I hit the Settings menu anywhere in a game
> 
> This sounds unrelated to AI crash.
> 
> This issue is too old to be recreated and too difficult to theorize possible causes. Closing for this reason.

Please reopen this bug.
