### ISSUE TITLE
Substitution allows for 'coop' mode

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1139]
If a player gets substituted - for example by disconnecting in the pregame phase - if they rejoin they are added as a player with the same 'player id' so both players can control the same 'player id' units, effectively adding a player to the team.

**Comment by daufinsyd** [comment]
Hi @badosu 
I'm actually trying to achieve coop !
Could you explain how do you do that?

**Comment by badosu** [comment]
This won't help you achieve coop unless certain conditions are met:

- Start a game as a player
- Leave the game, while there are other players in the game
- Have a spectator (not a player!) substitute you, for that they must have similar skill number
- Start the game
- Rejoin the game

**Comment by 6AKU66** [comment]
@daufinsyd 

!idShareMode all

**Comment by badosu** [comment]
Teiserver overrides ids by default, this issue has been raised with the maintainer. Please create an issue in Teiserver repository or discuss on discord

**Comment by Isy232** [comment]
disconnecting in the pregame phase isn't required for this to occur.

Notably it happened to myself when placed but not readied when a force start occured.
In this I did try to place too close to another person, putting my light thing in the red for a time when it then put a sub in or something.

**Comment by badosu** [comment]
Since sub is not available, this can be closed. Reopen if is reinstated and presents the same issue.
