### ISSUE TITLE
Substituting player can't give units, resources or resign

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1140]
Basically the title of this issue

**Comment by sprunk** [comment]
Engine issue iirc, the server tracks player team allegiance (to prevent spoofing give/resign) but when the Lua call moves a spec into a team there is no packet that tells server about it

**Comment by badosu** [comment]
Since sub is not available, this can be closed. Reopen if is reinstated and presents the same issue.
