### ISSUE TITLE
Players can remove own 'substitution markers'

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1141]
There's a mechanic, that is supposed to make fair - that the subber saw the other teams start positions -, by placing a marker for all players in game. However the marker is given as the own players marker for each player.

Since the player owns the marker they can just wait to delete it as soon as the commander is spawned, thereby nullifying the mechanic and giving a substancial advantage to the subbers team.

**Comment by sprunk** [comment]
Does the marker actually get erased from enemy PoV?

**Comment by badosu** [comment]
Yes

**Comment by SethDGamre** [comment]
this looks like a feature that's no longer used or supported.

**Comment by badosu** [comment]
Thank you, you are absolutely correct
