### ISSUE TITLE
Fog of war is not visible under certain circumstances

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1152]
https://www.youtube.com/watch?v=IL2ysl9r0TI

**Comment by Beherith** [comment]
Indeed, sufficient amounts of ethanol do that :P
More concerning is the spam from rank icons.

**Comment by 6AKU66** [comment]
> Indeed, sufficient amounts of ethanol do that :P More concerning is the spam from rank icons.

I read it right only after 1-5 attempt lol

**Comment by Damgam** [comment]
This seems to be fixed
