### ISSUE TITLE
Long nickname overlay player's FPS counter

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1161]
![изображение_2022-08-22_005429370](https://user-images.githubusercontent.com/89547444/185812433-c4ba65a6-7b35-4d3b-a5a0-fcb2b6305c9f.png)

P.S Ok, looks like it's only happening in pre-game stage. So it's really low priority, probably better just close ticket.

**Comment by Ruwetuin** [comment]
yes I'm aware of it and wontfix since it is indeed only pre-game, the playername shifts to the right to make room for the status 'light' icon
