### ISSUE TITLE
Bug cannot self-D labs with a Grid Menu D key binding (if Grid Menu Enabled)

### ISSUE THREAD

**Issue by Borg-King** [beyond-all-reason/Beyond-All-Reason#1165]
https://youtu.be/LgPejUG8dq8

**Comment by resopmok** [comment]
This can be solved temporarily by adding a binding for selfd in your uikeys.txt. There are a couple conflicts of default hotkeys with grid menu - Ctrl-c for select commander does not work when a lab is selected as well. The solution I think is for the grid menu option to select an alternate version of bar_cmd_hotkeys.lua which solves those conflicts.

**Comment by badosu** [comment]
This is not necessarily a bug. It could be an incompatibility with default keys and gridmenu for sure.

The resolution for this being providing a package for gridmenu to interop with alternative defaults and UI settings that integrate keybindings with other UI components.

As of now gridmenu is just a self-contained part of that approach

**Comment by resopmok** [comment]
There is now a keyset available which is designed to be used in conjunction with grid menu, and has no conflicts with grid menu keys or orders. It's available in Settings -> Control -> Hotkeys -> Keybinds -> Grid Optimized. More clear and explicit documentation about this setting is a WIP. There continue to be conflicts with default keybinds, and it is not recommended for use with grid menu (by me at least).

**Comment by badosu** [comment]
@Borg-King Does that sound good to you?

**Comment by Borg-King** [comment]
Yes this sounds good, nice one!
