### ISSUE TITLE
Taking unfinished advanced fusion reactor cause visual bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1169]
https://youtu.be/kkR6mlolqpE

![изображение_2022-08-28_034130460](https://user-images.githubusercontent.com/89547444/187052886-3a4ffcf8-f0ec-443f-a695-c33a9012d1f5.png)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/d29c7f3228f5dca8bad9acfe98830f05daa1194f
