### ISSUE TITLE
Add Mac build

### ISSUE THREAD

**Issue by Flexicon** [beyond-all-reason/Beyond-All-Reason#1176]
It would be cool if on top of Windows and Linux builds we could get a Mac OS X compatible build.

SpringRTS supports the OS out of the box as far as I know.

Any chance on that happening? 🙏

**Comment by Damgam** [comment]
SpringRTS USED TO support MacOS up to 103.0
Ever since OpenGL requirements increased in 104.0 that had to be dropped because MacOS is stuck at OpenGL2 or something... And now you have these Arm CPUs which are not really compatible from what i've heard from people who know more than me.

**Comment by Flexicon** [comment]
You're right - my bad. I did some digging after I posted this to verify what I wrote and yeah, no modern engine support for newer MacOS. Bummer.
