### ISSUE TITLE
Cortex scav tech 2 wind turbine wreckage bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1189]
https://youtu.be/EH7moEaHaYk

**Comment by Damgam** [comment]
lol :D
I did not make wreck for this guy

**Comment by Zecrus2** [comment]
Just fixed it, corwint2_dead.s3o already existed so I only needed to change 1 line in the unitfile.

**Comment by Damgam** [comment]
o, thank you. :)
