### ISSUE TITLE
Persecutors can block each other

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1193]
https://youtu.be/pdwiT4EpCWM

**Comment by Damgam** [comment]
Fixed

**Comment by 6AKU66** [comment]
Not fixed

**Comment by Damgam** [comment]
Someone broke it again while editing hitboxes.
@drivver44 was it you?

**Comment by drivver44** [comment]
@Zecrus2 
yes it was me 
but there is discussion about the turrets blocking that occurred in dms
this was changed based on those dms on discord
this is also true for the arm varriant

also welcome to the mess that is hitboxes where 3 files do something for 1 unit
