### ISSUE TITLE
game_end.lua attempt to index a nil value

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1201]
Version 20680

Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_end.lua"]:319: attempt to index a nil value
stack traceback:
	[string "LuaRules/Gadgets/game_end.lua"]:319: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:858: in function <[string "LuaRules/gadgets.lua"]:856>
	(tail call): ?
[t=00:16:35.989000][f=0045226] [Game::ClientReadNet][LOGMSG] sender="Antraxis" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_end.lua"]:319: attempt to index a nil value

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/6d6872b9e5e942d8699aa9253f94491b9773f9ca
