### ISSUE TITLE
Unit Energy Icons: Non-existing UnitID (14102) is supplied

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1221]
Error in GameFrame(): [LuaUtils::InstanceDataFromGetData] Non-existing UnitID (14102) is supplied
Removed widget: Unit Energy Icons

I was spectating for certain player and one team was resigning.

**Comment by SethDGamre** [comment]
old, I have no appearances of this issue in my infolog.txt over all my playtesting today.
