### ISSUE TITLE
"Spotted mobile anti" message spam

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1225]
Messages like "Spotted mobile anti, 27623, allynuke, 276233411_1836.85547_720" keep spamming during the game

**Comment by WatchTheFort** [comment]
@Beherith
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/da8ddc22e593226bcf85ed8ac6f3b95dc4fd500e/luaui/Widgets/gui_defenserange_gl4.lua#L892

**Comment by Beherith** [comment]
Hmm, defenserange gl4 wasnt completed, we could resolve appearance dilemma back then (merging overlapping ranges)

**Comment by Beherith** [comment]
Fixed!
