### ISSUE TITLE
Solar collectors don't produce energy when cheat nocost activated

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1227]
Arm and core solar collectors (which cost only metal) is affected.
https://youtu.be/jt3qOtN-kUk

**Comment by sprunk** [comment]
AFAIK this is because /nocost disables energy consumption, but Solars don't actually produce +20 but "consume" -20 (double negative is positive). This is setup that way because consumption is turned off when closed and production isn't.

**Comment by Ruwetuin** [comment]
wonfix
