### ISSUE TITLE
Constuction bar display bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1229]
Enemy can see constuction bar which for some reason often stays on 99% after unit have been built, happening only with disabled fog of war
https://youtu.be/U079yKxOQF8

**Comment by Beherith** [comment]
Could you please enable the unitcallins widget, and look at the texts? Each callin will float above the units position.  I think that the unitfinished callin is not being sent when the grunt finishes construction if globallos is on.

**Comment by 6AKU66** [comment]
> Could you please enable the unitcallins widget, and look at the texts? Each callin will float above the units position. I think that the unitfinished callin is not being sent when the grunt finishes construction if globallos is on.

@Beherith 
Remind me how to enable it

**Comment by 6AKU66** [comment]
Ah... I got it.

**Comment by hihoman23** [comment]
This seems to be fixed
