### ISSUE TITLE
Cloaked units is not visible on radar if fog of war disabled

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1230]
https://youtu.be/cT1Hac44GHI

**Comment by SethDGamre** [comment]
![image](https://github.com/user-attachments/assets/adccc647-6c14-4a26-89d4-405c2b94f601)

![image](https://github.com/user-attachments/assets/355108fd-7ccf-4105-94a0-b46859bcd041)

issue resolved

**Comment by hihoman23** [comment]
Seems to have been fixed recently
