### ISSUE TITLE
Chat: backspace and left/right arrow does not account for more than 1 byte-sized chars completely

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1235]
Suggested fix is to perform the same char length check being done here: https://github.com/badosu/Beyond-All-Reason/blob/251e56b96dc67241f129316f81d93ad9758f33af/luaui/Widgets/gui_chat.lua#L1339

To be done here: https://github.com/badosu/Beyond-All-Reason/blob/251e56b96dc67241f129316f81d93ad9758f33af/luaui/Widgets/gui_chat.lua#L1399

Correspondingly for left and right arrow keypress

To reproduce:

- Copy this char `ç` and paste into chat box with ctrl+v, or type a composited character into it
- Press backspace
- Observed garbled chat box

**Comment by Beherith** [comment]
how does string:sub handle this? 
fuck its complicated
local s = "abçde"
print (string.sub(s,3,4)) -- == "ç"
so how does one tell that the chat at the inputTextPosition is not 8 bits?

**Comment by badosu** [comment]
It's a simple fix, just send `slen` to input position like the original fix highlighted in my first message

**Comment by badosu** [comment]
It's also a #good-first-issue
