### ISSUE TITLE
Tootips text overlap with chat

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1250]
![screen00191](https://user-images.githubusercontent.com/89547444/189800956-a4ae3098-3bfe-42ef-86c3-77ccbc90a6c8.png)

**Comment by Ruwetuin** [comment]
couldnt reproduced but probably fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/1738998c858d35b7bf7ef7c68a4d99523db4ebd6
