### ISSUE TITLE
SmartSelect: selection box gets corrupted when started out of map bounds and view changes meanwhile

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1252]
To reproduce:

- Start a selection, say just out of the left edge of the map
- Extend it until it selects units on the map
- Further extend until the screen edge is reached, prompting a view translation. It can _probably_ also be reproduced by zooming out
- The actual computed selection box initial reference now is some random point

See:

- https://github.com/beyond-all-reason/Beyond-All-Reason/blob/0061dc2d5733ff39a84971d8357956a746a5e739/luaui/Widgets/unit_smart_select.lua#L150
- https://github.com/beyond-all-reason/Beyond-All-Reason/blob/0061dc2d5733ff39a84971d8357956a746a5e739/luaui/Widgets/unit_smart_select.lua#L193

**Comment by sprunk** [comment]
Why not use `Spring.GetBoxSelectionByEngine`?

**Comment by badosu** [comment]
Fixes
