### ISSUE TITLE
Rank icons don't appear

### ISSUE THREAD

**Issue by MasterBel2** [beyond-all-reason/Beyond-All-Reason#1261]
I can get an infolog if you want, but I've already trawled the log for errors and there's nothing. It just doesn't appear. Likely it's failing inside a drawlist - iirc errors inside a drawlist don't get reported anywhere? That should probably be fixed too.

Edit: added screenshot
![rankiconbug](https://user-images.githubusercontent.com/39206414/190838948-eff14067-c760-47fb-8a0f-a2237bd4ae7f.jpeg)

**Comment by MasterBel2** [comment]
Welp I just published the issue, meant to add a screenshot

**Comment by Ruwetuin** [comment]
tried tonumber it, not sure if it will do anything
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/37fcc4a769d6af0eb15b8a925f3befbec734e461

**Comment by MasterBel2** [comment]
Doesn't seem to have helped. Still not getting any icons

**Comment by Beherith** [comment]
Are we certain that ranks arent paletted images?

**Comment by Ruwetuin** [comment]
they are just individual png's located at https://github.com/beyond-all-reason/Beyond-All-Reason/tree/master/luaui/images/advplayerslist/ranks

**Comment by SethDGamre** [comment]
issue old. I haven't seen it happen since I started playing. I'll reopen this if anybody has objections to its closing.

**Comment by MasterBel2** [comment]
Wow this is an old issue! I completely forgot about it, but recently discovered that it was my own lua code responsible. Weird that at the time a lua reset didn’t help, but maybe I messed it up somehow.
