### ISSUE TITLE
Legion: Add mapping for pregame start on buildmenu

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1271]
See `corToArm` and `armToCor` [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_buildmenu.lua)

**Comment by Ezahiel** [comment]
Is it leg even done in 50%? Its not that time consuming to do it, but is it required while leg is still WIP?

**Comment by badosu** [comment]
If the game allows you to play with legion, it should not have a broken interface.

**Comment by Ezahiel** [comment]
> If the game allows you to play with legion, it should not have a broken interface.

ok will look at it then. Still not sure how to drop here corrected/fixed file or is it just txt and ref link ?
