### ISSUE TITLE
404 Not Found on First Update

### ISSUE THREAD

**Issue by WilliamFreau** [beyond-all-reason/Beyond-All-Reason#128]
Hi,

I want to try this game, but I can't install it on my W10. I have not try on Linux.

The updater say: Request Failed: 404

Here is the link to the complete log.
http://logs.springrts.com/logfiles/1251/

Extracted part for the error 404
```
[error] engine/104.0.1-1553-gd3c0012 maintenance: Failed to download resource: Request Failed.
Status Code: 404
```

Ps: I've disable my personal DNS before opening this ticket.

**Comment by lhog** [comment]
Thanks for the report, we are aware and working to solve the issue. Might take couple of hours for the spring engine to rebuild and for us to update hosts.

**Comment by lhog** [comment]
The issue has been rectified
