### ISSUE TITLE
Updates are broken on Enterprise Linux distros due to CA cert paths

### ISSUE THREAD

**Issue by apollosride** [beyond-all-reason/Beyond-All-Reason#129]
The in-game updater will fail on Fedora 33 with error on initial run. `[Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:487:processMessages():CURL error(1:77): Problem with the SSL CA cert (path? access rights?) 0 (https://repos.springrts.com/repos.gz)`

Enterprise Linux distros (CentOS, Fedora, Oracle Linux, RHEL) place CA certs in /etc/ssl/certs/ca-bundle.crt and  /etc/ssl/certs/ca-bundle.trust.crt (for extended validation certs). The updater should look for these paths in addition to /etc/ssl/certs/ca-certificates.crt. Symlinking /etc/ssl/certs/ca-bundle.crt -> /etc/ssl/certs/ca-certificates.crt fixes this issue on Fedora 33. I did not test on the other flavours of Enterprise Linux, but it likely affects all of them.

**Comment by tobias47n9e** [comment]
@apollosride I think all the distros you mentioned should either come with Flatpak by default or have it in their repositories. I tested your issue using this Flatpak https://flathub.org/apps/details/info.beyondallreason.bar and Fedora 34, and had no issues with updating the engine and downloading the maps:

![bar_pr_downloader](https://user-images.githubusercontent.com/6953323/132030779-9c745b0c-13d4-4cd5-9f0d-c5d67f3a5d73.png)

Is this a viable solution to your problem? Did maybe a distro update in the mean time fix your issues?

**Comment by Born2Crawl** [comment]
Hey, yes I finally fixed it here https://github.com/beyond-all-reason/pr-downloader/commit/f529bc96a0a6133e19439cf68014d5806eb24240 and it was included in the engine here: https://github.com/beyond-all-reason/spring/commit/acf6dfc030ace95457d9c55240a6bca5f396365a

On Fedora/CentOS, it should download and use a proper certificate bundle. You can check it easily by looking at cacert.pem file in Documents/Beyond All Reason folder, it now should contain a proper Bundle of CA Root Certificates, and not an HTML doc with "301 Moved Permanently" :D

**Comment by Born2Crawl** [comment]
Issue is confirmed to be resolved: https://discord.com/channels/549281623154229250/720076504461082685/906984756657418351
