### ISSUE TITLE
Point Tracker: does not draw outside a minimap quadrant

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1290]
![2022-09-24T13:58:15,135823735-03:00](https://user-images.githubusercontent.com/347552/192110002-05b4e35a-6dfe-46d8-8bc0-f328d5d63afc.png)

cc @Beherith

**Comment by Beherith** [comment]
oooh now that i has amd linux combo too :)

**Comment by Beherith** [comment]
I can repro it on amd, but have zero idea how to fix it, as classical draw methods work just fine, like the one done by customformations drag move.

**Comment by Beherith** [comment]
got a link to the old ticket where this happened for projectiles on mininmap?

**Comment by Beherith** [comment]
this one didnt help much https://github.com/beyond-all-reason/spring/issues/188
