### ISSUE TITLE
Clicking on enemies in advanced player panel not hide list if there's bots in that list

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1292]
![Снимок](https://user-images.githubusercontent.com/89547444/192120744-604e0f78-ba7b-40bc-aa53-7a96506a4c80.PNG)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/e675952ef861d68e67025c520b9f8ebb9bbed2e8
