### ISSUE TITLE
Nuclear ICBMs crash into terrain on Altored Divide map

### ISSUE THREAD

**Issue by AngleWyrm10** [beyond-all-reason/Beyond-All-Reason#130]
DAI repeatedly fires intercontinental ballistic missiles that appear to crash harmlessly into mountain terrain.

![blocked ICBM](https://i.imgur.com/ttYumob.png)

Trying to include zipped replay file, don't know if this will work.
Blue AI in lower left begins firing failed ICBMs around minute 53
[20201206_120007_Altored Divide Bar Remake 1_104.0.1-1553-gd3c0012 maintenance.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/5652271/20201206_120007_Altored.Divide.Bar.Remake.1_104.0.1-1553-gd3c0012.maintenance.zip)

**Comment by icexuick** [comment]
DAI probably selected target just behind mountain.
ICBM's have a 'fixed' trajectory, and a mountain could be in the way.
I believe it's pretty hard to let AI check if rockets/nukes also really hit their target to make them switch target/location.

**Comment by PtaQQ** [comment]
it shouldn't be that hard to make a check if there is a mountain on the way: 
- make an array of coordinates on the line between the target and silo (sampled every few elmos) 
- calculate the heights of triangles created by the point couplings (target coords, between point cords, trajectory point over the given "between point") 
- check if the ground height in the given between point coord is > triangle height 
- if not, go try nuking elsewhere  

I can try to write this check if someone points me to where the nuking script is

**Comment by AngleWyrm10** [comment]
Or maybe have the ICBM's trajectory drop straight down from high elevation during the final part of it's attack run?
