### ISSUE TITLE
Player Name and Mini-map showing upside down after 180 degree camera rotation - Spring Camera

### ISSUE THREAD

**Issue by harikrishnan-annappilly** [beyond-all-reason/Beyond-All-Reason#1308]
**Issue**
While rotating the spring camera the mini-map and name next to the cursor highlight is not rotating. Which resulting in upside down name and mini-map. Sample screenshot attached.

**Steps to reproduce**

1. select spring camera (setting -> camera settings -> spring camera)
2. rotate the view using Alt+ Arrow(Left/Right) key
3. 
    1. check cursor from team mate in same game **OR** from a replay
    2. check the mini-map
 
(Sample Screenshot)
![screen00073](https://user-images.githubusercontent.com/57492008/192528370-ebd27533-14c5-4085-80f1-404b0d761de0.jpg)

**Comment by badosu** [comment]
If available at the time:

> Use `_, rotY = Spring.GetCameraRotation()` to rotate the label here: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/c7ca090d35dd773afacc79a8610bdcb316c69921/luaui/Widgets/gui_ally_cursors.lua#L384-L385

Otherwise see if possible to infer from `Spring.GetCameraDir()`
