### ISSUE TITLE
Cleaning up unit interface and building consolidation

### ISSUE THREAD

**Issue by nf33** [beyond-all-reason/Beyond-All-Reason#1317]
Some suggestions:

Custom unit build menus Ability to hide unit building icons for the game unit of that particular type (aka say you won't be building radar or tier 1 turrets anymore, ability to to move it to a tab on the main build menu so you don't have to scroll through huge # of build icons, just keep it simple).

Right now there are too many buildings required to spam your eco in late game if you don't get metal resources early on, trying to grow your eco with huge numbers of pow + metal generators takes up too much space.  Maybe have building uppgrades that juts upgrades their stats instead?  It would save late game performance too without having to load new models/textures.

**Comment by SethDGamre** [comment]
suggestions like this should be made in the suggestions channel on discord, not issues to be resolved by us code monkeys
