### ISSUE TITLE
Illuminated units ignore depth of field

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1319]
![screen00143](https://user-images.githubusercontent.com/89547444/193316844-711315fa-b634-4e65-b0ef-6845d4a2e0b6.png)
![screen00144](https://user-images.githubusercontent.com/89547444/193316892-880a7888-d8ea-42de-813c-fcb06aeb04c8.png)

**Comment by Beherith** [comment]
A couple of things need to be checked here, as the original unit underneath the extra lighting seems to get the correct blurring. This leads me to believe that the depth of field widget is rendered before the lights in deferred rendering. 
I know that deferred lights are rendered in widget:DrawScreenEffects(), after DrawWorld. 

In the future, we are moving toward deferrred rendering gl4 so could you try checking wether the DOF is rendered correctly for DLGL4 lights? 

DOF is rendered in widget:DrawScreenEffects() . 

So it could either be fixable by draw order, or with the coming gl4 version.

**Comment by 6AKU66** [comment]
Looks like GL4 is not affected.

**Comment by Beherith** [comment]
Excellent!
