### ISSUE TITLE
fatal Lua Error, causes units to turn invisable

### ISSUE THREAD

**Issue by PitherBro** [beyond-all-reason/Beyond-All-Reason#1323]
# maybe it's too many units
![screen00001](https://user-images.githubusercontent.com/47367930/193437072-988e8104-24da-4d41-99d0-352f7f4b63ae.png)
text is small so i'll save your sight:
Fatal: [spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=0{alloced,maximum}={1610613283,1610612736}bytes

# save files if you want them
[20221001_224716.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9691774/20221001_224716.zip)

**Comment by Beherith** [comment]
Did you happen to have STAI as an AI in that game?

**Comment by guenichone** [comment]
Hello I got the same on 7 island, and yes I had a STAI AI in the game. A game before one the same map, I got a memory exception invoking garbage collector. Maybe not linked.

**Comment by pandaro** [comment]
@Beherith the text say: synced =0{aloc,max}={123,456}
Thin mean that st are using sync mem?

**Comment by Beherith** [comment]
There are like 4 lua contexts, synced gadget, unsynced gadget, luaui and luamenu :P all sharing the same mem pool. Yesterdays fixes to more aggressive GC when there is too much garbage should prevent 99% of this kind of OOM

> Hello I got the same on 7 island, and yes I had a STAI AI in the game. A game before one the same map, I got a memory exception invoking garbage collector. Maybe not linked.

@guenichone about 20 hours ago there were some changes, and you could have got a message like this: 
`"%d STAIs using %d MB RAM > %d MB limit, performing garbage collection and adjusting limit to %d MB"`
If you got the above message, and _still_ ran out of ram, please upload the replay of the game if possible.

**Comment by Beherith** [comment]
> @Beherith the text say: synced =0{aloc,max}={123,456} Thin mean that st are using sync mem?

That means synced = false

**Comment by janvladimirmostert** [comment]
Another one?
https://www.reddit.com/r/beyondallreason/comments/109gj0v/beyond_10k_units_units_just_stop_rendering/

**Comment by Beherith** [comment]
All lua mem is shared, limit is 1.6gb

**Comment by SethDGamre** [comment]
This issue is too old to be recreated and hasn't had activity in almost a year. 
Closing.
