### ISSUE TITLE
Game crash with Radar and sonar range multiplier =>3

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1325]
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9692749/infolog.txt)

![Снимок](https://user-images.githubusercontent.com/89547444/193458361-2eff197e-fe48-4944-bd4a-a24c6ce31f1a.PNG)

**Comment by Beherith** [comment]
Widget now removes itself, cant alloc vertex arrays this large.

**Comment by WatchTheFort** [comment]
We need to either fix the widget to support ranges this large, or limit range multipliers to not crash the widget, the first option would be preferable.
