### ISSUE TITLE
Gadget lups_shield.lua attempt to index field '?'

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1328]
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=ShieldPreDamaged trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/lups_shield.lua"]:149: attempt to index field '?' (a number value)
stack traceback:
	[string "LuaRules/Gadgets/lups_shield.lua"]:149: in function 'ShieldPreDamaged'
	[string "LuaRules/gadgets.lua"]:1669: in function <[string "LuaRules/gadgets.lua"]:1665>
	(tail call): ?
	
21014
Bounce everything setting for shields + 10 shield power multiplier
Looks like it's lags game a lot.

**Comment by Ruwetuin** [comment]
added an extra nil check https://github.com/beyond-all-reason/Beyond-All-Reason/commit/6ba1d541ef423dc45bad2fea26368f64acbe5d3b

**Comment by 6AKU66** [comment]
> added an extra nil check [6ba1d54](https://github.com/beyond-all-reason/Beyond-All-Reason/commit/6ba1d541ef423dc45bad2fea26368f64acbe5d3b)

21067 still affected

Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=ShieldPreDamaged trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/lups_shield.lua"]:149: attempt to index field '?' (a number value)
stack traceback:
	[string "LuaRules/Gadgets/lups_shield.lua"]:149: in function 'ShieldPreDamaged'
	[string "LuaRules/gadgets.lua"]:1669: in function <[string "LuaRules/gadgets.lua"]:1665>
	(tail call): ?

**Comment by Ruwetuin** [comment]
added another nil check https://github.com/beyond-all-reason/Beyond-All-Reason/commit/ad3d9a127de3de052aad30b42e3f29569ac73883

**Comment by 6AKU66** [comment]
> added another nil check [ad3d9a1](https://github.com/beyond-all-reason/Beyond-All-Reason/commit/ad3d9a127de3de052aad30b42e3f29569ac73883)

Should be live in 21072?

**Comment by 6AKU66** [comment]
Still affected @Ruwetuin
