### ISSUE TITLE
Units with selfdestructcountdown = 0 do not explode immediately

### ISSUE THREAD

**Issue by KyleAnthonyShepherd** [beyond-all-reason/Beyond-All-Reason#1329]
Self destruct is handled on SlowUpdate, but this causes units with a defined instant self-destruct time to randomly (to the player) take up to a half second to detonate. 

More consistent behavior could be achieved if units with selfdestructcountdown = 0 skip waiting for the SlowUpdate to detonate.

**Comment by Beherith** [comment]
see
Spring.[DestroyUnit](https://springrts.com/wiki/Lua_SyncedCtrl#DestroyUnit) ( number unitID [, bool selfd = false [, bool reclaimed = false [, number attackerID ]]] )
return: nil

    selfd := Makes the unit act like it self-destructed.
    reclaimed := Don't show any DeathSequences, don't leave a wreckage. This does not give back the resources to the team!

**Comment by sprunk** [comment]
steal from zk https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_instant_self_destruct.lua

**Comment by Beherith** [comment]
"Descruction" thank you sprunk!

**Comment by Beherith** [comment]
@Zecrus2  FYI this does have an impact on balance
