### ISSUE TITLE
Substituting during pre-game is buggy

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/Beyond-All-Reason#1334]
Substituting often ends up with shared control of a commander by two players, potentially a big advantage for that team. Sometimes subbing can still happen even after a player places their comm (the button stays red) and they are obviously not afk. If a player hasn't placed and is afk, the game must be forced to start, and an often undesirable start location is forced to the subbing player (which creates a disadvantage for their team). Another disadvantage for the subbing player's team is that they can't share resources or units or have resources shared to them, and a subbing player can't resign. In most cases where a player is afk, it's desirable to remake the game anyway.
I would ask the subbing just be disabled until it can be fully fixed or reimagined so that it isn't abused, on purpose or by accident, to allow for commander sharing.

**Comment by badosu** [comment]
cc https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1139 https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1141

Subbing is really broken

**Comment by badosu** [comment]
Subbing is currently unsupported afaik, this can be closed
