### ISSUE TITLE
SlowUpdate loading for long range artilery structures if it set fire at will (optimization request)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1337]
It's minor problem, but worth to look. For some reason only long range artilery structures have such relativity high loading.
![Снимок](https://user-images.githubusercontent.com/89547444/194111424-b2a82038-fcd4-439a-a3cf-544cfb3938b0.PNG)
![Снимок1](https://user-images.githubusercontent.com/89547444/194111473-fb6bc293-f036-4d43-8663-f4a3c8f9f02f.PNG)

**Comment by KyleAnthonyShepherd** [comment]
I think the AutoTarget routine runs every SlowUpdate, and long range arty covers most of the map, so more of the map, more units, have to be checked each SlowUpdate.

**Comment by 6AKU66** [comment]
> I think the AutoTarget routine runs every SlowUpdate, and long range arty covers most of the map, so more of the map, more units, have to be checked each SlowUpdate.

The thing is that even without any enemy units SlowUpdate still active. But short range weapons don't have it.

**Comment by KyleAnthonyShepherd** [comment]
Just did a test with range multiplier = 10, and that drastically increases every unit's SlowUpdate loading. 
But SlowUpdate loading seems to only scale linearly with the number of units, suggesting a high constant factor somewhere.
Adding more enemies does makes the loading way worse.

**Comment by 6AKU66** [comment]
Ah, yeah seems like long weapon range make a lot effort to AutoTarget loading... I don't know why i didn't come to test with multiplier .

**Comment by 6AKU66** [comment]
I think i will close this ticket since i thought SlowUpdate loading was anomaly. And we have more interesting case like: https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1270
