### ISSUE TITLE
Windowed mode behaving more like fullscreen and glitching out multi monitor setups

### ISSUE THREAD

**Issue by Corosauce** [beyond-all-reason/Beyond-All-Reason#1341]
Since the big new game engine update, borderless windowed mode acts like fullscreen and is also causing interesting glitches when alt tabbing out of the game.

See this video for the problem: [https://www.youtube.com/watch?v=7Zv8H4vGlSI](https://www.youtube.com/watch?v=7Zv8H4vGlSI)
Infolog: [20221006232640_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9740122/20221006232640_infolog.txt)

Issue can occur both in the lobby and in a match.

Engine version: 105.1.1-1214-gcf8d087

OS:
Edition Windows 10 Pro
Version 21H2
Installed on ‎7/‎6/‎2022
OS build 19044.1889
Experience Windows Feature Experience Pack 120.2212.4180.0

Hardware:
Processor Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz
GPU: AMD 6800 XT
Installed RAM 32.0 GB

**Comment by Corosauce** [comment]
Oops, messed up the formatting, it was there but just hiding, fixed xD

**Comment by Corosauce** [comment]
Accidentally found out via my other open issue it is the same commit: https://github.com/beyond-all-reason/spring/commit/128c68a78eabd70fef020be778fc679cbbfbd36e, see that issue for more info.

**Comment by SethDGamre** [comment]
Combining into https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1340#issuecomment-1272412644 as they both appeared at the same time on the same ancient game engine version and both apply to screen sizing.
