### ISSUE TITLE
Widget Unit Energy Icons crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1347]
[t=00:03:27.454000][f=0000008] Error in Update(): [string "LuaUI/Widgets/gui_unit_energy_icons.lua"]:230: Incorrect arguments to GetTeamList([allyTeamID])
[t=00:03:27.454000][f=0000008] Removed widget: Unit Energy Icons

21067

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/6c24d5a858dca3e530251edc0fc67535fafc1554
