### ISSUE TITLE
shields stop displaying after a period of time

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/Beyond-All-Reason#1350]
![image](https://user-images.githubusercontent.com/75929927/194776083-6b29a28d-0dbb-4d4e-989f-7bed29b0bb66.png)
![image](https://user-images.githubusercontent.com/75929927/194776123-984db497-554f-4492-bda2-a75f79082634.png)

[20221002053448_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9742417/20221002053448_infolog.txt)

**Comment by drivver44** [comment]
this started occuring after the engine update 
im unsure if its engine or game related however

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/ea0c7f4d31434ab812c41b550a25ce5dd219ebbc
