### ISSUE TITLE
Commander Stuck in Certain animation, causing massive emit-sfx (demo with BarB AI)

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/Beyond-All-Reason#1352]
Seems that the emit-sfx in the armcom_lus.lua seems to can get stuck in a certain 'frame'.
Emitting loads of particles.

I can be seen in this replay: https://cdn.discordapp.com/attachments/549286426026573833/1029075423058993232/20221010_163901_Tetrad_V2_105.1.1-1214-gcf8d087_BAR105.sdfz

Sovgut AI will get stuck on a mountain, but in a certain move-frame.
I think it's one of these 2 emit-sfx:

![image](https://user-images.githubusercontent.com/23189106/194935041-71e1335d-f1c3-41c1-b50d-3ecd898fafa1.png)

![image](https://user-images.githubusercontent.com/23189106/194935052-f218f311-55b8-4bda-9900-6132e3def80f.png)

How can we prevent this from happening?
Or at least make it so it can only spawn the effect once per second or so?

**Comment by icexuick** [comment]
With better AIs lately, this seems to have not been an issue anymore.

**Comment by SethDGamre** [comment]
Very old issue, I haven't noticed it either. It's probably resolved
