### ISSUE TITLE
Negative Resource Value on Scenario Loadout

### ISSUE THREAD

**Issue by Ezahiel** [beyond-all-reason/Beyond-All-Reason#1355]
Can confirm changing gadgets\game_team_resources.lua
On Preload, resolve Negative Resource Cap Bug in scenarios, and let load units loadout with all values, without going to Negative Resource Value when destroyed, that bugged gameplay of either AI or Player

function gadget:GameStart() <--- OLD

function gadget:GamePreload()
    -- reset because commander added additional storage as well
    setup()
end

**Comment by Beherith** [comment]
Thanks dude, you seem to have the fix pretty well covered, could you please make a pull request with your changes?

**Comment by Ezahiel** [comment]
> Thanks dude, you seem to have the fix pretty well covered, could you please make a pull request with your changes?

found root and other final change without messing global stats , or team resource send pull request for unit_scenario_loadout.lua ln44 GamePreload() to GameStart()
