### ISSUE TITLE
Shadow map size keeps resetting to 4096 even after changing its value through the settings menu.

### ISSUE THREAD

**Issue by totbuae** [beyond-all-reason/Beyond-All-Reason#136]
### Initial state ###
Begin with a `springsettings.cfg` which does not specify `Shadows` nor `ShadowMapSize`.

### After launching Chobby ###
```
[springsettings.cfg]
...
ShadowMapSize = 4096
Shadows = 1
...
```
Chobby adds `ShadowMapSize = 4096` and `Shadows = 1` if it doesn't find them in `springsettings.cfg`.

### After changing shadows to 2048 using the settings menu ###
```
[springsettings.cfg]
...
Shadows = 1
...
shadowmapsize = 2048
shadows = 1
...
```
The settings menu unconditionally adds `shadows = 1` (note the capitalization) and replaces `ShadowMapSize = 4096` with `shadowmapsize = 2048` (again, note the capitalization).

### After exiting the game and closing/relaunching Chobby ###
```
[springsettings.cfg]
...
ShadowMapSize = 4096
Shadows = 1
...
shadowmapsize = 2048
shadows = 1
...
```
Seems Chobby interprets `shadowmapsize` (all lower case) as being a different attribute than `ShadowMapSize` (CamelCase) and thus adds a redundant `ShadowMapSize = 4096`.

One solution would be to modify Chobby so it correctly interprets `shadowmapsize/shadows` as being the same attributes as `ShadowMapSize/Shadows`.

A better solution, in my opinion, would be to make sure that any code which writes to `springsettings.cfg` follows the same capitalization style.  This would solve an additional issue in which `springsettings.cfg` ends up with other redundant attributes: `Water/water` and `ShowFPS/ShowFps` and the previously mentioned `ShadowMapSize/shadowmapsize` and `Shadows/shadows`.

For reference, the capitalization Spring Lobby uses when adjusting settings through the `Edit > Engine preferences` dialog is:
`ShadowMapSize`
`Shadows`
`ShowFPS`
`Water`

BAR has a widget which dynamically sets water rendering to mode 4 when the map gets a crater deep enough to reach the map's water level. That widget would also have to be modified to write `Water = 4` instead of `water = 4`.

**Comment by Ruwetuin** [comment]
i ll fix with using capitals
