### ISSUE TITLE
Thor lighting chaining is incorrect

### ISSUE THREAD

**Issue by KyleAnthonyShepherd** [beyond-all-reason/Beyond-All-Reason#1362]
Due to the use of string.find in unit_lightning_splash_dmg.lua, armzeus chaining is overriding armthor chain behavior. 

Fixing this would significantly alter balance.

**Comment by Ruwetuin** [comment]
fixed code (but equalized Thor lightning chaining params to that of Welder) in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f056c7454d641e394265eec4a14c92c6c57de98f
