### ISSUE TITLE
unit_mex_upgrade_reclaimer.lua - bad argument

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1363]
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitFinished trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_mex_upgrade_reclaimer..."]:103: bad argument #4 to 'DestroyUnit' (number expected, got no value)
stack traceback:
	[C]: in function 'DestroyUnit'
	[string "LuaRules/Gadgets/unit_mex_upgrade_reclaimer..."]:103: in function 'UnitFinished'
	[string "LuaRules/gadgets.lua"]:1325: in function <[string "LuaRules/gadgets.lua"]:1323>
	(tail call): ?
	
	
1245 21108

**Comment by Ruwetuin** [comment]
never enountered this error before and has been working fine.

engine allows argument #4 to be nil

maybe something fishy with your setup, idk

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/pull/456

**Comment by Ruwetuin** [comment]
fixed in next engine version
