### ISSUE TITLE
game_team_death_effect.lua - got no value

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1372]
[EOH::DestroySkirmishAI(id=4)]
[EOH::DestroySkirmishAI(id=0)]
[EOH::DestroySkirmishAI(id=1)]
[Game::ClientReadNet] local skirmish AI "bot5" (ID: 4) being removed from team 1
[Game::ClientReadNet] local skirmish AI "bot1" (ID: 0) being removed from team 3
[Game::ClientReadNet] local skirmish AI "bot2" (ID: 1) being removed from team 5
LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_team_death_effect.lua"]:113: bad argument #4 to 'spDestroyUnit' (number expected, got no value)
stack traceback:
	[C]: in function 'spDestroyUnit'
	[string "LuaRules/Gadgets/game_team_death_effect.lua"]:113: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:882: in function <[string "LuaRules/gadgets.lua"]:880>
	(tail call): ?

1249; 21135.

**Comment by Ruwetuin** [comment]
fixed in next engine version
