### ISSUE TITLE
Unit_crashing_aircraft.lua - got no value

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1374]
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_crashing_aircraft.lua"]:120: bad argument #4 to 'DestroyUnit' (number expected, got no value)
stack traceback:
	[C]: in function 'DestroyUnit'
	[string "LuaRules/Gadgets/unit_crashing_aircraft.lua"]:120: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:882: in function <[string "LuaRules/gadgets.lua"]:880>
	(tail call): ?
	
1249 21141

**Comment by Ruwetuin** [comment]
fixed in next engine version
