### ISSUE TITLE
Artefact graphics at the launch of the parties

### ISSUE THREAD

**Issue by kazukyakayashi** [beyond-all-reason/Beyond-All-Reason#1376]
Hello,

After updating the game, I have a problem every time I play, once I arrive in the game I have a graphic artifact in the middle of the screen, it looks like a sprite / crater texture or impact and shapes.

![screen00034](https://user-images.githubusercontent.com/39823221/196218103-f7cda632-5214-4c91-9f42-824aae68b64c.png)

**Comment by Beherith** [comment]
We updated the engine with a lot of fixes, could you report back if this is still the case?

**Comment by Beherith** [comment]
Also, it kinda looks like a debug widget, atlas tester gl4 was enabled here...

**Comment by kazukyakayashi** [comment]
Problem solved after the update effectively :)
