### ISSUE TITLE
Display corruption + "[error] Spring failed with code: null" (in-game or spectator, crash on specific lava map)

### ISSUE THREAD

**Issue by liotier** [beyond-all-reason/Beyond-All-Reason#1381]
Hello ! On that lava map whose name I can't remember, as a spectator I encountered [this graphical defects](https://imgur.com/a/dhhfDo9).

In that same game, as a spectator, [I encountered a late-game crash - here are the logs](https://bar-infologs.s3.amazonaws.com/spring-launcher_1666043510492.log)

A second crash occurred earlier this this afternoon, also late-game but with a slightly different error code - also mentioning Spring (but I can't remember). But I was not encountering the graphical defects.

This is the first times BAR crashes on me... I suppose I'll avoid that specific map - the moving lava background may be too sophisticated for my old hardware and crusty Debian with geological layers of updates.

My BAR player handle is Gandhi.

**Comment by SethDGamre** [comment]
ancient issue. I've played this map plenty and haven't seen this problem before.
