### ISSUE TITLE
Error="[US::GetUnitVal] unknown get-constant 0

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#1389]
Error: [COBThread::ShowError] unitID=17291 defName=armaca error="[US::GetUnitVal] unknown get-constant 0 (params = 0 16 28579389 0)" (in scripts/Units/ARMACA.cob:IdleHover at 12f)

21184

**Comment by Beherith** [comment]
I thought i reverted this, any known reproduction method?

**Comment by 6AKU66** [comment]
I don't know

**Comment by 6AKU** [comment]
test
