### ISSUE TITLE
Not possible set target for radar targets

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1402]
https://youtu.be/DTTrKKL3Fbg

**Comment by 6AKU** [comment]
Honestly i don't know if this is bug, but pretty annoying thing.

**Comment by SethDGamre** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1486 I think this is related.

**Comment by saurtron** [comment]
@SethDGamre PR merged this should be now fixed.

**Comment by SethDGamre** [comment]
Once again, thanks for your work!
