### ISSUE TITLE
Unhardcode maverick/gunslinger xp scaling via customparams

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1411]
Add a customparams (e.g. `rangexpscale`) to [armmav](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/units/ArmBots/T2/armmav.lua) and unhardcode maverick check [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/73dabeeb16b98dc607534f55b1a7345a4054c11d/luarules/gadgets/unit_maverick_exp.lua#L55) and [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/73dabeeb16b98dc607534f55b1a7345a4054c11d/luarules/gadgets/unit_maverick_exp.lua#L29) by reading the unitdef.

**Comment by lonewolfdesignUK** [comment]
Hi there, I have completed the fix I believe. 

How would you recommend I upload?

**Comment by badosu** [comment]
Send a Pull Request, read more about it here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by badosu** [comment]
If you are unfamiliar and unwiling to learn how to send a Pull Request you can go through the file browser [here](https://github.com/beyond-all-reason/Beyond-All-Reason), click on the file you want to change and click on the pencil button to edit it in place.

**Comment by lonewolfdesignUK** [comment]
I have made a bull request :) https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1580
