### ISSUE TITLE
Widget Under Construction gfx GL4: attempt to call global 'RemoveHighLight' (a nil value)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1416]
[t=00:01:22.846000][f=0016609] [SpecTeamAction] local client 20 now spectating team 0 and allyteam 0
[t=00:01:22.849000][f=0016609] Error in VisibleUnitsChanged(): [string "LuaUI/Widgets/gfx_undercontruction_gl4.lua"]:43: attempt to call global 'RemoveHighLight' (a nil value)
[t=00:01:22.849000][f=0016609] Removed widget: Under Construction gfx GL4

Looks like it's happening when you try spectate for some player while being spectator.

**Comment by Beherith** [comment]
Hopefully fixed in latest :)
