### ISSUE TITLE
Widget Deferred rendering GL4: attempt to perform arithmetic on local 'unitHeight' (a nil value)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1418]
[t=00:04:09.485000][f=0039936] Error in UnitGiven(): [string "LuaUI/Widgets/gfx_deferred_rendering_gl4.lu..."]:1140: attempt to perform arithmetic on local 'unitHeight' (a nil value)
[t=00:04:09.485000][f=0039936] Removed widget: Deferred rendering GL4

**Comment by Beherith** [comment]
Related to units being given outside of LOS, fixed upstream.
