### ISSUE TITLE
Air defense target priority is not working

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1425]
https://youtu.be/yaymLptCh4o

**Comment by Beherith** [comment]
That video is too fast for me to identify how it differs from expected behavior :D

**Comment by 6AKU** [comment]
Yeah, it's too ADHD

**Comment by 6AKU** [comment]
I got it, it's was my mine mistake.

**Comment by 6AKU** [comment]
Ok, i updated video @Beherith

**Comment by Ezahiel** [comment]
@6AKU YUP its bugged always target fighters regardless of priority settings

**Comment by Ezahiel** [comment]
@6AKU @Beherith its this [gadget](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/unit_targetting_priorities.lua) 
, im looking at it now(and looking for problem with spEchos) , all I can say so far is that logic working fine with this [bit ](https://gist.github.com/Ezahiel/1144521f42e6db9edc75328dbbbf92fe)
Going to keep looking at it, as at the moment changing options doesn't change real AA behaviour

**Comment by Ezahiel** [comment]
So after dozen Echos found that [this bit](https://gist.github.com/Ezahiel/1144521f42e6db9edc75328dbbbf92fe#file-unit_targetting_priorities2-lua), is not getting called at all, therefore im 99% sure might be related to malfunction of Target Priority

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/80b16764e209f35a3a71f12facfca150c6cfe86a
