### ISSUE TITLE
BAR cannot start after update to 1.1779.0

### ISSUE THREAD

**Issue by quantuumsnot** [beyond-all-reason/Beyond-All-Reason#1437]
![bar bug cant start](https://user-images.githubusercontent.com/12394810/204161092-a21fc479-344b-46c8-a2b4-3b1725720d6f.jpg)

Picture shows everything. Clicked `Update`, and stopped working

**Comment by Beherith** [comment]
Please try uninstalling and reinstalling the whole game

**Comment by quantuumsnot** [comment]
Ok, this actually fixed the game -.-
