### ISSUE TITLE
Can't deselect units when cursor moves a miniscule amount

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#1454]
Not sure if this has been raised, but it's a very annoying new bug so I'd be surprised if it hasn't:

To deselect units, the usual action is to just left click anywhere on the map. If the cursor moves slightly, then the expected behaviour is for it to start making a rectangular selection, but the ultimate behaviour when left click is released is to still deselect the previous units. The issue occurs when moving the cursor only a very small amount, where it seems as if the game isn't recognising it as either a single click and release, nor a rectangular selection, and instead it keeps the previous units selected.

https://user-images.githubusercontent.com/1434248/208194816-396d2007-bb0c-4eae-91a6-9441fcf98116.mp4

**Comment by WatchTheFort** [comment]
@badosu Could this be related to smart select widget?

**Comment by badosu** [comment]
Yes, thanks for the video and reproducing it. I'll send a PR to fix

**Comment by badosu** [comment]
@Jazcash Sorry, but I can't reproduce it. I need more information. Can you send infolog and the settings you have on smart select? 
![2022-12-16T20:52:44,593568192-03:00](https://user-images.githubusercontent.com/347552/208209848-e4ca06e8-0ecb-4fce-bd99-5254f9b99206.png)

**Comment by badosu** [comment]
Ah, nvm, was able to

**Comment by badosu** [comment]
So, what happens is:

- Engine has a minimum drag threshold for selection, if the game wishes so it can make it infinitely small (but not 0 perhaps better), it's controlled by `MouseDragSelectionThreshold` and default is 4px.
- When you do a selection of say 3 px it is not recognized as a selection box, or better yet as an invalid selection box, so the smart select widget does not trigger (it keeps the same selection)

There are some possible solutions to this:

- Decreasing `MouseDragSelectionThreshold` for BAR
- Having engine return reason for invalid box on `Spring.GetSelectionBox`
- Some clever way with the smart select widget. I'll look into that for now

**Comment by badosu** [comment]
Ah, shit, I just remembered that MouseRelease engine behavior has builtin ownership logic (which it shouldn't have), that precludes me from actually doing a threshold check in the widget.

**Comment by badosu** [comment]
Done, not perfect but good enough. The complexity is annoying though

**Comment by badosu** [comment]
Thanks for reporting.
