### ISSUE TITLE
Heavy perf regressions since last week

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1466]
The lag when starting the game animation happens again now (this was addressed earlier), perhaps not preloading stuff anymore?

In some situations the performance is abysmal in a mild late t1 game, tried to run /profile but got a widget crash.

Infolog attached.
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10314475/infolog.txt)

**Comment by badosu** [comment]
I can't profile the widget consumption, the lack of preload or at least the start lag is present.

**Comment by sprunk** [comment]
Why close? Maybe somebody else can profile.
