### ISSUE TITLE
Snake torpedoes falling short when attacking floating HLTs.

### ISSUE THREAD

**Issue by totbuae** [beyond-all-reason/Beyond-All-Reason#147]
Snake torpedoes fail to score hits when attacking floating HLTs from the Snake's maximum range.

The torpedoes proceed in a straight line towards the HLTs' "sweet spot" but go ballistic and fall short following a parabolic trajectory before reaching their target. Maybe `flighttime` is too short?

**Comment by Lanndstrom** [comment]
Just checked this issue, and it worked fine to me. Shooting your own structures with any subs will cause the torpedo to miss, could that have been the issue?

![2021-02-04 13_19_15-Beyond All Reason (Spring 104 0 1-1714-g321b911 BAR)](https://user-images.githubusercontent.com/78264188/106898295-e9c0b380-66eb-11eb-8e7f-edfca6c1f541.png)

**Comment by Beherith** [comment]
I increased armfhlt colvol to extend below waterline. Use alt+v to see ingame. So possibly fixed.

**Comment by Beherith** [comment]
Also, it can fail much easer if you dont have LOS on FHLT

**Comment by Lanndstrom** [comment]
Is suspect that it probably is fixed. Tested loosing LOS while still attacking, and it still hit.

**Comment by Beherith** [comment]
yay
