### ISSUE TITLE
Coretex's wind turbine can be built using a grid, but Armanda's wind turbine cannot.

### ISSUE THREAD

**Issue by bc-lee** [beyond-all-reason/Beyond-All-Reason#1483]
Hello, first of all, thanks for the great game! I can't believe that this kind of game is FOSS.

BTY, I have a bug about the different behavior of wind turbines from Armanda and Coretex.

If I try to build multiple wind turbines using [Shift+Alt](https://www.beyondallreason.info/commands/grid-build-command), on Coretex, the game displays a grid and I can build multiple wind turbines normally. However, it doesn't show up when playing Armanda, and I can only build one turbine per click.

My game version is as follows:

Game: BAR-21919-67e4f34 Engine: 105.1.1-1354-g72b2d55105

**Comment by Beherith** [comment]
This is probably because the game remembers last grid spacing for each byilding type, and armwind got manually increased. See the keybinds on our discord, and you only need to reduce spacing on armwind

**Comment by bc-lee** [comment]
Oh, you're right. I didn't know that setting applies to individual buildings. Thank you for telling me.
