### ISSUE TITLE
Enforce maximum build grid spacing

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/Beyond-All-Reason#1484]
We repeatedly receive bug reports that grid build is not working, and every time the cause is that the grid spacing is larger than the view on screen, Enforce maximum grid spacing to be no larger than half a screen at the default zoom level.

**Comment by KyleAnthonyShepherd** [comment]
Or draw a line emanating out from the corner to the widely spaced out grid. 
Or some UI text at the grid corner along the lines of "Grid Spacing = X"

**Comment by Beherith** [comment]
I would indeed cap it at like 512 elmos max. (which is 32 build grid units)
