### ISSUE TITLE
Max Units option can't be set to less than 500

### ISSUE THREAD

**Issue by jasondunsmore** [beyond-all-reason/Beyond-All-Reason#1490]
When setting up a game, the Max Units option (under Advanced Options -> Restrictions) is limited to >=500. For example, when you enter 200 and then click Apply, the maxunits setting is 500.

I would like to be able to set it lower so that I can play a BAR game with more than three teams on a laptop with 12 GB of memory. 

Maybe the maxunits minimum could be 50 instead of 500?

**Comment by sprunk** [comment]
I'm not sure if memory is the bottleneck here or whether you'd even be playing proper BAR at that point.

**Comment by jasondunsmore** [comment]
I know the laptop is running out of memory because after BAR is killed, I look at the Linux kernel log and see that OOM (out-of-memory) killer has killed the BAR process.

We would probably end up playing with a maxunits of 200-300. I think that would add an interesting limitation that would require some different strategies. I'm not sure it'd be very playable with a maxunits of less than 50.

**Comment by sprunk** [comment]
> I know the laptop is running out of memory because after BAR is killed, I look at the Linux kernel log and see that OOM (out-of-memory) killer has killed the BAR process.

Yes, but I'm not sure if units specifically are the memory eater here. There is some overhead per live unit, some overhead for more complex units (a shooting mobile unit takes more mem than say a metal storage that just stands there), some overhead for larger map size, some overhead for elapsed game time etc. I don't think anybody measured this recently but a thousand units should be like a couple of megabytes tops.

**Comment by jasondunsmore** [comment]
I was mistaken. It's actually 10 GB RAM on my laptop.

BAR always runs out of memory late in the game when each team has nearly maxed out. 3 teams (1500 units total) is okay but not 4 teams (2000 units total). Larger map size does play a role in running out of memory. I have the graphics settings turned down all the way in case that matters.

My laptop has a crappy AMD Radeon Vega 8 graphics card. BAR is slow, but playable. Could this be the culprit with the memory issue?

You mentioned I might be doing something wrong in my system. Is there a list of things I can check?

**Comment by 6AKU** [comment]
> BAR always runs out of memory late in the game when each team has nearly maxed out. 

How are you sure that BAR always runs out of memory? Is there some message about this or?

**Comment by jasondunsmore** [comment]
Yes, I can see in the Linux kernel log that it's killed by the OOM killer.  https://neo4j.com/developer/kb/linux-out-of-memory-killer/

**Comment by 6AKU** [comment]
Units not should costs many RAM, but i never checked how many AI consume RAM.

**Comment by Ezahiel** [comment]
As far as i tested its not really units number but cmds (commands) number that eat Mem like crazy.

**Comment by jasondunsmore** [comment]
That makes sense, since the memory problem is much worse when we have AI teams in our game. The AI seems to queue up more commands than human players.

A lower maxunits setting would probably solve this memory issue we're having. I can't think of a downside to providing users the ability to set a lower maxunits.

Looks like it might be a one-line change:
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/21f1887db5ad34a263f8d262bfc6aaaf388ae444/modoptions.lua#L45

**Comment by sprunk** [comment]
> I can't think of a downside to providing users the ability to set a lower maxunits.

It's fairly unpolished. AI is unaware of the limit and doesn't play accordingly, PvE opponents like Scavs and Raptors might break because they fail to spawn key units, and even when played by aware people it warps gameplay to the point of being unrepresentative of the larger game. BAR seems to have a sort of policy where it's reluctant to make unpolished stuff easy to access. It might be fine to make a mutator with a lowered cap though, or something of the sort.
