### ISSUE TITLE
1495 Weird instant desyncs

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/Beyond-All-Reason#1491]
Instant desyncs are being reported in 1v1. This ticket is disorganised, but I am reverting to 1393, so it is best to write something.

Games.
- http://zero-k.info/Battles/Detail/1543938
- http://zero-k.info/Battles/Detail/1543970
- http://zero-k.info/Battles/Detail/1543982

Two of the games involve psanic. His issue seems to be having the wrong version of a map (bad map hash) and some new graphics error that takes out luarules. The error is possibly in how commander skins are drawn (with GL4). He says commanders have skins in 1393, so this is potentially a regression. The map version issue doesn't make much sense as it is a common MM map. Additionally, an instant desync occurred between two other players. Skel is the common thread of these, but the infolog doesn't say much.

There were pathfinding changes, was the path cache version bumped? This has to be done _every_ time there is anything which could be a pathfinding change, because path cache issues are hell.

Are the lua(rules/gaia) hashes supposed to match?

A bug that can be worked around by having everyone do something manually (eg redownload a map, or delete path cache) is not a solved bug for the purposes of deploying the engine.

psanic: https://pastebin.com/EdFKQSFH

Mine for replays:
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10447346/infolog.txt)

**Comment by GoogleFrog** [comment]
Skel: [Uploading infolog(21).txt…]()

**Comment by GoogleFrog** [comment]
[infolog(21).txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10447470/infolog.21.txt)

**Comment by GoogleFrog** [comment]
The comment "<HistidineStar> where my factory???" indicates that maybe luarules crashed for them as well. And (nil) in lua(Rules). But the engine is supposed to send luarules crash messages through the network to show up in the replay.

**Comment by Beherith** [comment]
CamelCase in RemoveGadget?
Lua error: Call failure] [LuaVFS::Include(synced=0)][pcall] file=LuaRules/gadgets.lua error=2 ([string "LuaRules/Gadgets/gfx_commander_skins.lua"]:472: attempt to call method 'Removegadget' (a nil value)) ptop=3 cenv=0
stack traceback:

**Comment by Beherith** [comment]
Also note:
[t=00:01:45.227429][f=-000001] [Nightvision Shader] Error: 0:15(6): error: could not implicitly convert operands to relational operator
0:15(6): error: if-statement condition must be scalar boolean
0:15(21): error: value of type int cannot be assigned to variable of type float
 
[t=00:01:45.763842][f=-000001] forceSingleThreaded, false

**Comment by sprunk** [comment]
> CamelCase in RemoveGadget? Lua error: Call failure] [LuaVFS::Include(synced=0)][pcall] file=LuaRules/gadgets.lua error=2 ([string "LuaRules/Gadgets/gfx_commander_skins.lua"]:472: attempt to call method 'Removegadget' (a nil value)) ptop=3 cenv=0 stack traceback:

That looks like a valid remark but that line is only reached if the shader fails to compile, and it didn't fail before.

**Comment by GoogleFrog** [comment]
Unsynced luarules can kill luarules entirely during loading, so it could desync.

> CamelCase in RemoveGadget?

Yes, I saw this yesterday but didn't push. The question is still why the shader is failing, for probably at least two people. Apparently it never failed before (if Removegadget is to be believed). I estimate it to have failed for about 10% of people.

**Comment by GoogleFrog** [comment]
More infologs http://zero-k.info/Battles/Detail/1543982

**Comment by Beherith** [comment]
@GoogleFrog did my shader fix help?

**Comment by GoogleFrog** [comment]
Yes. It was probably a luarules crash in the end.
