### ISSUE TITLE
Spring failed with code: null

### ISSUE THREAD

**Issue by scarf005** [beyond-all-reason/Beyond-All-Reason#1502]
![image](https://user-images.githubusercontent.com/54838975/213996748-e33d41a5-c838-4fcf-ae45-89b2453f1caa.png)

pressing start with fail with `Spring failed with code: null`

### Log
[crash log](https://bar-infologs.s3.amazonaws.com/spring-launcher-logs-20230123T083816053.zip)

### System info
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-58-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
```

**Comment by xelab** [comment]
Same here, my system :

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.1-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 15.5 Gio of RAM
Graphics Processor:  NVIDIA GeForce RTX 2070 with Max-Q Design

**Comment by xelab** [comment]
Now it's working, after reboot.
