### ISSUE TITLE
Wreckage and derbis metal values not adjusted if unit metal cost multiplier changed

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1507]
unit metal cost multiplier == multiplier_metalcost

**Comment by SethDGamre** [comment]
this appears to reference a lobby modoption that no longer exists. I couldn't find any existing references to it in the game code. Currently lobby options don't let you change the costs of units outside of unit tweaks and unit tweaks are not officially supported.

**Comment by hihoman23** [comment]
Correct, wreckage values should be adjusted in the tweak.
