### ISSUE TITLE
Commander's names is not adapted to changed FOV

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1519]
Commander's names looks too big with low FOV and looks too small with high FOV.
![screen01309](https://user-images.githubusercontent.com/116835691/216274940-41639f5a-579f-4c48-a4ae-434300c1791a.png)

**Comment by lonewolfdesignUK** [comment]
WiIl look into this :)

**Comment by SethDGamre** [comment]
any update on this?
I can't even find a setting to change my FOV in game.

**Comment by SethDGamre** [comment]
Will reopen upon request if someone finds a way to change FOV to reproduce this bug.
