### ISSUE TITLE
New wreck info doesn't update the metal value

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#1525]
![image](https://user-images.githubusercontent.com/1434248/217076382-8ce3cc0f-16a9-430d-a561-23482aa5258c.png)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/105555c28aaab3d93f2bb87e039f9ddcb28843d7
