### ISSUE TITLE
Address cormexp issue with activation changes

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1529]
I'm onto it, but anyone that can assist me understanding and addressing cormexp script is welcome.

In particular it deactivates itself when it finds an opponent

**Comment by badosu** [comment]
Ah, I see, the cormexp uses the ACTIVATION variable to start/stop firing, which also deactivates metal extraction.

**Comment by badosu** [comment]
I don't like that this COB variable is conflated with mex extraction, seems like an ugly hack. Trying to find a solution

**Comment by KyleAnthonyShepherd** [comment]
I'm working on updating the cormexp script now. 
The fundamental issue is it turns off extraction when it aims its weapon, but turret turn speed is directly proportional to its extraction rate. So it deactivates, sets its extraction rate to zero, engine calls into the script to tell it its extraction rate is now zero, and then the turret turn rate is set to zero.

**Comment by badosu** [comment]
Ok @KyleAnthonyShepherd Ill leave this one up to you then, I sent [this PR](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1530) as a mitigation but with balance implications.

Let me know what do you think is the best course of action.

**Comment by badosu** [comment]
Much appreciated @KyleAnthonyShepherd, thanks!
