### ISSUE TITLE
Scroll zoom speed option have no affect on zooming via page up, page down

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1535]
Scroll zoom speed option have affect on scrolling via middle mouse button, but it's not have affect on zoom speed performed via page up/page down.

https://youtu.be/oOC0E3M31g4

**Comment by badosu** [comment]
This is not a game issue, if you deem current zoom behavior on keyboard actions to be unsuitable please open an issue on engine with the expected behavior.

**Comment by SethDGamre** [comment]
Ok... So not something that can be done on the BAR side. It's been a while, let's close this one.

**Comment by badosu** [comment]
There's possibly something that can be done game side. But requires clarification
