### ISSUE TITLE
T2 core metal maker wreck looks like sea t2 meal maker

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1557]
What the title says

![2023-02-20T03:06:04,347761490-03:00](https://user-images.githubusercontent.com/347552/220024742-f2f67dfc-7c33-4537-b3e3-795f1c32d98b.png)

**Comment by Damgam** [comment]
Actually, this is old T2 metal maker model. They leave wrecks so rarely that nobody bothered to fix it. XD

**Comment by KyleAnthonyShepherd** [comment]
Made PR to resolve. 
Just fed the current model through Dr. Killinger

**Comment by badosu** [comment]
Thank you!
