### ISSUE TITLE
incompatible save-file specified

### ISSUE THREAD

**Issue by DmytroSokhach** [beyond-all-reason/Beyond-All-Reason#1561]
Hi All,
I'm attaching logs for convenience (with my user name removed)
[20230222173022_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10806707/20230222173022_infolog.txt)

Game version: Beyond-All-Reason - 1.1861.0

**Scenario:**
1. Yesterday I played the map
   a. Saved game
3. Today
   a. Updated the game
   b. Tried to load game

**Problem**
1. Saved game doesn't load
2. UI is stuck
3. Clicking any "Load" button does change sound track :-)

Q: Is there a way to downgrade to previous version of the game?

**Comment by sprunk** [comment]
> [t=00:07:10.742304][f=-000001] Warning: [LSH::LoadGameStartInfo][release=0] file "20230221_195123.ssf" saved by engine version "105.1.1-1538-gd2617f8 BAR105" incompatible with "105.1.1-1544-g058c8ea BAR105"

**Comment by DmytroSokhach** [comment]
I understand it is not super big problem, still just wanted to ask:
Is there a way to downgrade version, to be able to load saved file?

**Comment by Ezahiel** [comment]
> Is there a way to downgrade version, to be able to load saved file?

Yes there is, you can use [this](https://github.com/beyond-all-reason/bar_debug_launcher) , though I can not guarantee it will work. Bigger question would be , why would you like to do so?

**Comment by DmytroSokhach** [comment]
Thank you for answer. Closing.
