### ISSUE TITLE
Autogroup does not work on loading saved games

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1562]
What the title says.

See also: https://github.com/beyond-all-reason/spring/issues/655

**Comment by badosu** [comment]
#good-first-issue

**Comment by sprunk** [comment]
Why not `Initialize`?

**Comment by badosu** [comment]
Responded [here](https://github.com/beyond-all-reason/spring/issues/655#issuecomment-1440878117)

**Comment by badosu** [comment]
If you want the widget to be active before game starts that's ok. But if you specifically want to fix this issue while retaining the functionality (activating only when theres simulation going on) then Initialize does not suffice (at least on BAR)

**Comment by badosu** [comment]
Well, if that's deemed suitable for the game maintainers I won't argue.

**Comment by sprunk** [comment]
Note that this is not an issue with just loading. `/luaui reload` exists and has the same problems (which are caused by widgets initializing at arbitrary time points).

**Comment by sprunk** [comment]
The commit above is not yet merged, it's on the `sprunk-patch-2` branch.

**Comment by badosu** [comment]
@sprunk Do you intend to send a PR for https://github.com/beyond-all-reason/Beyond-All-Reason/commit/258acdaa189b01b22b0c16b0dfac1ad1d4a07200?

**Comment by sprunk** [comment]
It was written blind and I don't have the mana to test it properly.

**Comment by badosu** [comment]
@lonewolfdesignUK This is another simple fix to perform, basically check that https://github.com/beyond-all-reason/Beyond-All-Reason/commit/258acdaa189b01b22b0c16b0dfac1ad1d4a07200 works or any other fix you deem suitable (you can ignore my proposed suggestion).

**Comment by lonewolfdesignUK** [comment]
> @lonewolfdesignUK This is another simple fix to perform, basically check that [258acda](https://github.com/beyond-all-reason/Beyond-All-Reason/commit/258acdaa189b01b22b0c16b0dfac1ad1d4a07200) works or any other fix you deem suitable.

Awesome, thanks!!! @badosu will get working on it later.

**Comment by badosu** [comment]
Testing is a bit annoying, I never saved and loaded a game. You might have to ask people on how to perform it.

**Comment by hihoman23** [comment]
Is this issue still there?

**Comment by hihoman23** [comment]
Is probably linked to https://github.com/beyond-all-reason/spring/issues/1100
The autogroups actually save, but don't get applied to the units when the game starts

**Comment by badosu** [comment]
Not necessarily, the widget should be able to load the autogroups for units present on initialization after game starts.

**Comment by badosu** [comment]
Keep in mind autogroups are an internal state of this specific widget.

**Comment by sprunk** [comment]
A widget could assign units to their respective autogroups but not to the actual groups the units belonged to at save.

**Comment by badosu** [comment]
True, just saying those are orthogonal-ish issues.
