### ISSUE TITLE
Idle builders/Auto group icons are not clickable, if they are positioned on the very bottom

### ISSUE THREAD

**Issue by lolsteamroller** [beyond-all-reason/Beyond-All-Reason#1563]
![image](https://user-images.githubusercontent.com/7465747/221233548-9b7ac859-3fec-428e-bce9-2667c803c183.png)

Ever since de-cluttering the side (at least I found how to get elevation back), you can't click if the icons are at the very bottom (when units are deselected).

One workaround is re-enabling to have the block there, but moving cursor out of the map will disable it (not sure why, there is no downsides in showing -11k elevation). 

![image](https://user-images.githubusercontent.com/7465747/221234657-833f23b0-4c06-423e-8b0b-b516e0cbe048.png)

@Ruwetuin

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/b9a8a63a385fc99eb91a20ac86f0a9ca3897c0f9
