### ISSUE TITLE
Mouse Cursor and OBS Issues

### ISSUE THREAD

**Issue by NoahKarottu** [beyond-all-reason/Beyond-All-Reason#1577]
If I have OBS Studios open my cursor in game disappears and is only visible in the scene preview in OBS. If I am tabbed out, the cursor is detected on the game screen (with the in game cursor) , but when I tab in it disappears again. The cursor works as normal on all other screens and applications.
Also if I have HDR enabled when I close the game my brightness will be dimmed dramatically till I touch the brightness slider in my windows settings. 
Closing the game doesn't reset the brightness in the settings, just turns it down visibly.

**Comment by lonewolfdesignUK** [comment]
This may be linked to #1586 although not fully sure.

**Comment by SethDGamre** [comment]
I use OBS alot and typically have it running in the background while I'm debugging. I haven't had disappearing cursor issues. We're gonna need more data on your system settings.

Do you have cursor ghosting enabled?
Do you have an AMD graphics card? What are your specs?
Does your cursor fail to display under any other circumstances? 

Right now this issue isn't possible to debug unless the right dev boy happens to witness the same bug.

**Comment by SethDGamre** [comment]
This un isn't recreatable, didn't get a response. Will reopen upon request.
