### ISSUE TITLE
Game freezes completely during offline play when internet disconnects

### ISSUE THREAD

**Issue by DmytroSokhach** [beyond-all-reason/Beyond-All-Reason#1579]
I run normal Scenario campaign, which I assumed should be working offline.
Today my internet connection is quite not stable: breaks for 1-2 minutes 3-4 times in 1 hour.

Not sure why Internet is needed for BAR to work?

I've found this issue about launcher, not sure if it is related
https://github.com/beyond-all-reason/BYAR-Chobby/issues/168

**Comment by Beherith** [comment]
Ppease post your infolog.txt after such a freeze

**Comment by DmytroSokhach** [comment]
I've tried to reproduce the issue by switching Wi-Fi on and off, during the same level, but it worked fine.
I think I was misled by connection error in launcher, will explain step by step:

1. Launched game and started Scenario level
2. After around 40 minutes the game started freezing in a pattern:
   1. freeze for 1-10 sec
   2. play 1-2 sec
3. I was able to press "Save" button in top right menu
4. <kbd>ALT + F4</kbd>
5. Re-start the game Launcher
   1. Noticed connection error red text
   2. Waited couple minutes till router stabilizes DSL connection
6. Re-start the game Launcher, start the game and load previously saved game


Attaching 2 log files, for subsequent game starts in case it will help understand the issue.
I see some errors there, but those I read to be not related.

[1_20230310171412_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10948827/1_20230310171412_infolog.txt)
[2_20230310174613_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10948828/2_20230310174613_infolog.txt)

**Comment by DmytroSokhach** [comment]
Today loaded save and got small lags, 1-2sec, when those warnings appeared:

```Log
[t=00:01:10.338030][f=0139962] Warning: Bandwidth limit was reached for Maracon [packets delayed, 2834 sent]
[t=00:01:10.354116][f=0139962] Warning: Bandwidth limit was reached for Maracon [packets delayed, 3859 sent]
[t=00:01:10.364924][f=0139962] Warning: Bandwidth limit was reached for Maracon [packets delayed, 4884 sent]
[t=00:01:10.388227][f=0139963] Warning: Bandwidth limit was reached for Maracon [packets delayed, 5909 sent]
[t=00:01:10.406516][f=0139963] Warning: Bandwidth limit was reached for Maracon [packets delayed, 6934 sent]
```

**Comment by DmytroSokhach** [comment]
I think it is stalled, and no one else observed it. Closing.
