### ISSUE TITLE
Waterrendering broken on linux with AMD GPU (MESA RadeonSi)

### ISSUE THREAD

**Issue by ripper81** [beyond-all-reason/Beyond-All-Reason#158]
BAR is using bumpmapped waterrendering as the default. However this is unuseable if you are playing on linux with an AMD Radeon GPU using the MESA Drivers. Only a palin white field is displayed where water should be visible. Changing the waterrendering to another method in the advanced graphic options helps, but none of the other modes looks as good as bumpmapped water. Since BAR is using OpenGL it seems that there is bug with the MESA RadeonSi driver. I hope this will be fixed in the future.

**Comment by lhog** [comment]
Yes this is a known bug, but the origin is unknown as none of us has the same environment (AMD GPU + Linux).

If you feel like spending some time on that do us a favor: join Discord and reach out to the #engine channel there.

**Comment by spawel44** [comment]
It seems some of the game settings have gone and there are only two water rendering options: low, high. I have similar issue when I set it to high, but water is pink. I didn't have this issue at all in previous versions of the game with bumpmapped water and highest settings.
