### ISSUE TITLE
Optimize unit_xp_range_bonus.lua gadget

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#1581]
Some performance regressions might have been introduced on https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1580

Minimize callouts and overhead of the gadget with the following instructions (quoted from [this comment](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1580/files)).

> Instead of checking if `UnitDefs` and `customparams.rangexpscale` do a cache of unitdefs that have rangexpscale defined, like, for example:
> 
> ```lua
> -- on widget body (outside any function, will be initialized when code is loaded)
> local xpDefs = {}
> 
> for uDefID, uDef in pairs(UnitDefs) do
>   if uDef.customparams.rangexpscale then
>     xpDefs[uDefID] = uDef
>   end
> end
> 
> -- then in the place you check if attacker def is xpscale
> if xpDefs[attackedDefID] then
>   -- do stuff
>   
> -- at the same time if you need the value you already have it cached
> local xpscale = xpDefs[uDefID].customparams.rangexpscale
> -- do stuff with xpscale
> ```
> 
> Another optimization is to store the unitdefid directly on `updateList` so you don't need to call getunitdefid again later when iterating, e.g.:
> 
> ```lua
> -- function gadget:UnitDamaged(unitID, unitDefID)
> updateList[unitID] = unitDefID
> 
> -- then in the place where you need the unitdef data
> -- function gadget:GameFrame(n)
> -- ...
> -- for unitID in pairs(updateList) do
> -- ...
> local unitDef = xpDefs[unitID]
> ```
> 
> Remember this type of code does not run in a separate thread so any optimization you can do here is critical for the responsiveness of the game (and the fact we have TONS of widgets and gadgets, each accruing their own overhead, so any minimal performance improvement is welcome).

cc @lonewolfdesignUK

**Comment by lonewolfdesignUK** [comment]
I will work on this :)

**Comment by lonewolfdesignUK** [comment]
Implemented suggestions :) https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1582
