### ISSUE TITLE
Bug report game breaking: Cursor

### ISSUE THREAD

**Issue by Unluckyathecking** [beyond-all-reason/Beyond-All-Reason#1608]
My cursor does not show up making it impossible to play the game. Is there some easy fix for this. please help me.

**Comment by badosu** [comment]
Please upload infolog.txt, otherwise we can't address the issue.

**Comment by quonic** [comment]
It's due to cursor trails being enabled in Windows. https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2143

**Comment by djfremen** [comment]
Same with me. Not pointer trails. I'm guessing something else. Happened when I zoomed by accident and now permanently gone.

**Comment by djfremen** [comment]
Fix it! Wow. It was "Magnifier" in system settings. Totally repeatable on any system. Just enable magnifier, turned increment one and mouse completely gone from game until disabled.

**Comment by SethDGamre** [comment]
looks resolved
