### ISSUE TITLE
Spring crash after start the game with code 4294966293

### ISSUE THREAD

**Issue by JMauryy** [beyond-all-reason/Beyond-All-Reason#1642]
Greetings! So, I have installed the game in different ways, but the error keeps popping up. Any ideas? The error shows up every time I start the game. I have tried to look it up online, but I don't see anyone having the same issue and thanks for your help!

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/11067096/infolog.txt)

**Comment by TheDubiousLittleGoober** [comment]
dude i have the same problem if you find a solution please send it to me

**Comment by SethDGamre** [comment]
this was many game versions ago. issue expired.
