### ISSUE TITLE
invisible units and buildings

### ISSUE THREAD

**Issue by Frostedsun4011** [beyond-all-reason/Beyond-All-Reason#1644]
no units or buildings are rendering

**Comment by badosu** [comment]
Please provide more details (screenshots, infolog.txt, reproduction instructions), otherwise we can't really do anything.

**Comment by Frostedsun4011** [comment]
nothing but shadows show up on my screen for units buildings and only icons in the mini map for units. i can still slect and control everything but cants see them.

**Comment by Ezahiel** [comment]
> nothing but shadows show up on my screen for buildings and only icons in the mini map for units. i can still select and control everything but cants see them.

How to repro? As just tested engine test and didnt had any problems, beside its Engine Test not released engine version, as theres Player instead of your Nickname

**Comment by badosu** [comment]
Without infolog can be anything. Needs more information.

**Comment by StanczakDominik** [comment]
Is that on an AMD or integrated GPU? Sounds similar to an issue reported on discord.

**Comment by badosu** [comment]
Infolog.txt would answer that and many other questions.

**Comment by SethDGamre** [comment]
No infolog, no recreation possibilities... Impossible to debug.
