### ISSUE TITLE
Widget Health Bars GL4 ignoring hide interface feature (key F5)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1645]
![Untitled0](https://user-images.githubusercontent.com/116835691/227712789-87a5f970-fd8a-44f9-a7f8-7ccbb7c31f2a.png)
22607
1544

**Comment by Ruwetuin** [comment]
![2023-03-25 11_56_45-Beyond All Reason (Spring 105 1 1-1544-g058c8ea BAR105)](https://user-images.githubusercontent.com/11016921/227713009-1c72d246-d08e-4033-8757-68219e4e197e.jpg)

**Comment by 6AKU** [comment]
Oh. Probably i clicked on it by accident.
