### ISSUE TITLE
Crashing air constructors shown as idle (widget: idle builders)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1656]
![TESTTTTTTTTTTTTTTTTTTT2](https://user-images.githubusercontent.com/116835691/227943800-ea9b0652-9fdd-43ca-a2ab-60ecc6636329.jpg)

**Comment by hihoman23** [comment]
Can this be closed now?

**Comment by sprunk** [comment]
92aa4cd66ade11b08ac23dd8c36f64ffd1fd7136
