### ISSUE TITLE
Win11: Map differs from server version bug

### ISSUE THREAD

**Issue by derdodga** [beyond-all-reason/Beyond-All-Reason#1669]
When connecting a freshly installed BAR to a server, my friend always got a connection timeout with the reason stated in the title. Redownloading the Map from official BAR map repo does not change this. The MD5 hash compared to my clients map was identical though. My friend downgraded from Windows 11 to Windows 10, which made the game working again. Maybe there is some difference in a checksum-calculation on Win11 that makes the comparison fail?

Pastebin infolog:

https://pastebin.com/XujiaXP0

**Comment by p2004a** [comment]
I believe some hash calculation issuses were resolved in the last engine version. I will assume it's obsolte issue.
