### ISSUE TITLE
Anti-nuke may sometimes ignore raptors meteors

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1671]
https://www.beyondallreason.info/replays?gameId=28322464a39970490f1b66277597e0d6
AKU's base ~39:00.
https://youtu.be/5FOsNohE24k
![Untitled0](https://user-images.githubusercontent.com/116835691/228562863-2c143213-ebdc-4608-b58a-9c4f2a0d2747.png)

**Comment by SethDGamre** [comment]
link to the replay is too old to download it appears

unable to recreate issue EXCEPT it is possible for antinuke to be stuck reload state and not trigger defense when the raptor launches nukes. once its in the air it seems not to try to intercept again.

either way, issue expired. until we get a fresh replay or more bug reports
