### ISSUE TITLE
New bug: Placing T2 mex directly on the spot gets cancelled

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#1672]
When trying to place a T2 mex in the centre of the metal spot, the order now gets automatically cancelled as soon as it is issued. Tried this on a slightly older game version and it's not an issue, so must be a recent thing.

https://user-images.githubusercontent.com/1434248/228566292-8276a8ee-3e11-4033-8895-b6eb4e99e743.mp4

**Comment by badosu** [comment]
Ok, I was able to reproduce the bug, thank you!

**Comment by badosu** [comment]
Seems related to recent changes to rclick mex widget (still happens if you disable mex snap), I'll look at it.

**Comment by badosu** [comment]
Fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1674
