### ISSUE TITLE
In-game UI so large that it is unusable

### ISSUE THREAD

**Issue by mjk-gh** [beyond-all-reason/Beyond-All-Reason#1673]
While the lobby UI is scalable, the in-game UI does not seem to be (I tried various in-game window configs in the lobby ("Borderless", "Fullscreen", ...) to no avail). Every icon and menu is so ridiculously large that it renders the game practically unusable. That includes the loading screen (where some progress is shown in the lower middle, like "Finalizing models" etc.). See image attached at the end of this bug report -- which ironically shows the "Accessibility" tab being ... *drumroll* ... inaccessible. 🤦‍♂️️

Software:
- Current BAR [AppImage v1.1861.0](https://github.com/beyond-all-reason/BYAR-Chobby/releases/download/v1.1861.0/Beyond-All-Reason-1.1861.0.AppImage)
- Devuan (Chimaera = current stable version), 64 bit
- Xorg X server: package "xorg"/"xserver-xorg": 1:7.7+22, package "xserver-xorg-core": 2:1.20.11-1+deb11u6 
- fvwm3 1.0.5
- $ xdpyinfo | grep dots
  resolution:    96x96 dots per inch

Hardware:
- Ryzen 5 2400G with Radeon Vega Graphics
- Monitor with 1200 x 1920 (portrait orientation)

![gigantic-ui](https://user-images.githubusercontent.com/6675160/228607616-425c38b3-f910-4654-940e-2bfb84ae1068.jpg)

**Comment by badosu** [comment]
On settings -> interface there's a ui scale slider, did you try it?

**Comment by mjk-gh** [comment]
Thanks for the hint, but that slider (residing in the tab "Lobby") only changes the lobby UI scaling, the game UI stays unchanged.

**Comment by mjk-gh** [comment]
@WatchTheFort Aaaah, now I understand! Well ... the graphics tab is invisible (and its content only partially visible), that's why I did not try any sliders in it.

After hitting `Enter`, `/option uiscale 0.5`, `Enter`, much of the in-game UI scaled down to a more usable level.

However, there are many things that seem unimpressed by the uiscale command:
- Loading screen (after clicking "Start game" in single-player skirmish mode), so the nice hints are cut off left and right
- In-game:
  - Changes dialog
  - Keys dialog (additional bug: the dialog appears _under_ the build-command(?) icon-matrix on the left)
  - Settings dialog
  - All hover texts (over build-command icon, over stuff in the top menu, ...)

A few screenshots from after the uiscale command:

Loading screen:
![afterdownscale-loading-screen-small](https://user-images.githubusercontent.com/6675160/228935281-93e4daa7-0ba0-4cf3-a4a9-cb1470d14f4a.jpg)

In-game, settings dialog:
![afterdownscale-ingame-small](https://user-images.githubusercontent.com/6675160/228933237-6cc713b0-f178-4b68-861f-e3c9b334db32.jpg)

In-game, keys dialog:
![afterdownscale-keys-dialog-small](https://user-images.githubusercontent.com/6675160/228936701-5a3c6ab5-dbc5-459c-95e5-59dd7f4388e7.jpg)

**Comment by WatchTheFort** [comment]
@Ruwetuin Does anything jump out at you why certain widgets aren't obeying the UI scaling?

**Comment by mjk-gh** [comment]
> And nobody plays like the screenshot above.
Not if a game looks like this, indeed. ;-)

I know of a few casual gamers with portrait orientated monitors, as that format is perfect for a lot of tasks (editing text, chatting, surfing the web with its forums etc.). Portrait mode is just fine for RTS and various simulation games. The only drawback is that it is not well suited for an FPS, at least not if you are focused on competitive play. 

Games like
* [Warzone 2100](https://wz2100.net/)
* [Mindustry](https://mindustrygame.github.io/)
* [OpenTTD](https://www.openttd.org/)
* [0ad](https://play0ad.com/)
* [Tribal Trouble](https://github.com/sunenielsen/tribaltrouble) (you need to fiddle a bit, though, to get this old game to work in a modern linux environment)
* [Urban Terror](https://www.urbanterror.info/) (some texts appear a little stretched, but still readable) 
* and IIRC also a few Spring RTS engine games
work like a charm in portrait mode.

**Comment by SethDGamre** [comment]
Review requested: should we support portrait orientation?

**Comment by WatchTheFort** [comment]
@icexuick rmlui might handle this with CSS layouts, but do we plan on supporting portrait orientations?

**Comment by icexuick** [comment]
I think we will have all of our hands full on trying to find a proper/fitting layout for landscape screens.
We will try to make this work on a Steam Deck, but still landscape.

Testing RMLUI's power and also figuring out the best way to setup the framework/containers/zones will hopefully give more insight (and live results) on how flexible we can get.

Usually, as far as my web-dev responsive UI/UX goes, the jump between landscape and portrait is a big one.
It's usually requires a fully different setup.

I think our initial scope will be a NO on this, but if we succeed graciously and have power/time to config a portrait UI, then this might become a possibility. However it's in the same vein as "will this work on my PS5/XBox"?...

**Comment by WatchTheFort** [comment]
Closing as supporting portrait mode is not a planned feature
