### ISSUE TITLE
can't see my cursor ingame

### ISSUE THREAD

**Issue by Harmacist0** [beyond-all-reason/Beyond-All-Reason#1684]
my cursor dosent show up on the screen when im in the luncher or ingame and im not sure how to fix it. and ive tried uninstalling and reintalling but that didnt help either.

**Comment by SethDGamre** [comment]
this is over a year old and doesn't have any supporting debugging issues.

I think we should close this as there's no telling what caused it back then.

**Comment by hihoman23** [comment]
Maybe related to #2143
