### ISSUE TITLE
[Proposal] Remove the Upgrade Mex toggle

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#172]
I think the 'Upgrade Mex' toggle on T2 cons should be removed for the following reasons:

1. Due to the way this feature always tries to build the mexes in the center of the metal spot, constructors with this toggle enabled will reclaim buildings overlapping it in order for the T2 mex to be built perfectly in the center. This leads to unexpected and unintuitive behaviour. Case in point, new player few months ago had his T2 lab reclaimed when he wasn't paying attention because he built the lab next to his T1 mex when he turned the toggle on.
2. If the spot is blocked by an ally building, then I think the con will just reclaim your T1 mex and then leave? Could be wrong on that.
3. Again, because the T2 mex _has_ to be in the center with this toggle, it means T1 mexes will always be reclaiming first before building the T2 one. This means lost mining time and metal.
4. If manual placing isn't enough, the areamex and snap-to-mex widgets make upgrading to T2 quite easy already.
5. The command panel is already quite full and the space should be conserved for more useful things.

In my eyes, Areamex is just objectively better because it:

1. Acts like a regular command so can be chained and combined with other commands and modifiers (e.g. spacebar for split build).
2. Will build new extractors on unclaimed or lost metal spots
3. Will build the T2 mexes next to the T1 mex wherever possible, which means less accidental reclaiming of buildings
4. Won't reclaim the T1 mex, so no lost mining time
5. Has a hotkey
5. Is area draggable, which makes it more versatile for players to choose where they want to upgrade and in what order.

> if we're talking about fixing it instead of removing it, then it should probably be a lot smarter about it altogether. i.e. build next to it if possible, reclaim the t1 mex if it has to, always reclaim the t1 mex afterwards, reclaim cheap buildings like windmills/solars if that's the only way to place a t2 mex there etc
> if we're gonna have a built-in QoL toggle that's part of the command menu and not just an after-thought widget, it should probably be super robust and reliable

**Comment by PtaQQ** [comment]
![Uploading _20210130_092053.JPG…]()

**Comment by lhog** [comment]
Upload failed

**Comment by PtaQQ** [comment]
Fixed

**Comment by icexuick** [comment]
Latest intel - T1 mex has same footprint as T2 mex.
Upg mex should no longer be a problem.
