### ISSUE TITLE
FR: Source code and bugtracker at website

### ISSUE THREAD

**Issue by narcisgarcia** [beyond-all-reason/Beyond-All-Reason#1729]
This proposal is to link these developing resources at home website: www.beyondallreason.info

**Comment by narcisgarcia** [comment]
Why not? Or why no response?

**Comment by WatchTheFort** [comment]
Do you mean to put a link to the GitHub repositories on the website?
@icexuick thoughts?

**Comment by narcisgarcia** [comment]
> Do you mean to put a link to the GitHub repositories on the website?

Yes; both for bugtracking and code access.

**Comment by WatchTheFort** [comment]
There is currently a link to this GitHub repository in the site footer
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/36827423/921b1044-2864-4792-9eb9-fbc3b9f08790)

**Comment by narcisgarcia** [comment]
Logos bar means a requirement to common user:
Tho recognize Github, and to know what Github is for.

Better to link with "support" and "repository" labels.

**Comment by p2004a** [comment]
Opened https://discord.com/channels/549281623154229250/1152951788614471742 for Ice on Discord, as that's where he is actually looking.

**Comment by p2004a** [comment]
Check out the website now, this was updated and made more clear.

**Comment by narcisgarcia** [comment]
I see "Information" and "Development" links on header, but those links are not working on some web browsers.
Maybe due to 3rd party trackers dependencies (such as website-files.com and cloudfront.net)

**Comment by p2004a** [comment]
@narcisgarcia please provide more details, I'm not aware of any reports from other users that those menus don't work.

**Comment by narcisgarcia** [comment]
I must allow 3rd party trackers to do those links work as menus.
If you don't allow them, those elements completely don't work.

Tested M.Firefox, Brave, Iridium.

**Comment by p2004a** [comment]
What extensions are you using in Firefox? The website works correctly in clean Firefox. I need to replicate this.

If you yourself explicitly blocked those domains, that's wrong because those are generic webflow and aws domains for assets distribution. Sure someone can host their js code that does fingerprinting, but just because it's generic cdn anything legal can be hosted on.

**Comment by narcisgarcia** [comment]
No 3rd party tracker is generic. Althoug being useful scripts or fonts.

I (as meny others) block 3rd party trackers. Many antiviruses do by default, Firefox extensions, etc.
CSP-SOP policies care about this too.

2000's policies are obsolete for website development, overall if it's FOSS related (think in people who looks for FOSS games because of being more respectful to their privacy).

**Comment by p2004a** [comment]
Your understanding is wrong.

https://www.beyondallreason.info/ is build using https://webflow.com/. Webflow is hosting static assets on 2 domains:
- `d3e54v103j8qbb.cloudfront.net`, which is just a CDN bucket on the [AWS CDN offering]( https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html) That bucket is controlled by webflow that is hosting a bunch of static content. For our site, looks like only open source jQuery library is hosted there: so it makes sense that blocking that legitimate domain is breaking our site for you.
- `assets.website-files.com` which is cname to `d1r5qv5z4elg7c.cloudfront.net`, just another CDN bucket again maintained by webflow.

We are a client of Webflow, Webflow is a client of AWS. **None** of those entities are injecting any what you call "trackers" to our website, that's literally illegal.

We are going to continue using different infrastructure providers in BAR, whose we are paying customers, and it's not ad supported. Currently we are using AWS, Google Cloud, Cloudlare, BunnyCDN, OVH and many more, and that's not changing. We aren't going to run dedicated hardware on prem.

I'm not going to spend more time responding to your tickets if you aren't going to do due diligence on your side to try to understand explanations.
