### ISSUE TITLE
Game pauses and tries to catch up

### ISSUE THREAD

**Issue by vilius-p** [beyond-all-reason/Beyond-All-Reason#1730]
Game shows 'game paused' and then catching up to current game time being updated. 
Writing /pause in the console pauses the game for other players too. Repeating - unpauses. 
Other players still see the mouse colour hovering on the map, so technically the player is just suspended from taking any actions.

This happens when hosting and not hosting. Only way to come back into the game is leave and rejoin

**Comment by Ateya9** [comment]
This has been happening to my friend as well. It seems to happen randomly, and his game will never catch up to the current game time, effectively bricking the game.

**Comment by secastles** [comment]
Just happened to me in a 1v1 match with a friend. First time playing. Seems like a great game, but just kinda bricked about 30 min in with "Game Paused" and a catching up progress bar that eventually just disappears and the game goes nowhere. The person I was playing with was still in-game though and didn't even know anything happened.

**Comment by SethDGamre** [comment]
Old. Looks engine related. Many engine versions ago.

**Comment by eode** [comment]
Is happening to me currently.  Player on the same connection, with the same brand of laptop, has no issues.
