### ISSUE TITLE
Implement Flathub.org verification

### ISSUE THREAD

**Issue by loganmarchione** [beyond-all-reason/Beyond-All-Reason#1739]
Flathub.org just went live with a new verification system that uses blue-checkmark verification so that the community knows that the Flatpak app is official from the developer. 

The Flathub site has an [entire section of verified applications](https://flathub.org/apps/collection/verified). For example, look at the blue checkmarks on [LibreOffice](https://flathub.org/apps/org.libreoffice.LibreOffice), [Firefox](https://flathub.org/apps/org.mozilla.firefox), and [OBS](https://flathub.org/apps/com.obsproject.Studio).

You should implement Flathub.org verification for the [BAR Flatpak app]( https://flathub.org/apps/info.beyondallreason.bar).

Being verified would let users know that BAR is directly from the developer, not a third-party. There is a post [here](https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714) about how to get verified.

**Comment by Born2Crawl** [comment]
The team has discussed this [here](https://discord.com/channels/549281623154229250/549283190422896640/1101107047711379508), and unfortunately it requires to add a file "/.well-known/org.flathub.VerifiedApps.txt" to the main domain, which seems to be problematic with Webflow...

**Comment by loganmarchione** [comment]
I thought you could verify via GitHub repo? No?

**Comment by Born2Crawl** [comment]
When you start the verification process, it says "You'll need to prove that you have control of the app via a website on the app's domain **or** by checking access to the app's account on a source code hosting site", but then the only option provided is "Website verification: Create a page at https://beyondallreason.info/.well-known/org.flathub.VerifiedApps.txt containing the following token: ..."

**Comment by PerAstraAdDeum** [comment]
Hey there,

did anything change in regards of the verification requirements since this topic came up?

**Comment by p2004a** [comment]
Looks like Webflow just recently implemented needed change https://webflow.com/updates/expanded-well-known-file-support so we were able to verify the app.

**Comment by PerAstraAdDeum** [comment]
Just refreshed the Flathub page and indeed, Beyond All Reason is marked as verified. Nice, thank you! :-)
