### ISSUE TITLE
barb ai struggles with metal maps

### ISSUE THREAD

**Issue by matthiaskrgr** [beyond-all-reason/Beyond-All-Reason#1764]
I looked at some simplai vs barb ai matches to get a better feel for the game and I found that the `BARb` AI seems to struggle a bit with `SpeedMetal BAR V2` . 

It looks like the ai heavily prioritizes metal (aka "grab all you can get") which totally makes sense on a normal map, but here I saw it mine up to 1500 metal/s (while actually using only around 50-100 metal/s)  and STILL building metal converters, although its build power was actually limited by energy on this map and not by metal :D 

Beyond-All-Reason - 1.2124.0

**Comment by dzosz** [comment]
AI repo is https://github.com/rlcevg/CircuitAI/issues 
+ @rlcevg

**Comment by rlcevg** [comment]
Please try Engine Test, and select `dev` profile (`Testing AI`) when adding BARb ("gear" button).
Overbuilding metal converters fixed there. AI may still overbuild regular metal extractors though.

**Comment by matthiaskrgr** [comment]
Yes, looks better with `Testing AI` :)

**Comment by rlcevg** [comment]
Current stable engine was update, so now `Testing AI` should be same similar to default profile on metal maps
