### ISSUE TITLE
High usage of minimap widget while watching replay

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1787]
Steps to reproduce:
1. Start match at map flats and forests.
2. Move camera (scroll, zoom) until minimap widget start to have abnormal high usage (more than 5%)

![27095ae5770260ca](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/116835691/dd5c1911-82eb-435c-b7c2-edab84817f6a)

**Comment by SethDGamre** [comment]
unable to recreate, old enough to where I think others would have reported more of the same or it's been resolved between then and now.
