### ISSUE TITLE
No option to take other players after they leave

### ISSUE THREAD

**Issue by domburger** [beyond-all-reason/Beyond-All-Reason#1798]
Somehow since I started the game, I never got the option to take another player when they leave a game. I checked all the settings and found nothing wrong. Is this possibly a bug?

**Comment by SethDGamre** [comment]
this sounds more like a suggestion: "As a spectator, I want to be able to take over for players that resign from a match."
this feature doesn't exist right now and there's no plans that I'm aware of to add it. This isn't a bug. Could make for a good suggestion on the discord suggestions channel.

I'd say, mystery solved. Resolved.
