### ISSUE TITLE
Blocky graphics on Linux - AMD

### ISSUE THREAD

**Issue by matbon108** [beyond-all-reason/Beyond-All-Reason#1814]
I tried both ENGINE and normal I get the same effect as attached when zoomed out. As I gradually zoom in it becomes fine.
![photo_2023-05-29_10-27-20](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/54409685/e06d17b5-ff25-4ea9-87ca-ed8f23c8a93f)

Update:
I tested a bit more, it's not zoom related it's "elevation" related. If I zoom in it get fine and then as I move to hills or higher terrain it's starts flashing and getting blocky like the pic above

Happens on Wayland or X11.

Operating System: ArcoLinux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.4-1-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C91
System Version: 2.0

**Comment by N-Upchurch** [comment]
Same issue here on a 6800; running EndeavourOS / Arch

**Comment by Benn1x** [comment]
I have the same issue on Fedora Linux with a 7900 TX

**Comment by finesseseth** [comment]
Another here, currently on Manjaro, 6750XT, XFCE. Game installed from the flatpak.

**Comment by darkensk** [comment]
Same issue:

```
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

```
$ lspci -k | grep -EA3 'VGA|3D|Display'
0b:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3)
	Subsystem: Sapphire Technology Limited Radeon RX VEGA 56 Pulse 8GB OC HBM2
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

```

**Comment by lordofswarm** [comment]
I see the same issue on the steamdeck

**Comment by finesseseth** [comment]
I noticed my flatpak mesa version was different to my system version (23.0.3 system vs 23.1.1 flatak). After manually updating my system to 23.1.1 (not available in Manjaro repo's) the issue is fixed for me.

**Comment by matbon108** [comment]
I managed to narrow down the bug - It's related to "Map Edge Extension' - If you disable this it works fine without issues.

**Comment by PeanutsRevenge** [comment]
Oh, this is new.  I only discovered this fork a week or so ago and had that glitch.
Disabling Map Edge Extension is how I resolved it, so ... seconding that on AMD/Mesa Arch-based AppImage.

**Comment by finesseseth** [comment]
> I managed to narrow down the bug - It's related to "Map Edge Extension' - If you disable this it works fine without issues.

I've seen people say this in other places too, but for someone new to BAR where and how does one do that?

**Comment by matbon108** [comment]
> > I managed to narrow down the bug - It's related to "Map Edge Extension' - If you disable this it works fine without issues.
> 
> I've seen people say this in other places too, but for someone new to BAR where and how does one do that?

Start a game > F10 > Graphics > Advanced (top right) look around the middle of the screen by enviroment.
![Screenshot_20230609_102543](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/54409685/76309869-1e21-495f-849c-5d5673f56063)

**Comment by finesseseth** [comment]
Thanks @N-Upchurch and @matbon108, I miss-interpreted 'extension' as meaning add-on or mod so was looking elsewhere.

**Comment by wadael** [comment]
Same here. Workaround solved issue without even restarting game


```
0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c8)
	Subsystem: ASUSTeK Computer Inc. Cezanne
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

```
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: RENOIR (renoir, LLVM 15.0.6, DRM 3.52, 6.3.0-060300-generic) (0x1638)
    Version: 22.2.5
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 387 MB, largest block: 387 MB
    VBO free aux. memory - total: 13105 MB, largest block: 13105 MB
    Texture free memory - total: 387 MB, largest block: 387 MB
    Texture free aux. memory - total: 13105 MB, largest block: 13105 MB
    Renderbuffer free memory - total: 387 MB, largest block: 387 MB
    Renderbuffer free aux. memory - total: 13105 MB, largest block: 13105 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 18019 MB
    Currently available dedicated video memory: 387 MB
OpenGL vendor string: AMD
OpenGL renderer string: RENOIR (renoir, LLVM 15.0.6, DRM 3.52, 6.3.0-060300-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```






ryzen 5700G using dualscreen on mint 21.1 w/ k 6.3

**Comment by vliedel** [comment]
> > > I managed to narrow down the bug - It's related to "Map Edge Extension' - If you disable this it works fine without issues.
> > 
> > 
> > I've seen people say this in other places too, but for someone new to BAR where and how does one do that?
> 
> Start a game > F10 > Graphics > Advanced (top right) look around the middle of the screen by environment. ![Screenshot_20230609_102543](https://user-images.githubusercontent.com/54409685/244637058-76309869-1e21-495f-849c-5d5673f56063.png)

This worked for me, thanks!

**Comment by PeanutsRevenge** [comment]
I'm now able to use map edge extension without issue.  I don't know if it's a mesa update, engine update or what, but I tried it yesterday and worked fine.
Mesa 23.1.3-1
Kernel 6.4.1-zen2
BAR 23560-3b609b8
Engine 105.1.1-1821

Arch base, RX6600 GPU, AppImage install.

**Comment by abigrock** [comment]
> I'm now able to use map edge extension without issue. I don't know if it's a mesa update, engine update or what, but I tried it yesterday and worked fine. Mesa 23.1.3-1 Kernel 6.4.1-zen2 BAR 23560-3b609b8 Engine 105.1.1-1821
> 
> Arch base, RX6600 GPU, AppImage install.

I have a system with an RX6800 running Arch and can confirm the AppImage (installed via the AUR package) works fine with the Map edge extension option enabled. I tried the Flatpak version of BAR earlier this week on a NixOS installation and the graphical glitches were present with the same hardware. I suspect it was a newer version of Mesa that fixed it as well.

**Comment by p2004a** [comment]
This was issue with Mesa drivers, it's resolved now for some time.
