### ISSUE TITLE
Space-Left-Click Build behavior seems buggy

### ISSUE THREAD

**Issue by fibbert** [beyond-all-reason/Beyond-All-Reason#1820]
When using the Space Left-Cliick command to place a building into a build order, the builder unit moves to the "center" of the building that was placed (seems to move to the left click location), then is blocked from building, and moves randomly out of the way to build the unit that was requested.

The correct behavior would be to move to within the nano-lathing radius and begin building and not further.

Easily reproduced.

Select a unit (Commander) and set a build of a group of buildings (such as Wind Power) and then select a new building (eg: a lab) and use Space and a left click to insert that unit in the build order.

The Commander should not walk if the new unit inserted is within range to be built, but does.

BAR-23176-c6f09ec Engine105.1.1-1767-gaaf2cc3105

**Comment by SethDGamre** [comment]
I was unable to recreate this bug. I think it's been fixed in the time since this issue was made. Can close this.
