### ISSUE TITLE
Setting starting energy or metal to 0 may lead to negative values

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1822]
1. Set Starting energy or metal to 0.
2. Set game mode end = neverend.
3. Self-D commander.
Result: Negative values.

**Comment by SethDGamre** [comment]
can't reproduce
doubt it was resolved. But, damn, this is obscure

**Comment by SethDGamre** [comment]
Negative storage underflow from paralyzed storages being destroyed while paralyzed might need investigating however but that's a separate issue
