### ISSUE TITLE
Unhandled Exception immediately on open in Crossover

### ISSUE THREAD

**Issue by alanpaone** [beyond-all-reason/Beyond-All-Reason#1830]
I'm not sure if this is a crossover issue or a BAR one, but the game will not launch in Crossover 22.1.1, using bottles for win10, 8, or 7. The current version of BAR that I"m trying this is 1.2124.0, and I've attached the Crossover report for the Windows 10 bottle. 
[BAR win10 crossover bug report.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/11646584/BAR.win10.crossover.bug.report.txt)

**Comment by p2004a** [comment]
Unfortunately we don't support Mac or compatibility layers, none of the game engine developers uses Mac, nor we heard about anybody successfully running BAR on different compatibility layers on Mac.
