### ISSUE TITLE
context build doesn't work for offshore torp launcher with beaver and muskrat only

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/Beyond-All-Reason#1853]
How to reproduce: make a muskrat and a beaver (T1 amphibious cons), select LLT from the build menu (doesn't matter grid or reg), then hover the LLT build frame over water. It should turn into a torpedo launcher but doesn't. Behavior is correct for all other constructors that can build both LLTs and floating torp launchers.

**Comment by hihoman23** [comment]
This is now fixed in #2497

**Comment by sprunk** [comment]
74860d1ac5be3fbd9c34ec5d0440a74a95a09f36
