### ISSUE TITLE
arm sniper can have trouble shooting over hills if it hasn't lifted its gun

### ISSUE THREAD

**Issue by SteelBlueZK** [beyond-all-reason/Beyond-All-Reason#1857]
Due to engine physics, the query piece/flare piece of cannon weapons needs to have a 'clear shot' for a unit to animate to fire its weapon. armsnipe lets its arm hang low when there's no enemies nearby, and raises it very high when it is ready to shoot, which can cause a lowerer'd arm's flare piece to be below the horizon. A player can get around this by issueing an attack-ground command, that will cause the sniper to aim its gun, then cancel that and due to the gun being aimed it now discovers a firing solution to an enemy over the hill. Or the script can be hacked to return the 'aimfrompiece' piece instead of the flare piece dependant on the 'GunOpen' variable that (theoretically) tracks when the gun is aimed high.

Example shot on 8horses:
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/8924181/a48159e9-2110-4537-b039-3fa53ab56284)
This sniper close to the camera has the ship within range, and by all means should be able to fire at it. But the gun currently sits too close to the horizon, and cannot shoot from the un-elevated position and hit. (for completeness, the red dot is the gun flare position and the yellow dot is aimfrom/sweetspot of sniper)

relevant bos script:
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/scripts/Units/armsnipe.bos#LL903

I've never edited a bos script before I'm more familiar with lua scripts. Additionally, I don't know the animation-related tools used to generate the script.

**Comment by WatchTheFort** [comment]
@KyleAnthonyShepherd

**Comment by KyleAnthonyShepherd** [comment]
@SteelBlueZK, you have exactly the right idea to set the Query point to the more elevated AimFrom point (torso) when the sniper is all packed up (the GunOpen variable). 

https://github.com/ashdnazg/bos2cob
This is what I use to edit BOS/COB files.
You edit the .bos file in your editor of choice.
Call bos2cob.py (it uses Python2)
It should output the compiled COS file that the unit uses in game.
Also, while you have a dev $VERSION game running, you can use 
`/reloadcob armsnipe` to test the new COB file you compiled, without having to restart the entire skirmish.

**Comment by SteelBlueZK** [comment]
attached PR includes sneaky change to animation times.
-3 seconds after losing target, if laser is active, deactivate laser
-5 seconds after losing target, close gun

**Comment by KyleAnthonyShepherd** [comment]
Relevant PR merged in, closing
