### ISSUE TITLE
Add this game to Steam

### ISSUE THREAD

**Issue by Mart-Bogdan** [beyond-all-reason/Beyond-All-Reason#1878]
Flathub and manual download from web site is nice, but having it in Steam would be way cooler.

We can create some kind of fund to raise this $100 needed to create dev account on Steam.

**Comment by 6AKU** [comment]
Steam release on roadmap.
https://www.beyondallreason.info/development/steam-release

**Comment by c33s** [comment]
would be cool to keep this issue open until the game is release, so we can easily subscribe this topic
