### ISSUE TITLE
Missing executable

### ISSUE THREAD

**Issue by JDLewis77** [beyond-all-reason/Beyond-All-Reason#1882]
Hi.  I have been playing BAR on OpenSUSE Tumbleweed for a few weeks and Windows 11 before that.  I have done a few different installs and one bug that I have found is that the shortcut to the BAR executable dissapears from the Games sub-folder on the start menu (I am using Plasma for my desktop).  I am not sure why this is happening but I have not been able to find an executable file using the 'which' command or by browsing through the BAR installation directory.  I have only been able to start the game by activating the App Image file that I used for the initial installation.  Any ideas on how to fix this?

**Comment by JDLewis77** [comment]
Ah... It seems that as someone new to Linux I misunderstood what an 'AppImage' is.  I thought it was a type of installation file but after some reading it turns out to be more like a portable executable in Windows.  I have to admit I don't understand why it looks like installation media on most sites.  I guess I should have used the Flatpak instead.  It would be handy for people making the switch to Linux for this to be a bit more obvious both on download sites (as I have the same issue with Heroic) and in general documentation as 'AppImage' does come over as a form of installation media.

**Comment by p2004a** [comment]
I've posted proposal to update install instructions on website with https://gist.github.com/p2004a/365c263fb9b0f3a3b555ea14456284f7.
