### ISSUE TITLE
cannot unload enemy units into lava

### ISSUE THREAD

**Issue by matthiaskrgr** [beyond-all-reason/Beyond-All-Reason#1885]
I played round a bit on forge, had an abductor and picked up an enemy unit.
I wanted to drop it into a lava pool in order to get rid of it but the game wouldn't let me. :D

Is this because lava is just "spicy water" that deals damage over time and none-water units cannot be dropped into water or something like that?

Should players be able to drop enemy units into lava/water to destroy them?  :slightly_smiling_face:

**Comment by Jazcash** [comment]
It's a fun idea but you're right, lava is just spicy water and you can't unload units into water. Maybe could be revisited in the future if lava ever gets promoted to being a first-class citizen where it isn't just hacked water, but closing for now.
