### ISSUE TITLE
Scavengers game mode unplayable

### ISSUE THREAD

**Issue by esfaust** [beyond-all-reason/Beyond-All-Reason#1893]
I attempted to play Scavenger game mode on June 26th, ~1am EST, and received the error `"[string "LuaUI/Widgets/gui_scavstatspanel.lua"]:188: attempt to compare nil with number`

This seems to have rendered the gamemode unplayable - the scavengers never spawn.

[Line it is referencing](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/e039ccdc454210694a6611301a590f5040ddd903/luaui/Widgets/gui_scavStatsPanel.lua#L188)

This happened very early June 26th, and I had friends playing the gamemode successfully only ~4-5 hours prior, so it must be a very recent commit that caused this.

**Comment by drivver44** [comment]
this is now fixed
blame me for not changing one line of code 
damgam has fixed this issue
