### ISSUE TITLE
Player consistently stuck at 1 open skill rating

### ISSUE THREAD

**Issue by nielsgroen** [beyond-all-reason/Beyond-All-Reason#1953]
A friend of mine, under account name `SkipTheMaster`, has a consistent openskill rating of 1 on multiple(?) game modes. He is a lot better than a rating of 1. The impression is that, even after multiple consecutive wins, his rating stays at 1. 

But you guys have the hard data. Is his rating bugged?

**Comment by StanczakDominik** [comment]
I would point your friend towards https://server4.beyondallreason.info/teiserver/battle/matches/ratings - they can log in with a one-time code by typing $website into the lobby chat.

What's happening here is that the openskill rating displayed in the game is capped at a minimum of 1. The website will show their real, uncapped rating.

In other words, I'm afraid the only solution here for your friend is to *git gud*. 😜

**Comment by sprunk** [comment]
> the openskill rating displayed in the game is capped at a minimum of 1

That would then be the actual issue.

**Comment by StanczakDominik** [comment]
That always did strike me as a bit weird. I guess it might be meant to prevent harassment and ridicule of players on negative ratings.

**Comment by sprunk** [comment]
Offset ratings by 100 or something. So current 60 is displayed as 160 and current -10 is displayed as 90.

**Comment by nielsgroen** [comment]
That was indeed it: His skill is a fair bit higher than 1, but his match rating was consistently below 0 due to uncertainty. Thanks for the help!

**Comment by nielsgroen** [comment]
For future reference, the URL seems to have changed.
https://server4.beyondallreason.info/battle/ratings/Team
