### ISSUE TITLE
Stockpile limit bug

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#1955]
If you SHIFT+CTRL+rightclick a Juno, stockpile should go down to x/0 (disable) but it instead gets stuck making you unable to change stock limit anymore. Seems going out of range once gives the bug.

SHIFT+CTRL = "disable" x/0 stock
CTRL = ±20
SHIFT = ±5
ALT = currently nothing

This doesnt seem to be exclusive to Junos but all other stockpile units too.

I did manage to find how to fix it, you have to SHIFT+CTRL+leftclick once, then ure able to change stock again but you never should click SHIFT+CTRL+rightclick, that gives the bug. Going outside floor with any command.

Example x/19 + CTRL+rightclick = bugged again.

Edit: Propose a setting to control the limits you want to be persistent default per game. Example i might never need 99 juno missiles but only want 5 as default.

**Comment by sprunk** [comment]
Note, SHIFT+CTRL is just ±100.

**Comment by Damgam** [comment]
It's my code that handles these limits so i'll take a look later.

**Comment by Damgam** [comment]
Fixed but i have to wait till post-tournament to push it.
Thanks for report @MeSaber! <3

**Comment by MeSaber** [comment]
> Note, SHIFT+CTRL is just ±100.

Yea but Juno is max 99.
