### ISSUE TITLE
FR: Ask for target directory on first setup

### ISSUE THREAD

**Issue by narcisgarcia** [beyond-all-reason/Beyond-All-Reason#1968]
AppImage installs, updates and downloads studd to user's "Documents" directory.
Sometimes user has another disk volume with appropiate space, or even faster for games.
And sometimes "Documents" directory is a network drive, inconvenient for software or rapid i/o.

AppImage should ask where to install files on first run.

**Comment by p2004a** [comment]
Since last release, `$XDG_STATE_HOME` is used following [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Before then, it was Documents as you point out, and if launcher detects files there, it uses that location to not break existing installs.

So, it's following the standard behavior of Linux applications.

**Comment by narcisgarcia** [comment]
Thank you for attending this issue, but:
No answer for the request: Be able (user) to select target directory.

**Comment by p2004a** [comment]
1. You can set the directory be setting `$XDG_STATE_HOME` environment variable to what you want for application
2. You can also set the directory also by specifying `--write-path` argument to the application.

So there are already 2 separate options how you can set it.

**Comment by narcisgarcia** [comment]
1. Download Beyond-All-Reason-1.2470.0.AppImage
2. Open file "properties" and enable executable checkbox
3. Double-click on AppImage file

How to say it something about XDG_STATE_HOME or write-path ?

Note symlinks don't work on network folders and some other filesystems.

**Comment by p2004a** [comment]
There are many options

- Use the menu editing program in your distribution (or something like https://flathub.org/apps/page.codeberg.libre_menu_editor.LibreMenuEditor if your distro doesn't ship one) to add entry with correct invocation

- Create a `.desktop` file with correct invocation following some instruction from internet, e.g. https://www.baeldung.com/linux/desktop-entry-files

- Run from command line

  ```sh
  ./Beyond-All-Reason-1.2470.0.AppImage --write-path /some/path
  # or
  XDG_STATE_HOME=/some/path ./Beyond-All-Reason-1.2470.0.AppImage
  ```

- Create wrapper script that does it for you, e.g. `run_bar.sh`
  
  ```
  #!/bin/sh
  ./Beyond-All-Reason-1.2470.0.AppImage --write-path /some/path
  ```

> Note symlinks don't work on network folders and some other filesystems.

I strongly recommend *not* putting your home user directory on filesystem that doesn't support basic features like that, or overall putting it on networked filesystem. Putting BAR on networked file system is also pretty bad idea as it will very significantly slow down game load times (10k files to read)
