### ISSUE TITLE
commander stuck in metal extractor while building

### ISSUE THREAD

**Issue by ManabBala** [beyond-all-reason/Beyond-All-Reason#2011]
commander was building mex under him and got stuck.

![Screenshot (13)](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/94683653/47e5fa7c-c083-4f3f-ab83-25f0952f81de)

log link -  https://log.beyondallreason.dev/logs-20230806T1931-DzvmGSD4.zip

replay file: https://drive.google.com/file/d/1VR1916RgsngcDMDDMvV7nqNGa16ruGYv/view?usp=sharing

**Comment by WatchTheFort** [comment]
@robertthepie Looks like another victim of yardmap hackery

**Comment by marcushutchings** [comment]
Is there an Engine ticket about this? I think it is time that a better approach is taken.

**Comment by sprunk** [comment]
I think some recent changes do some sort of cruel abuse of yardmaps and add holes inside, so the engine is doing what it's supposed to when it lets you surround yourself with a mex such that you're in the hole.

**Comment by robertthepie** [comment]
While the questionable design of my yardmaps does in fact have a 2x2 space in the centre that allows units to get stuck inside of mexes, as well as an outer shell thin enough on t1s for units to push each other into the mex.
A mex being placed ontop of a commander seems to be unrelated to that. The smallest unit i'm aware of blocks a 2x2 area that even stackable yardmaps respect.
I'll look into moving the construction yardmap somewhere else for now
![YardmapsFix1Scrible](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/59885012/24f2fdb2-4f00-43ec-b2de-dc59ca1be27b)

**Comment by marcushutchings** [comment]
There should be no open/walkable blocks in the yardmap except around the edges. Extra yardmap block types were created  explicitly to deal with this issue. Leaving open yard map blocks will also mess up the pathing system.

**Comment by Ruwetuin** [comment]
should be fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2016
