### ISSUE TITLE
Models Not Visible

### ISSUE THREAD

**Issue by ShadowHawk0** [beyond-all-reason/Beyond-All-Reason#2047]
Hello.  I haven't played BAR in a long time, but today I decided to get back into it. I updated to the most recent version and hopped into a game. 

The models for structures and units are invisible/transparent. When I put the mouse over them, I can see their outline, but without that, the only thing visible is their shadow. It looks something like this:

![BAR Help](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/143293241/aebfd1fc-f5fd-4703-b3f6-f7ec1ad3bb33)

I restarted both the program and my PC, but I still can't see the models or units.

EDIT: People asked to see system specs. Here they are:

Device specifications:

     Processor: AMD Ryzen 5 3600 6-Core Processor, 3.59 GHz
     Installed RAM: 32.0 GB
     System type: 64-bit operating system, x64-based processor

After restarting, I also tried updating my AMD drivers. Here's what became of that:

![Drivers](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/143293241/3bc31b44-c8b6-4dc7-812a-7750fa61ff1d)

After updating AMD drivers, I uninstalled them and reset my PC again. Still no better.

**Comment by StanczakDominik** [comment]
We're probably going to need to see logs, and hardware information would be nice. My bet is on some outdated GPU drivers or some such.

**Comment by Damgam** [comment]
I'm gonna assume you have AMD graphics card, in which case, reinstall your graphics drivers.
You don't have to update them, just uninstall them and install fresh.
