### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by mongalong247** [beyond-all-reason/Beyond-All-Reason#205]
Line 29 in tips_en.lua

useReclaim = "Press E and drag a circle to quickly rEclaim all resources/wreckages.",

rEclaim - reclaim or Reclaim

**Comment by WatchTheFort** [comment]
Good eye. At some point I'm going to through and correct all the tips and other UI text.

**Comment by mongalong247** [comment]
> Good eye. At some point I'm going to through and correct all the tips and other UI text.

If you want some help let me know.

**Comment by sprunk** [comment]
It's on purpose because the hotkey for reclaim is E

**Comment by mongalong247** [comment]
> It's on purpose because the hotkey for reclaim is E

oh, that didn't stick out.  But it makes sense why the Repair one has the capitalized R then.

**Comment by sprunk** [comment]
If you didn't realize this then the line probably fails at conveying this well enough (but then it already says "press E"). I think ideally it would be something like "r <color=yellow> e </color> claim" but that might be too much hassle.

**Comment by mongalong247** [comment]
> If you didn't realize this then the line probably fails at conveying this well enough (but then it already says "press E"). I think ideally it would be something like "r <color=yellow> e </color> claim" but that might be too much hassle.

what about reclaim [E]?

You'd have to standardise that across all tooltips moving forwards.

**Comment by WatchTheFort** [comment]
I don't see the need to have hotkeys in tips at all, especially once editing keybinds is introduced.
