### ISSUE TITLE
Make unit defs and UnitDefs consistent

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/Beyond-All-Reason#2053]
In unit defs you've got (for example) `maxDamage`, and `maxVelocity` in elmo/frames, but in `UnitDefs` it's `health`, and `speed`in elmo/second. This makes development confusing. Change it so they use the same keys and units. Here's a checklist for what's currently available in the engine:

### Changes to be done in unit defs (`units/bla.lua` & some stuff inside `gamedata/`), simple name replacement
* maxDamage → health
* metalUse → metalUpkeep
* energyUse → energyUpkeep
* buildCostMetal → metalCost
* buildCostEnergy → energyCost
* unitRestricted → maxThisUnit
* name → humanName
* acceleration → maxAcc
* brakeRate → maxDec
* losEmitHeight → sightEmitHeight
* cruiseAlt → cruiseAltitude

### Changes to be done in unit defs, also involving a value change
* maxVelocity (elmo/frame) → speed (elmo/second)
* maxReverseVelocity (elmo/frame) → rSpeed (elmo/second)

### Changes to be done to `UnitDefs` (in widgets and gadgets)
* tooltip → description
* wreckName → corpse
* buildpicname → buildPic
* canSelfD → canSelfDestruct
* selfDCountdown → selfDestructCountdown
* losRadius → sightDistance
* airLosRadius → airSightDistance
* radarRadius → radarDistance
* jammerRadius → radarDistanceJam
* sonarRadius → sonarDistance
* sonarJamRadius → sonarDistanceJam
* seismicRadius → seismicDistance
* kamikazeDist → kamikazeDistance
* targfac → isTargetingUpgrade
* losHeight → sightEmitHeight
* wantedHeight → cruiseAltitude

@WatchTheFort always reacts with "🤪" to the current state of affairs so he's the first volunteer/assignee, but this is a relatively trivial task involving just finding and replacing text so anybody could do it.

**Comment by WatchTheFort** [comment]
What about feature and weapon defs (and armor defs and move defs)?

**Comment by sprunk** [comment]
Other def consistency not yet available in the engine. Some unit def tags are also still divergent. I don't think it's a reason to wait though because changes don't happen on any sort of schedule engine-side, and the game-side benefits of change are immediate.

**Comment by hihoman23** [comment]
I would be interested in doing this

**Comment by hihoman23** [comment]
Can this be closed now?

**Comment by sprunk** [comment]
Probably. More engine changes are upcoming but I guess I will reopen when that happens.
