### ISSUE TITLE
Negative metal total storage value.

### ISSUE THREAD

**Issue by Plagzor** [beyond-all-reason/Beyond-All-Reason#2054]
For some reason I decided to enjoy some suffering in nearly two hour long game on the map I hate the most.

Around 70m, my UI element for metal (metal storage bar?) extruded outside of the screen. Two minutes later (72m) I lost most of metal storage extending units/buildings and my metal stored became negative (range -0 to -500 with current value of -535, with income near +200 metal/s). Buildings started did not progress. 
Had to be donated storage to get into positive numbers.

Playing as yellow player - Plagzor.
![negativemetalstorage](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/112214063/1b4bb0a6-01f1-4908-95f8-cc5d69eb2faf)
[20230828_170512_Supreme Strait v1_105.1.1-1821-gaca6f20 BAR105.sdfz.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/12458292/20230828_170512_Supreme.Strait.v1_105.1.1-1821-gaca6f20.BAR105.sdfz.zip)

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/d6f99d1c-0eb9-454f-9bce-8c06033228bd)
Watching this monster of a replay. 71:14, I see this

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/3ab764d3-294a-497d-9150-547eb270bdeb)
This is the frame when things go wonky. 
Still have no idea what is going on

**Comment by Plagzor** [comment]
i5-3750, 16GB RAM, RTX 2070, Win 10
Could it be, that a random ray 'flipped' a bit on my local instance of the game, while other players have it correct in theirs? :)

**Comment by PeanutsRevenge** [comment]
You can find out by downloading the server's version of the replay and watching that, Plagzor.
https://bar-rts.com/replays/c8d3ec6429bd5bc21bdc55a2e9da53df

**Comment by sprunk** [comment]
That would have been a desync. I'd expect it's something like EMPed storage dying

**Comment by Plagzor** [comment]
Rewatched the server version.
- It is identical.
Tracked metal storage progression, doing headcount of buildings.
- No deviation until ~71:08
70:19 - last change from 7900 to 7800 (lost shipyard)
71:08 - Metal storage becomes 0 ( and bar goes somewhere where no bar have gone before). All units building stops as there is no metal available.
72:15 - Commander dies and metal storage becomes -535 no metal storage total change occurred prior to this, nothing died, been EMPed or build.  Bar is not still outside of the usual frame, but not extruding outside of the screen.
72:20 - T1 air factory blows up: value becomes -642. (Not sure if this value was in my version, but I'm not watching it second time. :D)

**Comment by Plagzor** [comment]
Im 99,9999% confident I did, as I removed all files before I copied in the downloaded file.

**Comment by KyleAnthonyShepherd** [comment]
I was watching server version too

**Comment by Ruwetuin** [comment]
i applied a probable fix
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/unit_stun_metal_storage.lua

**Comment by KyleAnthonyShepherd** [comment]
How does the fix work?
I suspected that gadget, because `Spring.SetTeamResource` is the only way to direct set storage values (even the engine just adds or subtracts from the storage value instead of setting it directly).
But I did not see anything around 71:08 that would have triggered `Spring.SetTeamResource`

**Comment by Ruwetuin** [comment]
its the only gadget that uses spring.SetTeamResource after gamestart and in a regluar game.

I noticed it lacked a nil check on one of its table, so it could set the value nil and that might have cause it to be set a 0 as a result
