### ISSUE TITLE
General unit control and design

### ISSUE THREAD

**Issue by izirayd** [beyond-all-reason/Beyond-All-Reason#207]
There is no key remapping mechanic, for example, none of the keys in the screenshot below can be reassigned:
![image](https://user-images.githubusercontent.com/20372478/109766487-48a01c80-7c07-11eb-806c-20c1cf5e4faf.png)

There is no way to move the GUI elements, below I have provided a screenshot of my monitor, the fact is that I have a huge monitor and only one minimap the size of a large palm of an adult man, because of this it falls out of the field of view of my eyes or requires me to concentrate on it. The correct position of the mini-map would be quite comfortable.

Here's another example, i can't move the chat input field.

![image](https://user-images.githubusercontent.com/20372478/109766803-b9473900-7c07-11eb-9d78-f8d92382d8d2.png)

There is not one reason why the information about the highlighted units in the lower left corner, and the general information about the health in the farthest corner - this requires a high concentration, in addition to moving the mouse to select a certain group of the squad, it requires an additional path of the mouse.

![image](https://user-images.githubusercontent.com/20372478/109767320-6d48c400-7c08-11eb-9418-5fab87fe9036.png)

The construction panel or the commands do not have information about the available keys bindings, moreover, the command panel will show them only when selected, but the panel below does not contain information at all.

![image](https://user-images.githubusercontent.com/20372478/109767595-d3cde200-7c08-11eb-8fce-77653653b4f8.png)

- Does it make sense to group buildings by type? As a beginner, I find it difficult to concentrate on their type.

**Comment by icexuick** [comment]
Works is being done on many fronts here.
Please check out our discord to get (or ask for) the latest intel.
