### ISSUE TITLE
Attack on move gadget have too high load on CPU

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2083]
https://bar-rts.com/replays/6ae6f8647386f642c146391a7a23a389 25:00 min mark
I didn't find a way to reproduce this bug.

https://discord.com/channels/549281623154229250/1149111516495356045

**Comment by Ruwetuin** [comment]
maybe the player was using "Improved Targeting" widget and it might apply a SET_TARGET cmd each gameframe glancing at its code

**Comment by 6AKU66** [comment]
Reopen if still occur.
