### ISSUE TITLE
Constructor not leaving factory

### ISSUE THREAD

**Issue by DomNomNomVR** [beyond-all-reason/Beyond-All-Reason#2088]
In this game, t1 cortex vehicle constructors weren't able to leave the factory.
https://bar-rts.com/replays/f1d606654ba5b0e61b5cddf51ea186db

There was no way of moving it out, seemed properly stuck. 
This kinda screwed over my entire build and probably caused the entire team to loose.

**Comment by SethDGamre** [comment]
replay expired. I believe this was a known issue and has been worked on and possibly resolved. But this ticket with its expired replay doesn't help that effort along anymore.
