### ISSUE TITLE
armason hovering-information error

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#2093]
Displays 'Closed: +117% Max HP' , seeing as there is no button to close nor as its attacked i guess this is an error.

**Comment by SethDGamre** [comment]
![image](https://github.com/user-attachments/assets/7748bb66-4eaf-47cb-b973-f8bd5c403a81)

the unitdef has damagemodifier = .46 which is where the bonus +117% comes from. What it needs is onoffable = true or something in the animation .bos script that makes it turn on and off based on specific triggers. This looks like an unfinished unit to me.

**Comment by SethDGamre** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3787 this pr will resolve or push this forward.

issue can be closed
