### ISSUE TITLE
Website repository

### ISSUE THREAD

**Issue by carstenjaksch** [beyond-all-reason/Beyond-All-Reason#2125]
Hi, I would like to contribute to the website, but can’t find a repository for it.

Would love to help you guys out a bit, even though I can’t play the game currently.

**Comment by Jazcash** [comment]
The website actually doesn't have a repo, it's built using Webflow. There's a subsection of the site for replays, leaderboard and battle list which _is_ under version control and hosted on a separate site, injected into the main site through an iframe. That site is https://bar-rts.com, repo is https://github.com/Jazcash/bar-live-services and https://github.com/Jazcash/bar-db
