### ISSUE TITLE
Savegame

### ISSUE THREAD

**Issue by teodio** [beyond-all-reason/Beyond-All-Reason#2154]
Hey,
nach dem Laden eines Savegames zerstört sich der Commander. Hatte ich jetzt schon ein paar mal. Ohne ersichtlichen Grund. 
Gibts da schon Lösungen?

Hey,
after loading a savegame the commander destroys itself. I've had this happen a few times now. Without any apparent reason. 
Are there already solutions?

**Comment by SethDGamre** [comment]
Oof. A year ago without recreation steps. 

I tried reloading a save 10 times with commanders up in there. No explosions. Maybe this is an issue that got resolved somehow in the last year and a half.

I'd mark this as resolved and wait for a bug report to reoccur (if it reoccurs)
