### ISSUE TITLE
unit_paralyze_damage_limit.lua error when EMP rework is not enabled

### ISSUE THREAD

**Issue by salinecitrine** [beyond-all-reason/Beyond-All-Reason#2163]
Introduced in https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2159

See the relevant changes [here](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2159/files#diff-659ca4d939be93d401b594e326b32c6d95c5f4a7f396a02b22c70b801c3b7128)

---

`unitOhms` is initialized only if EMP rework is enabled, but `local ohm = unitOhms[uDefID]` and `local thismaxtime = weaponParalyzeDamageTime[weaponID] * ((ohm == 1 and 0.75) or ohm)` are run even if EMP rework is off, causing this error every time an emp weapon hits:

```
[string "LuaRules/Gadgets/unit_paralyze_damage_limit.lua"]:83: attempt to perform arithmetic on local 'ohm' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_paralyze_damage_limit.lua"]:83: in function 'UnitPreDamaged'
	[string "LuaRules/gadgets.lua"]:1636: in function <[string "LuaRules/gadgets.lua"]:1624>
	(tail call): ?"
```

Possibly this causes the lag mentioned in https://discord.com/channels/549281623154229250/1166178770089148426/1166178770089148426 , but I don't know for sure.

**Comment by salinecitrine** [comment]
@TheSilverHornet

**Comment by badosu** [comment]
This can be closed

**Comment by marcushutchings** [comment]
If the revert was the permanent fix, then yes this ticket should be closed; otherwise if it is a temporary fix, then this issue whould remain open so that a permanent fix can be researched, applied and documented here.

**Comment by badosu** [comment]
It is a permanent fix for the issue introduced by the PR.

The PR should be resubmitted accounting for the offending behavior.

This particular issue can be closed, unless the scope is not the fix but to also have the intended feature.
