### ISSUE TITLE
Posting a tweakunit on a tweakdef will crash the game

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#2189]
This [pcall](https://github.com/badosu/Beyond-All-Reason/blob/badosu%2Frework-gridmenu/gamedata/unitdefs_post.lua#L226-L229) seems to not be doing its job in this situation. Might be only reproduceable on autohosted games

# How to reproduce

Assign `ewphcm1wdyA9IHsgYnVpbGRDb3N0TWV0YWwgPSAxMCB9Cn0` to tweakdefs

**Comment by Beherith** [comment]
Does it throw anything into infolog, and or provide a stack trace?

**Comment by badosu** [comment]
Most likely, I haven't really checked in a while, might be able to post one here when I get the chance. The crash is not engine side I think. The room is unrecoverable in spads

**Comment by Beherith** [comment]
Do tell which host crashed, so I can try to fish out the infolog :)

**Comment by badosu** [comment]
Oh, this was at least a week ago, I just remembered now to create the issue

**Comment by badosu** [comment]
Just tested, game hangs at:

```
[t=00:00:14.128254][f=-000001] Warning: [CSMFReadMap::CreateSplatDetailTextures] Invalid SMF splatDetailTex maps/iwantDNTS.tga. Creating fallback texture
[t=00:00:14.534750][f=-000001] [~ScopedOnceTimer][Game::LoadMap] 3868ms
[t=00:00:14.534866][f=-000001] [LoadScreen::SetLoadMessage] text="Loading GameData Definitions"
```

Room is unrecoverable

**Comment by Beherith** [comment]
Which room was it?

**Comment by Beherith** [comment]
It should have, at that point, emitted:
```				
    Spring.Echo("Error parsing modoption", name, "from string", postsFuncStr, "Error: " .. err)
else
    Spring.Echo("Loading tweakdefs modoption", append or 0)
    Spring.Echo(postsFuncStr)
```
				
So I'm thinking its failing before that, here:
`			local postfunc, err = loadstring(postsFuncStr)` 

The above string looks more like a tweakdef than a tweakunits by the way.

**Comment by Beherith** [comment]
Hmm, that isnt even valid for loadstring:

```
local s = [[
{
armpw = { buildCostMetal = 10 }
}
]]

local postfunc, err = loadstring(s)

print(err)
```
`[string "{..."]:1: unexpected symbol near '{'`
