### ISSUE TITLE
Don't target flyover nukes gadget can lag and crash game

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2191]
1. Spawn 100 nukes for team 0;
2. Spawn 100 antinukes for team 1;
3. Stockpile it;
4. Launch all nukes to an area not covered by antinukes.
Result: game start to lag for 5-15 seconds with a chance to crash.

**Comment by hihoman23** [comment]
Is this fixed now?
The lag for me is barely noticeable and I have a laptop that has low specs

**Comment by 6AKU66** [comment]
I tested, it's much better now. Only 0.5-1 second lag.
