### ISSUE TITLE
Volume issues

### ISSUE THREAD

**Issue by PyTaldan** [beyond-all-reason/Beyond-All-Reason#2205]
The game starts at 100% volume, despite previous settings. It should never default to 100% volume

**Comment by SethDGamre** [comment]
![image](https://github.com/user-attachments/assets/be215e4a-288b-4013-94ea-65b8185a901b)
before restart

![image](https://github.com/user-attachments/assets/be27e760-5e5a-4fb9-96e6-7a133ff5853e)
after restart.

Sounds to me like a user-side issue. Maybe it has to do with lack of write permissions granted to BAR?
Either way, this is an old problem I don't have any hope of recreating. I'd like to mark this as resolved.
