### ISSUE TITLE
Default action for right clicking builders on other builders

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#2206]
Currently, when right clicking a builder on another builder, the command used is guard, _unless_ the target builder is not full HP, in which case the command becomes repair. However, the guard command already makes the unit repair the damaged unit anyway, before continuing with whatever else the guard command does, so I believe it's just strictly better for the default right click command to always be guard. Otherwise, if the target builder is 99% HP, and you right click it with other builders, they will heal it to 100% and then become idle.

**Comment by sprunk** [comment]
steal from zk https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_default_commands.lua
