### ISSUE TITLE
Saved game reload , causes self destruct to all commadores and game ends

### ISSUE THREAD

**Issue by mfouadthabet** [beyond-all-reason/Beyond-All-Reason#2213]
Single player mode , load game.
started to happen only one week ago , random maps , some saves work fine , but mostly after loading all commanders self destruct same like when game end and players exit.
[20231109161400_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13310448/20231109161400_infolog.txt)

**Comment by hihoman23** [comment]
Closing, if this is a mistake reopen #2154
