### ISSUE TITLE
[Bug] Autogroup immediate mode: Off - Builders don't get autogrouped after first idle on creation

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2221]
### Short description

Builders don't get autogrouped after going idle next to factory after creation, with "Autogroup immediate mode: Off". Tested with Armada Construction bot and Butler. It does work for Lazarus and army units in general.

They get autogrouped as expected on the next idle (e.g. after moving them 2 meters).

Video example: https://monosnap.com/file/LU5x8IgxW4p83qIgu0EFbzFpGTBiG0

"Autogroup immediate mode: Off" is borderline unusable because of this.

### Other (optional)

Might be related to the default builder rally point, although Lazarus use the same default builder rally point and work fine.

**Comment by badosu** [comment]
Can't reproduce, if you have the option of builders automatically guard factory they'll never be idle so the autogroup will never trigger. Can you verify?

**Comment by sprEEEzy** [comment]
You're right, I had it on. It's a bit of an inconvenient interaction for Butlers, but it does make sense.

**Comment by sprEEEzy** [comment]
You're right, I had it on. It's a bit of an inconvenient interaction for Butlers, but it does make sense.
