### ISSUE TITLE
New Option: Disable command auto-repeat for single unit when Shift is held

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2223]
### Short description

Current implementation: Game always auto-repeats (100+ times per second) commands while right click dragging with a single unit. It queues them up, like you're holding shift, creating hundreds of waypoints. This behavior is fine (and desired?) if you're not holding shift. However, it does the same exact thing if you're holding shift.

### Problems this will solve

Why could this behavior be a problem? If you're trying to do **fast shift - right clicks** to issue an accurate command queue to your unit, like a delicate move around a hill, this feature gives you **2-3x more waypoints than you'd want**, and you could end up crossing over the hill, instead of going around it. Your units can also get stuck trying to reach unreachable areas.

**Proposed solution:**
New Option in settings: Disable command auto-repeat for single unit when Shift is held.

This way, when you're holding Shift, you can fully control the amount of waypoints you're issuing, eliminating unwanted waypoints inbetween desired ones.

### Other (optional)

This only applies to single units, as right click drag with multiple has a completely different behavior (formations).

**Comment by sprunk** [comment]
The same happens if you want to queue buildings quickly and do it too fast, resulting in redundant copies:
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/2573076/4daed9d3-3eed-4ecf-8849-400b310bbe98)

This variant is harder though because shift repeats by design.

**Comment by sprEEEzy** [comment]
Correct, I ran into that issue quite a few times in live games - especially with small turrets and radars.

**Comment by thehobojoe** [comment]
Could this be addressed similarly to the drag threshold work that was done earlier this year for area commands etc? This setting was added for experimentation, but then removed when a reasonable default was found. https://github.com/beyond-all-reason/Beyond-All-Reason/commit/21c80b284e25229cdafc53a0f03c274c226e1d9e.

**Comment by sprunk** [comment]
Drag threshold should probably also have a way to involve time rather than moved pixels.

**Comment by PtaQQ** [comment]
Item approved by the Game Design Team (as an option default off)
