### ISSUE TITLE
[FR] Increase Max Move Speed of edge scrolling

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2230]
### Short description

Max move speed feels too slow on 1440p, even at max setting of 50 (compared to what some players are used to in SC2 / AoE2 / Dota 2 / LoL / etc)

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/634ec5e9-8c27-4fe5-8bfe-43faa9de3fc0)

### Problems this will solve

**Proposed Solution:**
Make it go to at least 100.

**Comment by badosu** [comment]
### Proposed fix:

```
		{ id = "cameramovespeed", group = "control", category = types.basic, name = widgetOptionColor .. "   " .. Spring.I18N('ui.settings.option.cameramovespeed'), type = "slider", min = 0, max = 50, step = 1, value = Spring.GetConfigInt("CamSpringScrollSpeed", 10), description = Spring.I18N('ui.settings.option.cameramovespeed_descr'),
```

On `gui_options.lua` check and change max value.

**Comment by sprEEEzy** [comment]
I've tried it, 100 is very fast, but seems like a good max value.

**Comment by badosu** [comment]
@sprEEEzy Can you confirm you use the same changes as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2346 ?
