### ISSUE TITLE
how to set language in GUI setting?

### ISSUE THREAD

**Issue by samgod1995** [beyond-all-reason/Beyond-All-Reason#2240]
### Short description

When I first saw this game, it really amazed me.But when I read a lot of new English words in a long game time, it is very difficult for me.So, can anyone here tell me how to switch the language of the GUI display? Thank you very much.

**Comment by WatchTheFort** [comment]
Multi-language support is still under development, but if you activate developer mode by entering `/devmode` in the in-game chat, you can switch language from in the developer tab in settings.
