### ISSUE TITLE
Missing unit language entries noising up the logs

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/Beyond-All-Reason#2241]
A number of units (mostly generated scavs) lack language entries, which pollutes the infolog every load.
This is doubly bothersome as it noises up with the word 'error' 29 times each load, making it a royal nuisance when developing things and searching for causes of misbehaviour.

[t=04:19:12.025095][f=-000001] [i18n] Warning: "units.names.armminebomber" is not translated in en
[t=04:19:12.025146][f=-000001] [i18n] Error: No translation found for "units.names.armminebomber"
[t=04:19:12.025357][f=-000001] [i18n] Warning: "units.descriptions.armminebomber" is not translated in en
[t=04:19:12.025375][f=-000001] [i18n] Error: No translation found for "units.descriptions.armminebomber"
[t=04:19:12.039135][f=-000001] [i18n] Warning: "units.names.corvacct" is not translated in en
[t=04:19:12.039354][f=-000001] [i18n] Error: No translation found for "units.names.corvacct"
[t=04:19:12.039406][f=-000001] [i18n] Warning: "units.descriptions.corvacct" is not translated in en
[t=04:19:12.039510][f=-000001] [i18n] Error: No translation found for "units.descriptions.corvacct"
[t=04:19:12.045021][f=-000001] [i18n] Warning: "units.names.raptor_worm_green" is not translated in en
[t=04:19:12.045177][f=-000001] [i18n] Error: No translation found for "units.names.raptor_worm_green"
[t=04:19:12.045239][f=-000001] [i18n] Warning: "units.descriptions.raptor_worm_green" is not translated in en
[t=04:19:12.045506][f=-000001] [i18n] Error: No translation found for "units.descriptions.raptor_worm_green"
[t=04:19:12.047881][f=-000001] [i18n] Warning: "units.names.raptor_6legged_l" is not translated in en
[t=04:19:12.047909][f=-000001] [i18n] Error: No translation found for "units.names.raptor_6legged_l"
[t=04:19:12.048018][f=-000001] [i18n] Warning: "units.descriptions.raptor_6legged_l" is not translated in en
[t=04:19:12.048055][f=-000001] [i18n] Error: No translation found for "units.descriptions.raptor_6legged_l"
[t=04:19:12.105982][f=-000001] [i18n] Warning: "features.names.armeyes_scav_dragonseyes_dead" is not translated in en
[t=04:19:12.106011][f=-000001] [i18n] Error: No translation found for "features.names.armeyes_scav_dragonseyes_dead"
[t=04:19:12.106297][f=-000001] [i18n] Warning: "features.names.armshltx_scav_armshlt_heap" is not translated in en
[t=04:19:12.106313][f=-000001] [i18n] Error: No translation found for "features.names.armshltx_scav_armshlt_heap"
[t=04:19:12.106842][f=-000001] [i18n] Warning: "features.names.cordrag_scav_rockteeth" is not translated in en
[t=04:19:12.106880][f=-000001] [i18n] Error: No translation found for "features.names.cordrag_scav_rockteeth"
[t=04:19:12.107197][f=-000001] [i18n] Warning: "features.names.corscavdtm_scav_rockteeth" is not translated in en
[t=04:19:12.107366][f=-000001] [i18n] Error: No translation found for "features.names.corscavdtm_scav_rockteeth"
[t=04:19:12.107834][f=-000001] [i18n] Warning: "features.names.coreyes_scav_cdragonseyes_dead" is not translated in en
[t=04:19:12.107853][f=-000001] [i18n] Error: No translation found for "features.names.coreyes_scav_cdragonseyes_dead"
[t=04:19:12.108485][f=-000001] [i18n] Warning: "features.names.corscavdtf_scav_rockteeth" is not translated in en
[t=04:19:12.108503][f=-000001] [i18n] Error: No translation found for "features.names.corscavdtf_scav_rockteeth"
[t=04:19:12.108617][f=-000001] [i18n] Warning: "features.names.armlwall_scav_rockteeth" is not translated in en
[t=04:19:12.108678][f=-000001] [i18n] Error: No translation found for "features.names.armlwall_scav_rockteeth"
[t=04:19:12.109728][f=-000001] [i18n] Warning: "features.names.armclaw_scav_rockteeth" is not translated in en
[t=04:19:12.109769][f=-000001] [i18n] Error: No translation found for "features.names.armclaw_scav_rockteeth"
[t=04:19:12.110721][f=-000001] [i18n] Warning: "features.names.armshltxuw_scav_armshlt_dead" is not translated in en
[t=04:19:12.110764][f=-000001] [i18n] Error: No translation found for "features.names.armshltxuw_scav_armshlt_dead"
[t=04:19:12.111230][f=-000001] [i18n] Warning: "features.names.corscavfort_scav_rockteethx" is not translated in en
[t=04:19:12.111249][f=-000001] [i18n] Error: No translation found for "features.names.corscavfort_scav_rockteethx"
[t=04:19:12.112148][f=-000001] [i18n] Warning: "features.names.armfort_scav_rockteethx" is not translated in en
[t=04:19:12.112187][f=-000001] [i18n] Error: No translation found for "features.names.armfort_scav_rockteethx"
[t=04:19:12.112532][f=-000001] [i18n] Warning: "features.names.corfort_scav_rockteethx" is not translated in en
[t=04:19:12.112704][f=-000001] [i18n] Error: No translation found for "features.names.corfort_scav_rockteethx"
[t=04:19:12.114442][f=-000001] [i18n] Warning: "features.names.cormaw_scav_rockteeth" is not translated in en
[t=04:19:12.114491][f=-000001] [i18n] Error: No translation found for "features.names.cormaw_scav_rockteeth"
[t=04:19:12.114594][f=-000001] [i18n] Warning: "features.names.armshltxuw_scav_armshlt_heap" is not translated in en
[t=04:19:12.114798][f=-000001] [i18n] Error: No translation found for "features.names.armshltxuw_scav_armshlt_heap"
[t=04:19:12.114943][f=-000001] [i18n] Warning: "features.names.corscavdtl_scav_rockteeth" is not translated in en
[t=04:19:12.114960][f=-000001] [i18n] Error: No translation found for "features.names.corscavdtl_scav_rockteeth"
[t=04:19:12.115075][f=-000001] [i18n] Warning: "features.names.cormwall_scav_rockteeth" is not translated in en
[t=04:19:12.115091][f=-000001] [i18n] Error: No translation found for "features.names.cormwall_scav_rockteeth"
[t=04:19:12.115314][f=-000001] [i18n] Warning: "features.names.armdrag_scav_rockteeth" is not translated in en
[t=04:19:12.115331][f=-000001] [i18n] Error: No translation found for "features.names.armdrag_scav_rockteeth"
[t=04:19:12.115455][f=-000001] [i18n] Warning: "features.names.armshltx_scav_armshlt_dead" is not translated in en
[t=04:19:12.115474][f=-000001] [i18n] Error: No translation found for "features.names.armshltx_scav_armshlt_dead"
[t=04:19:12.115862][f=-000001] [i18n] Warning: "features.names.corscavdrag_scav_rockteeth" is not translated in en
[t=04:19:12.115905][f=-000001] [i18n] Error: No translation found for "features.names.corscavdrag_scav_rockteeth"
[t=04:19:12.116244][f=-000001] [i18n] Warning: "features.names.legvision_scav_cdragonseyes_dead" is not translated in en
[t=04:19:12.116260][f=-000001] [i18n] Error: No translation found for "features.names.legvision_scav_cdragonseyes_dead"

**Comment by SethDGamre** [comment]
these particular errors have cleared up.

now there's completely new (albiet fewer) ones.
Such is life.
