### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by ryansch** [beyond-all-reason/Beyond-All-Reason#2258]
I have an M1 Max based mac. I've installed Asahi Linux and tried to run BAR. There's an ARM64 flatpak but it appears that the spring/recoil binaries are actually built for x86_64.

I fiddled with the build system and managed to get through `cmake` but the generated Makefiles are trying to pass x86 options to gcc.

Has there been any effort to build for arm? Is it a build tooling issue or would the engine require an actual porting effort?

**Comment by ryansch** [comment]
Let me know if this issue belongs in https://github.com/beyond-all-reason/spring instead.

**Comment by StanczakDominik** [comment]
Yes, it does. And it's a duplicate, use the search function.

**Comment by ryansch** [comment]
@StanczakDominik I did. There's an issue about the graphics portion which would affect me in linux. I'll reopen over there.
