### ISSUE TITLE
icon is not being displayed

### ISSUE THREAD

**Issue by Taza53** [beyond-all-reason/Beyond-All-Reason#226]
the .desktop file in _~/.local/share/applications/_ does not display the icon as well.

**Comment by icexuick** [comment]
Should be fixed.
@Taza53 Can you verify after updating?

**Comment by Taza53** [comment]
nope it did not work even reinstalled it after removing all saved files. on kde plasma.

**Comment by KyleAnthonyShepherd** [comment]
Closing this issue, it feels very outdated and no active conversation
