### ISSUE TITLE
Removing first/last command from queue doesn't work during Game Start Countdown

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2311]
You can queue buildings, but you cannot use remove first or last command (N / Shift + N by default?). In order to reset your queue, you have to release shift and put down a new building.

Solution: Make it work as it works during the game

**Comment by thehobojoe** [comment]
@lolsteamroller this will require hooking in the command skip behavior into the pregame widget, is this something you're comfortable doing?

**Comment by hihoman23** [comment]
Should be fixed in #3361
