### ISSUE TITLE
Make Buildings Autogroup-able

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2312]
### Short description

Right now you cannot autogroup buildings. It'd be handy to have production buildings on one hotkey, Juno/Nuclear on another, etc.

**Comment by hihoman23** [comment]
This used to be a feature, it got removed
I would be willing to make the change if it does get approved

**Comment by sprEEEzy** [comment]
Interesting. What prompted the change?

**Comment by hihoman23** [comment]
Closed in #3048
