### ISSUE TITLE
Add option to remove Fight left click drag behavior (formation orientation) or increase drag delay

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2315]
Currently, when you issue a (Shift +) Fight command, you always have to apply orientation, even for single units. This is not always what you want to do if you're just issuing a quick fight command queue.

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/fb70775e-3d9c-44dd-9bf2-751d573959bc

Solution: add option to turn this behavior off, or add higher delay on drag, in order to have more control over when you want to issue it.

**Comment by sprEEEzy** [comment]
Yes, still the same. Not sure why you can't reproduce it...? 

Select fight, hold shift, click fast around the map. It'll issue the "pink arrow", whenever you hold LMB for more than X pixels (which you will do a lot of, since you're moving your mouse fast).

**Comment by thehobojoe** [comment]
I see, I thought the bug was that these commands wouldn't be issued without a drag. What's the downside to the facing showing up when dragging? It still only places a single command and the placement should be affected negatively by a little drag.

**Comment by Beherith** [comment]
Drag threshold is not defined via a timer, it is defined via user-changeable configuration options of Drag Thresholds:

Formation orientation has no effect when a single unit is commanded to fight anyway.
```local baseDragThreshold = 16
baseDragThreshold = math.round(baseDragThreshold * (xresolution + yresolution) * ( 1/3000) ) -- is 16 at 1080p
baseDragThreshold = math.max(8, math.min(40, baseDragThreshold)) -- clamp between 8 and 40
Spring.Echo(string.format("Setting Mouse Drag thresholds based on resolution (%dx%d) for Selection to %d, and Command to %d", xresolution,yresolution,baseDragThreshold, baseDragThreshold + 16))
Spring.SetConfigInt("MouseDragSelectionThreshold", baseDragThreshold)
Spring.SetConfigInt("MouseDragCircleCommandThreshold", baseDragThreshold + 16)
Spring.SetConfigInt("MouseDragBoxCommandThreshold", baseDragThreshold + 16)
Spring.SetConfigInt("MouseDragFrontCommandThreshold", baseDragThreshold + 16)```
