### ISSUE TITLE
Cannot remove Guard on Factory command with "command_skip_current"

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2318]
If you queue some buildings, and then Space + click on a Factory (Guard), you can't remove that command with  "command_skip_current" hotkey. If you're assisting the factory with Repair on the unit being built, then you can.

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/a8f9206f-c4f1-4102-9dd4-3a58b231f59e

**Comment by sprEEEzy** [comment]
Does that mean that "command_skip_current" needs special behavior written for complex commands (guard, patrol)?

**Comment by badosu** [comment]
Closed by what?

**Comment by sprEEEzy** [comment]
> Closed by what?

I misclicked yesterday, thanks for reminding me. It's still open.

**Comment by hihoman23** [comment]
I fixed this but I was wondering if someone has a less dirty approach:
I check if there is a guard command after the repair command and if there is one, I also delete the guard command.
This isn't optimal because the repairs could be queued normally and don't have to be because of the guard command.

**Comment by badosu** [comment]
I don't think there's a better fix, best you can do is have a `maxDepth` setting that tells your guard cmd search how many orders in the queue to traverse to find a guard cmd.

**Comment by badosu** [comment]
I did something similar for fight command somewhere (I guess cmd_prepend)

**Comment by hihoman23** [comment]
I just coded it with `maxDepth` as 1, I don't see why it should be more

**Comment by sprEEEzy** [comment]
A fix is one the way? Nice!

Please keep in mind all complex commands have this issue (I think!).

**Comment by hihoman23** [comment]
> A fix is on the way? Nice!
> 
> Please keep in mind all complex commands have this issue (I think!).

Could you provide examples of more?

**Comment by sprEEEzy** [comment]
Well, a variant is this: https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2324

_Command_cancel_last_ doesn't work on factories /w the guard use case.

_Command_cancel_last_ doesn't work with Patrol -> it creates a weird patrol circle if u try to cancel it. 
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/cff09d0d-727c-49e6-a2f1-cbc4cb96f25d)

**Comment by hihoman23** [comment]
The fix won't contain the `set_target` fix since this isn't really the same issue and actually not an actual engine command.

**Comment by lolsteamroller** [comment]
@sprEEEzy I'll take a look at this week & probably have improvements for this button already, thanks for reporting.

**Comment by thehobojoe** [comment]
Is this issue resolved with that PR that got merged @sprEEEzy?

**Comment by sprEEEzy** [comment]
Think it is! @thehobojoe
