### ISSUE TITLE
Heavy stuttering, FPS drops on Intel Arc discrete GPU

### ISSUE THREAD

**Issue by JeroenAdam** [beyond-all-reason/Beyond-All-Reason#2325]
Hi, it has been 2 months I played BAR on my laptop with Intel Arc A350M discrete GPU and I experience heavy stuttering, FPS drops to 2 FPS. After a few short-lived stutters back to normal 30-50 FPS. And back again intermittently during the whole game. All worked fine maybe 2 months ago.

I switched back from engine 105.1.1-2127-g9568247 to 105.1.1-1821-gaca6f20 but the issue remained. Maybe I should go back to an even older version.
Next a try with minimal graphic options, advanced shaders disabled, vsync off, unit tracking off etc., FPS +100 FPS but the issue remains.
Next a try with a clean install and standard settings, the issue remains.
I'm running the latest Windows 23H2 with latest Intel drivers. It could be Windows 23H2 , who knows.

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13507150/infolog.txt)

[spring-launcher-20231130T005209.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13507152/spring-launcher-20231130T005209.log)

Video recording:
[screen-capture (8).webm](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/16437621/927bc611-cff2-4225-91d9-504fe2c141bd)

**Comment by JeroenAdam** [comment]
If only I could download a previous version of BAR and incrementally update, I could help pointing to the release which causes the issue.

**Comment by 6AKU66** [comment]
Try to do "/luaui disable" and see if it's still happening.

**Comment by JeroenAdam** [comment]
/luaui disable did remove the UI elements, the issue remains

**Comment by 6AKU66** [comment]
Can you open /debug and make a video with it?

**Comment by JeroenAdam** [comment]
Here a short video with debug on screen.
[screen-capture (17).webm](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/16437621/e5e7cdf4-772c-4939-9440-7492d0f46fee)

**Comment by JeroenAdam** [comment]
FYI, workaround: disable Intel ARC in Device Manager so that BAR falls back to integrated Intel Iris Xe.

**Comment by Daroude** [comment]
Any updates on that? It is stil hardly playable on Intel Arc.

**Comment by JeroenAdam** [comment]
I have been trying to play from time to time and since +/- 1 week all goes well on my Intel Arc A350M!
I'm on BAR-27023-f596825 and engine v105.1.1-2590-gb9462a0 (see C:\Program Files\Beyond-All-Reason\data\engine)
Intel Arc driver from August 2014 v32.0.101.5972

**Comment by JeroenAdam** [comment]
All goes well now, with older & latest drivers v32.0.101.6325
