### ISSUE TITLE
Cannot place building blueprint if placing over movement waypoint

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2333]
This one happens basically every game, and I cannot be sure I've put a building down without double checking. Easy to replicate.

When you select a building blueprint, and try to put it down with Shift + Left click, if there is a movement waypoint (exactly) underneath the blueprint, the blueprint will get ignored, and your click will only update the position of the movement waypoint slightly.

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/f31f7901-d21a-4bc7-9d75-bd7233fced9e

EDIT: **Cause found - Waypoint Dragger widget**. It has priority over blueprint placement. Does anyone use this widget anyway? I recommend to turn it off for new players by default. I'm turning it off myself to fix this issue, as it's a major one.

Solution: Give priority to blueprint placement when using Shift + left click, over movement waypoints (other widgets).

**Comment by 6AKU66** [comment]
Honestly i don't know if someone use a feature which move your movement waypoint
