### ISSUE TITLE
Fight Command queued after Repair/Guard instead of replacing it

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2340]
If your unit is repairing, and you issue a Fight command (without Shift), it gets added to queue. It even issues two fight commands.

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/14b7a8cf-1770-4f73-90a9-230224f0d750)

Solution: Make it cancel repairing and issue Fight.

**Comment by hihoman23** [comment]
I would like to fix this but don't know if I should make a new gadget or if this is better done somewhere else

**Comment by salinecitrine** [comment]
I'm not sure this is a bug - I think this is the intended behavior of the fight command, since fight includes repairing. Maybe I'm missing something? If so, could you explain in more detail how you expect it to behave differently?

**Comment by sprEEEzy** [comment]
> I'm not sure this is a bug - I think this is the intended behavior of the fight command, since fight includes repairing. Maybe I'm missing something? If so, could you explain in more detail how you expect it to behave differently?

Oh, you're actually right I think. Case closed?
