### ISSUE TITLE
Cancelling the first/last command in queue is sluggish

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2370]
### Description

There's a hard cap on how many commands you can cancel per sec, which is about 2. Add in 300ms delay if the servers are far away - you waste of lot of time ingame.

Can this be fixed easily?

### Reproduction steps

Queue 3-4 commands, then cancel them by using cancel last or first in queue.

**Comment by thehobojoe** [comment]
I can't reproduce this, it appears to go as fast as I'm able to press the button. I cleared ~40 commands in 3 or so seconds

**Comment by icexuick** [comment]
Can't reproduce either (in skirmish)

**Comment by sprunk** [comment]
go test in multiplayer then

**Comment by sprEEEzy** [comment]
This might have been fixed with the queue cancel changes few months ago. Will report back.

**Comment by sprEEEzy** [comment]
Seems fixed!
