### ISSUE TITLE
Icon of current unit in production gets stuck on 0 percent, even though it's being built normally

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2371]
### Description

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/2e23b274-3588-4e00-8867-4d69f32dd74d)

### Reproduction steps

Not sure how to reproduce yet. I do get it few times per day.

**Comment by thehobojoe** [comment]
Is this something you still see @sprEEEzy? I am trying to reproduce with no luck. There have been some somewhat related fixes in the last couple months, so it's possible this was fixed incidentally.

**Comment by sprEEEzy** [comment]
Cannot confirm nor deny, as I haven't play as much lately.
