### ISSUE TITLE
Burning trees can (only) be reclaimed via area reclaim command

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2386]
Burning trees can be reclaimed via area reclaim command, but cannot be reclaimed with non-area reclaim command. I don't know if reclaiming burning trees is intended feature or not.
https://youtu.be/ZaVFHxEzfLs

**Comment by SethDGamre** [comment]
I was able to recreate this

**Comment by SethDGamre** [comment]
duplicate of https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1513

**Comment by hihoman23** [comment]
Closing duplicate
