### ISSUE TITLE
Camera starts scrolled down

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#239]
At some update maybe ~2 weeks ago the camera starts like this at the beginning of every game and I have to ctrl+scroll wheel to get it back to normal.

![image](https://user-images.githubusercontent.com/1434248/113510774-4279c480-9554-11eb-983c-89c339182145.png)

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/6254640/infolog.txt)

**Client:** SpringLobby 0.271
**OS:** Windows 10
**GFX:** RTX  2080 Super
**Engine:** 104.0.1-1828-g1f481b7 BAR
**BAR:** Beyond All Reason test-15933-5b91342

**Comment by Damgam** [comment]
It's not since 2 weeks ago
It's like this since we use Chobby

Change your camera to diffrent one.

**Comment by Jazcash** [comment]
> It's not since 2 weeks ago
> It's like this since we use Chobby
> 
> Change your camera to diffrent one.

Chobby fixes this? How? I have this in springsettings:
![image](https://user-images.githubusercontent.com/1434248/113512620-5ece2f00-955d-11eb-9a00-fedd287e8bfd.png)

But I don't want to use a different camera, overhead is correct, it's just the initial scroll position is messed up every game

**Comment by lhog** [comment]
Worth revisiting again. 
https://github.com/beyond-all-reason/spring/issues/14

**Comment by lhog** [comment]
See if didn't waste 5h for nothing (i.e. check if fixed)

**Comment by Jazcash** [comment]
> See if didn't waste 5h for nothing (i.e. check if fixed)

Fixed! 👍
