### ISSUE TITLE
Units phase through armplat building, block construction blueprints with no collision

### ISSUE THREAD

**Issue by lolsteamroller** [beyond-all-reason/Beyond-All-Reason#2398]
### Description

Armada Seaplane Factory, once producing pop's out of the water. Units (like hovercraft) phase through the building as if it didn't exist. 

Unfortunately this means, if you park hovers right, the building wouldn't produce, and new engine release tackled those issues well, but not for this.

### Expected Behaviour

Hovercraft go around the armplat, treating it as unnavigable.

### Actual Behaviour

Hovercraft phase through armplat, if stopped block any potential aircraft building.

### Other

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/7465747/e5b7816f-1e7c-4df8-83b0-49cc9617f724)

**Comment by SethDGamre** [comment]
![image](https://github.com/user-attachments/assets/23cc3a8d-9c5a-4d77-80cc-9aa5bc692639)
this has been fixed
