### ISSUE TITLE
Com refuses to fire with laser

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#241]
Have seen this a few times now. For some reason, com sometimes refuses to laser stuff. Possibly related to dgun stall assist widget. Somebody also mentioned it only happens with arm com.

https://user-images.githubusercontent.com/1434248/113512806-3b57b400-955e-11eb-827a-c7d4b4704a4e.mp4

[_script.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/6254784/_script.txt)

Replay: https://www.beyondallreason.info/replays?gameId=38c06960202442b20ea642ef88c94c45

**Client:** SpringLobby 0.271
**OS:** Windows 10
**GFX:** RTX 2080 Super
**Engine:** 104.0.1-1828-g1f481b7 BAR
**BAR:** Beyond All Reason test-15933-5b91342

**Comment by Jazcash** [comment]
Does com laser perhaps cost energy? Dgun stall assist could be preventing it from firing, just a hunch. Although if that were true I'm guessing we'd have known sooner because that widget's been around forever

**Comment by Beherith** [comment]
still present? I fixed a lot of things around comm

**Comment by PtaQQ** [comment]
It happened to me once within last week.

**Comment by PtaQQ** [comment]
It happens when I frantically queue few quick dguns and move commands, com refuses to fire for a while.

**Comment by Jazcash** [comment]
> still present? I fixed a lot of things around comm

Haven't seen this since this comment so gonna assume fixed for now, can reopen if anybody's seen it recently

**Comment by WatchTheFort** [comment]
I can reliably reproduce this issue, it only affects the Armada Commander:
1. Be stalling energy, ensure not enough to D-gun
2. Give Commander D-gun order
3. Give Commander attack order

The attack order will replace the D-gun order, but the laser won't shoot for a short time period.

I disabled the DGun Stall Assist widget, so that is not the cause.

**Comment by WatchTheFort** [comment]
Cause found:
The unit script sets a flag `isAimingDgun` while aiming the D-gun, and does not allow firing the laser until this flag is cleared. However, the flag is not cleared until the D-gun fires, so when stalling energy, it remains `true`, even when another is given. The `Restore()` command also clears this flag, but after doing a `Sleep(3000)`, which is where the delay comes from when the laser refuses to fire. 

https://github.com/beyond-all-reason/Beyond-All-Reason/blob/a7177e77092903ec53d39b1232906cf3aba61bac/scripts/Units/armcom_lus.lua#L588

**Comment by WatchTheFort** [comment]
The purpose of this functionality appears to be so that the Commander does not fire the laser when firinga the D-gun. The Cortex Commander does not have this limitation, and can freely fire the laser while queuing a D-gun shot. Both Commanders fire the laser and D-gun from different arms, so it is was not done in consideration of aiming.

**Comment by WatchTheFort** [comment]
@Beherith @PtaQQ @Jazcash
This behaviour has been around since the first commit. Was this done for a reason, or can this code be removed?

**Comment by Beherith** [comment]
This code can be removed, to allow the comm to fire laser while aiming dgun. Thank you for this investigation!

**Comment by WatchTheFort** [comment]
It turns out the purpose of that flag is to resolve issues when the Commander is auto-attacking and gets a D-gun order outside the laser's angle. Removing the flag causes torso twitching.

Resolved by moving the call to clear the flag to before the call to `Sleep()`.
