### ISSUE TITLE
Trees on Quicksilver can cause reclaimers to get stuck

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#243]
If units get a reclaim order on the trees on Quicksilver, but the trees are crushed before they've been reclaimed, then reclaimers get stuck because the trees sink below the map, out of reclaim range. Idk whose map this is so tagging @icexuick and @Beherith 

https://user-images.githubusercontent.com/1434248/113636246-1a7c8500-966a-11eb-8cc5-1507b2856f84.mp4

**Comment by badosu** [comment]
To reproduce send an ak and order to attack ground on trees.
As they burn, area reclaim

**Comment by M0nty-BAR** [comment]
So waiting does not seems to effect the reclaim que item for the area, it goes indefinitely. I did notice the point the unit thinks the next reclaim moves around as you scroll wheel in and out as if it is not bound to a specific spot on the map. However if you attempt to reclaim out side the are  where the tree burned down it does not produce the bug.

**Comment by Beherith** [comment]
Hopefully fixed, re-report if it persists
