### ISSUE TITLE
Ghost buildings

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2433]
Reproduce:
https://youtu.be/hlckg1lg9uY

**Comment by TheSilverHornet** [comment]
I've seen this from _enemy_ buildings too, unclear how

**Comment by sprEEEzy** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2353

**Comment by 6AKU66** [comment]
Closing as dublicate.
