### ISSUE TITLE
Cannot issue Guard command on Metal Extractor

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2446]
### Description

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/4ad94e7b-9d32-4bf8-adf1-9667b9f8a9d4)

It doesn't do anything on Metal Extractors. Works on Factories/Solars...

Additionally, some mexes have the wrong(?) hover icon displayed. 
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/932a1cd1-b803-4ac4-9183-d77f02b56868)

### Expected Behaviour

Guard issues guard

### Actual Behaviour

Guard (icon appears on hover) doesn't do anything on Metal Extractors.

### Reproduction steps

Right click on a completed Mex.

**Comment by thehobojoe** [comment]
This can be closed.
