### ISSUE TITLE
Old area mex hotkey still shown in keyboard shortcuts image

### ISSUE THREAD

**Issue by luukoudshoorn** [beyond-all-reason/Beyond-All-Reason#2460]
### Description

When viewing the in game keyboard shortcuts, the control grid menu tab still shows Ctrl + Z as area mex command. However, this was changed in #2339
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/8614214/60fc7ab7-5700-4a5a-8bb3-e688fc4e8174)

### Expected Behaviour

No action should be shown for Ctrl + Z

### Actual Behaviour

Area mex is shown

**Comment by hihoman23** [comment]
The reason for this is because the keybind still works, which would be a bad idea to remove

**Comment by StanczakDominik** [comment]
No, it got removed from grid by @thehobojoe a while back. Are you on custom?

**Comment by hihoman23** [comment]
Ah yes, that's why

**Comment by hihoman23** [comment]
And also for anyone searching it, it is here: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/images/keybinds_defaults/BAR_Keyboard_Shortcuts_GRID_CTRL.png

**Comment by thehobojoe** [comment]
Yeah this needs an update, I don't have access to the figma files used to create it. @icexuick is this something you'd be able to do?

**Comment by icexuick** [comment]
Updated the shortcut keys + overall improved design + Default keys as well

**Comment by icexuick** [comment]
Fixed.
