### ISSUE TITLE
Thor Freezes when ordered to attack ground inside its EMP range

### ISSUE THREAD

**Issue by MTKing4** [beyond-all-reason/Beyond-All-Reason#2487]
### Description

if you order thors to attack ground beyond the main cannon range but within the EMP range, thor freezes and it wont move to its target

Videos, replay, and log in Link below
https://discord.com/channels/549281623154229250/1190126309356093480/1190126309356093480

### Expected Behaviour

thor should move closer to its target and shoot it

### Actual Behaviour

thor freezes and it won't move closer to the target therefore not shooting

### Reproduction steps

attack ground beyond the main cannon range but within its EMP range

**Comment by SilverSolZ** [comment]
maxrange = "570" in customparams of unitdef would likely fix. Similar problem on a few other units was fixed with that solution here: https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2179

**Comment by TheSilverHornet** [comment]
I've already fixed it

**Comment by StanczakDominik** [comment]
For the future, @TheSilverHornet, if you add a note like `Closes #2487` on a separate line in a PR, merging it will automatically close the linked issue :)

**Comment by TheSilverHornet** [comment]
> For the future, @TheSilverHornet, if you add a note like `Closes #2487` on a separate line in a PR, merging it will automatically close the linked issue :)

I wasn't aware it was raised AS an issue when I did so, I'd already said at the time on discord that I was looking into it, wasn't expecting a bug to be reported about it too :)
