### ISSUE TITLE
give Thors the ability to Multi Shoot EMP Missiles and scatter them like Nuke Missiles

### ISSUE THREAD

**Issue by MTKing4** [beyond-all-reason/Beyond-All-Reason#2488]
### Description

when having multiple thors selected you cant scatter their rockets, they all shoot at the same spot which is just a waste, having to select them manually is cumbersome and inconvenient and it should be changed

### Problems this will solve

gives more control over the units and eliminates thor babysitting, wasting rockets, or complete negligence of this feature when massing thors

**Comment by PtaQQ** [comment]
Issue approved by the Game Design Team, awaiting implementation.

**Comment by thehobojoe** [comment]
Is this widget ready for implementation? https://discord.com/channels/549281623154229250/1192937312280137864

**Comment by ChrisFloofyKitsune** [comment]
This has been implemented in #2628
