### ISSUE TITLE
Add the ability to Resume from replay at any point in the game possibly with godmode on

### ISSUE THREAD

**Issue by MTKing4** [beyond-all-reason/Beyond-All-Reason#2501]
### Description

it should be at least enabled with god mode 3 on, meaning all human players fall under the observer's control, but if you want it to be more advanced, you can allow more than 1 player to resume the game, taking over themselves or even other players if you choose to allow them to

### Problems this will solve

it can be useful in many ways for example
1. analyze what could have happen otherwise if a different decision was made
2. can be useful for beginners to replay a game vs AI that they lost at

**Comment by SethDGamre** [comment]
this issue looks like it has to be done Spring Game Engine side. See https://github.com/beyond-all-reason/spring/issues/1179

that makes this a duplicate in the BAR rather than Spring github

**Comment by lostsquirrel1** [comment]
@SethDGamre - having a ticket in engine isn't a duplicate for the game side. In fact, the correct work flow is for all feature requests and bug reports for BAR to have a BAR ticket, and for anything that trickles down to the engine has an engine ticket also. Fixing the issue or ask in the engine does not automatically solve it for the game side. At the very least the game should verify the change is fit for the game's purpose. Also, many changes, like this one would require game-side changes as well to make the feature work.
