### ISSUE TITLE
Shield's projectile collisions cause performance leak

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2505]
Shield power Multiplier: 10000
Weapon Range Multiplier: 5
Shield Type Override: bounceeverything
Attacker unit: armfast
Attacked unit: armgate

Note: attacker units should be outside of shield.
https://www.youtube.com/watch?v=9i8htLHZj2M

**Comment by 6AKU66** [comment]
Those hexagons are causing lag when it's keep triggering non-stop.
![5555](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/89547444/2ccdc5d0-58de-4fcd-9ccb-d87bba94e792)
![5556](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/89547444/a3ec4f70-7ec8-47c9-b098-87d9aeb22e9c)

**Comment by Beherith** [comment]
Fixed
