### ISSUE TITLE
Favorite Maps

### ISSUE THREAD

**Issue by wheezardth** [beyond-all-reason/Beyond-All-Reason#2510]
### Description

There are a LOT of maps for BAR and this number will only keep growing.

It would be great if there would be an option to ⭐ a map in the list and then sort the list for favorites.

### Problems this will solve

I think one of the reasons why so many people play the same maps over and over is that even if they enjoyed a map after they played it, it's hard to remember the name when you try to start a new game.

Simply adding one more column and the option to ⭐a map to the map browser would make it much easier to diversify the number of maps that end up getting played on.

**Comment by thehobojoe** [comment]
Implemented in the lobby
