### ISSUE TITLE
Create option to share resource overflow with enemy teams

### ISSUE THREAD

**Issue by Toothwitch** [beyond-all-reason/Beyond-All-Reason#2543]
### Description

A settings option to enable sharing/giving your overflowing resources equally to the enemy teams.

### Problems this will solve

This feature would create a pressure on correctly managing resource production and demand and give teams which are lagging behind a boost to equalize the playfield if not managed correctly. 
This way the players could choose to make the economy more attention demanding instead of just building more resource production than one needs. 

### What area of the game does this feature request pertain?

Gameplay, UI/UX, Settings, Controls or Hotkeys

### Other (optional)

Other ideas to punish overflowing resources would also be great, but this is the best we came up with.

**Comment by 6AKU66** [comment]
Define overflow (because i'm not sure if we define it in same way). And for me it's doesn't sounds intuitive that for some reason overflow suddenly start to go to enemy teams.

**Comment by Toothwitch** [comment]
Overflowing in the sense of "The whole team is wasting metal/energy".

As for the intuitiveness. Yes if you do not know about this option when it is active you don't think about and don't expect it at all. But there is also no way for me to explain it logically how the energy whould be transported to the enemy team.

The thought behind this was: "How would i punish wasting resources" and "How can this game be more complicated" as an optional feature for players who like to suffer.

**Comment by Beherith** [comment]
I thought I wrote a comment on this one:
This would in no sense equalize the playing field. The ideal state to be in is all resources are being consumed. If a team is overflowing, that probably means they are behind and scrambling, or just got their production destroyed. This would feed the team who is ahead.

**Comment by PtaQQ** [comment]
Item rejected by the Game Design Team, for the following reasons, in short: 
- overflowing resources means you are not menaging your economy properly, overflowing to enemy punishes you additionally for that  
- unitintuitive (why realistically would that even happen?)
- we need less game options not more
