### ISSUE TITLE
Unit info GUI at bottom left doesn't update whilst using camera pan mode

### ISSUE THREAD

**Issue by Borg-King** [beyond-all-reason/Beyond-All-Reason#2559]
### Description

Noticed whilst casting the 2v2 Tournament. Whilst in camera pan mode (middle mouse button click), the unit info box at the very bottom left would be frozen - either not appearing at all or not updating if already there.

### Expected Behaviour

Should work as when not in panning mode

### Actual Behaviour

Unit info box frozen whilst in panning mode

### Reproduction steps

I've checked and this affects all camera modes. Enter camera pan mode with middle mouse button (or otherwise mapped key, this should be default) and left click on a unit (which you have to center on your screen to do, as the mouse cursor is hidden, hence why this hasn't been noticed before). GUI box showing the selected unit at bottom left will not appear/update

**Comment by thehobojoe** [comment]
Can you provide more info or a video? I can't reproduce this.

**Comment by Borg-King** [comment]
On the 2v2 tournament:
https://youtu.be/ytLC_N9JhUw?t=1162

**Comment by Borg-King** [comment]
As I select the commander here too:
https://youtu.be/ytLC_N9JhUw?t=1717
