### ISSUE TITLE
"_Or_" for keybind selection filters

### ISSUE THREAD

**Issue by Hazy-uhyR** [beyond-all-reason/Beyond-All-Reason#2581]
### Description

Right now, when doing selection filters for keybind, all the filters need to be true for something for it to be added to the selection. It would be nice if we could have _Or_ between filters, rather than the forced _And_s "that are there" now.

I am not sure how to do something like "(filter 1 and filter 2) OR (filter 3 and filter 4)", but that stuff could be useful too, maybe. Simple Ors between filters would be nice, for now.

### Why?

This would make it possible to create specific filter combos for selecting, for instance: all fighters, all specific kinds of infantry bots, etc. Right now, that is not really possible, unless the weapon ranges of those units somehow match up, and doesn't happen to include stuff outside of what you actually want to filter for.

### What area of the game does this feature request pertain?

Settings, Controls or Hotkeys

**Comment by thehobojoe** [comment]
Already implemented in engine (temporary rollbacks notwithstanding)
