### ISSUE TITLE
Issuing area reclaim command interacts badly with chat box

### ISSUE THREAD

**Issue by Brian-Catcow-B** [beyond-all-reason/Beyond-All-Reason#2588]
### Description

When issuing an area reclaim command using [select unit] -> 'e' -> ctrl+[left click + drag], if the initial left click position collides with the chat message correlating to a pinged location, the camera will snap to that position while drawing the circle.

### Expected Behaviour

The pinged location should not be jumped to, as the player is issuing a command for their unit(s)

### Actual Behaviour

The pinged location is jumped to, often resulting in a HUGE circle being drawn

### Reproduction steps

Ping a few locations so the corresponding chat messages show up, then click a constructor, press 'e', hold ctrl, left click and drag starting on the message in chat

**Comment by hihoman23** [comment]
I guess this can be closed now

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/10bf1f0ff13f233edd837fa6ffea3b9e99622ed2
