### ISSUE TITLE
Add unit options for target types and target prios

### ISSUE THREAD

**Issue by Brian-Catcow-B** [beyond-all-reason/Beyond-All-Reason#2594]
### Description

Add an option button that can be cycled through various options to each unit that can attack.

It would be called Target Types so that the unit would only attack the targets of selected types, if revealed by LoS (if not revealed by LoS but is by radar radar it will attack regardless):
1. All (default for most)
2. Aggressive/Transport (units that can attack -- default for long range AA)
3. Passive (units that can't attack)
4. Economy (units that produce a considerable amount of resources)
5. Ground Firing (units that can attack ground -- a good option for long range AA)
6. Air Firing (units that can attack air)
7. Ground (units that are on the ground)
8. Air (units that are in the air)

This is not an exhaustive list and can certainly be culled for easier end user experience or gameplay.

### Why?

Long range AA has the problem of firing one of its big rockets at the cheapest of air units, making it not a viable way to stop bombing runs. This change would allow for long range AA to only target ground firing units or aggressive/transport units so that its big rockets don't get wasted on low-metal, low-impact planes. It also comes with some improvements to micro'ing things such as rapid fire LRPC's by setting them to economy so that they will auto-target various economic buildings instead of firing at tick spam.

This makes some fast-moving parts of the game more feasible, since setting long range AA to "Hold Fire" and then manually targeting the incoming bombers is completely infeasible for an actual in-game scenario.

### What area of the game does this feature request pertain?

Gameplay

**Comment by Jazcash** [comment]
Discussed this with GDT and we concluded that we'd be open to default targeting priority be changed for certain specific cases, but as far as making these priorities user-configurable it's too much UI bloat which we're actively trying to trim down on anyway.
