### ISSUE TITLE
Category selection filter doesn't work

### ISSUE THREAD

**Issue by Hazy-uhyR** [beyond-all-reason/Beyond-All-Reason#2597]
### Description

The filter is accepted by the game, but then nothing happens. Tested with COMMANDER and UNDERWATER categories. I'm not sure why it doesn't work, as the code is too advanced for me to understand.

https://github.com/beyond-all-reason/spring/blob/43959c94747ebc6a82445dd07efe65892821a0ca/rts/Game/UI/SelectionKeyHandler.cpp#L186
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/4a3bec664454582645fcca84b996f48e9bdfbe89/units/armcom.lua#L18

### Expected Behaviour

It should work.

### Actual Behaviour

The action is accepted by the game, but then nothing happens.

### Reproduction steps

Put the below in uikeys.txt and start up a game. Set keybind preset to Custom. Note that comms do not get selected on execution.
bind ctrl+g select AllMap+_Category_COMMANDER+_ClearSelection_SelectOne+

**Comment by Hazy-uhyR** [comment]
https://github.com/beyond-all-reason/spring/issues/816 ..

**Comment by SethDGamre** [comment]
looks like this is going to be handled on the Spring side of things. Makes sense, as this is an engine issue. https://github.com/beyond-all-reason/spring/issues/816
