### ISSUE TITLE
Over build advanced Solar Panels (reclaim T1 upon completion)

### ISSUE THREAD

**Issue by djfremen** [beyond-all-reason/Beyond-All-Reason#2608]
### Description

This function should work exactly like T1 mex area upgrade with T2 construction bot but instead for advanced solar panels.

Edit: I wrote T2 but actually T1.5 since T1 construction bot creates advanced solar panels.

### Why?

Makes upgrading easier and seems intuitive for energy upgrading.

Advanced Solar Panel is much more efficient than standard solar panel created by commander.

### What area of the game does this feature request pertain?

Settings, Controls or Hotkeys

**Comment by WatchTheFort** [comment]
But there are no T2 solar panels...

**Comment by djfremen** [comment]
> But there are no T2 solar panels...
Ops! I mean advanced solar panel unit.

**Comment by djfremen** [comment]
Also noted that hotkey works for Geothermal upgrade.

**Comment by Ruwetuin** [comment]
unlike metal extraction points, the sun isnt a scarce resource therefore there is little need to implement this just for solars and not more widely for other building advanced 'versions' of certain t1 units.
