### ISSUE TITLE
I would like it if you could also see the damage dealt when you click on a unit.

### ISSUE THREAD

**Issue by TheDeinosuchus** [beyond-all-reason/Beyond-All-Reason#2619]
### Description

I would like it if you could also see the damage dealt under where it shows kills are when you click on a unit.

### Why?

This would be useful to see how much value a unit has gotten throughout it's existence.
This is not very important but it would be nice.

### What area of the game does this feature request pertain?

Other

**Comment by SethDGamre** [comment]
Please post ideas like this on the Suggestions section in the Discord.
