### ISSUE TITLE
Kilo and Mega mines have their 3D models swapped.

### ISSUE THREAD

**Issue by totbuae** [beyond-all-reason/Beyond-All-Reason#262]
Assuming the buildpics are correct then the Kilo is using the 3D model of the Mega and viceversa.

**Comment by Beherith** [comment]
I think its the buildpics that are incorrect and need a swap, care to PR?

**Comment by PicassoCT** [comment]
I want a refund on those mines i built, those games i lost! Cryptic Mine labelling in game is a crime!

**Comment by Sipke82** [comment]
i made a PR #273
