### ISSUE TITLE
Cortex T2 vehicle combat engineer

### ISSUE THREAD

**Issue by Nitromachine** [beyond-all-reason/Beyond-All-Reason#2621]
### Description

I would like to humbly request a Cortex counterpart to the Armada Consul combat engineer **vehicle**, either as a T1 unit or T2 unit.

### Why?

I know that Cortex has combat engineering bots but they do not have a vehicle factory equivalent. I often avoid building bot factories as Cortex since I do not like the unit selection currently offered by these buildings. I also prefer Cortex to Armada for various reasons.

If the omission is intentional, I'll simply point out that Cortex and Armada both have T1 stealthy minelayer vehicles, which are closely related to combat engineering vehicles.

### What area of the game does this feature request pertain?

Gameplay

### Other (optional)

Give it a dozer blade and a cannon! Thank you.

**Comment by hihoman23** [comment]
What about the forge?

**Comment by Nitromachine** [comment]
Explain?

**Comment by TheChronographer** [comment]
There already exists 2 vehicle engineers for cortex. One is available in the release candidates pack; the 'Printer' - a high HP engineer that can reclaim and repair while moving. The second is the 'Forge' - an armed combat engineer vehicle that has a flame thrower.

The latter is more a 'fun' unit which will not likely be added to the base game outside the scavengers game mode. But the Printer is currently undergoing balance testing.

Questions like this would probably get a lot more engagement on the BAR discord. There are many channels for suggestions and balance testing. I in no way represent the BAR development team.

**Comment by Nitromachine** [comment]
I haven't played with the release candidate units so I was unaware of them. No point in keeping this discussion open then.
