### ISSUE TITLE
Error in Update(): [string LuaUI/Widgets/cmd_quick_build_extractor.lua]:236: attempt to perform arithmetic on field ? (a nil value) 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#2657]
https://github.com/beyond-all-reason/Beyond-All-Reason/blame/567d42cea149f5d89617461f11aabd5299d7d0f2/luaui/Widgets/cmd_quick_build_extractor.lua#L236

Possibly the 5th element of the list is nil if its complaining about arithmetic error. 

Very frequent error, got hundreds of it.

**Comment by thehobojoe** [comment]
I've never seen this warning before, do you know the context in which it happened? I've tried everything I can think of to reproduce, but so far unable to get an instance of this error. Every field passed in on that line is very thoroughly null checked, so I'm not sure how this happens.
