### ISSUE TITLE
Error in Shutdown(): [string LuaUI/Widgets/gui_pregame_build.lua]:215: attempt to call field StopDrawUnitShapeGL4 (a nil value) 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#2659]
https://github.com/beyond-all-reason/Beyond-All-Reason/blame/567d42cea149f5d89617461f11aabd5299d7d0f2/luaui/Widgets/gui_pregame_build.lua#L211

Got hundreds of this, could it be that people are disabling the DrawUnitShape GL4 API? 

All in gameframe -1.

**Comment by Ruwetuin** [comment]
these errors must come from the widget:shutdown of the gui_pregame_build widget, the other places will check the existance of the DrawUnitShape GL4 API, not sure how the order of shutdowns usually go but that could explain it?
