### ISSUE TITLE
No effects in top half of screen

### ISSUE THREAD

**Issue by Musikermomo** [beyond-all-reason/Beyond-All-Reason#2677]
### Description

Construction particles and other effects (lightning, bullets in the air, smoke etc.) don't show on the top half of the screen. It startet yesterday and is independent of the map I play. I didn't change any Settings.

![Screenshot_20240301_173519](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/18223993/289d91da-0eaa-4e8f-af08-10909dab9ecb)
![Screenshot_20240301_173412](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/18223993/bb9f9de3-132e-4ad1-b08f-dbd535a75156)

### Expected Behaviour

The effects should be visible on the whole screen.

### Actual Behaviour

Effects only visible on lower half of the screen

**Comment by kagadar** [comment]
+1, this is happening on my system as well.

Specs on my end:
```
CPU: Ryzen 7800X3D
GPU: Radeon 7900XTX
```

I'm using the Linux appimage version of BAR, and running it via lutris with game mode, mangohud and gamescope enabled.

**Comment by Musikermomo** [comment]
Oh I forgot to mention. I'm using the Linux app image as well.

**Comment by eode** [comment]
Same issue.

**Comment by eode** [comment]
Occurs in both XOrg and Wayland.

**Comment by Beherith** [comment]
Known issue for current engine release, fix in progress :)

**Comment by eode** [comment]
I *just* loaded "engine test" and the issue is not present.

**Comment by Beherith** [comment]
Yes, engine test however has other stability issues being looked at.

**Comment by starkers** [comment]
Same bug detected here; noticed a streamer on AMD had same bug today also.. (mine is Radeon 9800 XT)

**Comment by eode** [comment]
Are there any workarounds?

**Comment by Ruwetuin** [comment]
last engine release resolved this

**Comment by Compizfox** [comment]
I'm getting this issue now (lastest Alpha version, Recoil 2025-06-19), but the other way around: no particle effects in the *bottom* half of the screen...

I'm on Linux, with a RX 7800XT.

**Comment by eode** [comment]
Me too.  Perhaps we should open a new issue, though, and reference this one, since this one is closed.
