### ISSUE TITLE
set target show ennemy position

### ISSUE THREAD

**Issue by triton13** [beyond-all-reason/Beyond-All-Reason#27]
BA9 solved this issue

**Comment by lweberk** [comment]
Can you elaborate a little more?

**Comment by triton13** [comment]
it's in their changelog

**Comment by triton13** [comment]
I think they mostly use engine 103 btw

**Comment by lweberk** [comment]
I meant what do you mean by the issue description?

**Comment by PtaQQ** [comment]
He means that set target yellow lines don't disappear when the targeted unit goes out of LOS. This way you can "see" locations of the units you are not supposed to. It was fixed in BAR too, but started showing up again some time ago.

**Comment by Ruwetuin** [comment]
fixed it
