### ISSUE TITLE
Window 7 bar errros with virtual memory error.

### ISSUE THREAD

**Issue by mors555** [beyond-all-reason/Beyond-All-Reason#2708]
### Description

The error: procedure entry point DiscardVirtualMemory could not be located in the dynamic link libary KERNAL32.dll

On startup.

Recompiling for win32/win 7 should work just fine as the fix.   Since BAR did work just fine on window 7 until I recently updated it.

### Expected Behaviour

App should star.

### Actual Behaviour

The program errors with

The error: procedure entry point DiscardVirtualMemory could not be located in the dynamic link libary KERNAL32.dll

### Reproduction steps

Try running BAR with latest update on windows 7.

**Comment by 6AKU66** [comment]
Windows 7 is not supported now. Not-a-bug.
Update Windows or migrate to Linux. Or use third party client (on your risk).

**Comment by mors555** [comment]
> Windows 7 is not supported now. Not-a-bug. Update Windows or migrate to Linux. Or use third party lobby client (on your risk).

There's no reason you can't compile it under win32, since the last version of bar worked fine on windows 7.  AKA there is no reason for it to require windows 10+, since windows 10/11 are crapware that removes your right to own your own PC.

**Comment by 6AKU66** [comment]
We use Electron for launcher. Electron uses chromium. Chromium no longer supports Windows 7 and that's why it fails (Marek)
