### ISSUE TITLE
Widget chat might lag when simple team colors on

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2710]
### Description

Condition: simple team colors must be on 

![Capture](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/89547444/f6e7ce25-d8e5-4c73-99c2-eb5bac9f668a)

### Expected Behaviour

Too much lag

### Actual Behaviour

Less lag

### Reproduction steps

1. Spectate some match
2. Enable simple team colors
3. Change team of spectating
Result: it's might lag a bit or might lag very hard (Maybe it's depends on how much there's messages in history?)

**Comment by Ruwetuin** [comment]
should be fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/72d1b1849f4d745fd96d5ecb79dba52cd28bc1aa
