### ISSUE TITLE
FFA gadget sending a lot of data if there's a lot of players (60 players)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2711]
4500 kB/s on for this gadget in this example. If we will go higher (amount of players) it's might cause problems since it's might be exponential load grow.
![Capture](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/89547444/62ca4fc7-0421-493e-b358-e9b336b66134)

**Comment by sprunk** [comment]
> If we will go higher (amount of players)

so don't

**Comment by Beherith** [comment]
Thanks for making an issues for this, i noticed it as well.

**Comment by Ruwetuin** [comment]
fixedin https://github.com/beyond-all-reason/Beyond-All-Reason/commit/c491b97c35e3d245463b6753b2423447b0f17c12
