### ISSUE TITLE
Chat widget crash with enabled simple team colors (with enabled use different shades toogle)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2718]
It's happening sometimes. If need more info ask me to get it.

[t=00:00:48.671338][f=0000431] Error in AddConsoleLine(): [string "modules/i18n/i18nlib/i18n/interpolate.lua"]:33: bad argument #2 to 'format' (no value)
[t=00:00:48.671360][f=0000431] Removed widget: Chat

**Comment by Ruwetuin** [comment]
sometimes.... is sometimes equal to when someone shares x units?
