### ISSUE TITLE
Add an option for anti-air units and defenses to specifically target anti-ground units (like bombers, shurikens, etc.) or anti-air units (like fighters)

### ISSUE THREAD

**Issue by Dennshirennshij** [beyond-all-reason/Beyond-All-Reason#2736]
### Description

I think there could be a button on for example the Arbalest to choose a primary target with special priority. 
If the button is set to Anti-ground first, the gun would target bombers, gunships and shurikens first. 
If the button is set to Anti-air first, the gun would give special priority to killing all the fighters of the enemy team before anything else. 

Every other visible air unit would get the next lower priority (would get targeted after the chosen priority target group).

There could also be a default mode, that treats every air unit the same like it is now (all air units have the same priority). 

### Why?

For example if you play at the front positions, you build anti-air defenses to stop enemy bombing runs. Although when the enemy tries to do a bombing run they typically send in their fighters with the bombers so that the anti air defenses target the fighters first. 
I think that the player should be able to assign priorities to different air unit groups because it would be more realistic that way. 

### What area of the game does this feature request pertain?

Gameplay, Settings, Controls or Hotkeys

### Other (optional)

This selecting feature could be implemented by using a button like the one that is already used in the "fire at will"/"return fire"/"hold fire" setting.

**Comment by WatchTheFort** [comment]
Declined by the Game Design Team. This used to be in the game, where anti-air units had a toggle to prioritize bombers or fighters. The toggle was removed to simplify command clutter, and as the overwhelming majority of the time it was set to bombers, all AA by default was set to prioritize bombers.

**Comment by 6AKU66** [comment]
To my knowledge the toggle was removed because it's was bugged and no one fixed it.
