### ISSUE TITLE
Benchmark results can vary because of different settings

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2748]
We need more reliable benchmark results for ability more accurate compare different systems.
Solutions:
1. The best solution probably gonna be to have one single graphics/widget preset system that will ensure that everyone using the same graphics options and widgets. Most likely it's require developer's work.
2. Worse solution only for widget problem can be applying `/luaui disable` code before start of the test. This won't require developer's work, it's less optimal because it's might skew results and it's don't solve graphics variance.

P.S 
Benchmark most affecting settings in descending order:
Particle limit (amount of particles on the battlefield)
Reclaim field hightlight
Lights (gadget explosion_light)
Grass (gadget explosion_light)

**Comment by 6AKU66** [comment]
> Why is this a useful ability?

Because people might plan update for them system and they would like to know how much faster new system will be. Like maybe they wanted update system to another one, but they changed them's mind because it's would give only 5-10% speed gain.

**Comment by thehobojoe** [comment]
I don't think this is a useful issue, performance differences can only be accurately tracked by running the same tests on the same hardware with the same parameters.

**Comment by 6AKU66** [comment]
"by running the same tests on the same hardware"
Some people would like to compare results for them's machines.

"with the same parameters"
This is why i created this ticket, we need to make sure that everyone running game on same graphics settings.

**Comment by Beherith** [comment]
This benchmark is mainly for benchmarking our own systems and settings vs itself, not for comparing users to each other in a broad sense.

**Comment by Beherith** [comment]
There is too much uncontrollable variability otherwise.

**Comment by 6AKU66** [comment]
It's can be both. I can remake this ticket to more fitting one.
