### ISSUE TITLE
Resource bars improvement.

### ISSUE THREAD

**Issue by Sipke82** [beyond-all-reason/Beyond-All-Reason#275]
A while a go i saw mentioning of Supcoms UI, with in particular about the Mass/Energy being in one place and giving a final number. I think its a really good idea.  also helps on eye movement as everything is in 1 place
Perhaps we can build further on it, to also create more awareness of metal maker efficincy and buildpower efficiency (Sadly that buildpower bar was removed, but perhaps it was just not used enough because it was a bit hidden for the new players). so i made an awesome Paint mockup of such a panel.
Perhaps the metamaker efficiency could have 2 bars, one for regular ones and one for moho?

![image](https://user-images.githubusercontent.com/30873812/116809043-82749d00-ab3c-11eb-8f46-12523e0b6249.png)

**Comment by WatchTheFort** [comment]
I lean toward simplifying the UI, rather than complicating it. The more there is, the less friendly it is to new players.

Do the idle builders and factory build bars address buildpower efficiency?

**Comment by KyleAnthonyShepherd** [comment]
Closing, and linking to discord where suggestions like this (that are not bugs) can be made, 
https://discord.com/channels/549281623154229250
