### ISSUE TITLE
Map_grass_gl4.lua is affecting simulation speed even on maps without grass

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#2752]
It's lagging simulation this via gadget explosion_light when units are firing at the ground.

Solution: disable grass if grass is not even present on map.

**Comment by 6AKU66** [comment]
Sorry for no data, but i need to sleep.

**Comment by Ruwetuin** [comment]
should be fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/9377c0bb49a8409b9d1a0d58bfce05f4ff6f1109
