### ISSUE TITLE
nano particles do not follow construction aircraft movement

### ISSUE THREAD

**Issue by Sipke82** [beyond-all-reason/Beyond-All-Reason#276]
When a construction aircraft is reclaiming and it moves, the nanoparticle beam will not move along.

![image](https://user-images.githubusercontent.com/30873812/116812675-48ad9180-ab50-11eb-9dd9-8af5ee8834bc.png)

**Comment by Beherith** [comment]
Because nano particles cant change their start/end points after spawning. Kind of unfixable :/
