### ISSUE TITLE
Gather and Wait Command: Last Unit(s) to arrive don't follow the next command

### ISSUE THREAD

**Issue by MTKing4** [beyond-all-reason/Beyond-All-Reason#2799]
### Description

it seems that the last unit to arrive at the gathering is triggering the others to move but doesn't move itself, i assume that it's transitioning to 'Gathering' status too Quick and is not taking the move command

### Expected Behaviour

All Units should follow to the next Path

### Actual Behaviour

Last arriving units are remaining idle after switching from `Gather and Wait` move Order

### Reproduction steps

1.Select a group of units and order them to move somewhere
2. Press Gather and Wait Command
3. Press Shift and queue another move command
4. Once all Units reach the `Gather and Wait` location some of them will idle there.

### Other
Discord Report
https://discord.com/channels/549281623154229250/1222971351464149122

**Comment by thehobojoe** [comment]
@MTKing4 can you please make an issue in the engine repo for this, with a video+replay (as short as possible) demonstrating the issue? https://github.com/beyond-all-reason/spring/issues
