### ISSUE TITLE
Hitbox issues

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#2979]
### Description

Pitbull vs Scorpion: Scorpions targetpoint is set way higher than pitbulls. A pitbull can be walled off with a teeth vs thugs (arcing projectile / janus) while Scorpions is very vulnerable to even rockos (linear projectile).

Cortex T2 metal storage: Hitbox width is rectangular, missing hitbox size on its left side in north facing direction.

Cortex T2 storages also misses some hitbox height in comparison to Armada energy storage. Might not be doable but it does matter when you wanna use it for walls, for example Cortex HLT got its targetpoint set so high you cant wall with T1 metal storage, while you can wall the other turrets (llt/beamer/tg/armhlt). The Armada T2 energy storage can be used for walls also, while Cortex energy storage cannot as it misses this hitbox height.

### Expected Behaviour

Balance / Uniformity

### Actual Behaviour

Imbalance

### Other

Pitbulls being wallable with a single 8 metal piece (adds 2800 HP) is really op, maybe it should have its targetpoint raised to Scorpion instead of lowering Scorpions.

T1 walls are already good for claw/maw and as mentioned metal storage can be used to have a wall for the other turrets, with a repair speed of 200+ HP/s per 300 bp which is really good.

**Comment by drivver44** [comment]
Aimpositions have massive consiquences and have certain requirements
I’ll look into the other hitboxes 
But I’m still waiting on the gdt to define what hitboxes are meant to be
Aimpositions while they can be dynamic are not in the scorpion and pit bull case

**Comment by drivver44** [comment]
so in regards to the pop up sabots
no change will occur
since im using my own hitbox ruleset that is why no change will occur
if the gdt decides to go with a different hitbox ruleset then changes may occur
in regards to the storages ill have changes done

**Comment by SethDGamre** [comment]
@drivver44 if this issue will be taken care of by your aim position standardization initiative, does that mean this issue can be closed?

**Comment by drivver44** [comment]
i want to say it can be closed for now

> @drivver44 if this issue will be taken care of by your aim position standardization initiative, does that mean this issue can be closed?
