### ISSUE TITLE
IceXuick

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/Beyond-All-Reason#3000]

**Comment by StanczakDominik** [comment]
Indeed

**Comment by hihoman23** [comment]
How are we planning to implement this?

**Comment by sprunk** [comment]
not feasible atm, requires engine change

**Comment by hihoman23** [comment]
Is there a workaround?

**Comment by StanczakDominik** [comment]
Seriously though, what's the story here, typo or...? I'm curious

**Comment by hihoman23** [comment]
I think it’s because it’s number 3000

**Comment by icexuick** [comment]
Sorry I was testing out Git Projects, which is kinda annoying as you can only add drafts to the kanban, but can only change that by converting it to an issue. Need some training to understand this, or I should just stick to Trello :)
