### ISSUE TITLE
 "shorterror": "[t=00:50:27.270160][f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=RecvLuaMsg trace=[Internal Lua error: Call failure] [string \"LuaRules/Gadgets/game_initial_spawn.lua\"]:494: Incorrect arguments to GetTeamList([allyTeamID])"

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#3010]
### Description

Happens when draftmode is enabled. About a few dozen instances of this bug in the past few days. @TomFyuri 

### Expected Behaviour

Should not

### Actual Behaviour

Does

### Reproduction steps

Draft Mode

**Comment by TomFyuri** [comment]
The code for that was fixed here.

https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2930
