### ISSUE TITLE
Timeline in replay

### ISSUE THREAD

**Issue by Benliam12** [beyond-all-reason/Beyond-All-Reason#3018]
### Description

Add a timeline in the replay so you can see specific moment of a replay.

The timeline could also have some other features (markers) such as big event during a game (massive destruction of unit, commander destoyed/killed, etc)

### Why?

Currently, you can only go forward at different speed in a replay. Sometime you only want to watch a certain period in the replay which i hard to get to the exact moment, and location that you want to watch.

### What area of the game does this feature request pertain?

Other

**Comment by sprunk** [comment]
neither going backwards nor predicting events forwards are really feasible due to engine architecture
