### ISSUE TITLE
six-legged spiders

### ISSUE THREAD

**Issue by tamebits** [beyond-all-reason/Beyond-All-Reason#3068]
### Description

Call me smartass, but spiders have 8 legs. It caused a severe wtf moment when I scrolled through the unit list and saw all those 6-legged bots named spider. Name them hexapods, bugs, whatever but not spiders. Or add more legs :-)
Ticks are arachnids too so they also deserve 8 legs.

### Why?

Because it hurts to see 6-legged spiders in an otherwise great game.

### What area of the game does this feature request pertain?

Graphics

**Comment by SethDGamre** [comment]
Hexapod might work, insectoid might be better

**Comment by sprunk** [comment]
keep as-is, making autists upset is a feature

**Comment by SethDGamre** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3797/files this PR and the discussion within it will take over for this issue.
