### ISSUE TITLE
center view when fully zoomed out

### ISSUE THREAD

**Issue by spooky** [beyond-all-reason/Beyond-All-Reason#310]
Supcom has a nice feature when you zoom out all the way, it centers the map on the screen. This helps with scenarios when you zoom out from e.g. a corner of the map to see the entire thing.
I think it would be nice to port this feature to BAR.

**Comment by KyleAnthonyShepherd** [comment]
Issue worded as a suggestion. Linking to discord, where suggestions can be discussed, and closing due to age.
https://discord.com/channels/549281623154229250
