### ISSUE TITLE
[FR] CTRL + LMB on a unit to select all visible units of same type (as an option)

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3115]
### Description

This feature exists in Starcraft 2, and it makes micro a lot smoother than having to double-click to select all of same type.

### Why?

A hotkey exists for this already, but it's clunky to use. CTRL + LMB is much smoother.

### What area of the game does this feature request pertain?

Gameplay, UI/UX, Settings, Controls or Hotkeys

### Other (optional)

Due to how modifiers work currently in BAR, this may affect some other behaviors.

**Comment by Ruwetuin** [comment]
CTRL-click is a well defined default selection behavior across all UI app implementions so this would interfere with expected behavior
