### ISSUE TITLE
Fac buildqueue cancels from the back unless ALT

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3120]
### Description

There are two scenarios that happen with priority queue on factories with repeat turned on: one works as expected, and the other doesn't.

In both scenarios, you start by normal queueing e.g. 5x Fatboys, and then ALT-queueing (prio queue) 1x Advanced Constructor.

### Expected Behaviour

1. If you let the current Fatboy finish, the Constructor should queue up after it.

2. If you want to rush out the Constructor, you cancel the Fatboy that's building. The Constructor should queue up.

### Actual Behaviour

1. Works as expected. The Constructor is put in queue.

2. **The next Fatboy gets queued, ignoring the priority queue!** In order to get the constructor to start building, you need to **cancel all Fatboys**!. It doesn't matter if you use mouse clicks (with different modifiers), or hotkeys. The result is the same.

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/9ff6505d-7eec-47e4-8822-48687849d4e0

### Reproduction steps

Make factory, put it on Repeat, queue unit X multiple times, priority queue unit Y, cancel unit X.

**Comment by sprEEEzy** [comment]
Hold on, this may not be a bug in the full sense of the word.

If you hold ALT and then RMB, it cancels the front unit, and jumps to the prio queue. If you don't hold ALT, it cancels the back unit, and the front one is still being built.

Same can be done using hotkeys on grid, but the button combination to cancel the front unit is CTRL+ALT+key.

It may be a bit unintuitive while playing, but it seems to be consistent?

**Comment by hihoman23** [comment]
I think this would count as intended behavior
