### ISSUE TITLE
Factory (not on repeat) overwrites current unit that's building, even if it's the same unit type

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3121]
### Description

When adding a unit using ALT, while factory is not on repeat, there's a redundant unit cancellation in one case.

### Expected Behaviour

If you have 5x Welders queued, and you ALT+queue 1x Welder, you'd expect the game to just add another Welder to the queue.

### Actual Behaviour

The factory **cancels the current Welder and starts making a... Welder.** This also means that if you add 10x Welders thru ALT-queue (1 by 1), they'll cancel one another out, and the last one added will start from scratch.

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/405c2d8d-01bd-44a3-9497-e959ac880faf

### Reproduction steps

Make factory, put it on Repeat, queue unit X, priority queue unit X.

**Comment by sprunk** [comment]
Engine https://github.com/beyond-all-reason/spring/issues/1537

**Comment by hihoman23** [comment]
Closed by #1522
