### ISSUE TITLE
Website feedback - Wrong use of the word "detrimental"?

### ISSUE THREAD

**Issue by hoijui** [beyond-all-reason/Beyond-All-Reason#317]
hey guys,
I am impressed that you are still here! :-)

feedback regarding:
https://www.beyondallreason.info/news/lets-see-clearer

It seems to me, that the meaning of "detrimental" you had in mind, does not fit the common understanding of it:
*tending to cause harm*

all the best with this project, looks great!

**Comment by icexuick** [comment]
fixed / replaced with "crucial".
