### ISSUE TITLE
Starting spot suggestions as default on rotation 8v8 maps

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3174]
### Description

Playing map rotation lobbies (non-"op") can be a painful experience for a lot of players, because most of the maps are confusing to newcomers in terms of where to even place your com at start. More experienced players tend to offer guidance, but not all players are willing to listen to that and/or cooperate, creating a lot of non-games.

### Why?

The starting spot suggestions would streamline the spot drafting experience, and have players better understand the very start of each map. If players want to deviate from those suggestions, that's fine, but at least they're first made aware of what a default strategy would look like.

If this is to be made, it's vital that this becomes core part of the game, and enabled (as an option) by default. Otherwise, it doesn't serve any purpose - e.g. if newcomers first have to download a custom widget.

### What area of the game does this feature request pertain?

UI/UX, Settings, Controls or Hotkeys, Other

### Other (optional)

This can be further expanded with short comments on positions, and other features.

**Comment by TheSilverHornet** [comment]
If this is done then more attention needs to be paid to updating the start position information, there's many that are outdated or flat out wrong, Koom for one example

**Comment by MeSaber** [comment]
Would it be more dynamical to have a starting spot script? Because each map can have custom starting zones like horizontal or vertical.
script: you have this particular starting zone and this many players, find the x-playerAmount of best spots in terms of metal/s around y-commanderRange and point those out with a ping.

**Comment by sprEEEzy** [comment]
Ideally, you'd want someone with experience in playing these maps to put markers in correct spots, and write in few words what the role is (air, sea, eco, whatever).

**Comment by BillyTom** [comment]
I would argue that for new players slightly out of date markers are better than no markers at all.

**Comment by sprunk** [comment]
Solved by #3486 ?

**Comment by hihoman23** [comment]
Yes
