### ISSUE TITLE
Air Repair Pad the ability to set patrol or waypoint route after repair

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3244]
### Description

Have the ability to set a 'default' patrol/waypoint route for air units that gets repaired but dont have own orders.

### Why?

Less clutter around the air repair pad / usefulness to assign default paths. Basically QoL.

### What area of the game does this feature request pertain?

Gameplay

**Comment by WatchTheFort** [comment]
After discussion in the Game Design Team, we have decided to remove Air Repair Pads from the game.
