### ISSUE TITLE
"zzz" indictor on idle factories only when no spot designated for produced units to go through

### ISSUE THREAD

**Issue by matthiaskrgr** [beyond-all-reason/Beyond-All-Reason#3271]
### Description

1) have factory
2) "clear queue" of the factory
=> "zzz"  appears
I assume this supposed to indicate "this unit is idle"
3) designate a location of the built units of the factory to go somewhere (select factory + right click somewhere)
=> the "zzz" disappears although factory is still idle technically

Seems like the code is something like "if this unit is not moving and has not reached its target location, display "zzz"" but factories cannot move  so it never gets into "zzz" state although not producing any units? :D

### Expected Behaviour

see above

### Actual Behaviour

see above

**Comment by hihoman23** [comment]
I am planning on doing this soon

**Comment by hihoman23** [comment]
Sorry, I accidentally clicked the button
