### ISSUE TITLE
Refine "Show Start Position" Widget, add it to core game in order to improve NPE

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3342]
### Description

[Discord Suggestions thread](https://discord.com/channels/549281623154229250/1259438392316526602).

The **New Player Experience (NPE)** would benefit from having starting position suggestions displayed on maps, especially in rotation lobbies. This would be a point of reference for players coordinating initial commander placement, but it would not be a rule that must be followed. It should overall be a net positive even for players arguing about where to start, and a huge boon to those that are playing a map for the first time. A map like e.g. "Riverrun", that gets played a lot, is a huge mess, and it requires some guidance from the mapmaker, even at high level lobbies.

Start positions are defined by map makers. Currently, most maps **don't have the starting spots defined in correct places** for the "meta" in 2024. The point of this widget is not to have the latest meta, but a distribution of positions that ensures a fair and interesting game for all participants. The recent addition of numbers on the positions adds more depth to the initial coordination: "I'll play position 4!".

The widget does need some extra polish before being put into the core game. Biggest issue seems to be editing the already-defined start spots. @salinecitrine is the creator.

Widget on Discord: https://discord.com/channels/549281623154229250/1174062016231649410
Widget file: https://gist.github.com/salinecitrine/55875fb0fe5f983ffc0fa7131c2dd9e4

![quicksilver (1)](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/fea3b64c-0944-4abf-98ce-da50ec7218b7)

### Why?

Players often have no idea where they're supposed to play on a map they've never see before, especially if the mexes in the starting area don't paint a clear picture of how the start would look like.

This also puts pressure on the red/blue player to coordinate everyone, but not every player trusts strangers they're playing with for the first time.

Players are obviously encouraged to experiment with different strategies, and this is **by no means a tool for players to harass other players that don't respect the recommendations**.

**It is crucial that this widget makes in into the core game, and is turned ON by default, otherwise its existence is not useful to that many players**. By the time a new player realizes this custom widget exists somewhere on the Discord, he has probably played 50-100 games already.

If this idea is approved, I'll gather a few high level players and get them to define positions together for the 30 most popular 8v8 maps for starters, with more added over time.

### What area of the game does this feature request pertain?

UI/UX, Other

### Other (optional)

Rename widget to: "Start position suggestions".

The widget could be expanded further by adding short "role" comments for each position.

**Comment by p2004a** [comment]
Resolved via #3486
