### ISSUE TITLE
Context Build doesn't work for Beaver (T1 Vehi Ambhib Con) LLT -> Torpedo

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3344]
### Description

The only Armada builder that I could find that doesn't have auto conversion of LLT into Torpedo within Context Build Widget.

### Expected Behaviour

LLT turns into Torpedo Launcher when on water

### Actual Behaviour

LLT stays LLT

**Comment by hihoman23** [comment]
Should have been fixed in #2497

**Comment by hihoman23** [comment]
I also can't reproduce, are you using a current version?

**Comment by sprEEEzy** [comment]
> I also can't reproduce, are you using a current version?

Weird, I had a late 2023 version in custom widgets, apparently. Thanks. Closing!
