### ISSUE TITLE
Add Ability to Turn OFF command cancelling by clicking on issued commands on the ground

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3370]
### Description

Currently, if you're trying to transport 3 units to the same spot one by one, you're likely going to cancel one of your unload commands with another unload command, because you clicked on the same spot.

### Why?

It'd be nice if the game offered choice of having this ability turned off. But, this should be separated from cancelling your building queue by placing another building on top of the current blueprint (if that's even connected!).

### What area of the game does this feature request pertain?

Gameplay, Settings, Controls or Hotkeys

### Other (optional)

Is this an engine issue? If yes, please redirect to engine hub.

**Comment by WatchTheFort** [comment]
Does this impact anything other than transport unloading? That specific issue should be mitigated in the transport rework.

**Comment by sprEEEzy** [comment]
> Does this impact anything other than transport unloading? That specific issue should be mitigated in the transport rework.

Well, yes. If you want your units to go back and forth a few times, you can accidentally cancel the move commands, for example.

**Comment by sprunk** [comment]
Here's an engine ticket (since removing duplicates is an engine behaviour), but I wouldn't close this one yet because it would be good to discover what can be done game-side (since UI design should be game responsibility). beyond-all-reason/spring#1593

**Comment by WatchTheFort** [comment]
Declined by the GDT. Editing and cancelling orders needs to be handled through proper UX, rather than the current hidden mechanics.

e.g. Holding shift displays an X button in the corner of individual orders in the unit's queue, and clicking this cancels the individual order.
