### ISSUE TITLE
Swap server region without making a whole new lobby

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3372]
### Description

Currently, it's not possible to just switch from EU to US, when most people are US-based in the lobby.

### Why?

This feature would enable higher quality connection for the avg player in the lobby, when used at appropriate moments.

### What area of the game does this feature request pertain?

Other

**Comment by p2004a** [comment]
Belongs in teiserver repo, in which there is already issue for it: https://github.com/beyond-all-reason/teiserver/issues/356
