### ISSUE TITLE
Fido's are broken 

### ISSUE THREAD

**Issue by triton13** [beyond-all-reason/Beyond-All-Reason#34]
when there is something on a hill, they stay too far with fight command, and wont shoot or move.
Not sure it's only for fidos...

**Comment by icexuick** [comment]
Is this still the case?

**Comment by triton13** [comment]
idk try to shoot on hillz on altored with fight command

**Comment by icexuick** [comment]
I believe there was done something here - is that correct? @Ruwetuin

**Comment by fruehling76** [comment]
yeah there was a problem on altored divide once , but i am not sure if it was only for fidos.

**Comment by PtaQQ** [comment]
Please provide more info on how to reproduce. I have not experienced this bug. Quick glance at the units script and I see nothing suspicious.

**Comment by fruehling76** [comment]
is that problem resolved? if "yes" someone close pls

**Comment by sprunk** [comment]
As far as I can tell that's an engine issue that can happens somewhat haphazardly for any ballistic units (see ZK ticket https://github.com/ZeroK-RTS/Zero-K/issues/2955 )

**Comment by KyleAnthonyShepherd** [comment]
Combing through old issues. 
I think this is an engine side issue, where on flat ground the two fido fire modes are equal range, but on elevation changes the different velocity attacks get different elevation range boosts, and the unit only advances to the maximum range weapon and not the currently active weapon, stopping too early.
Gonna close this here and link to relevant engine issue
https://github.com/beyond-all-reason/spring/issues/776
