### ISSUE TITLE
I can login to the website but my login doesn't work with app.

### ISSUE THREAD

**Issue by Bitcoinrocket** [beyond-all-reason/Beyond-All-Reason#3424]
@Beherith
Hi I am facing the same issue. Do you know how can I fix this?

Username : vesa
email : vesadn@pm.me

_Originally posted by @Bitcoinrocket in https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2908#issuecomment-2236444045_

**Comment by Bitcoinrocket** [comment]
I can login to the website but my login doesn't work with app.
It tells me that it send me an email with code but I received nothing even in my spam.
Please help me

**Comment by TheSilverHornet** [comment]
You should have made a ticket on the BAR Discord instead, this is not the right place
