### ISSUE TITLE
Factory auto-repeat should set the repeat state as soon as the lab is created

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#3443]
### Description

![image](https://github.com/user-attachments/assets/ac4fa6f9-e956-4283-8cee-024a769eabec)

Currently, when this setting is enabled, the repeat state becomes true when the lab has finished building. An improvement would be to set the state as soon as the lab has started being built.

### Why?

This would allow for players to turn a lab off repeat before it has finished building, as currently this setting will always override this choice.

### What area of the game does this feature request pertain?

UI/UX, Settings, Controls or Hotkeys

**Comment by WatchTheFort** [comment]
This sounds like a general problem that stateful orders cannot be applied before a unit is finished?

**Comment by sprunk** [comment]
They can, the widgets are just ancient.
