### ISSUE TITLE
Add additional option for "Autogroup immediate mode" that adds a unit into autogroup while it's being built

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3449]
### Description

Currently, if a unit is being built, it's not added to autogroup with "Autogroup immediate mode": ON, until it leaves the factory.

![image](https://github.com/user-attachments/assets/5efe37e6-ec93-4173-9a2f-104277e450b7)

### Why?

This makes for clunky micro when you want to rally a single unit to defend your base. I usually use _group unset_, instinctively, but that doesn't work, as the autogroup currently assigns it when it leaves the factory. Group unset does nothing.

### What area of the game does this feature request pertain?

Gameplay, UI/UX, Settings, Controls or Hotkeys

**Comment by WatchTheFort** [comment]
Approved by the GDT. This should be implemented to replace the current behaviour, and no additional option added.
