### ISSUE TITLE
Ticks can glitch inside factory and become untargetable by attacks

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3457]
### Description

Ticks (and possibly other small units) can get "inside" a armada t1 bot lab and shoot at it, while being untargetable, due to widget/engine blocking friendly fire.

https://clips.twitch.tv/KindBeautifulOstrichAliens-0kXu72vuFsCaP_ky

### Expected Behaviour

Can still shoot enemies, even if inside a friendly building (at the cost of taking ff)

### Actual Behaviour

Cannot shoot enemies

**Comment by WatchTheFort** [comment]
We will be able to address this after the upcoming engine release, see https://github.com/beyond-all-reason/spring/issues/453

**Comment by sprEEEzy** [comment]
> We will be able to address this after the upcoming engine release, see [beyond-all-reason/spring#453](https://github.com/beyond-all-reason/spring/issues/453)

Ah nice, so it's already queued.

**Comment by drivver44** [comment]
> We will be able to address this after the upcoming engine release, see [beyond-all-reason/spring#453](https://github.com/beyond-all-reason/spring/issues/453)

i dont share confidence that this fixes the issue
the core problem is that units are not being properly pushed out of the footprint of the factory to begin with

**Comment by SethDGamre** [comment]
Looks like this issue is resolved thanks to Hornet and engine changes.
