### ISSUE TITLE
Be able to disable repeated commands from rightclick drag

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3461]
### Description

You are able to disable this for shift+rightclick drag, but there is no option to disable it altogether.

### Why?

Sometimes you dont want accidental extra moves when rightclicking where you want a unit to go, makes you have to stand very still with mouse when clicking.

### What area of the game does this feature request pertain?

Gameplay

**Comment by sprEEEzy** [comment]
Id like to see this too, but it might be an engine issue.

**Comment by ChrisFloofyKitsune** [comment]
This behavior is indeed in the cmd_customformations2.lua widget

I poked around in there a bit when I was adding formation right-click drag to the Thor EMP missile- but also made sure that it didn't make a path when you only had one selected

This would be a new option yeah? something like... "Enable repeat command when dragging". The existing could be renamed to "Hold shift to repeat command drag"?

Or replace it all together with a list of options

#### Repeat command when dragging
* Disabled
* On, Shift disables
* Always On

I can knock out the code for this, I'm just having trouble with how to word the options

**Comment by MeSaber** [comment]
i think this would be better if it had an option to make the spacing between rightclicks bigger, currently it sets a new move command for every millimeter of mouse movement. With proper spacing the command would be fine to use as is, it would also fix the accidental mouse drag when you want a single move command.

**Comment by WatchTheFort** [comment]
It sounds like there needs to be an additional threshold on this, for absolute mouse pixel travel distance. Right now there are thresholds for time and minimum map distance.

Would this mitigate the issue, so that at zoomed out levels small movements of the mouse cursor don't trigger it?

**Comment by WatchTheFort** [comment]
Declined by the GDT, as the root cause should be addressed, rather than adding an additional setting.
