### ISSUE TITLE
Give scorpion enough fuel to hit the target

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3471]
### Description

Missing some fuel to hit the full range when on a tall mountain.

https://i.imgur.com/TqWb5Mc.png

### Expected Behaviour

To hit.

### Actual Behaviour

Blows up early.

**Comment by SethDGamre** [comment]
But you are seeing is burnblow = true for the weapon. It blows up if the missile goes beyond its maximum range, otherwise it would go on continuously forever. There is no fuel. 

How did you set the target for this thing to shoot the scout vehicle down below? Attack ground or attack unit or Auto targeting?

**Comment by SethDGamre** [comment]
![image](https://github.com/user-attachments/assets/833e1844-80cc-48ab-8a7a-94fa2bbc9ecc)
yep, I see it too

**Comment by SethDGamre** [comment]
flighttime is the name of the def that determines this behavior. looks like it was miscalibrated.

**Comment by SethDGamre** [comment]
burnblow doesn't work on missiles apparently
![image](https://github.com/user-attachments/assets/db986f4e-99aa-4fa3-bfd0-733d339352bd)

increasing flighttime makes missiles yeet beyond max range allowing for cheese shots. 1.05 value appears to be carefully calibrated to prevent bonus range.

**Comment by SethDGamre** [comment]
disabling burnblow allows the projectile to exist without continued velocity.

**Comment by SethDGamre** [comment]
this will be fixed with the above PR. If it isn't, it'll push the issue along. I'm closing this issue as resolved.
