### ISSUE TITLE
Tremor erratically changing target

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3472]
### Description

After you switched to 'spread fire' it seems to behave very badly, it stops firing because it has to move turret towards the other side of targets instead of using closest targets. It also seem to prefer targets in the backline of targets found, and switch between backline target sides so turret keeps changing.

[2024-07-25_06-51-40-638_Center Command BAR v1_105.1.1-2511-g747f18b BAR105.sdfz.zip](https://github.com/user-attachments/files/16371840/2024-07-25_06-51-40-638_Center.Command.BAR.v1_105.1.1-2511-g747f18b.BAR105.sdfz.zip)

### Expected Behaviour

Fire at closest target in both modes.

Edit: Maybe not change target until current target drops out of attack range.

### Actual Behaviour

Erratic target changing especially in spread mode.

**Comment by SethDGamre** [comment]
I'm gonna bet this is related to proximity priority forcing target changes to farther target.

**Comment by MeSaber** [comment]
Yes this is still an issue with gauntlet/rattle in high trajectory too.

**Comment by SethDGamre** [comment]
it's as I thought.

proximityPriority = -3 for the tremor, and -2 for only high trajectory mode on the gauntlet.

I typically avoid using them because of this exact problem where it forces the unit to reacquire long range targets rather than committing to a shot on a barely closer target.

**Comment by SethDGamre** [comment]
https://youtu.be/ExU1KKRJy6g example of the dumb shit that happens when you have proximity priority < -1

**Comment by SethDGamre** [comment]
https://discord.com/channels/549281623154229250/724924957074915358/1291221698460389407 reducing to -1 seems to create better results

**Comment by SethDGamre** [comment]
I'm gonna consolidate these proximityPriority issues into this and seek approval.
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3807

**Comment by MeSaber** [comment]
> https://youtu.be/ExU1KKRJy6g example of the dumb shit that happens when you have proximity priority < -1

This is the reason you cannot use high trajectory ever because it becomes a micro management issue or manually aiming :/
