### ISSUE TITLE
Improve startbox graphics

### ISSUE THREAD

**Issue by salinecitrine** [beyond-all-reason/Beyond-All-Reason#3476]
### Description

There are several ways to accomplish this. Here are some examples:
* Instead of drawing green/red over placeable ally/enemy areas, darken areas that are not placeable for the current player. Enemy boxes could possibly have patterned darkness. This option is my personal preference.
* Instead of drawing the whole area green/red, only draw the outline, so that most of the enclosed area looks normal. @loveridge has made something like this, mentioned here: https://discord.com/channels/549281623154229250/724293659809284137/1266209734126735442

The solution primarily has to address the "Why?" section below.

### Why?

The current green/red box style:
* Interferes with existing graphics or UI that is on the map; for example, start position circles, or even some terrain. Anything drawn in blue or green within a green start box becomes practically invisible. We should be making the areas that players are interacting with as clear as possible, to make understanding and interacting with that area easier.
* Draws focus towards the center of the map, instead of the actual startboxes. We should be guiding players' focus towards their own start box.
* Looks unpolished compared to much of the rest of the game (understandable, since the code is ~15 years old). This seems like a relatively low-effort way to improve a very common component of the BAR experience.

Current graphics, with start position widget:
![Screenshot 2024-07-25 202432](https://github.com/user-attachments/assets/d38a7fe0-bc4d-42dd-aea0-3eb67b316b8b)

### What area of the game does this feature request pertain?

Graphics, UI/UX

**Comment by MeSaber** [comment]
As the start boxes ATM is only a box, isnt it enough to just make a colored outline instead of filling whole terrain with color?

**Comment by salinecitrine** [comment]
> As the start boxes ATM is only a box, isnt it enough to just make a colored outline instead of filling whole terrain with color?

That would be an improvement over the current version (though I think we can do even better). It sounds similar to what lov has made, which I think is a tweak of the original widget:

![image](https://github.com/user-attachments/assets/228dec96-96c4-4aaf-a784-850212bd281b)
