### ISSUE TITLE
UI suggestions & more

### ISSUE THREAD

**Issue by guivc** [beyond-all-reason/Beyond-All-Reason#351]
First of all thanks for the amazing work!

### Icons vs text
Replace text by icons and when you hover the mouse over you get the description
![image](https://user-images.githubusercontent.com/25881395/123519529-34829e00-d682-11eb-9363-398ef375baee.png)
by
![image](https://user-images.githubusercontent.com/25881395/123519589-a8bd4180-d682-11eb-917d-2dba88c8fdd7.png)

### Font scaling
The available options in the menu for fonts should have much more options.

When I tested the game with my notebook (1366x768 res) I couldn't read lots of text on the screen even changing the font to poppings-medium and ui scaling to 1.10. Please add something "big" for all fonts on the screen (even the in game dialog where I was trying to configure is unreadable).

### Unit paths
By default just see the paths when you hold a key (ex.: shift in supreme commander).
![image](https://user-images.githubusercontent.com/25881395/123520260-42d2b900-d686-11eb-987d-40f9b0cf50fc.png)

**Comment by icexuick** [comment]
We are in the process of making the UI more icon based.
We have multiple designs ready to be build.
Though we're transitioning to a new Rendering method, which requires re-do of the entire UI.

![image](https://user-images.githubusercontent.com/23189106/126344707-eca9a468-9830-43c6-bd75-d69d9e0107c5.png)

**Comment by icexuick** [comment]
Regarding the move-lines - iirc you can disable these when you disable "Command FX" in settings.

**Comment by KyleAnthonyShepherd** [comment]
Issue worded as suggestion. Linking to discord, and closing due to age and due to UI updates in the past 2 years.
https://discord.com/channels/549281623154229250
