### ISSUE TITLE
Better key bindings for sweeping the camera down

### ISSUE THREAD

**Issue by kvanbere** [beyond-all-reason/Beyond-All-Reason#3523]
### Description

It would be nice if the key bindings for sweeping the camera down were changed to something more exotic so they are more difficult to trigger.

### Why?

When you are trying to build in a grid and you press SHIFT+ALT+Z and drag while trying to zoom out or move the camera at the edge, the camera sweeps down and/or you accidentally build over the entire map because there are multiple confusing camera-related key bindings that overlap in this case.

**Expectation:**
Hold Shift + Alt
Drag the area where I want to build
Adjust the spacing by pressing Z and X
Zoom out with mouse wheel
Pan the edge of the screen with mouse pointer
Pick final build dimensions and release mouse to build

**Current:**
Hold Shift + Alt
Drag the area where I want to build
Adjust the spacing by pressing Z and X
Trying to zoom out with mouse wheel switches current building (perhaps we should delete this key binding, it doesn't seem helpful because it takes a long time to cycle through all the buildings 1 by 1?)
Trying to pan the camera causes it to sweep down instead

I do not imagine that sweeping the camera down is done often vs. for example building in a grid or setting the build grid spacing.

Additionally, a UI indicator for the current build spacing would be helpful.

### What area of the game does this feature request pertain?

Settings, Controls or Hotkeys

**Comment by Ruwetuin** [comment]
issue seems to be fixed already / cant reproduce

**Comment by badosu** [comment]
> issue seems to be fixed already / cant reproduce

How was this resolved? Honest question, I want to understand since it relates to issues present in the game (so it can be a regression maybe?)
