### ISSUE TITLE
Remove the requirement of an email when registering for an account

### ISSUE THREAD

**Issue by K4LCIFER** [beyond-all-reason/Beyond-All-Reason#3526]
### Description

Currently an email is required to register for an account. I propose removing this requirement in favor of only requiring a username and password.

### Why?

Requiring an email can be a privacy issue, and it relies on the user to use a 3rd party service to be able to play the game.

### What area of the game does this feature request pertain?

Other

**Comment by p2004a** [comment]
E-mail will remain a requirement. It's valuable for password reset like flows, any potential communication about account, and improves to some degree our moderation functionality.

**Comment by K4LCIFER** [comment]
> It's valuable for password reset like flows, any potential communication about account

I'd argue that there's no need to force these two on the user.
