### ISSUE TITLE
stuff are really invisible 

### ISSUE THREAD

**Issue by icf20** [beyond-all-reason/Beyond-All-Reason#3561]
### Description

![image](https://github.com/user-attachments/assets/7419ce03-b2d1-426e-b865-01dad395c0e7) spectating picture

unless unit shadow is enabled models are not displayed

### Expected Behaviour

unit needs to be transparent no invisible 

### Actual Behaviour

models are not shown

**Comment by drivver44** [comment]
@Beherith is this fixed now?

**Comment by Beherith** [comment]
Fixed
