### ISSUE TITLE
Disable Alt+Scroll While Grid Building (Alt+Shift)

### ISSUE THREAD

**Issue by calmilamsy** [beyond-all-reason/Beyond-All-Reason#3581]
### Description

Tin, basically just make Alt+Scroll just not do it's thing when holding down Alt+Shift.

### Why?

When I use the grid build mode, I have to avoid scrolling, or I get the centered map-wide view, which is awkward when I want to zoom out a little for a better view after picking out my contructors and autopiloting hotkeys for building.

### What area of the game does this feature request pertain?

Settings, Controls or Hotkeys

### Other (optional)

Shifting the bind to Ctrl+Shift+Scroll would also work I think, but I figured the best way for muscle memory would be to do what's mentioned on the title.

I could be missing some interaction that folk rely on, but nothing comes to mind.

**Comment by MeSaber** [comment]
CTRL+scroll might need the same treatment.

**Comment by WatchTheFort** [comment]
In general, we need to decouple modifier keys from camera controls, because they universally interfere with other functions

**Comment by sprunk** [comment]
Just unbind `movefast`, `movetilt`, and all the other `movefoo`.

**Comment by salinecitrine** [comment]
> In general, we need to decouple modifier keys from camera controls, because they universally interfere with other functions

> Just unbind `movefast`, `moverotate`, and all the other `movefoo`. (Don't allow to rebind them because they suck.)

I agree, particularly because even if we handle the case while placing buildings, that will leave pseudo-building (pregame_build and blueprints) with the same issue.

**Comment by sprunk** [comment]
I don't even mean conflicts with other actions and wasting an important key, though those are good reasons as well. Holding a key to pan slower/faster is just very inefficient compared to other means to move the camera. Would anybody ask for it if it wasn't already there?

**Comment by Ruwetuin** [comment]
issue seems to be fixed already

**Comment by badosu** [comment]
> In general, we need to decouple modifier keys from camera controls, because they universally interfere with other functions

They are already decoupled in some way, at least that the action is available (and can be unbound from). I'm not sure how this issue was fixed. I'll add my suggestion to remove movereset bindings (at least in its current incarnation) from default keybinding presets in [this issue](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/4877) instead of reopening this one.
