### ISSUE TITLE
HLLT keeps changing target without killing the first targeted one

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3588]
### Description

Compared to beamer which focuses a target until its killed or moves out of range.

![image](https://github.com/user-attachments/assets/10feffc9-7eaf-463a-9454-b35146f278fd)

### Expected Behaviour

Focus first target (or priority).

### Actual Behaviour

Randomly changing target to give all targets equally much HP.

**Comment by MeSaber** [comment]
Funnily enough the HLLT is doing the enemy a favor here indirectly microing. This is actually a big deal, if you have no repairer on HLLT side no rockos would ever die.

Enemy commander would repair a single unit, and the HLLT would automatically change to this repaired unit because it got the most HP, leaving the other units below 50% alone.

**Comment by SethDGamre** [comment]
proximityPriority strikes again.

From my observations it isn't switching targets based on HP, but rather based on proximity. When proximityPriority is greater or less than -1 or 1 then it'll force the weapon to switch targets at certain proximity thresholds before enemy is killed.

**Comment by SethDGamre** [comment]
I'm gonna consolidate these proximityPriority issues into this and seek approval.
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3807
