### ISSUE TITLE
Not able to play Multiplayer

### ISSUE THREAD

**Issue by DanielAndi** [beyond-all-reason/Beyond-All-Reason#3594]
"You are not connected to the server. Please wait 30 seconds while we automatically reconnect you."

That's the only message displayed on the multiplayer section, It won't change, I haven't found a solution yet

![image](https://github.com/user-attachments/assets/7e708a0f-27b4-4f0d-90c2-cdf674236894)

**Comment by p2004a** [comment]
Best please open a thread on discord support forum and link to uploaded logs.

**Comment by dmdd1233** [comment]
The night before yesterday, after I entered the game, I lost the navigation bar and couldn't think it was my fault; Reinstalled the game But it still remains the same; About an hour later, the developer fixed the bug, but after reinstalling the game, they were unable to access it and received the same error message as you

**Comment by HKScorp** [comment]
change config in launcher, dk how but help me btw

<img width="833" height="452" alt="Image" src="https://github.com/user-attachments/assets/328184e8-76f1-4fbb-9ab7-691705d7cd26" />
