### ISSUE TITLE
Mercury AA T2 tower is missing targets way too much

### ISSUE THREAD

**Issue by triton13** [beyond-all-reason/Beyond-All-Reason#36]
smurf : lol mercury are so fucked
L0v3 : lol yeh

**Comment by Ruwetuin** [comment]
it somehow had a very low startspeed, I've set it the same as the screamer and I think this will fix blowing up before maxrange.

**Comment by Ruwetuin** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/7504367d90d101ab411c3e8bd831ee3f894972a6#diff-8c1a86254185b33657d774872085b960 caused it

**Comment by icexuick** [comment]
I'm sorry! Could we bring back slow start rate and increase flight time? that would probably also solve it AND make it look good :)
