### ISSUE TITLE
Give Claw the same treatment as Thor

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3616]
### Description

![image](https://github.com/user-attachments/assets/c5189b2a-c30b-4c63-bc96-7138efbed67f)

Unlimited search arc for remaining burst.

### Expected Behaviour

Fire the burst in the direction its facing.

### Actual Behaviour

360 burst. See: https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2776

### Other

Implications: Will make the unit far worse vs mass ticks as surrounding ticks dont get insta-shot by same volley.

**Comment by SethDGamre** [comment]
this will be fixed or pushed forward by this PR: https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3808
