### ISSUE TITLE
Conturrets are mobile units (?)

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3617]
### Description

![image](https://github.com/user-attachments/assets/95e69ee9-b3c4-46ff-91cd-7983af56eb43)

This intentional? If so why?

LLT can also be transported but isnt floating around.

### Expected Behaviour

Looks messy, should probably be a static unit like LLT even though it can be moved.

### Actual Behaviour

Its a mobile unit, disappears from radar too.

**Comment by WatchTheFort** [comment]
This is due to an engine limitation when a structure cannot assist construction. There is an engine issue to remove this limitation.
https://github.com/beyond-all-reason/spring/issues/1597

**Comment by sprunk** [comment]
Radar wobble can be removed independently. Steal https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_radar_wobble.lua

**Comment by matthiaskrgr** [comment]
MeSaber  you can also tell from the fact that units have a "front" which they will always reset their turret to after a while (as does the con turret), whereas "real" defensive turrets keep pointing towards their most recent targets after shooting.
So yes, proper orientation of a con turret towards a factory can actually save you a bit of time ^^

**Comment by WatchTheFort** [comment]
> MeSaber you can also tell from the fact that units have a "front" which they will always reset their turret to after a while (as does the con turret), whereas "real" defensive turrets keep pointing towards their most recent targets after shooting. So yes, proper orientation of a con turret towards a factory can actually save you a bit of time ^^

That is entirely due to the unit script, so whether a unit is a building or mobile will have no bearing on that

**Comment by sprunk** [comment]
Turret reset is controlled by this line. https://github.com/beyond-all-reason/Beyond-All-Reason/blob/a0565ce1484df67f04a5e002cf5b7cdeae05b778/scripts/Units/armnanotc.bos#L64

**Comment by SethDGamre** [comment]
This is a question with a definitive answer. Other discussed problems have open issues that more accurately address said issues. 

Side note about turret orientation, that is due to the transport aircraft placing the units at whatever heading they're facing. Separate issue. 

Restore after delay may be able to correct the turret body orientation but seems like a nitpick for a uncommon use case.

Please update the title to something more fitting a real issue or close it.

**Comment by SethDGamre** [comment]
I found another issue that already has obtained approval that can take care of the construction turret orientation issue.
