### ISSUE TITLE
UnitDamagedReplay, but for spectating

### ISSUE THREAD

**Issue by MasterBel2** [beyond-all-reason/Beyond-All-Reason#3634]
### Description

BAR has an [unsynced gadget](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/dev_replay_data.lua) that enables UnitDamaged when the game is a replay, but, this would be valuable when spectating also. Can we have this for spectators also?

### Why?

_

### What area of the game does this feature request pertain?

Codebase or APIs

**Comment by SethDGamre** [comment]
@sprunk do you think this is an engine side issue?

**Comment by MasterBel2** [comment]
@SethDGamre I strongly suspect this could be implemented in the engine, but it also seems appropriate to raise the issue here, since they already are working around engine behaviour.

**Comment by saurtron** [comment]
Implemented this at #3902.

**Comment by saurtron** [comment]
@SethDGamre PR merged some days ago, this should now be fixed.

**Comment by SethDGamre** [comment]
Thanks for your work!!
