### ISSUE TITLE
Platypus untargetable on water

### ISSUE THREAD

**Issue by CaptainKickass** [beyond-all-reason/Beyond-All-Reason#3637]
I built a row of urchin (torpedo tower) with a row of slingshots behind it (floating anti air tower). Torpedoes should (to my knowledge) be able to target everything below and on water while anti-air missiles should be able to target everything above water. Yet the enemy platypus came in and neither the torpedoes nor the AA missiles could target it.

**Comment by MeSaber** [comment]
No torpedos dont hit hovers, and platy is secretly a hover unit.

**Comment by drivver44** [comment]
@SethDGamre this issue can be closed as its an intended feature
