### ISSUE TITLE
Dgun can hit air units

### ISSUE THREAD

**Issue by kvanbere** [beyond-all-reason/Beyond-All-Reason#3661]
### Description

I was playing a game and rushed gunships. Their commander d-gunned my gunships which makes no sense visually as the projectile doesn't even hit the planes.

### Expected Behaviour

The d-gun doesn't seem like it should be able to hit air.

### Actual Behaviour

The d-gun seems to be able to hit air.

**Comment by SethDGamre** [comment]
Has to specifically target an air unit.

In skirmish pause the game and target an air unit.
Or disable command fire for the commander d-gun.
D-guns scoot along the ground once it collides with ground like a bowling ball. If it doesn't collide with ground it shoots straight forward.

**Comment by SethDGamre** [comment]
this issue can be closed. further discussion should be done in "suggestions" channel on discord

**Comment by sprunk** [comment]
it's not a bug it's a feature
