### ISSUE TITLE
tutorial [i18n] "tips.notifications.makeFactory" is not translated in en

### ISSUE THREAD

**Issue by aand18** [beyond-all-reason/Beyond-All-Reason#3674]
### Description

In the first mission of the tutorial, the "make factory" translation appears to be missing.

![image](https://github.com/user-attachments/assets/d776f3ab-0df3-4477-b744-c3494ecbb00d)

### Expected Behaviour

"makeFactory" message should be displayed

### Actual Behaviour

A notification is displayed `[i18n] "tips.notifications.makeFactory" is not translated in en`.

### Reproduction steps

1. start mission 1 of the tutorial
2. place metal extractor(s) and windmill(s)   - not sure the exact quantity to trigger the `makeFactory` message

**Comment by WatchTheFort** [comment]
@Ruwetuin this looks like a problem with how the sound notification widget is passing I18N keys, the entry in tips.json has always been `buildFactory`, not `makeFactory`.

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/87b267d8d49a04d81ed6d0ae2c5a8585cd7cba96
