### ISSUE TITLE
minor bugs (hover/sea)

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3686]
### Description

Hover AA's displaying having sonar, they do not.

Carriers having reclaim showing when selected and 'restore' button.

Lightning Ship displaying having radar, it does not.

### Expected Behaviour

.

### Actual Behaviour

Detailing errors.

**Comment by hihoman23** [comment]
I couldn't reproduce 1 and 3, could you maybe send some screenshots or explain what displaying having radar means?

**Comment by MeSaber** [comment]
It says Lightning ship has radar in the details window (i / space, or hover info window bottomleft).

**Comment by SethDGamre** [comment]
yeah I'm seeing what you're seeing. I think it's because hovercraft aren't actually IN the water, they're just above it. Meaning sonar isn't a thing? Just a theory.

**Comment by SethDGamre** [comment]
I was wrong. the torpedo aircraft has sonar that works. Must be something else

**Comment by SethDGamre** [comment]
found the problem. Doesn't have activateWhenBuilt = true

**Comment by SethDGamre** [comment]
the reason why this isn't an issue with sonar planes is because when they take flight they automatically activate the on state meaning so too is sonar activated.

**Comment by SethDGamre** [comment]
this will resolve the rest of the issues https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3812
