### ISSUE TITLE
Grass flickering with zoom

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#375]
After a while the check for draw distance or some other setting gets bugged and grass flickers: https://www.dropbox.com/s/pez3s7tfnu3rpsf/2021-07-18_14-46-34.mkv?dl=0

**Comment by badosu** [comment]
Can't reproduce anymore

**Comment by badosu** [comment]
Nevermind, still present.

Seems to be reproducible only on altair

**Comment by Beherith** [comment]
Its caused by an engine but in tracescreenray
