### ISSUE TITLE
Holding META key doesn't seem to auto-reclaim enemies anymore.

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/Beyond-All-Reason#376]
As title says
While META parameter is given via gadget/widget, it works.

**Comment by KyleAnthonyShepherd** [comment]
Is this still an issue?
More detailed steps to reproduce are needed

**Comment by sprunk** [comment]
isn't meta insert?

**Comment by SethDGamre** [comment]
being that nano's reclaim stuff that enter within their range, I checked to see if the meta key was used there. It appears so.
![image](https://github.com/user-attachments/assets/67e1655a-5366-49ef-b2b3-fdfb790de132)
issue resolved?

**Comment by Damgam** [comment]
I have no F'ing idea

**Comment by SethDGamre** [comment]
what I do know is area reclaim does work while holding... alt? and drag clicking enemies. They'll be queued up to get reclaimed. But you have to click at least one of the enemy units to trigger this behavior.

skill issue. lol

**Comment by SethDGamre** [comment]
Closing as it is unclear what's the original post means, what the reproduction steps are, or what the desired outcome is.
