### ISSUE TITLE
Spectator hud doesn't play nicely with ecostats

### ISSUE THREAD

**Issue by saurtron** [beyond-all-reason/Beyond-All-Reason#3800]
### Description

Spectator HUD widget behaviour conflicts with ecostats, since it will enable and disable it using the wrong heuristics, possibly resulting in difficult to enable ecostats again. Also, toggling spectator hud does not toggle ecostats back.

### Expected Behaviour

- Keeps ecostats disabled if user disabled it through F11.
- Toggling in settings toggles between both widgets immediately.
- Ecostats won't be permanently disabled if spectator hud was enabled at some point.

### Actual Behaviour

- When enabling spectator hud in settings, ecostats will be disabled, but disabling it won't enable ecostats again. What is worse, there is no way afterwards to have ecostats back unless going to f11 menu, or going to ffa with spectator hud enabled again.
- If spectator hud is enabled but not going to be activated (not 2 team spec), it will enable ecostats, even if the user doesn't want it (like if the user disabled it manually through F11).

### Reproduction steps

1. Enable spectator hud in some 2 player replay or spec
2. Disable spectator hud again immediately
3. Now ecostats is gone (doesn't come back)
4. Start another replay or spec
5. Ecostats still not there (it's not coming back)

Alternatively:
1. Disable ecostats through f11
2. Activate spectator hud
3. Go to a ffa replay or spec
6. Now ecostats is enabled again

**Comment by hihoman23** [comment]
I think the above PR fixes it.
