### ISSUE TITLE
Implement GDD "custom widgets disabled in ranked games"

### ISSUE THREAD

**Issue by SethDGamre** [beyond-all-reason/Beyond-All-Reason#3879]
### Description

Custom widgets are enableable and enabled by default in ranked games still.

### Why?

"Modding is 100% encouraged, it is the lifeblood of game longevity. Mods must enhance the game experience for the player, but not degrade the game experience for other players.

Mods are split into four categories:

Game mods: these change the gameplay and are non-client side, every player must have them.
Cosmetic mods: these change the visual and audio appearance of the game, and are client side.
Interface mods: these change the UI for the player who has them, and are client side.
Automation mods: these issue commands on behalf of the player, and are client side.

In ranked games, all mods are restricted except for cosmetic mods.This is so that no player has an unfair advantage over the others, and to provide a curated game experience."
-from the game design document

### What area of the game does this feature request pertain?

Gameplay

**Comment by nevniv** [comment]
I have to agree with Hayaji's comment.. discouraging widget use will discourage widget creation and they add to the game as many are integrated into the game as QoL improvements (ex. Factory Quotas).  Turning it off for ranked games is turning it off for practically everything.

If you do decide to go forward with this, I ask that when an AI is present, widgets are still enabled at least.  I know that AI matches are not ranked no matter what, but in chobby it still says ranked game = 1 in them so I'm concerned widgets will still be off depending on the implementation.

**Comment by drivver44** [comment]
> I have to agree with Hayaji's comment.. discouraging widget use will discourage widget creation and they add to the game as many are integrated into the game as QoL improvements (ex. Factory Quotas). Turning it off for ranked games is turning it off for practically everything.
> 
> If you do decide to go forward with this, I ask that when an AI is present, widgets are still enabled at least. I know that AI matches are not ranked no matter what, but in chobby it still says ranked game = 1 in them so I'm concerned widgets will still be off depending on the implementation.

the goal is to set what a default match should look like, not what the idea for everyones match is supposed to look like.

**Comment by nevniv** [comment]
Sure, but if you made unit market = 1 the default, the vast majority of people would just leave it on.  This is the same situation.  If you disable widgets, I think they will most likely be off more than on.

Maybe not, maybe people who really want them will try to turn them on and deal with explaining what they are to people who don't know what they're voting for.  Maybe it will raise awareness of widgets, it could be a good thing.

**Comment by SethDGamre** [comment]
From GDT Minutes:
The GDT is amending the decision that all custom widgets should be disabled by default for ranked play. Many BAR mainstays started their lives as custom widget mods. Until proper mod support and whitelist infrastructure is added, the intermediary is deemed necessary. That will be:
The boolean modoption to "Allow Custom Widgets" will become a dropdown menu with the following options:
Cosmetic Only (Default)
Tooltip: UI, informative, reskinning
    
All
Tooltip: Automation and Cosmetic
When Cosmetic Only is selected, any widget that uses a call-in that issues orders on behalf of the player is disabled at runtime. Examples of such call-ins can be found here: https://springrts.com/wiki/Lua_UnsyncedCtrl#Give_Order
