### ISSUE TITLE
Remove or fix construction turret listed upkeep cost

### ISSUE THREAD

**Issue by sthartman** [beyond-all-reason/Beyond-All-Reason#3917]
### Description

I've noticed construction turrets, both land and naval, list an energy upkeep of 30 which is not applied in game. This is also true for the T2 armada construction sub, which might have escaped from #2246  If these aren't intended to have upkeep, and it isn't required for game engine reasons, I'd like to remove the value from the files.

### Why?

These values are confusing to players doing quantitative analysis of units, especially if the unit comparison GUI on the website is ever enhanced to list energy costs.

### What area of the game does this feature request pertain?

Codebase or APIs

**Comment by saurtron** [comment]
I made a PR to fix the issue, but I couldn't see the energy upkeep listed in-game anywhere. Where did you see it? Is it on the lua files or some way to see it ingame?

**Comment by sthartman** [comment]
I've only seen it in the lua files, I'm not aware of any indication of energyupkeep in-game for the construction turrets.
