### ISSUE TITLE
Launcher broken?

### ISSUE THREAD

**Issue by gantsevdenis** [beyond-all-reason/Beyond-All-Reason#393]
I have downloaded appImage launcher from website, however, clicking on "Update" raises error:
And I agree with that error because `dig springfiles.com ` returns NXDOMAIN ...

![image](https://user-images.githubusercontent.com/25161465/129768099-bf058053-6c43-44cd-9347-4d805cce3512.png)

**Comment by Ruwetuin** [comment]
springfiles.com, our map provider has been down.
you can download maps manually via this gdrive:
https://drive.google.com/drive/folders/16eBcMpkgMTV9mlKxYmNda64X_dmCFdkk
place these into the gamedatadir/maps
