### ISSUE TITLE
Transport picks up neutral animals

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#3992]
### Description

Doing area loading selects crab, crab in trans:
![image](https://github.com/user-attachments/assets/fa45771a-c308-4f80-aaf2-03bb4f403d5e)

### Expected Behaviour

Not pickup neutrals.

### Actual Behaviour

Picks up neutrals.

**Comment by sprunk** [comment]
crab bro is an ally

**Comment by MeSaber** [comment]
> crab bro is an ally

If only it had a weapon, then i wouldnt complain LUL

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/dddd1dbcc1fddac7bcb15639741f9057f437d71b
