### ISSUE TITLE
Add SelectionVolumes to units to make them easier to select by clicking on them

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#414]
Most units have too small clickable selection volumes, and it would be nice if one went through and edited at least the major ones (like commanders at least).

Docs here: https://docs.google.com/document/d/1YumnnAU4a6NQP3IoZLocOkmnO7kNa1eVSNp4U5WxE18/edit#

**Comment by sprunk** [comment]
ZK post-processes most units to have enlarged selection volumes (by default; can be overridden explicitly of course), see https://github.com/ZeroK-RTS/Zero-K/blob/master/gamedata/unitdefs_post.lua#L752 and the chunk of code below

**Comment by Beherith** [comment]
Thanks sprunk, damgam merged it, floris tweaked it, seems great so far :)
