### ISSUE TITLE
unit_builder_priority gadget excessive table allocation and load

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#422]
A large part of lategame load is related to garbage collection, unit_builder_priority  is a pretty heavy offender, one of the main reasons being it allocates a ton of small tables with the keys "metal" and "energy" every time it runs.

This gadget badly needs a refactor to reduce its massive mem load. 
@Ruwetuin  could you please take a look at this?

**Comment by Ruwetuin** [comment]
done: reduced table creation resulting in a mem allocation decrease x10
