### ISSUE TITLE
Clamp top bar wind at 25, cause engine wont allow windgens to make more E than that anyway

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#449]
If someone finds where the engine limit of 25 wind is, do scream :D

**Comment by WatchTheFort** [comment]
Is this controlled by the `windgenerator` tag in the unitdef?
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/0a92f1efa55486fb19543d65f5e39f3ccc21d7c2/units/ArmBuildings/LandEconomy/armwin.lua#L40

**Comment by WatchTheFort** [comment]
Why does this tag exist?

**Comment by Beherith** [comment]
Legacy reasons, purely. 

I propose changing this to 1000.0, scream if unhappy with this.

**Comment by sprunk** [comment]
My guess is that it's a crutch to make speedmetal slightly less degenerate.

**Comment by Beherith** [comment]
No you :P 

Speedmetal was only 30, and the 25 limit has been there since the AA days. 

Also, note 2 self, dont let the windgen anim go too fast, use an sqrt or something

**Comment by WatchTheFort** [comment]
What is the design reason for capping the wind generator production?

If it is to have multiple tiers of wind generators, and a higher map max wind, all it results in is the lower tiers getting saturated and spending most of their time at their maximum generation.

The current customparam `energymultiplier` makes more sense, where a higher tier wind generator generates a multiple of the wind speed.

**Comment by sprunk** [comment]
> What is the design reason for capping the wind generator production?

How else do you salvage a good map that has silly high wind values that would otherwise warp the earlygame economy, when it's 2005 and you have no control over maps and no Lua?

**Comment by KyleAnthonyShepherd** [comment]
Issue appears answered. Wind is capped at 25 at the unitdef level. 
And a map with 20-30 wind has a different wind distribution and average wind with the clamped generators than a map with 20-25 wind, so clamping the UI does not make sense. 

Might make sense to have a modoption to override the unitdef windspeed cap, but that should be a different issue or discussed on discord.

**Comment by sprunk** [comment]
> Speedmetal was only 30

IIRC there was some popular variant of speedmetal that had like 9999 wind.
