### ISSUE TITLE
Co-operation through npm packages

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/Beyond-All-Reason#45]
I think the most realistic approach to any kind of cooperation between the various JS lobbies and launchers is to make npm packages that do most of the hard stuff.

I've written a list of what I plan to produce from spring-launcher.
- https://github.com/gajop/spring-launcher/issues/37

Luckily I've already written most of this functionality with spring-launcher, it "just" needs to be made into packages other people could use.

I hope someone will write a package for the communication with various lobby servers, (most importantly Uber, and if really bored a ZK one as well and whatever else new comes along).

Would like to hear what everyone has in mind regarding this. I will only be creating these packages if I see there's strong desire for such a thing and if I think this will be mutually beneficial.

**Comment by tomjn** [comment]
I think all of those would be super handy, especially if anybody wanted to build a `node` based autohost

**Comment by lweberk** [comment]
A good candidate is also unitsync. I could concentrate on rewriting and binding it for nodejs. Its the next logical step on AutumnLauncher anyways.

**Comment by gajop** [comment]
likewise, outdated and probably not going to happen
