### ISSUE TITLE
Lobby Status Quo Research

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/Beyond-All-Reason#46]
Before running into choosing an implementation, I think we should first describe the current situation and what we like or dislike about it - only then can work be sensibly directed.

I would like to split this into two parts: User Experience and Technical Concerns, as knowing where the issue is will be critical in determining tech stacks and problem areas.
So without further ado:

# User Experience

Chobby + spring-launcher:
- TODO: Write key pros & cons

SpringLobby:
- TODO: Write key pros & cons

uberserver & other existing infra stuff:
- TODO: Write key pros & cons

# Technical Concerns

Chobby + spring-launcher:
- TODO: Write key pros & cons

SpringLobby:
- TODO: Write key pros & cons

uberserver & other existing infra stuff:
- TODO: Write key pros & cons

**Comment by icexuick** [comment]
Where should i write the User Experience (feedback) and Technical concerns ?
Here, or in a Git Project board, or Trello?

**Comment by tomjn** [comment]
I’d write them as comments, someone can compile it all into a summary at
the end, otherwise I wonder if a google doc might work better for the final
list

**Comment by icexuick** [comment]
I'd like to work this out in Trello.
There are already quite some 'known-issues' on there (https://trello.com/c/ml3Yl5Mn)
I will try to write down what i would like to see different/improved (and also what i do like)

**Comment by icexuick** [comment]
Check out my PROS and CONS on Trello: https://trello.com/c/3SFyFMdC/309-lobby-re-imagined
I'll update them there. Below the last version:

`Chobby + Springlauncher`

**PROS**
1. Easy install
2. Choose your install location freely and keep all files there
3. Updates work nice
4. Basic interface of Chobby is okay-ish - basics do work

**CONS**
1. [launcher] Updates are way too slow - should be 10 times as fast
2. Lacks important features
3. Cannot host your own games!
4. Has bugs/problems with team/allies when they do switch
5. Friends system is unreliable
6. Minimaps of maps are not loaded automatically
7. Starting options are very limited (no startbox editing, no default start pos)
8. No robust replay-system
9. First run is still bad?
10. Is quite the hassle to tweak/update
11. Changing layout is told to be very hard
12. Is heavy on perf - i'd like a streamlined lobby
13. Option for very small windowed mode should work well

`SpringLobby`

**PROS**
1. Has almost every possible setting as an option - very conifigurable (though could even be more extensive)
2. Is lean/mean - easy to keep active during the day
3. Fast in selecting/config (most stuf except maps)
4. Show minimap automatically
5. Has okay replays and auto-download capabilities, though not stable for everyone

**CONS**
1. Is a pain to install - and on some systems (±10-15%) not even installable
2. even when installed, can break reasonably easy
3. Has problems with 64 bit spring unitsync!
4. Looks like software from 1998
5. Too complicated connection to server / also registering is confusing
6. Shows too little information on what players are missing to play a game
7. Currently on the servers the settings aren't always correct
8. New map layout/starting options take a while to update
9. Currently with SPADS/servers you need to vote for everything - a game-master or host (choosen democratically) is much easier, so he/she can setup everything for the game without vote y vote y vote y vote y vote y (also applies for chobby)

**Comment by gajop** [comment]
This is what I think about the Chobby + spring-launcher issues you mentioned. It's important to note that some issues will be present by any other lobby using the underlying Spring/uber tech (e.g. pr-downloader being slow to update - that needs to be fixed there)

[launcher] Updates are way too slow - should be 10 times as fast
-> pr-downloader needs to be improved. It's possible (medium size issue)
Lacks important features
-> Which?
Cannot host your own games!
-> If you want to be a real host (as far as network goes), I think Chobby is fundamentally a bad idea, and I wouldn't recommend this in general (expect NAT/connection and bandwidth issues). 
-> If you're OK with using a dedicated host in the background (ZK does this by spawning Springies), then Chobby is fine but will need some infra support (autohost spawning side)
Has bugs/problems with team/allies when they do switch
-> Which?
Friends system is unreliable
-> Fixable on either Chobby or uber side (minor issue)
Minimaps of maps are not loaded automatically
-> Fixable in Spring side (medium issue but doing this could benefit other Spring games)
Starting options are very limited (no startbox editing, no default start pos)
-> This is surely doable with a little bit of Lua scripting. Could be someone's first issue. 
No robust replay-system
-> Fixable with a bit of work in the launcher. Will require a bit more infra work if you want to have a replay system on the site like ZK: https://zero-k.info/Battles
First run is still bad?
-> Is it really still bad after you've made it copy springsettings? Something stinks here, but I think this is a minor issue
Is quite the hassle to tweak/update
-> Hmm? Can you be more specific? I maybe fixed some of these issues already
Changing layout is told to be very hard
-> This is only partially true. I think current layout is good enough, and changing this should probably be done by splitting the layout from the logic in Core Chobby (something I talked with GoogleFrog and I think it's not impossible)
Is heavy on perf - i'd like a streamlined lobby
-> This may be a blocking issue if you expect it to have no performance cost. Some optimizations can be done but there are limits.. don't expect it to ever be as light as Discord or SL
Option for very small windowed mode should work well
-> Don't they? What's wrong?

**Comment by icexuick** [comment]
Thx for the feedback!

1. Features that lack are things like editing teams, see/use ally numbers, startpositions, use/save presets (local) for game settings you like, replays.
2. I'm not sure about first run, i haven't used chobby in a couple of weeks because SL is just way faster, lighter and has a lot more config options = outweighs the visuals of chobby.
3. I was told changing layout was hard - not sure who did - i believe googlefrog
4. A little perf cost is no real problem, but it should be super fast. If that is impossible i think this can be a deal-breaker
5. it's that i just don't really like the UI setup.. could be the config from floris, but it's just not sharp/tight/good enough imho. The smaller versions are just not working well responsively... but i will take another look at all this soon to see if i can confirm that this still bothers me much or might be fixable.
6. teams-allies can get mixed up wrong when some players leave/change team (f.e. also players from SL). Then the ally or team is wrong and can't be fixed from within chobby, only be removing bots or players from teams - redoing the team config (or even disconnect-reconnect)

**Comment by gajop** [comment]
outdated and not going anywhere imo
