### ISSUE TITLE
Core T2 Gunship (Rapier) not inheriting "Land at..." parameter from factory

### ISSUE THREAD

**Issue by Flash512** [beyond-all-reason/Beyond-All-Reason#466]
The Core Rapier Gunship (T2) does not inherit the "land at" setting of the factory. The interface also shows up the "LandAt" interface button twice. Once with the regular aircraft tooltip and once with the factory-tooltip.

Every other Core and Arm T1/T2 aircraft inherits the setting fine (just checked)

![rapier-problem](https://user-images.githubusercontent.com/91898244/135870138-ba0238bb-7d08-40fc-8a85-f996f4dc890f.png)
.

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f2eefe1065b3e9df7dd10cfda50a125f1a646229
