### ISSUE TITLE
How do I tell if CORSHIVA actually has an armor modifier?

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#474]
Its cob script is setting ARMORED on start and stopmoving :D

**Comment by sprunk** [comment]
Deal damage and compare? Or `local armored, armorMult = Spring.GetUnitArmored(unitID)` and see what the second value shows when the first is `true`. The default is 1 (no armor) so given Shiva has nothing defined it's probably a no-op.

**Comment by Beherith** [comment]
I meant, where in the unitdef files?

**Comment by Beherith** [comment]
Good, it doesnt, thanks @sprunk !
