### ISSUE TITLE
Big volume units get stuck in labs inside the next unit nanoframe 

### ISSUE THREAD

**Issue by triton13** [beyond-all-reason/Beyond-All-Reason#48]

**Comment by PtaQQ** [comment]
Attaching a video that shows the issue. A newly produced unit walking out of the lab gets cought by the nanoframe of the next unit. This happens most often with big, slow units. Supposedly fixable by increasing the delay between productions of units. 

https://cdn.discordapp.com/attachments/549282926596980738/755579620497162290/Ship_geting_stuckv2.mp4

A solution has been tried with 
unit_factory_anti_slacker.lua

but with no success, the problem remained.

**Comment by Ruwetuin** [comment]
the added gadget below should fix this
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/8ecae87900faf1776172da3abb4e0b18bbe3c355
