### ISSUE TITLE
Integrate mapmarks fx into deferred lights

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#492]
Spam a few points and watch mem allocs go crazy

Should I GL4 it? 
![image](https://user-images.githubusercontent.com/109391/137346603-c114cacf-da7b-40cd-85e7-9959f0921e41.png)

**Comment by sprunk** [comment]
Fixed by 3f78e8c5843151ed8c616c9d38408183a6683be2 ?

**Comment by KyleAnthonyShepherd** [comment]
Old issue, has this integration been completed yet?

**Comment by SethDGamre** [comment]
An old issue that hasn't gotten a reply since the last inquiry since last year. Requesting session review to determine if anybody else knows about this issue before closing as unplanned.
