### ISSUE TITLE
Scenario friendly AI - while trying to upgrade MEX, while reclaiming - the friendly bot healed the MEX

### ISSUE THREAD

**Issue by Norrdec** [beyond-all-reason/Beyond-All-Reason#505]
While playing the helping hand scenario (I think) a friendly repair bot was close to my t2 builder.
I tried to upgrade MEX to moho. My T2 bot tried to reclaim, but before it could finish the AI friendly bot repaired it faster than I reclaimed. 

You probably want a check if the building is being reclaimed, or really getting damaged.

**Comment by SethDGamre** [comment]
@Damgam what do you call this issue old enough to where it can be closed

**Comment by Damgam** [comment]
#Won'tFix
