### ISSUE TITLE
Changes in build menu removed positional build shortcuts

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#51]
Are those to go away for ever? They where incredibly nice.

**Comment by lweberk** [comment]
8:12 PM] Quintus: @Floris The positional shortcuts for the build menu are going to go for ever? They where really really nice
[8:12 PM] Floris: no they'll be there sooner or later
[8:12 PM] Quintus: :+1: 
[8:13 PM] Floris: parts of the code required are already there

**Comment by WatchTheFort** [comment]
Closing as grid menu solves this problem
