### ISSUE TITLE
[PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#513]
[t=00:00:15.712897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: cortship_scav
[t=00:00:15.713897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: armtship
[t=00:00:15.716897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: cortship
[t=00:00:15.717897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: corwolv_scav
[t=00:00:15.717897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: armart
[t=00:00:15.718897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: armart_scav
[t=00:00:15.718897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: corwolv
[t=00:00:15.720897][f=-000001] [PUSH RESISTANCE REMOVER] Push Resistant Unit with no mass: armtship_scav

Is this easily solveable by just giving them mass?

**Comment by KyleAnthonyShepherd** [comment]
Not seeing these errors in my infolog, assuming issue is fixed, closing

**Comment by sprunk** [comment]
Also units always have a mass. It defaults to metal cost if undefined.
