### ISSUE TITLE
Bertha (and other plasma units?) target air in flight mode

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#53]
This renders them pretty much useless while left on auto attack

**Comment by fruehling76** [comment]
yes that behaviour should be stopped. plasma should not target air. would maybe improve also performance a little bit

**Comment by Ruwetuin** [comment]
I just checked and see that all 4 LRPC cannon units have set onlytargetcategory = "SURFACE", therefore they cannot target non surface units
