### ISSUE TITLE
Game scope and casual play

### ISSUE THREAD

**Issue by Eonfge** [beyond-all-reason/Beyond-All-Reason#533]
_I didn't find any CONTRIBUTING.md guidelines, so forgive me for bringing up issues that are not open to discussion. I understand and respect the artistic merits of game design and development, even if it means that my feedback will be rejected._

---

Beyond All Reason is good. It has a fresh look, the unit design is on point at it makes it easy to see what’s going on, and the UI is the best in its class. But I find that most games against the AI overwhelm me with unit and building choices. As such I was wondering, would there be any interest in simplifying the game-play for a more streamlined experience?

My problem is of cause not totally unheard of. Chris Taylor himself said that this was an important change from Total Annihilation to Supreme Commander: Lowering the amount of factories to three and halving the amount of total units, made it easier for users to understand the basics and to feel in control. Other projects have struggled with the same problem. Planetary Annihilation had the same issue. Moving the entire RTS game into space, over multiple planets, makes it a great game for casting but not very much for playing on a casual level. It's hard to make an RTS game, and it's very hard to make it understandable.

To give some straight examples; Why are there three factories for ground forces? Why are there two types of aircraft factories? Why does the navel-based factory build different bombers then the land-based factory? 2 types of solar collectors, 3 types of nuclear power plants? These are just a few examples of complexity that could be stripped from the game without impacting players, except perhaps those that play on the highest level.

Some other RTS games have struggled with the same balance of complexity vs interaction. Star Craft focuses on a smaller unit roster and smaller battlefields, with units who are micro-heavy. Games like Age of Empires have a simpler combat system, but focus more on technical advances and economic challenges over time. Even a series like C&C has continuously worked on improving the balance of complexity and interaction, although it's arguably the simplest RTS game on the market. 

It feels that BAR is on a bit of a cross-roads; You can streamline the process and abandon the Total Annihilation mould, or you’ll have to accept that you’ll limit the market for your game. I certainly see potential and I think you should start a Patreon and/or kickstarter, but I do fear that this game is ultimately to complex for me.

**Comment by Beherith** [comment]
We are pretty much dead set on the path that offers (even if a bit excessive) unit diversity, as that was one of the starting goals from the beginning. 

A good tutorial and a well structured campaign will help in turning the unit diversity into a fun learning experience instead of overwhelming.

**Comment by Eonfge** [comment]
> We are pretty much dead set on the path that offers (even if a bit excessive) unit diversity, as that was one of the starting goals from the beginning.

I'm sorry, I was not aware of that. Perhaps it would be good to make a CONTRIBUTING.md to describe what the short and long-term creative goals of this game are. Approaching this project as a FLOSS-contributor, I think you should make clear guides on what parts are open to discussion, and what parts are not. 

As I stated, before, your creative choice is valid, even if that excludes me. I hope to see your project on Kickstarter and/or Patreon in the future.

**Comment by fruehling76** [comment]
the unit setup u see now is a result of years of devepment, playing, balancing. there are a lot of mechanic behind that ppl love. goal was never to make a simple but a complex game. we did also put a hell of work in ui and also graphic to make that that complexity controllable. this decision might lead that ppl that a used to simple games drop off. but simple games there are plenty on the market. what we offer is a unique game experience and long lasting fun cause there is a long learning curve in every aspect. not every units etc makes sense if u play just some games. but the more u play the more u will discover game mechanics that u even didnt seen before as well u get used to great amount of different units. anyway for give u a starter: in the beginning i would suggest to stuck to basic units types like light tank, medium, heavy tank and learn the game. and step by step u try out other units. the same thing counts for different factories. and a general tipp: focus on few unit (usually 2-3) types and learn to micro them. the selection of unit types has to be picked based on enemy or yours strategy or counter strategy. have a great day
