### ISSUE TITLE
Loading a save game makes stones and trees no longer disappear after being reclaimed.

### ISSUE THREAD

**Issue by konrad-jamrozik** [beyond-all-reason/Beyond-All-Reason#536]
I noticed that when I save a singleplayer skirmish game and then load it, reclaiming any stones or trees doesn't remove them from map. They can no longer be reclaimed after first reclaim, but they are still there, and no buildings can be built on top. This problem doesn't exist if the game is run afresh, only after loading a save game. This issue happens on maps Fallendell_V4 and Taldarim_V3, but curiously, not on Quicksilver Remake v1.24.

I am running 105.1.1-533-g73cb706 bar. Let me know if I should provide any other info. I am not familiar with bug reporting etiquette yet. Thanks!

**Comment by Beherith** [comment]
Oooh, thank you this is indeed very interesting, especially the part about which maps it happens on, as that gives me some good clues. Could you please test the nature of this on the map Green Fields Fixed (as that uses a different method of placing trees)?

**Comment by konrad-jamrozik** [comment]
Hey, sorry for the late reply; I am in the PST timezone and I went to sleep ;)

I updated to 105.1.1-549-g0d9f349 bar.

The issue:

- does not appear on Green_Fields_fix
- still does appear on Fallendell_V4

I also noticed that:

- D-gunning the props also turns them into unreclaimable but still visible "ghosts".
- trees removed before the game was saved re-appear as "ghosts" after it is loaded.

**Comment by Beherith** [comment]
Thank you for testing this, this gives me a good starting point to debug it

**Comment by Beherith** [comment]
So in the api_saveload, I should check for any pre-existing features and straight up destroy them then and there. seems like the easiest workaround.

**Comment by Beherith** [comment]
Features are destroyed by saveload api, but could they be loaded from gaia after?

**Comment by Beherith** [comment]
Hmm, @konrad-jamrozik could you perhaps maybe upload your data/infolog.txt file after loading a save game that shows these feature bugs?

**Comment by Beherith** [comment]
Test 1.
Loading chobby, starting a game on Green Fields Fixed (no luagaia), with non sdd BAR, reclaimed 3 trees, then saving the game. 
Restart the game, load the save file, all features are invisible (their hitboxes are there tho), but the features can otherwise be interacted with regularly:
![image](https://user-images.githubusercontent.com/109391/139733566-a6f2c11f-75f9-4e10-8d28-fdda545f0d50.png)

Infolog is spammed with:
[t=00:01:56.209646][f=-000001] Error: Function with name LuaGaiaFeatureDefs.1.__mt.__newindex was not found during deserialization

@ashdnazg could I please ask for your help on this one?

**Comment by ashdnazg** [comment]
ugh, that's very weird. I'll try to have a look in the weekend - remind me on Discord!

**Comment by Beherith** [comment]
Thank you very much, shall I attach a replay file or infolog?

**Comment by ashdnazg** [comment]
nah, steps for reproducing is enough

**Comment by Beherith** [comment]
Ok, am i doing something wrong that I cant Spring.Echo from the loading part of api_loadsave.lua? 
```	local oldfeatures = Spring.GetAllFeatures()
	Spring.Echo("Number of features before loadfeatures is run = ", #oldfeatures)
	-- delete them all
	for i, fid in ipairs(oldfeatures) do
		Spring.DestroyFeature(fid)
	end
	```

**Comment by konrad-jamrozik** [comment]
@Beherith  I uploaded the infolog.

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7457819/infolog.txt)

The errors start at line 1832:

```
[t=00:01:56.475093][f=-000001] [LoadScreen::SetLoadMessage] text="Loading Saved Game"
[t=00:01:56.518023][f=-000001] Error: Function with name LuaGaiaxpcall was not found during deserialization
[t=00:01:56.518023][f=-000001] Error: Function with name LuaGaiatostring was not found during deserialization
[t=00:01:56.518023][f=-000001] Error: Function with name LuaGaiaprint was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaiaunpack was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaiagetfenv was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaiasetmetatable was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaianext was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaiaassert was not found during deserialization
[t=00:01:56.518958][f=-000001] Error: Function with name LuaGaiatonumber was not found during deserialization
[t=00:01:56.521924][f=-000001] Error: Function with name LuaGaiagetmetatable was not found during deserialization
[t=00:01:56.524914][f=-000001] Error: Function with name LuaGaiaload was not found during deserialization
[t=00:01:56.525913][f=-000001] Error: Function with name LuaGaiaSendToUnsynced was not found during deserialization
[t=00:01:56.525913][f=-000001] Error: Function with name LuaGaiaCallAsTeam was not found during deserialization
```

**Comment by sprunk** [comment]
> Ok, am i doing something wrong that I cant Spring.Echo from the loading part of api_loadsave.lua?
> 
> ```
> 	Spring.Echo("Number of features before loadfeatures is run = ", #oldfeatures)
> 	-- delete them all
> 	for i, fid in ipairs(oldfeatures) do
> 		Spring.DestroyFeature(fid)
> 	end
> 	```
> ```

Isn't that for old Lua save (while new save is engine-side and doesn't use that)?
