### ISSUE TITLE
T2 constructors do not assist T2 mexes

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/Beyond-All-Reason#537]
When giving orders to multiple T2 constructors to build a T2 mex, only one builds it, while all others stand around in their build stance but not actually constructing.

If the non-constructing ones are selected and given an assist order for the T2 mex, they will start assisting the constructiong properly.

**Comment by WatchTheFort** [comment]
Added echoes to widget:UnitCommand, and all the T2 constructors are receiving identical orders.

**Comment by WatchTheFort** [comment]
Checking the `UnitCmdDone` callin, which is called a unit completes an order, all but one of the constructors immediately hit this callin (i.e. the one actually doing the construction is the one omitted).

**Comment by WatchTheFort** [comment]
Cause found:
It is the checkerboard footprint. Reverting the `armmoho` footprint to the previous version allowed multiple T2 constructors to all build Armada Moho Mines.

**Comment by Beherith** [comment]
What the hell? Does this happen when there is a t1 mex in place there already?

**Comment by WatchTheFort** [comment]
The presence of a T1 mex does not make a difference.

**Comment by WatchTheFort** [comment]
Cause is the high-res yardmap flag `h`.
This is an engine bug, as it occurs with both luarules and luaui disabled.

Moving issue to Spring repo.

**Comment by WatchTheFort** [comment]
This has been fixed with the latest engine version.
