### ISSUE TITLE
Copy radar coverage effect from NOTA

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#54]
Don nott know where they got it from or if it is an original, but it helps to see radar coverage in sight coverage mode very nicely. 

Specially since you do not see the radar shadows cast by terrain otherwise

**Comment by icexuick** [comment]
I don't like it, if you mean these colored lines. Could be a thing to look into a different way, though i like it that the (exact) radar coverage is a bit 'blurry' and you don't exactly/always know where you have radar coverage and where not.
![image](https://user-images.githubusercontent.com/23189106/81536762-5b8deb80-936c-11ea-9816-afa86e9e8d54.png)

**Comment by Ruwetuin** [comment]
these are spring's defaults... i changed them for ba at the time

**Comment by lweberk** [comment]
Yeah, the effect leaves to be wished for.

**Comment by lweberk** [comment]
Can we agree to activate it in the meantime? Until a better solution comes around? Currently you are literally blind, and implementing the raytracing on the lua side is not something I'd gun for right from the beginning.

**Comment by icexuick** [comment]
Well you can use it already, though it is a bit harder to see.

Use L to turn Los/Radar on/off and use ; to switch between los or los/radar mode.
(the most dark one has both los and radar - los being bright, and radar being darker and no los/radar = darkest)

Personally i'm against all kinds of markers/lines/rings/radiusses etc. 
It kinda pollutes the game visually for me.
If most people do really want this, i'd strongly suggest we start to think of a better visual implementation for it (first).

**Comment by lweberk** [comment]
Personally I keep deactivating L, due to it being hard to currently interpret. As for the coverage I go by what little experience I have from the past. The main maps are still the same.

Would you consider a full perlin-noise overlay instead of outline? I'd be interesting to explore visually. It provides the information in an even more obvious way.

Do you guys play with L on most of the time?

**Comment by icexuick** [comment]
i think it's pretty good to interpret with L.
I use it always.

![image](https://user-images.githubusercontent.com/23189106/81995340-4fdf4500-964a-11ea-91da-b97039b0f4e8.png)

**Comment by lweberk** [comment]
I forced myself to play with that view mode enabled and realized you are right. There is even some noise on the parts that are radar only.

So my point would change to; 
* Make the distinction between LOS and RLOS stronger by tweaking color and/or strengthening perlin noise effect on the latter.
* Reduce the overall darkening of the map for the areas outside of both LOS and RLOS.

Is RLOS always a superset of LOS in the game? Are there scenarios where it is the other way around?

**Comment by icexuick** [comment]
You can strengthen the view with **;** 
Did you try that as well? Then the no LOS/RLOS area gets really dark.
Personally i don't like that, because it kinda destroys the overall map view, though sometimes, with survival mode or chickens, this can enhance the experience/atmosphere.

**Comment by lweberk** [comment]
Superseded by #71 with the traction this never got.
