### ISSUE TITLE
Set target / Cancel target

### ISSUE THREAD

**Issue by Sutrinc** [beyond-all-reason/Beyond-All-Reason#543]
Hi
May be can this change to the priority of the target? 
for example 
list( com, eng, atry, ships, snipers and etc)

![image](https://user-images.githubusercontent.com/92538938/140031560-d37897f5-e439-40e3-9e22-c326d60d2adf.png)

**Comment by Ruwetuin** [comment]
targetting preference isnt possible all that specifically, there are unit categories but they are much more broad
