### ISSUE TITLE
Enhance action radius of patroling rez units

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#55]
And construction units too?

**Comment by fruehling76** [comment]
maybe patroling can be connected to hold position, maneuver and roam to have control over action radius. as well i would like to see rezzers/con return to their starting position when finished a task if set to maneuver. same for area commands in general for that unit type

**Comment by insanemal** [comment]
This is probably a bit of a big ask, but I'd love to have a squad function. Where I can group units into squads. And I could assign a rez unit squad to guard another squad of defending/attacking units. 

So similar to the current per unit functionality but at a group/squad level.

**Comment by icexuick** [comment]
Interesting.
So grouping is nog problem, but assisting whole other group is.
Is there some widget or possibility here?
