### ISSUE TITLE
Storms/Rocko (and now the entire unit selection) - Friendly Fire in groups

### ISSUE THREAD

**Issue by KrashKourse** [beyond-all-reason/Beyond-All-Reason#550]
Storms: use an alternating left/right attack pattern to shoot rockets from their top side launchers, this some times causes them to shoot their own team or friendly team units. like rockos these rockets can often be intercepted at point blank range.

Rockos: also have this problem and will fire in to their own units or friendly units when shooting

To recreate: give group of Storms/Rockos attack order just outside all their ranges (more common on Storms) rockos were more consistent but could still walk in front of rockets

what I feel needs to happen is their rocket not fire to friendly targets and have some way of shooting them over the top like a catapult or have them fire better in a group.

Attached files are videos and pictures of the Storms and Rockos in action as well as their aim zones
![Storm_Rocko](https://user-images.githubusercontent.com/77669424/140833193-87ac5ed3-5aa0-4c24-9977-cfb6effd4da6.png)

https://user-images.githubusercontent.com/77669424/140834346-e1ce1670-8d48-4d93-8cfb-67ce7d299989.mp4

https://user-images.githubusercontent.com/77669424/140834799-9dce141b-a8e2-4bfb-8847-f892c1c74389.mp4

**Comment by Beherith** [comment]
`FirePrimary()
{
	if( gun_1 )
	{
		emit-sfx UNIT_SFX0 from rexhaust;
		turn turret to y-axis <-8> now;
		turn launcher to x-axis <-5> now;
		
		turn launcher to x-axis <0> speed <5>;
		turn turret to y-axis <0> speed <16>;
	}
	else
	{
		emit-sfx UNIT_SFX0 from lexhaust;
		
		turn turret to y-axis <8> now;
		turn launcher to x-axis <-5> now;
		
		turn launcher to x-axis <0> speed <5>;
		turn turret to y-axis <0> speed <16>;
	}
	sleep 32;
	// WHY DO WE NEED TO SLEEP A FRAME HERE? well simple!
	// the order of the calls is 
	//1. AimFromWeapon
	//2. FirePrimary
	//3. QueryWeapon
	// If we swap guns on fireprimary, then we would shoot from other barrel that we aimed from, so we delay swapping barrels by one frame
	gun_1 = !gun_1;
}
`

**Comment by KrashKourse** [comment]
this still happening on storms when attacking in a group and hitting other members in the group. rockos also have this issue still and will still hit each other.

I think what is happening is they step in front of a just barely fired rocket when trying to fire their own gun at the target. even while the gun is forward is it more noticeable and replicable on rockos now

https://user-images.githubusercontent.com/77669424/140915830-88ae549c-6891-4e7c-bdce-26e7312741eb.mp4

https://user-images.githubusercontent.com/77669424/140916623-55ef0d0f-f095-4c2c-99eb-e0e49de60ccb.mp4

**Comment by Beherith** [comment]
You deserve extra kudos for the great video bug reports!

These both seem to be cases of units being pushed just into the line of fire after the projectile was fired. You may be able to find and engine tag in targetting that somehow tries to constrain the targetting params for friendlies.

**Comment by Beherith** [comment]
https://springrts.com/wiki/Gamedev:WeaponDefs#Collision_.26_Avoidance

**Comment by KrashKourse** [comment]
" bool collideFriendly  default: true lua: noFriendlyCollide 

Does the weapon projectile collide with friendly units or pass through? "
----------------
this may be an option as to not collide with friendly units
but
if you wanted to keep them from mass group firing you would need to keep
----------------
" bool avoidFriendly  default: true 

Should the weapon avoid firing if a friendly unit is in the line of fire? "
----------------
as to prevent them from group shooting like thuds and hammers, and this would actually be pretty cool if they both did group fire like in TA would be better for them stacking and shooting when trying to micro them in a group rather than microing a line that can still hit its self on moving

**Comment by KrashKourse** [comment]
Not only is self and team damage happening to these units but also thuds when told to attack in a group as well. the Levelers also team damage when trying to shoot close targets

im going to look in to all the units with this problem and see if this is a global issue
__________

https://user-images.githubusercontent.com/77669424/140920940-15cf8c6c-76cb-4435-872d-8133f2e9119b.mp4


https://user-images.githubusercontent.com/77669424/140920953-6dee2e29-5d98-408a-ad9d-c80884286839.mp4

**Comment by KrashKourse** [comment]
these tests are on various other units some with single and dual firing zones as well as shooting up projectiles or straight like lasers and some plasma
______________________

https://user-images.githubusercontent.com/77669424/140922804-bcdb52a7-d281-4ee9-827c-2af36ef7ed37.mp4

https://user-images.githubusercontent.com/77669424/140922821-3516ae4f-f5b4-41d3-b29c-298cbb40b75f.mp4

https://user-images.githubusercontent.com/77669424/140923547-699b5315-a698-4db9-b6d9-ecc678959818.mp4

https://user-images.githubusercontent.com/77669424/140923608-f5bccae5-3740-4bb5-9685-fd9342a72ff0.mp4

https://user-images.githubusercontent.com/77669424/140923758-cf578e03-20a3-48b7-9107-b8f8fb3d2c9b.mp4

**Comment by KrashKourse** [comment]
it also seems that the units that have long laser attack times are easy to get team damage from.
____________
https://user-images.githubusercontent.com/77669424/140924256-657638c6-8ffc-4e83-8cb8-db4b03cba75e.mp4

**Comment by Beherith** [comment]
Ok, while this seems sytemic, it requires individual investigation. Have you tried /debugcolvol yet? See the small red and yellow dots for aimfromweapon and queryweapon? 
Need help with setting up scriptor to edit the unit scripts? (its quite easy and straightforward to do, see my linked commit)

**Comment by KrashKourse** [comment]
just tried the /debugcolvol (TBH i never even seen these commands as im mostly a normal user XD) but this will help a bit more in finding out the cause, 

would it be worth having no team bullet collisions for many units that are able to group so closely? or would this cause problems with how things are currently balanced around

**Comment by sprunk** [comment]
Maybe not as much balance, but it would heavily undermine the whole "physical simulation" selling point, even if units avoid shooting when they think they would hit an ally (because clearly they are bad at deciding if this is going to happen).

**Comment by KrashKourse** [comment]
i mean you could sell a physical simulation, but i believe a game should still be a game and it feels bad to have these blow eachother up when grouped. 

you could think of it as a soft arming timer for the rocket so it doesnt blow up point blank

**Comment by sprunk** [comment]
It's not just about grouping, collisions have to be disabled wholesale and it's really jarring when a unit walks in front of an already-flying rocket and it just ghosts through.

A thing to check would be aimfrom vs query weapon points in the script, IIRC the line of fire is checked from the former but the projectile is spawned from the latter, possibly they should be the same. Check what ZK sniper does (it has a very long weapon that used to have this problem in the extreme, it still does to an extent but now it's heavily mitigated).

**Comment by KrashKourse** [comment]
in TA the storms had this property and fired through friendlies to their target. this was also the case with many units like the skeeter/searcher, missile trucks, and any laser based weapon, would not hit friendly unless told to.

**Comment by KrashKourse** [comment]
the biggest problem is that this is across the whole game and it promotes not clumping units together and for many users in a choke point even if you line move them they clump up and with vehicles and hovers hills cause more clumping that causes more friendly fire.

its almost like taking 25% of your units (via HP total) off the board in a fight  because they clumped or pathed through a part of the map that caused them to do this behavior as well as if you all tell them to attack one big unit like a bantha or a korgoth, its pretty effective at giving you opponent an upper hand if they choose to use less big units instead of more little.

**Comment by sprunk** [comment]
> in TA the storms had this property and fired through friendlies to their target.

Yes, but it wasn't as jarring because TA had an orthogonal 2D camera that always rendered projectiles above units. It looked as if they went over the target instead of clipping right through.

**Comment by Zecrus2** [comment]
I think about a year ago there was the opposite problem, where a clump of units would only have the front 1-2 units fire.  This was a large problem for the barbarian ai as it would commonly send a clump of warriors to attack only to have them deal barely any damage.  I don't know what the fix ended up being, but I'm guessing that the firing restrictions to avoid friendly units was relaxed, which could be causing the current friendly fire issue.

**Comment by KrashKourse** [comment]
some of the units still have that problem like Groups of Gimps and how only 2-3 fire from the front. lots of grouping and firing issues need to be solved. because not every unit line uses lines and avoids chokes

**Comment by KrashKourse** [comment]
would also be great to see units like Pyro not cook friendlies as hard as these are hard to group up as their counterparts Zeus do not have this problem of damaging team units.

Zeus fire point is far from the bot and near the right edge, where the Pyro is at the same edge but has projectile life time and aoe on its attack and will hit team units.

**Comment by KyleAnthonyShepherd** [comment]
Combing through old issues:
I made a few engine PRs to address these friendly fire issues. 
1. Cannons (and trajectoryheight missiles) now correctly predict their own path for friendly fire
2. A new tag to update MuzzlePos *before* friendly fire checks

And a few game-side changes, like making sure the `FirePrimary` unitscript does not *immediately* switch muzzlepos, or otherwise animate and displace the muzzlepos after the friendly fire check.
