### ISSUE TITLE
Unit_continuous_aim too much

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#554]
I wonder if we can get away with only reaiming every second frame instead of every frame....

**Comment by KrashKourse** [comment]
this would make microing units a bit easier for dodging projectiles, some players may find this to be fun as you also free up some CPU

**Comment by sprunk** [comment]
ZK uses 5 frames on most weapons, with a bunch of exceptions on sensitive things (llt, dgun etc) that have 1.

**Comment by Beherith** [comment]
I reduced all units to at best every second frame. Noone so far has complained.
