### ISSUE TITLE
Shaprshooter projectiles ignoring shields 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#560]
Shaprshooter projectiles ignoring shields (plasma deflector). Settings for shields: deflect everything.

**Comment by icexuick** [comment]
probably because of ultra high speed of projectile.

**Comment by sprunk** [comment]
Because it's a laser? https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/units/ArmBots/T2/armsnipe.lua#L154

**Comment by Ruwetuin** [comment]
wontfix
