### ISSUE TITLE
Russian text not visible in game chat

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#562]
Russian text not visible in game chat.

![Not visible](https://user-images.githubusercontent.com/89547444/141511345-881ad772-270f-4313-a844-ddcd7a044f31.JPG)
![Visible (1)](https://user-images.githubusercontent.com/89547444/141511349-fccf29a2-d2c0-4c34-bf94-c5cd4241f4e0.JPG)
![Visible (2)](https://user-images.githubusercontent.com/89547444/141511353-199d6cf2-44f4-4e6b-bc92-4186909c97c3.JPG)

**Comment by 6AKU66** [comment]
Font poppins don't support russian language. If someone want use russian during the match you can type this command in chat:
/option font exo2-regular
And with another command you can back poppins font.
/option font poppins-regular

Use it on own your risk only.

**Comment by WatchTheFort** [comment]
Resolving engine font substitution bug should resolve this:
https://github.com/beyond-all-reason/spring/issues/87
