### ISSUE TITLE
Empty AllyTeam (Startbox without a team) causes victory condition to not trigger

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#563]
Adding team without members in MP session cause no win condition: after defeating enemy game don't consider that as a win.

https://www.beyondallreason.info/replays?gameId=b6b48e619d0165b8aa82e657c12fde9d

**Comment by Beherith** [comment]
Can you screenshot how to reproduce in lobby?

**Comment by 6AKU66** [comment]
> Can you screenshot how to reproduce in lobby?
Yeah
![Uploading No win lobby.jpg…]()

**Comment by Ruwetuin** [comment]
couldn't reproduce locally, but possible fix in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/2d88b3ee8872468078d98c92f310bb36a3598e89
