### ISSUE TITLE
Metal extractor wrong readout (metal output)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#564]
Metal extractor wrong readout (metal output) after match have been started. In phase picking position readout working fine.

https://youtu.be/8WFLSqDVNHE
![screen00002](https://user-images.githubusercontent.com/89547444/141600438-12e3a017-2191-4d9d-807f-e560c9546fc7.jpg)
![screen00003](https://user-images.githubusercontent.com/89547444/141600442-ee0bb99f-23e6-44a5-a5b4-803441d7e504.jpg)

**Comment by Beherith** [comment]
This is because snap is not on during placement phase

**Comment by icexuick** [comment]
different problem = metal output is not adjusted when "bonus resources" is set to > 1

**Comment by Ruwetuin** [comment]
applied resource bonus multiplier to spot values in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/8ffa76856719fe506cb299003f523bc6b44b389d
