### ISSUE TITLE
Flying Epoch can stuck on aircraft plant

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#565]
Flying Epoch can stuck on aircraft plant. Not exactly sure how it's happening, but selecting flying epochs and click on aircraft plant unbug it.

https://youtu.be/NmPc6dR5WlQ

**Comment by Damgam** [comment]
STILL?????
For fucks sake i've tried to fix it a few times already.

**Comment by Beherith** [comment]
At this point, it might even need a MoveCtrl command inserted on UnitFinished

**Comment by Rawh** [comment]
If you want to unstuck it, select those aircraft which are stuck and put a guard order on the factory. In all my matches they suddenly pop out of the building area and you can use 'm.

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/704f283f-f26e-4374-963b-262e0605a20f)
Seems to have been fixed in some recent commit, closing
