### ISSUE TITLE
Not linear volume scales in advanced player list

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#567]
Volume scales in advanced player list behave less linear than in Menu - Audio

https://youtu.be/IMk0tZamV6Q

**Comment by Beherith** [comment]
@badosu are playerlist ones log scale? And by menu, you mean lobby?

**Comment by badosu** [comment]
This was intended behavior yes, the widget one is db scale while the settings one I didn't change.

The ideal solution is changing in engine to do it db level there

**Comment by badosu** [comment]
I feel that tuning audio slider in widget is much more useful than in settings because the db level adjusts better to human perception.

But ye, this should be extended to engine so widgets don't have to do it on their own.

**Comment by 6AKU66** [comment]
![screen00009](https://user-images.githubusercontent.com/89547444/143296032-e8052c97-f405-479d-a470-88c7ece5c5b2.jpg)
![screen00010](https://user-images.githubusercontent.com/89547444/143296044-98a4d6e3-d10e-4441-9bbf-8228a77a6062.jpg)
Well i still don't think that sound slider working good in in advanced player list.

**Comment by 6AKU66** [comment]
I increased it to 8 (max 200) from 0 and slider jumped almost to center...

**Comment by badosu** [comment]
Yes, that's expected. One is linear, the other isn't. I should revisit this

**Comment by SethDGamre** [comment]
I was able to recreate this

**Comment by badosu** [comment]
Recreate what? What's the actual vs expected result?

**Comment by SethDGamre** [comment]
Over by the music player controls on the bottom right corner the volume slider is not linear. Sliding it up to 50% volume actually output something more like 25%. 

The volume sliders in the settings menu is linear, however.

**Comment by badosu** [comment]
So, my question stands, what's the expected outcome?

**Comment by SethDGamre** [comment]
Somebody has to make the call. GDT?

**Comment by SethDGamre** [comment]
> I mean, the solution is obvious to me, I don't think anibody needs approval to send a PR to fix it.
> 
> I am just asking, what is this issue about? A discrepance, now what's the fix expected?
> 
> My proposed solution is porting my code from advplayerlist to a shared lib and use db sliders everywhere sound volume is present.

Discrepancy. I think the objective is to make the volume slider by the music player work the same way as the volume slider in the settings menu.

**Comment by badosu** [comment]
Really? Why would you ever want to have a terrible slider? Just put a mute button, its the same thing

**Comment by SethDGamre** [comment]
I agree. If @6AKU66 agrees. I will take off the gdt tag if so. I understand it as a UI inconsistency issue.
