### ISSUE TITLE
Target stockpile values bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#568]
Target stockpile values behave differently if it's have number not equals 100.

If target stockpile number less 100 it's resets to 100.
If target stockpile number equals 100 it's don't change after commiting of attack.
If target stockpile number more 100 it's decrease by 1 point

https://youtu.be/-j-0Md7aig8

**Comment by KyleAnthonyShepherd** [comment]
Closing due to updates to stockpiling in past couple of years
