### ISSUE TITLE
Stutter on spec leave - Playerchanged callin load?

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#571]
Does playerchanged get called on spec leave? Maybe its some of our widgets reloading themselves on specleave that is causeing stutter?

Players

addon.PlayerChanged(playerID)

    Called whenever a player's status changes e.g. becoming a spectator.

addon.PlayerAdded(playerID)

    Called whenever a new player joins the game.

addon.PlayerRemoved(playerID, reason)

    Called whenever a player is removed from the game.

**Comment by Ruwetuin** [comment]
the stutter only happens fairly lategame so I heavily doubt its a widget responsible for this.

**Comment by Beherith** [comment]
Quite a few widgets now 'reload' themselves on playerchanged, but this is hard to test. Do replays stutter on exit too?

**Comment by icexuick** [comment]
i believe it's also for players - why i try to only leave when there is not a massive battle going on.

**Comment by Ruwetuin** [comment]
fixed in next engine release
