### ISSUE TITLE
LuaShader error on the t430 lenovo laptop on Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by FranzHeubach** [beyond-all-reason/Beyond-All-Reason#572]
Main shaders for all vehicles, metal deposits, and trees don't show up. The glow when selecting them does. Here are two examples: 
![Screenshot from 2021-11-14 14-21-45](https://user-images.githubusercontent.com/29097323/141693530-53bbe8ca-f357-42b5-85fd-6ce8561de7f4.png)

![Screenshot from 2021-11-14 14-21-17](https://user-images.githubusercontent.com/29097323/141693526-b8215bfa-5abd-4ba4-8695-4cb7f29035be.png)

Attached is the log file:
[20211114175508_infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7534361/20211114175508_infolog.txt)

Computer specs are:
T430 Lenovo
Ubuntu 18.04.6 LTS
Memory: 11.4 GiB
Processor: Intel® Core™ i5-3380M CPU @ 2.90GHz × 4 
Graphics: Intel® HD Graphics 4000 (IVB GT2)
64bit

I don't expect this issue to be fixed or given priority. This is an older computer so I expect the support to be spotty. The game ran fine at about 25 fps and other than the shader issue it did not seem to have a problem running the game on low / medium graphics settings. I submitted this issue mainly for your information (I don't know if it affects other platforms) and if your answer is "Your computer is to old to support" that's all good.

Thanks putting in work on such a great open source project!

**Comment by lhog** [comment]
This Intel GFX driver has no necessary support for "modern" (~10 years old nonetheless) OpenGL features and unlikely to ever get any for the older hardware. Given we move the game to the aforementioned modern OpenGL full-speed, the game will be breaking more and more for you eventually.

Try to update your drivers.
