### ISSUE TITLE
Unit promotion icons going reversal

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#581]
After some point unit promotion icons going reversal
![0](https://user-images.githubusercontent.com/89547444/142057787-a462c7f0-abb1-412c-9744-1039e050b78b.JPG)
![1](https://user-images.githubusercontent.com/89547444/142057792-ccb2284a-11bb-41b0-806e-43084cc651b8.JPG)
![2](https://user-images.githubusercontent.com/89547444/142057794-8b9a79dc-fff9-4884-a552-89f514ab78ae.JPG)
https://youtu.be/TLR0zsaTlqQ?t=1

**Comment by Damgam** [comment]
Rank icons and XP will be replaced at some point.

**Comment by Beherith** [comment]
Yes i will help damgam rewrite the xp icons

**Comment by icexuick** [comment]
I can't wait!! 👯

**Comment by Ruwetuin** [comment]
I dont think the GL4 version we use since february has this anymore
