### ISSUE TITLE
Reload time in GUI calculated wrong for promoted units

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#582]
![0](https://user-images.githubusercontent.com/89547444/142058142-91f0527e-9085-4811-8760-5bfc25c54d32.JPG)
![1](https://user-images.githubusercontent.com/89547444/142058146-767aae68-1bde-4081-915a-6cd8ddc5a80b.JPG)
https://youtu.be/TLR0zsaTlqQ?t=1

**Comment by Ruwetuin** [comment]
was fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/de2db8c4a6b4f3a7d40b130ddd80f3d6f7661632
