### ISSUE TITLE
Bug: bots start with high construction priority

### ISSUE THREAD

**Issue by yuyaryshev** [beyond-all-reason/Beyond-All-Reason#590]
All construction robots start with high priority. Which is strange: how do I quickly set higher priority then?
Suggestions: make 'normal' priority default

**Comment by Beherith** [comment]
Dont they inherit their priority from their factory?

**Comment by WatchTheFort** [comment]
> Dont they inherit their priority from their factory?

That's an issue, because priority is a stateful order that applies to the factory itself, unlike the other stateful orders that its units inherit.

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/f0209368-7af4-4364-8298-c4cfdd84de83)
Option exists in-game to set constructor priority. 
Closing issue, as the issue is not fully specified
