### ISSUE TITLE
Energy for turrents priorities, and also metal for repair

### ISSUE THREAD

**Issue by yuyaryshev** [beyond-all-reason/Beyond-All-Reason#591]
When you start building something big like a big Energy Storage, a Nuclear plant or a Vulcan - all tower usually freeze without energy.
Suggestion: additional "bar" on energy bar which reserves some energy for weapons.

For this to work nicely i also suggest "Energy priority" on units. All T1-T2 defences and army should have "normal" by default. All the rest should default to "low". "high" can only be set by player.

So Vulcan, Shields won't kill all your defences requiring you to stop building/charging them

...And a bar on metal bar for repair purposes would also be nice.

**Comment by sprunk** [comment]
Repair costs 0 metal, only energy.

**Comment by WatchTheFort** [comment]
Repair doesn't even cost energy, it's completely free.

**Comment by KyleAnthonyShepherd** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/494
Skimming through github issues. Similar to this issue, which also discusses energy use priority, closing this issue in favor of the older issue, which needs help implementing a solution
