### ISSUE TITLE
Barb AI random CTDs, error 3489660927

### ISSUE THREAD

**Issue by rsslcs** [beyond-all-reason/Beyond-All-Reason#618]
Dupe of report posted to Discord on 12/12/21

The game keeps crashing for me, with error 3489660927 during gameplay, usually towards 10-20 minutes in.

My infologs are never very useful, even with LogFlush Level = 0, but here everything log/setting related anyway:

I do not crash in multi at all, this is only skirmish vs AI, or scenario, always crashes with the same error code; the game hangs for a few secs with music as if it might recover, but then it all stops, and windows "stopped responding" dialog appears.

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7699174/infolog.txt)
[spring-launcher.log](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7699175/spring-launcher.log)
[springsettings - Copy.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7699177/springsettings.-.Copy.txt)

Specs are win10 pro x64, 9600k, 64gb RAM, RTX 3080, installed on C: but outside of program files

**Comment by Beherith** [comment]
Hmm, could you maybe try fishing the logs out of BAR/data/logs?

**Comment by Beherith** [comment]
See if there are any stack traces in those

**Comment by rsslcs** [comment]
> 

sadly, none of the infologs have a stacktrace; they just stop, for instance, in the middle of "rocko is being attacked!" I will post a couple more logs this evening as I reproduce with latest version

**Comment by Born2Crawl** [comment]
Try to add in springsettings.cfg anywhere:

`LogFlushLevel = 0`

That will ensure log flushing, and hopefully give a stack trace after crashing.

**Comment by rsslcs** [comment]
> Try to add in springsettings.cfg anywhere:
> 
> `LogFlushLevel = 0`
> 
> That will ensure log flushing, and hopefully give a stack trace after crashing.

hey there, this is weird but the line is in the file, within the game dir, but doesn't seem to have an effect, and I dunno why the log isn't more detailed.

The line appears exactly as LogFlushLevel = 0

is there another setting that may exist that overrides this one or something? I think I have a LogLevel = 0 setting or something too

**Comment by Beherith** [comment]
Does it crash very often for you? Because id love it if you could help debugging it a bit

**Comment by Beherith** [comment]
something like http://zero-k.info/Forum/Post/215110#215110
except that it's
./spring --menu 'BYAR Chobby $VERSION'
or
./spring --menu 'BYAR Chobby test-276-5cfc418'
(9test-276-5cfc418 is taken from infolog after last run)

**Comment by Born2Crawl** [comment]
`~/Documents/Beyond All Reason/engine/105.1.1-659-g800da82 bar/spring --write-dir ~/Documents/Beyond All Reason --isolation --menu rapid://byar-chobby:test`

**Comment by rsslcs** [comment]
Hi again, I have a way to reproduce the bug semi-repeatably by playing the "outsmart the barbarians" scenario, most recent crash took 2 minutes! I'm not doing much at the time, just placing mexes by right clicking the mex spot with a con kbot in the most recent instance.

I'm awful at anything relating to code, but what can I do exactly, debugging-wise?

**Comment by Beherith** [comment]
Still the case? there have been updates to the logging subsystem as well as the AI.

**Comment by segatrade** [comment]
Game stop to respond when I'm trying to load my save
https://bar-infologs.s3.amazonaws.com/spring-launcher_1652029616290.log

**Comment by Beherith** [comment]
That last bug is fixed upstream, we hope to deploy it this week, please feedback if it still persists next week :)

**Comment by segatrade** [comment]
Thank you!
Just updated game and tried to load. Same bug seems. New log:
https://bar-infologs.s3.amazonaws.com/spring-launcher_1652200562091.log

**Comment by 5teel** [comment]
I've just started getting the spring error on outsmart the barbarians as well :(

**Comment by marcushutchings** [comment]
What version of the game are you running?

**Comment by 5teel** [comment]
[23:17:03.07 info] Beyond-All-Reason - 1.2838.0

**Comment by SethDGamre** [comment]
> I've just started getting the spring error on outsmart the barbarians as well :(
> 
> Spring failed with code: 4294966293 For support please upload log and share it with us on [Discord](https://discord.gg/beyond-all-reason).

This is a different bug with a different error code. Please create a new issue if it persists.
