### ISSUE TITLE
[Proposal] Mexes should only be placable in the center of metal spots

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#622]
https://discord.com/channels/549281623154229250/722148569007521863/919924191145390090

Now T2 metal extractors can be placed over the top of T1 extractors, I think this makes more sense. It's ugly when mexes are placed off their designated texture and is unintuitive behaviour.

I think this would have to be synced so players can't simply turn off a widget to get around it.

Thoughts?

**Comment by fruehling76** [comment]
what about twinlights?

**Comment by Jazcash** [comment]
Twilights are cool, but I don't like the fact they're so good that people don't even care about placing them off metal spots. So imo we should either:

a) remove twilights and replace with emp mines that are more fit for purpose
b) only allow twilights to be placed on metal spots
c) repurpose twilights to not be metal extractors

**Comment by Beherith** [comment]
I also agree with mexes only on centers, its a simplification that is now ripe, and applicable to twilights as well

**Comment by Ruwetuin** [comment]
making mex buildable not on metalspots is just bad game-design
building around our game to quirks like emp-mex be placed anywhere isnt a good look 
esp when you'd have to disable mex-snap via widgetlist

centering on top of this will make sense taking the above into account

**Comment by sprunk** [comment]
steal from zk

**Comment by fruehling76** [comment]
no way. twilight are too cool to get rif off. sound like we need d.) t2 twilight

**Comment by fruehling76** [comment]
what means build over btw? reclaim and build i would say.

**Comment by Damgam** [comment]
> what means build over btw? reclaim and build i would say.

You can build T2 extractors on T1 ones now, then T1 gets auto reclaimed once T2 is done.

**Comment by KyleAnthonyShepherd** [comment]
Due to migrating mex snap widget to gadget space, and current work on mex upgrading systems, and the intentional decision to allow for off-center mexes to require scouting and not just blind firing, I am closing this issue.

**Comment by PeanutsRevenge** [comment]
Will need to check maps for conflicts.  I don't know about BAR certified, but it was far from uncommon for mexes to be unbuildable directly on their texture.
