### ISSUE TITLE
Text not visible in-game

### ISSUE THREAD

**Issue by krishnaravi94** [beyond-all-reason/Beyond-All-Reason#628]
When entering a game, none of the text is visible.

I've attached my infolog and screenshot as reference.
![no text BAR gameplay](https://user-images.githubusercontent.com/45928059/146205361-ca0ab5c7-c4e5-4c1d-aa2b-1c0b03c707b3.png)
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7720238/infolog.txt)

**Comment by Beherith** [comment]
Thanks for reporting, we are reverting for a bit, so things should be good to go in 30 minutes
