### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by aronsky** [beyond-all-reason/Beyond-All-Reason#631]
Since this is cross-platform, and the engine supposedly supports macOS, can BAR be ported to support macOS, as well?

**Comment by PtaQQ** [comment]
SpringRTS dropped mac support in the transition from v.103 to 104. New engine additions particularly GL4 support make it very hard to port to macOS, but there is some effort trying to sort it out. No promises. 

Check #Zink - MacOS thread under #engine on our discord for the details.

**Comment by aronsky** [comment]
Thanks!

**Comment by paviad** [comment]
Revisiting this, according to the home page of SpringRTS, they support macOS, is this relevant?

**Comment by joelharkes** [comment]
seems related? 

* https://community.khronos.org/t/how-to-use-opengl-on-zink-mesa-moltenvk-and-macos/108160/8
* https://www.reddit.com/r/opengl/comments/y70y04/getting_zink_to_compile_and_work_on_macos/

**Comment by joelharkes** [comment]
I see comments on the internet now that zink should be working with mac? (https://www.google.com/search?q=zink+mesa+macos+support&oq=zink+mesa+macos+support&aqs=chrome..69i57.4128j0j7&sourceid=chrome&ie=UTF-8)

I haven't come around to actually trying to download the source and build it, i might give it a shot. 

maybe @aronsky  can reopen the issue now? it seems requested a lot in the discord.

@PtaQQ I cannot find the thread you mentions when searching discord do you have a direct link?
