### ISSUE TITLE
Minimap disappears when spectating a match

### ISSUE THREAD

**Issue by Born2Crawl** [beyond-all-reason/Beyond-All-Reason#632]
Steps to reproduce:
1. Start spectating a game.
2. Switch to Player TV mode to start watching someone
3. Switch to overview camera with Tab yourself (minimap will be hidden as usual)
4. As soon as the player moves their camera, it will exit the overview to return to TA style camera, but the minimap will appear empty (only an underlying panel visible).

There's nothing in the log apart from switching camera modes.

![Screenshot 2021-12-16 12-59-55](https://user-images.githubusercontent.com/346670/146400524-de2886c3-4bbf-4810-b623-6f09a06f031e.png)

Video:
[![Video](https://img.youtube.com/vi/OiwuWtkamSU/0.jpg)](https://www.youtube.com/watch?v=OiwuWtkamSU)

Versions: BAR-18395-6b03c18, Spring 105.1.1-659-g800da82

**Comment by Beherith** [comment]
does this one still happen?

**Comment by Born2Crawl** [comment]
Yes, it does. Just checked. Super reproducible.

**Comment by Born2Crawl** [comment]
Disabling/enabling Minimap widget helps though. So it's definitely something in it, but I couldn't figure out what :(
