### ISSUE TITLE
Paralyzed seconds counter goes negative

### ISSUE THREAD

**Issue by Born2Crawl** [beyond-all-reason/Beyond-All-Reason#633]
Steps to reproduce:

1. Paralyze the enemy unit using a bladewing. Each shot increases the paralyzed time seconds (up to 10 sec I think).
2. Pick the paralyzed enemy unit with the air transport.
3. The paralyzed counter goes down to 0s and then continues to -1s, -2s and so on, as long as the unit is being carried.

Desired behavior: the unit should be able to un-paralyze even when being carried.

![Screenshot 2021-12-16 13-43-40](https://user-images.githubusercontent.com/346670/146403168-dc7bd9b4-096e-4e19-b9bf-bf0391f47795.png)

Video:
[![Video](https://img.youtube.com/vi/x2q5FpQlD5c/0.jpg)](https://www.youtube.com/watch?v=x2q5FpQlD5c)

Versions: BAR-18395-6b03c18, Spring 105.1.1-659-g800da82

**Comment by Born2Crawl** [comment]
No, it gets unparalyzed immediately, but while the paralyze cooldown bar is not depleted, the negative seconds counter still works and becomes visible if you pick it up again (and it will continue going down into more negative).

**Comment by Beherith** [comment]
noting this one, as ill need to test it on new healthbars. on the other hand, you can clear paralyze by load unload? thats op for mobile antinuke 🗡️

**Comment by Born2Crawl** [comment]
I think it gets up-paralyzed immediately on release because it already reached negatives. But I think if you release while it's still positive, it will behave normally.

**Comment by Beherith** [comment]
Ok gl4 version does not suffer from this :D

**Comment by Born2Crawl** [comment]
Perfect, I'm looking forward to GL4 version, then we can close this, too :)
