### ISSUE TITLE
Display of potential resource consumption

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#64]
Due to passive builders and metal converters behaving passively, you have no idea how much you "could" consume vs what is actually being consumed, while build processes are idling in the background.

**Comment by Beherith** [comment]
Best bet could be 'fraction of buildpower used'

**Comment by lweberk** [comment]
Good point. "<consumption> / <buildpower>"

**Comment by Ruwetuin** [comment]
good idea, sceduled

**Comment by Ruwetuin** [comment]
added in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/db150590abebdb3628cb661ed58d7f5bcbbade43
