### ISSUE TITLE
STAI defense placement improvement

### ISSUE THREAD

**Issue by pandaro** [beyond-all-reason/Beyond-All-Reason#641]
Better analisy of seddles and the points of greatest passages of units.
Better choice of turrets to build.
Managed as a grid, so build in this box just the turrets that are needed here

**Comment by vvbudh** [comment]
What if in this box, we had a limit to how many turrets could be in it? Say in the box we have space for 10 LLTs, what if we put one LLT down, then if an enemy units comes there, we add one more, then if they come back we add another, until the box is filled with the max volume of turrets? That way the AI reacts to the players behavior? Then we might consider a function to reduce the number of turrets or, to delete the entire box and recreate it somewhere else when the front moves. Things to think about.

**Comment by KyleAnthonyShepherd** [comment]
@pandaro any updates on this issue?
