### ISSUE TITLE
Random Crashes Occurring in Middle of Game / While Loading Game

### ISSUE THREAD

**Issue by krishnaravi94** [beyond-all-reason/Beyond-All-Reason#648]
I've been experiencing crashes today while loading a game and while in the middle of the game. I'm not sure what causes it as it happens irrespective of whether map is populated or not. I'm attaching infolog for reference.
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7757761/infolog.txt)
.

**Comment by Beherith** [comment]
Thank you, new engine has fixed this.
