### ISSUE TITLE
Frame grapher widget crashing

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#649]
Widget crashing after 2-4 seconds of use

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7758872/infolog.txt)

[t=00:00:53.296000][f=0000134] Loading:  LuaUI/Widgets/dbg_frame_grapher.lua
[t=00:00:55.751000][f=0000208] false
[t=00:00:55.751000][f=0000208] Error in DrawScreen(): [LuaVAOImpl::DrawCheck]: Requested rendering of [500] instances, but no instance buffer is attached. Did you succesfully call vao:AttachInstanceBuffer()?
[t=00:00:55.751000][f=0000208] Removed widget: Frame Grapher

**Comment by 6AKU66** [comment]
@Beherith 
Looks like it's broke somewhere in that commits
![3](https://user-images.githubusercontent.com/89547444/147422519-4dacae65-2504-4467-8877-acba466b5c47.JPG)

**Comment by Beherith** [comment]
fixed
