### ISSUE TITLE
Word spacing too short in 4k (3840x2160)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#650]
Word spacing too short in 4k for system messages

![1080p](https://user-images.githubusercontent.com/89547444/147010320-94395c26-c19c-4ece-a836-8d8bc7ac7f03.JPG)
![4k](https://user-images.githubusercontent.com/89547444/147010323-63e1d5e4-816c-491a-bd68-25bb1e3ad154.JPG)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/a368bc39ba4bd9be85a62f7827b9c381a76446f0
