### ISSUE TITLE
Effects render bug 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#652]
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7762662/infolog.txt)
![Снимок](https://user-images.githubusercontent.com/89547444/147094506-55d407f4-4ff1-4592-8ac2-56f0084fb47f.JPG)
[20211221_152852_Pillar_of_Doom_V1_105.1.1-710-g9040a65 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7762668/20211221_152852_Pillar_of_Doom_V1_105.1.1-710-g9040a65.BAR105.zip)

GTX 1060 3gb, win7, replay target speed 20x

https://youtu.be/2EF7hPUKseA

**Comment by 6AKU66** [comment]
P.S First intensive battle happening around 6-9 minute of match....

**Comment by icexuick** [comment]
hmm never seen that before..
was is with all particle textures?

**Comment by 6AKU66** [comment]
> hmm never seen that before.. was is with all particle textures?

I don't know about that, it's already second bug that happening only (not sure 100% though) with high speed of replay.

**Comment by 6AKU66** [comment]
I think human error happened here. I will reopen ticket if i will meet this bug again.
