### ISSUE TITLE
Underwater metal extractors autoplacement working not correct

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#654]
![Underwater metal extractors placement mp4_snapshot_00 04_ 2021 12 22_16 45 38](https://user-images.githubusercontent.com/89547444/147102664-e4fb4955-3168-4d3a-8632-b778377982ec.jpg)
![Underwater metal extractors placement mp4_snapshot_00 06_ 2021 12 22_16 45 56](https://user-images.githubusercontent.com/89547444/147102687-447c6c27-9425-4ac8-9e73-f186e614cf14.jpg)

https://www.youtube.com/watch?v=jwwjsbyzWH8
18455
105.1.1.714

**Comment by Damgam** [comment]
It is correct. But the way it works is that you have to click on water level.
Same thing goes for placing build orders on water.

**Comment by KyleAnthonyShepherd** [comment]
Due to above statement saying this is working correctly, closing issue
