### ISSUE TITLE
Some build projections is invisible

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#655]
![2021-12-22 17-00-45 mp4_snapshot_00 06_ 2021 12 22_17 24 58](https://user-images.githubusercontent.com/89547444/147107610-5421e76d-fd0e-4020-872d-17cdc64844d6.jpg)
![2021-12-22 17-00-45 mp4_snapshot_00 08_ 2021 12 22_17 25 05](https://user-images.githubusercontent.com/89547444/147107638-fc58fb4b-7d0a-4776-9c8e-bb053b581ee8.jpg)
https://youtu.be/lSkayCgnF1Y

**Comment by Beherith** [comment]
This is a perf optimization thing, and will get fixed with gl4 soon

**Comment by 6AKU66** [comment]
> This is a perf optimization thing, and will get fixed with gl4 soon

So i guess this problem with strategic icons is not related to that?
https://www.youtube.com/watch?v=OFKE-3FoH2s

**Comment by lhog** [comment]
> https://www.youtube.com/watch?v=OFKE-3FoH2s

It is the engine bug. Are these new icons (`/iconsasui 1` or old ones).
It should be easy to fix, but usually very hard to reproduce.

**Comment by 6AKU66** [comment]
> > https://www.youtube.com/watch?v=OFKE-3FoH2s
> 
> It is the engine bug. Are these new icons (`/iconsasui 1` or old ones). It should be easy to fix, but usually very hard to reproduce.

It's /iconsasui 1. 

/iconsasui 0 seems ok.

**Comment by Beherith** [comment]
Gl4 show builder queue has been deployed, should fix this issue. If the icons asui bug is still relevant, keep this one open.

**Comment by lhog** [comment]
Re: `/iconsasui 1` bug, I'd appreciate if you could send:
1) A map name
2) A screenshot showing approximate position of units that should have their icons but do not have them (1 unit with missing icon is enough)
3) Data dump from `Spring.GetCameraState()` so I could position my camera exactly as you did

**Comment by 6AKU66** [comment]
> Gl4 show builder queue has been deployed, should fix this issue. If the icons asui bug is still relevant, keep this one open.

Seems, ok now.

One question: is there setting for making projections less transparent?
![3](https://user-images.githubusercontent.com/89547444/147713144-ccdffb4f-7a6a-454f-86d1-25da6d39d12d.JPG)

**Comment by 6AKU66** [comment]
> 3. Data dump from `Spring.GetCameraState()` so I could position my camera exactly as you did

I don't know how to do that

**Comment by lhog** [comment]
Good point. @Ruwetuin can you add some "dump camera state" button, that would `TableEcho(Spring.GetCameraState())` to F10/dev menu?

**Comment by Ruwetuin** [comment]
Can do

**Comment by Ruwetuin** [comment]
I just added dev-tab debug option: Echo CameraState
