### ISSUE TITLE
First spectator's nickname is bold

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#656]
When match started first spectator's nickname becoming bold

Signis
![screen00010](https://user-images.githubusercontent.com/89547444/147280272-4db5b894-fc50-4d70-8cd4-32cbddb0de67.png)

https://www.youtube.com/watch?v=gVa6VAiggKM

**Comment by Beherith** [comment]
I didnt quite understand this either, why some are bold, some are grey and some white :D

**Comment by Ruwetuin** [comment]
The white, light grey and grey is depending on user moving camera... user key/mousemove input or idle.

First spectator being fuzzy i havent figured out why... toggling the playerlist fixes it but cant figure out why it happens  fiddling with its code

**Comment by 6AKU66** [comment]
Ok, here are close look.

![screen00249](https://user-images.githubusercontent.com/89547444/149654644-24a95058-48ed-47db-b0ca-c70903b7e1c3.jpg)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/62324a0724a52f4b76e95a0c30f6d5df0b5d891f
