### ISSUE TITLE
Explosions making black squares

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#659]
Explosions sometimes start making black squares
[20211224_182153_LV412 1_105.1.1-714-ge909643 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7775024/20211224_182153_LV412.1_105.1.1-714-ge909643.BAR105.zip)

Timestamp around 3:30-3:50

https://www.youtube.com/watch?v=jTYmZkv_rj0
https://www.youtube.com/watch?v=X_4UsbOQoIQ

![Снимок](https://user-images.githubusercontent.com/89547444/147369254-cedbeede-1bae-42b2-b79a-ad5b63998108.JPG)
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7775727/infolog.txt)

**Comment by lhog** [comment]
You are running some kind of non-standard configuration here:

`[t=00:00:54.912000][f=-000001] Error in [SSAO] widget: Deferred shading is not enabled or advanced shading is not active`

I wont' be surprised if decals misbehave w/o advanced map shading, because in that mode deferred rendering, decals most probably depend on, is not run.

**Comment by 6AKU66** [comment]
> I wont' be surprised if decals misbehave w/o advanced map shading, because in that mode deferred rendering, decals most probably depend on, is not run.

With advanced map shading.
Result: no black squares.

W/o advanced map shading result (ground scars off or on: no difference).
Result: black squares started formed.

**Comment by lhog** [comment]
So:

- with advmapshading: no issues
- w/o advmapshading: black squares


have I got it right?

**Comment by 6AKU66** [comment]
> have I got it right?

Yes

**Comment by lhog** [comment]
ok I've rechecked it's using `[t=00:00:46.926000][f=-000001] Loaded DecalsDrawer: Legacy` which name suggest something we would rather remove rather go and fix.

Also I plan to remove `/advmapshading` and `/advunitshading` switches. What was relevant 10 years is becoming obsolete by the end of 2021

**Comment by 6AKU66** [comment]
> Also I plan to remove `/advmapshading` and `/advunitshading` switches.

Hm... advmapshading, advunitshading pretty heavy for GPUs though.

**Comment by lhog** [comment]
Should give almost equal performance as non-advanced modes.
`/advunitshading` also triggers custom unit shading (if not disabled), which is not fast, it might give the false impression.

**Comment by 6AKU66** [comment]
> `/advunitshading` also triggers custom unit shading (if not disabled), which is not fast, it might give the false impression.
Is there some command for disable custom unit shading? I want to do some benchmarks later.

**Comment by lhog** [comment]
It's a bit of misnomer in BAR.

What is called `Advanced Unit Shading` is in fact `Custom Unit Shading` (see F10 menu).
The real `Advanced Unit Shading` is only triggered by `/advunitshading` or the respective springsetting.cfg key.
