### ISSUE TITLE
AI increase target stockpile value every x seconds

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#661]
BARbarianAI increase target stockpile value every 5 second. 
ScavengerAI also affected by this.
Seems all units with stockpiling affected.

![изображение_2021-12-24_223431](https://user-images.githubusercontent.com/89547444/147370323-b74092fd-c012-462e-823a-e0afb6a5d960.png)

https://www.youtube.com/watch?v=fxYiClxSt2I

**Comment by SethDGamre** [comment]
couldn't recreate issue. seems resolved
