### ISSUE TITLE
ai_ruins.lua got nil

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#662]
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/ai_ruins.lua"]:176: bad argument #1 to 'SetUnitNeutral' (number expected, got nil)
stack traceback:
	[C]: in function 'SetUnitNeutral'
	[string "LuaRules/Gadgets/ai_ruins.lua"]:176: in function 'spawnRuin'
	[string "LuaRules/Gadgets/ai_ruins.lua"]:338: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:861: in function <[string "LuaRules/gadgets.lua"]:859>
	(tail call): ?
	
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7775740/infolog.txt)
[20211224_204915_Titan v3_105.1.1-714-ge909643 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7776354/20211224_204915_Titan.v3_105.1.1-714-ge909643.BAR105.zip)

**Comment by Damgam** [comment]
That sounds like unit failed to spawn and proceed further into the code with nil unitID

**Comment by 6AKU66** [comment]
"The only reason i can think of is unit cap..."

I think you are right, because there's was message about unit cap.

**Comment by Damgam** [comment]
NEED MORE NIL CHECKS

**Comment by 6AKU66** [comment]
Infolog added

**Comment by 6AKU66** [comment]
Ok, i doubt that it's unit cap, since it's happen really early in game.

**Comment by Damgam** [comment]
Well, all ruins spawn very early in the game so...

**Comment by Damgam** [comment]
Fixed
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/c55dc246bfd5e8295ec10e2b3f18a9ca1abeeb71
