### ISSUE TITLE
Advanced Map Shading is not enabling if it's was disabled before match

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#663]
![изображение_2021-12-25_161404](https://user-images.githubusercontent.com/89547444/147385705-950b6a55-d5f7-41ce-9b9f-77ca72854fcc.png)

Advanced Map Shading enabled before starting of match
https://www.youtube.com/watch?v=Z0EnO2KqBmU

Advanced Map Shading disabled before starting of match
https://www.youtube.com/watch?v=3gMcH8dkm74

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7775857/infolog.txt)

**Comment by Beherith** [comment]
Is it disable able outside of developer mode? Last i checked i couldn't even disable it.

**Comment by Beherith** [comment]
Yeah that setting need s to be removed or made Dev only, as some maps rely on it to show metal spots.

**Comment by 6AKU66** [comment]
> Is it disable able outside of developer mode? Last i checked i couldn't even disable it.

Yeah, it's shows in dev only. Advanced Map Shading saving pretty much of performance though.

**Comment by icexuick** [comment]
On spectating, catch-ing up is always with AMS enabled, even though it's disabled stated is saved, and gets applied only after having caught up.

**Comment by Ruwetuin** [comment]
this is indeed irrelevant for BAR since it is a dev only option, seems like an engine problem.
