### ISSUE TITLE
Self-destruct unit's name missing

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#669]
![3](https://user-images.githubusercontent.com/89547444/147413870-c82dd405-f502-4c11-894f-04a1ea490c94.JPG)

https://youtu.be/5HM4URQxlaw

**Comment by WatchTheFort** [comment]
Which unit was this?

**Comment by 6AKU66** [comment]
> Which unit was this?

Armada commander, but look like all units affected.

**Comment by 6AKU66** [comment]
Probably need seacrh problem in game versions 18402 (46be971)-18405 b40155a

**Comment by sprunk** [comment]
This is an engine-generated message. Have the widget that displays it hide it and make its own using i18n.

**Comment by WatchTheFort** [comment]
This is from a widget? I was always under the impression this was an engine message sent directly to the log.

**Comment by Ruwetuin** [comment]
must be so, i guess we need to filter this message from the console then
