### ISSUE TITLE
Restore with negative sea level

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/Beyond-All-Reason#671]
![image](https://user-images.githubusercontent.com/167068/147422048-5a1bce2e-5b35-4136-b462-35469fee7c1b.png)

We set sea level to -500 on Neurope and restored the land, that happened.

**Comment by Beherith** [comment]
If a modoption cant override mapoption, then GG, this method of set waterlevel was a nasty hack anyway.

**Comment by sprunk** [comment]
Is this about map vs mod options? I thought this just means that Spring sticks to the "true", pristine original height as the original for restore purposes (instead of the height after the modoption is applied).

**Comment by Ruwetuin** [comment]
yes
