### ISSUE TITLE
Crawling bombs don't copy factory settings

### ISSUE THREAD

**Issue by L-e-x-o-n** [beyond-all-reason/Beyond-All-Reason#673]
When the factory is set on hold fire, Bedbug and Skuttle ignore that and keep the default fire at will. Other units are working fine.

**Comment by WatchTheFort** [comment]
I believe this is intentional, as kamikaze units are meant to be on hold fire?

**Comment by L-e-x-o-n** [comment]
Right now they are always on fire at will,  unless you select them and set them to something else.
 This change just makes them copy the settings from the factory like any other unit.

**Comment by L-e-x-o-n** [comment]
How can I link a pull request to issue like that?

**Comment by WatchTheFort** [comment]
> How can I link a pull request to issue like that?

If you're using the GitHub website, there is a column to the right to link reviewers, projects, labels, etc.

**Comment by L-e-x-o-n** [comment]
> > How can I link a pull request to issue like that?
> 
> If you're using the GitHub website, there is a column to the right to link reviewers, projects, labels, etc.

I see, but I can't click it or do anything with it? Edit button only edits the name.

**Comment by WatchTheFort** [comment]
Probably have to be assigned as a contributor on the repository

**Comment by L-e-x-o-n** [comment]
Ok, I found I need to use the Reference an issue button in this chat box to make it work.
