### ISSUE TITLE
Paralyze effect widget crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#674]
Error in GameFrame(): [string "LuaUI/Widgets/gfx_paralyze_effect.lua"]:335: attempt to perform arithmetic on local 'paralyzeDamage' (a nil value)
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7790257/infolog.txt)
@Beherith

**Comment by Beherith** [comment]
Floris did a nil check :)

**Comment by icexuick** [comment]
is this fixed now?
