### ISSUE TITLE
Some scav units stuck at experimental gantry

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#676]
List of units:
Epic Tzar
Epic Karganeth
![4](https://user-images.githubusercontent.com/89547444/147705950-c496e081-981e-421b-a64a-6b7d379e243c.JPG)
https://youtu.be/ON-O9EFKCgA

**Comment by Damgam** [comment]
Fixed
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/e81d8615e0e5308656ad4aa968a1dd4a695dd787
