### ISSUE TITLE
It's snowing with disabled snow

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#677]
Enabling and disabling snow not give any results
![3](https://user-images.githubusercontent.com/89547444/147714150-24ee9b97-0366-462e-8fbe-705c2d08d744.JPG)
https://www.beyondallreason.info/replays?gameId=ccaacc611bb267e072e643c6c9d8e203

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7791162/infolog.txt)

**Comment by Damgam** [comment]
It's map bug. IceXuick has to update his older maps.

**Comment by Damgam** [comment]
@icexuick do it plz.

**Comment by icexuick** [comment]
I'll update Koom this week

**Comment by icexuick** [comment]
Koom was updated t0 3.1 so this map should be clean of snow now.
