### ISSUE TITLE
Autopause bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#679]
Some actions cause autopause not functioning anymore
https://www.youtube.com/watch?v=XhgiMnRehz0
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7794599/infolog.txt)

**Comment by KyleAnthonyShepherd** [comment]
Not sure how to replicate on my side. Is this still an issue?

**Comment by SethDGamre** [comment]
very old issue, I don't quite understand the OP or video.
It also hasn't been touched in four years and last inquiry was a year ago.
