### ISSUE TITLE
Scavengers don't spawn beacons

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#680]
We captured a lot of beacons and controlled all map.

https://www.beyondallreason.info/replays?gameId=efadd0619897f56ae00279e8090bfe22
[infolog_1641065967010.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7798288/infolog_1641065967010.txt)

**Comment by Damgam** [comment]
In such case game should fast forward to boss fight and spawn him in the center of the map.

**Comment by 6AKU66** [comment]
> In such case game should fast forward to boss fight and spawn him in the center of the map.

Yeah, boss spawned in center of the map.

**Comment by Damgam** [comment]
I'll make him attempt to spawn in scav startbox and only then in map center.
