### ISSUE TITLE
Add bonus not working after changing ally

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#683]
Chobby

Step to reproduce:
1. Go singleplayer - skirmish
2. Add bonus to yourself
3. Change ally (team in chobby)
4. Start game to observe bug

https://youtu.be/nZDV3SpyWkY
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7799269/infolog.txt)

I don't know if this belong to lobby issue or game.

**Comment by KyleAnthonyShepherd** [comment]
Not sure when, but this issue seems to be fixed. Followed the reproduction steps, and I kept the bonus after changing ally
