### ISSUE TITLE
Logging while being in skirmish menu and starting game moving player to spectator

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#684]
Chobby
1. Start game without logging in account.
2. Go to Singleplayer - Skirmish.
3. Logging in account.
4. Start game.
5. Observe game (You're had moved to spectator).

https://youtu.be/bMuApBzQh14
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7799435/infolog.txt)

I don't know if this belong to lobby issue or game.

**Comment by Beherith** [comment]
Known naming bug :(
