### ISSUE TITLE
Minelayers: should be excluded from smart select as builders

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/Beyond-All-Reason#686]
When the "include builders" setting (from interface menu) is off, minelayers should also be excluded from selection by box select without the shift override. It seems they are not currently flagged as builders. It can be a big issue when they get selected with a box select for army and their mine-laying queue is canceled as a result (after a fight or move command).

**Comment by WatchTheFort** [comment]
The problem is they also shouldn't be considered builders, since they cannot assist construction, so they are kind of limbo as neither combat units nor builders.

**Comment by Ruwetuin** [comment]
done! included anythign that has buildoptions a builder
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/084d99bfcb1fc85c8e301482b37e8c6f9b53fcfa
