### ISSUE TITLE
Some scavenger's units don't have collisions if they spawned from beacon

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#687]
Group 1 was spawned from beacon.
![group1-beacon](https://user-images.githubusercontent.com/89547444/147963741-608f2ea3-1f43-4938-a508-c9c669ecbd2d.jpg)
Group 2 was produced from factory.
![Group2no-beacon](https://user-images.githubusercontent.com/89547444/147963775-ec3668eb-7e8f-47c9-83a1-b7c038e1c922.jpg)

https://youtu.be/D-MvwrTZq00

**Comment by Damgam** [comment]
Scav rezzers have tiny footprint...
I should revert that now that they are all-terrain...

**Comment by SethDGamre** [comment]
Ancient, seems to no longer be an issue from my play testing
