### ISSUE TITLE
Some units rotate almost instantly

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#688]
Scav's armada commanders (Decoy commanders is not) and epic grunt affected by this. 
https://youtu.be/wdT6i0vx0eU
https://www.youtube.com/watch?v=AZCrlYusC74

**Comment by Beherith** [comment]
This seems intentonal, as 
Beyond-All-Reason.sdd\gamedata\scavengers\unitdef_changes.lua
states
	turnrate = 50000,
for armcom, but @Damgam  knows for sure

**Comment by 6AKU66** [comment]
Added epic grunt list, renamed title.

**Comment by Damgam** [comment]
For commanders it's intentional
For Grunt it's not. It's supposed to move similar to Epic Pawn.

**Comment by Beherith** [comment]
Seems fixed for epic grunt scav version too :) reopen if not :D
