### ISSUE TITLE
Ambient occlusion and bloom graphic artefacts 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#691]
Probably happened because of fullscreen (no borderless) was enabled before match was started.

https://www.youtube.com/watch?v=SQQ1WHnPxdI
![Can i have one day without bugs](https://user-images.githubusercontent.com/89547444/148108123-9a09c098-822f-4283-a5eb-1299875f179a.jpg)

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7809676/infolog.txt)

**Comment by lhog** [comment]
Hard to say what happened here. Some "effects" look like stale bloom widget textures.
If you happen to reproduce how to trigger it, post the steps.

**Comment by 6AKU66** [comment]
I think human error happened here. I will reopen ticket if i will meet this bug again.
