### ISSUE TITLE
STAIunitdamage give nil engineunit 

### ISSUE THREAD

**Issue by pandaro** [beyond-all-reason/Beyond-All-Reason#693]
Sometime unitdamage give nil engineunit

**Comment by lhog** [comment]
Which of the following params is nil `addon.UnitDamaged(unitID, unitDefID, unitTeam, damage, paralyzer, weaponDefID, projectileID, attackerID, attackerDefID, attackerTeam)` ?

**Comment by pandaro** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/ai/STAI/unithst.lua#L246

At first look seem a problem with unitID, but I need to run up to the wheel, where af rewrite the func.

https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/AILoader.lua#L202

Here, as you see there are a shardify_unit that have ever work fine.

As best I need a replay with log, so I can add the correct game version and check in which situation this appened

**Comment by pandaro** [comment]
#https://github.com/beyond-all-reason/Beyond-All-Reason/pull/730/commits/1aa49ec1c696900e274de5b22d4cd7356520cce2
 this will solve, i will delete this issues when i close this PR
