### ISSUE TITLE
Scav demon dead body offset

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#696]
![Scav Demon bug mp4_snapshot_00 08_ 2022 01 05_14 14 57](https://user-images.githubusercontent.com/89547444/148208942-0cc4e16c-2649-44ae-bc56-51bee7485786.jpg)

https://www.youtube.com/watch?v=ob_1GhYst00

**Comment by Damgam** [comment]
Upscaling "artifact"
Needs someone who knows what they're doing to fix it.

**Comment by Beherith** [comment]
fixed
