### ISSUE TITLE
armthor right EMP laser turret cannot fire sideways

### ISSUE THREAD

**Issue by Rhade1** [beyond-all-reason/Beyond-All-Reason#697]
the left EMP laser is able to cover about 90 degs from the front to the left side 
bug: the right EMP laser can only fire very close to the front direction, and can only turn about 20-30 degs

**Comment by Rhade1** [comment]
Just a guess:
for one of the turrets
 maxangledif = 120 -> maxangledif = -120
notice the negative sign

**Comment by WatchTheFort** [comment]
Cause is due to two underlying issues, both in the unit script:
- Angle check is being done in script, ignoring the unitdef
- Copy-paste error is using `lempslv` piece for both flank lasers

A fix is on the way.
