### ISSUE TITLE
Radar coverage is very difficult to see

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/Beyond-All-Reason#71]
There is practically no visibility of radar coverage (LOS difference - if any - is insignificant). Radar is very important in BAR and it's going to confuse newbie players if such information is hidden

**Comment by icexuick** [comment]
I kinda agree, though i don't find current options good, f.e. the ugly blue/green lines in ZK.
I would like to test/explore possibilities of showing radar-line somehow though.

**Comment by fruehling76** [comment]
just increase los difference for and see if that works. that would be the most subtile and elegent way to go.

**Comment by Ruwetuin** [comment]
(being) fixed
