### ISSUE TITLE
Scavengers regeneration affect reclaim speed

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#711]
Probably need stop regeneration while reclaiming
https://youtu.be/DjPJj3nESo8

**Comment by SethDGamre** [comment]
I'm not aware of any instance where scavengers reclaim their own stuff. 

The boosted healing rate is set in post in unitdefs intentionally. On top of that, builders have a constant healing radius that heals stuff around them. @Damgam iirc you're happy with these mechanics. If you don't intend to change this, could you resolve this issue?

**Comment by Damgam** [comment]
Not A Problem
