### ISSUE TITLE
Widget unit energy icons crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#718]
Step to reproduce:
1. Start replay.
2. Spectate StarDoM.
3. On timestamp 6:12 error should appear.

[t=00:01:26.973000][f=0011448] Error in GameFrame(): [LuaUtils::InstanceDataFromGetData] Non-existing UnitID (11387) is supplied
[t=00:01:26.973000][f=0011448] Removed widget: Unit Energy Icons

[20220101_024908_Altored Divide Bar Remake 1_105.1.1-714-ge909643 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7853903/20220101_024908_Altored.Divide.Bar.Remake.1_105.1.1-714-ge909643.BAR105.zip)

**Comment by Beherith** [comment]
Hmm, thanks, I think I know this one, were you spectating or playing at the time?

**Comment by 6AKU66** [comment]
> Hmm, thanks, I think I know this one, were you spectating or playing at the time?

Yes

**Comment by Beherith** [comment]
So spectating? :)

**Comment by 6AKU66** [comment]
> So spectating? :)

I was spectating.

**Comment by 6AKU66** [comment]
This happened to me again, i was spectating certain player and after clicking "turn off" (stop spectating certain player) this error happened.

**Comment by 6AKU66** [comment]
Changed replay and added steps for reproducing.

**Comment by Beherith** [comment]
This looks like a job for the new TraceFullEcho :)

**Comment by Ruwetuin** [comment]
I dont think his happens any longer
