### ISSUE TITLE
Found invalid unit/featureID (Ground AO Plates bug)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#719]
[t=00:20:09.568000][f=0085565] Warning: Found invalid unit/featureID, 1830, at, 52, while resizing, Ground AO Plates FeaturesVBO
[t=00:20:09.568000][f=0085565] Warning: Found invalid unit/featureID, 2918, at, 112, while resizing, Ground AO Plates FeaturesVBO

[20220112_041016_Neurope_a7_v3_105.1.1-739-ga241485 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7851951/20220112_041016_Neurope_a7_v3_105.1.1-739-ga241485.BAR105.zip)

**Comment by 6AKU66** [comment]
I tried watch replay, no error appeared. Sad.

**Comment by Beherith** [comment]
I should slowly get rid of the warnings, as ive now prevented widget crashes.

**Comment by 6AKU66** [comment]
In some matches this looks bad though.

![изображение_2022-01-18_131342](https://user-images.githubusercontent.com/89547444/149917212-5e3c4962-b825-49a3-b1d1-b15c68ce9476.png)

**Comment by Ruwetuin** [comment]
have not seen this happening anymore
