### ISSUE TITLE
Error: Not a flying unit 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#720]
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_airbase.lua"]:519: Not a flying unit
stack traceback:
	[C]: in function 'SetUnitLandGoal'
	[string "LuaRules/Gadgets/unit_airbase.lua"]:519: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:861: in function <[string "LuaRules/gadgets.lua"]:859>
	(tail call): ?
	
[20220112_133511_SpeedMetal BAR V2_105.1.1-739-ga241485 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7856272/20220112_133511_SpeedMetal.BAR.V2_105.1.1-739-ga241485.BAR105.zip)

**Comment by WatchTheFort** [comment]
Should we finally pull the plug on repair pads?

**Comment by Ruwetuin** [comment]
maybe landed planes are "not a flying unit" so lets try checking ground height
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/af3b0c152b67c169735d3405c65159d69afcd3e6#diff-e35e452b4b7e98eaa4abf45b69411dd801400c63b11ab08f804e2fd114f5abb2
