### ISSUE TITLE
Feature request: enable flanking circle display for turrets and other buildings with weapons

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/Beyond-All-Reason#724]
If someone has time to do this it would be great. It seems fine for non-combat units to not show flanking damage since that is less important but I am curious to see how turrets in general respond to the way units move around them. Maybe it would be an easy first project for a new dev? The widget is called "Flanking icons GL4"

**Comment by Beherith** [comment]
Maybe @L-e-x-o-n  could give this a shot, the relevant line checking for mobile units is this one: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/ccd4c67bd0d77e786c0938448a5f3765b591f43d/luaui/Widgets/gui_flanking_icons.lua#L78

**Comment by L-e-x-o-n** [comment]
Done
