### ISSUE TITLE
Loading the game causes all AI to go dormant

### ISSUE THREAD

**Issue by BrianAdams** [beyond-all-reason/Beyond-All-Reason#727]
Bar version I am running: 
![Screenshot from 2022-01-15 10-57-33](https://user-images.githubusercontent.com/1471826/149634471-eb5ba55d-c574-4e2c-8a78-416c62bce7fe.png)

Bar version of save:
![Screenshot from 2022-01-15 10-57-12](https://user-images.githubusercontent.com/1471826/149634476-b225f0bc-6418-4f94-9c30-242b89774514.png)

What the screen looks like. All of the AI is just sitting around no longer building or directing troops.

![Screenshot from 2022-01-15 10-55-27](https://user-images.githubusercontent.com/1471826/149634493-9f20c4b5-1fad-4907-9bc2-9a3cc503faec.png)

I then exited and here is the infolog.txt:

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7875680/infolog.txt)

**Comment by Damgam** [comment]
Savegames are just straight up broken so... yea.

**Comment by lhog** [comment]
The fact they are broken doesn't mean we shouldn't fix them.

cc: @rlcevg

**Comment by rlcevg** [comment]
`[AI Loader] ShardLua bot Deactivated!`
`VFS.FileExists("luarules/gadgets/ai/" .. luaAI .. "/boot.lua") == false`

**Comment by lhog** [comment]
Oh lol

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7893713/infolog.txt)

I also have circuit AI breaking. It doesn't quite go dormant though.

**Comment by SethDGamre** [comment]
Very old issue I haven't been able to reproduce
