### ISSUE TITLE
Unable to click update checkbox after un-selecting it in initial menu, menu diappears too quickly

### ISSUE THREAD

**Issue by keithphw** [beyond-all-reason/Beyond-All-Reason#731]
Hi,
I un-selected auto-update in the initial menu and now I'm unable to select it again since this initial menu disappears too quickly. This has forced me to uninstal and re-install. 
Would be great to fix this. 
By the way, fantastic work on this game. It's very impressive.
Cheers,
Keith

**Comment by Beherith** [comment]
Yes, the latest update fixes this :) but thanks for reporting.

**Comment by keithphw** [comment]
Thank you Beherith, confirming that the problem is fixed after un-installing and re-installing the latest version. 
Thank you for your kind support. I just made a small donation.
Cheers,
Keith

**Comment by Beherith** [comment]
Thanks, its highly appreciated! :)
