### ISSUE TITLE
unitDefID, nil, is neither arm nor cor

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#732]
In logs: The given unitDefID, nil, is neither arm nor cor, only those two are supported at the moment.

P.S I didn't manage spot exact unit what did that. Really spammy message.

Timestamp is 00:31
[20220116_132441_Centerrock Remake 1_105.1.1-739-ga241485 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7877170/20220116_132441_Centerrock.Remake.1_105.1.1-739-ga241485.BAR105.zip)

**Comment by WatchTheFort** [comment]
Debug message from unit shape drawer widget:
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/8243c252938515da2cc57c1961067a438bc12703/luaui/Widgets/gfx_DrawUnitShape_GL4.lua#L237

**Comment by Beherith** [comment]
Fixed, thanks!

**Comment by 6AKU66** [comment]
[t=00:02:51.065000][f=0016338] The given unitDefID, nil, is neither arm nor cor, only those two are supported at the moment
[t=00:02:51.065000][f=0016338] TraceFullEcho:[DrawUnitGL4	]
1: DrawUnitShapeGL4  @LuaUI/Widgets/gfx_drawunitshape_gl4.lua:257 Locals:(unitDefID=nil; px=6526.49609; py=343.602325; pz=2687.53857; rotationY=0; alpha=0.5; teamID=14; teamcoloroverride=0; highlight=0; DrawUnitShapeVBOTable=nil)
2: addUnitShape  @LuaUI/Widgets/unit_ghostradar_gl4.lua:43 Locals:(unitID=28290; unitDefID=nil; px=6526.49609; py=335.602325; pz=2687.53857; rotationY=0; teamID=14; (*temporary)={}[#0])
3: ??
4: pcall  @=[C]:-1 Locals:()
5: UnitLeftLos  @LuaUI/barwidgets.lua:654 Locals:(w={LUAUI_DIRNAME:LuaUI/, VFS:<table>, tostring:<function>, gcinfo:<function>, WeaponDefs:<table>, }[#72]; (*temporary)={}[#0])
6: ??
7:   @=(tail call):-1 Locals:()
[20220118_043954_Coastlines_Dry_V2_105.1.1-739-ga241485 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7887429/20220118_043954_Coastlines_Dry_V2_105.1.1-739-ga241485.BAR105.zip)
