### ISSUE TITLE
Highlight Unit GL4 widget crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#733]
[t=00:19:30.839000][f=0031899] false
[t=00:19:30.839000][f=0031899] Error in SelectionChanged(): [LuaUtils::InstanceDataFromGetData] Non-existing UnitID (20654) is supplied
[t=00:19:30.839000][f=0031899] Removed widget: Highlight Unit GL4
[t=00:19:30.934000][f=0031902] Tried to pop back an invalid unitID, 20654, from, highlightUnitVBOTable, while removing instance, 3784, . Ensure that you remove invalid units from your instance tables
[t=00:19:30.968000][f=0031903] Unable to remove what you wanted in StopHighlightUnitGL4, 3786
[t=00:19:30.968000][f=0031903] Tried to pop back an invalid unitID, 20654, from, highlightUnitVBOTable, while removing instance, 3783, . Ensure that you remove invalid units from your instance tables
[t=00:19:30.968000][f=0031903] false
[t=00:19:30.968000][f=0031903] Error in UnitDestroyed(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [11]
[t=00:19:30.968000][f=0031903] Removed widget: Highlight Selected Units GL4
##########################################################################################
[t=00:09:29.436000][f=0029603] Tried to pop back an invalid unitID, 11620, from, highlightUnitVBOTable, while removing instance, 8432, . Ensure that you remove invalid units from your instance tables
[t=00:09:29.437000][f=0029603] false
[t=00:09:29.437000][f=0029603] Error in SelectionChanged(): [LuaUtils::InstanceDataFromGetData] Non-existing UnitID (11620) is supplied
[t=00:09:29.437000][f=0029603] Removed widget: Highlight Unit GL4
[t=00:09:29.631000][f=0029609] Tried to pop back an invalid unitID, 11620, from, highlightUnitVBOTable, while removing instance, 8427, . Ensure that you remove invalid units from your instance tables
[t=00:09:29.631000][f=0029609] Tried to pop back an invalid unitID, 11620, from, highlightUnitVBOTable, while removing instance, 8442, . Ensure that you remove invalid units from your instance tables
[t=00:09:29.631000][f=0029609] Unable to remove what you wanted in StopHighlightUnitGL4, 8443
[t=00:09:29.631000][f=0029609] false
[t=00:09:29.631000][f=0029609] Error in UnitFinished(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [7]
[t=00:09:29.631000][f=0029609] Removed widget: Under Construction gfx GL4

**Comment by Beherith** [comment]
Hm digging into this one, were you using dev cheats to switch teams? Were you spectating and changing teams?

**Comment by 6AKU66** [comment]
> Hm digging into this one, were you using dev cheats to switch teams? Were you spectating and changing teams?

Pretty sure spectating.

**Comment by 6AKU66** [comment]
Also i got this, i think i was a player.

Tried to pop back an invalid unitID, 22375, from, highlightUnitVBOTable, while removing instance, 93, . Ensure that you remove invalid units from your instance tables
TraceFullEcho:[]
1: popElementInstance  @LuaUI/Widgets/Include/instancevboidtable.lua:221 Locals:(iT={myName:highlightUnitVBOTable, primitiveType:4, VAO:<userdata>, indexVBO:<userdata>, indextoUnitID:<table>, }[#19]; instanceID=93; noUpload=nil; oldElementIndex=2; lastElementIndex=6; lastElementInstanceID=98; iTStep=16; endOffset=80; oldOffset=16; myunitID=22375)
2: StopHighlightUnitGL4  @LuaUI/Widgets/gfx_highlightunit_gl4.lua:195 Locals:(uniqueID=93)
3: removeUnitShape  @LuaUI/Widgets/gui_highlight_selectedunits_gl4.lua:66 Locals:(unitID=31539)
4: ??
5: pcall  @=[C]:-1 Locals:()
6: UnitDestroyed  @LuaUI/barwidgets.lua:654 Locals:(w={LUAUI_DIRNAME:LuaUI/, VFS:<table>, tostring:<function>, gcinfo:<function>, WeaponDefs:<table>, }[#66]; (*temporary)={}[#0])
7: ??
8:   @=(tail call):-1 Locals:((*temporary)=<function>)
