### ISSUE TITLE
Ghost Radar GL4 widget crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#738]
false
Error in Update(): [string "LuaUI/Widgets/unit_ghostradar_gl4.lua"]:147: attempt to index field '?' (a nil value)
Removed widget: Ghost Radar GL4

**Comment by Ruwetuin** [comment]
likely fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/d108f1c7ae7878eecff2e8f05cea6afe2076a1bb
