### ISSUE TITLE
Skirmish games have bad AI positioning - they start in the middle of the map

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/Beyond-All-Reason#74]

**Comment by Beherith** [comment]
I dont know if anything changed, But I set up a skirmish game on a map with 4 start positions, and 3 ais in different allyteams; STAI, DAI and Barbarian. 
On game start I was prompted to choose a start position, I chose the center of the map, but all the AI's started in their correct start position as if 'startpos=fixed was on'  
respective _script.txt : 
[_script.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/5417837/_script.txt)
![screen00000](https://user-images.githubusercontent.com/109391/96758504-2683cb80-13d7-11eb-854d-117dd01f8a26.jpg)

**Comment by totbuae** [comment]
A workaround for this inconvenience is to activate cheats (press <Enter> to open the chat console, type /cheat and press <Enter> again) and then switch control to each one of the skirmish AIs in turn (use /team <id number>) and manually choose their starting point. This should all be done before you click the [Ready] button.

An example placing two AIs would be as follows ("Say:" appears when you press <Enter>, it is not necessary to type this).

Say: /cheat

Say: /team 1
Pick the starting point for the AI corresponding to team 1 just like you would pick the starting point for your own commander. You can also choose the AI's faction; again, just like you would choose your own.

Say: /team 2
Repeat the process.

Say: /team 0
Switch back to controlling your own units.

Press the [Ready] button to start the skirmish.

**Comment by Damgam** [comment]
Known issue. Most of BAR Certified maps have built in startboxes for 2 teams. Everything else will have this issue.

**Comment by Beherith** [comment]
This SHOULD be fixed in chobby for single players, unless you have >2 allyteams.
