### ISSUE TITLE
Calamity don't respect lower reload time gained by XP (most of time)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#741]
Sometimes it's shot twice per turn though.
https://youtu.be/AzCiEBVQWfU

**Comment by sprunk** [comment]
This is because the final reloadspeed depends on both nominal reloadspeed and the spinning animation and the animation doesn't get any faster.

**Comment by 6AKU66** [comment]
Ragnarok somehow ignore that limitation

**Comment by Beherith** [comment]
Probably due to different script for animation

**Comment by KyleAnthonyShepherd** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1564
fixed with this PR, closing
