### ISSUE TITLE
First-launch issues, help me list, find, and fix them

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#742]
Are there any outstanding issues that happen on first-launch clean systems? I'd rather not wipe my whole crap to find out, or if someone knows of a way to launch in isolation (isolation.txt?) then that is fine too.

**Comment by Beherith** [comment]
#762

**Comment by p2004a** [comment]
@Beherith what is the purpose of this issue? It doesn't list any specific issues, and I assume we would run in any at the beggining of this year. I'm closing this as obsolete.
