### ISSUE TITLE
Nanoturrets don't start reclaim with using queue (shift)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#744]
Problem similar to https://github.com/beyond-all-reason/Beyond-All-Reason/issues/681

https://youtu.be/OFiDo-cb6sE

**Comment by SethDGamre** [comment]
appears resolved by hihoman23

**Comment by hihoman23** [comment]
I made a mistake, it's not completely fixed

**Comment by SethDGamre** [comment]
Perhaps also close this issue once this one is resolved https://github.com/beyond-all-reason/Beyond-All-Reason/issues/681
