### ISSUE TITLE
Fusion reactor's light don't obey to simple team colors

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#756]
Need force update fusion reactor's light.
https://youtu.be/wkHjF1WGDpE

**Comment by Beherith** [comment]
This stems from an earlier optimizatoin of the lups fusion balls + lights: previously, they were reset each frame, this being very expensive, they are now only on create. There is no callin for teamcolorchanged, so it is up to the implementer of those accessibility changes to implement this.

**Comment by Ruwetuin** [comment]
should be fixed with https://github.com/beyond-all-reason/Beyond-All-Reason/commit/72a729f9bc6bdf9894d7b4c855b52376983b81a8
