### ISSUE TITLE
Game window freezing after turn off fullscreen

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#760]
https://youtu.be/iQBl9cfm6F0
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7948654/infolog.txt)
Chobby, i tried to do that with skylobby no lack.

**Comment by Beherith** [comment]
Latest engine should mitigate most of these screenrez change bugs, hopefully.

**Comment by 6AKU66** [comment]
I don't know

**Comment by KyleAnthonyShepherd** [comment]
Checkin in again, is this fixed?

**Comment by SethDGamre** [comment]
I wasn't able to reproduce this and the issue is old from many game engine versions ago.
