### ISSUE TITLE
Not possible resign before start of match

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#761]
https://youtu.be/-XqV9K8XyCw

[t=00:00:46.778000][f=-000001] [Game::ClientReadNet] remote skirmish AI "n/a" (ID: 0, Short-Name: "n/a", Version: "n/a") took over control of team 5
[t=00:00:53.424000][f=-000001] Spectator AKU sent invalid team resign
[t=00:01:04.416000][f=-000001] Player 1 sent spoofed NETMSG_STARTPOS with teamID 1

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7948695/infolog.txt)

**Comment by SethDGamre** [comment]
resign button no longer exists before start, !resign doesn nothing before start, a player must resign after starting or exit to lobby before. This issue is resolved.

**Comment by MasterBel2** [comment]
Resign button is technically still accessible through engine quitmenu, and if a user uses this button, they are not resigned, but they can no longer adjust starting placement in pre-game.
I cant remember if quitmenu is bindable by default - if not, this is probably very low priority

**Comment by SethDGamre** [comment]
Review requested to ask if there's any objections to closing this as unplanned.

**Comment by WatchTheFort** [comment]
Closing as resigning before game start is not a planned feature

**Comment by MasterBel2** [comment]
@WatchTheFort @SethDGamre afaict this was a bug report, not a feature request, so it doesn’t make sense to use the “unplanned” reason for closing.

**Comment by sprunk** [comment]
Fixing the bug is not planned tho
