### ISSUE TITLE
Symbols at screen if springsettings.cfg was deleted previously

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#762]
![2022-01-27 11-47-18 mp4_snapshot_00 26_ 2022 01 27_11 57 15](https://user-images.githubusercontent.com/89547444/151325522-b129930b-8e09-4e82-8185-c02a51986853.jpg)

https://youtu.be/SGs4dx0kdsk

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7949032/infolog.txt)

Lobby: skylobby, chobby seems not affected.
Second start of game fixing that.

**Comment by Beherith** [comment]
Oooh, this is a good one, needs to be filed along other 'first start bugs'

**Comment by Ruwetuin** [comment]
on luaintro BAR makes sure:
Spring.SetConfigInt("MaxTextureAtlasSizeX", 8192)
Spring.SetConfigInt("MaxTextureAtlasSizeY", 8192)

maybe chobby should do this as well (before bar gets loaded)

**Comment by Ruwetuin** [comment]
chobby indeed was setting 4096

fixed in https://github.com/beyond-all-reason/BYAR-Chobby/commit/64a9787759680101446aa3dec7b23b0c8087ca18
