### ISSUE TITLE
Cortex nuke launching duds

### ISSUE THREAD

**Issue by mkow** [beyond-all-reason/Beyond-All-Reason#765]
Please take a look at https://www.beyondallreason.info/replays?gameId=eefcf26160b686e3a40f73f186efe134 around 25:00, I play as `[T0]Redford`. I issued an attack with my nuke at a player without anti, the launcher opened, then nothing happened and then it just closed 🤨 
I'm pretty sure that I didn't issue the "stop" command (is it even possible to stop nuke mid-launch?). Fortunately it didn't eat the missile, but I changed the target thinking it was anti and I just missed the in-air explosion.

**Comment by 6AKU66** [comment]
"is it even possible to stop nuke mid-launch?"

Yes, it's possible.
