### ISSUE TITLE
Ghost commander appear after start of match (Pregame UI bug)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#767]
![Ghost commander appear after start of match](https://user-images.githubusercontent.com/89547444/151541908-4122f480-fe51-40d7-a6e6-73ea6237393c.jpg)

This is happening while watching replays, ghost commander appering after start of game.
https://youtu.be/a6PUwomS2rM
https://www.beyondallreason.info/replays?gameId=eefcf26160b686e3a40f73f186efe134

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/045b52ef3073e06537ea2bfb4987db2875edfad5
