### ISSUE TITLE
Building flickering if finished too fast (Show Builder Queue widget bug)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#769]
![изображение_2022-01-30_153530](https://user-images.githubusercontent.com/89547444/151699872-69f43044-4367-4497-b591-d9018cdc2e71.png)

[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7965871/infolog.txt)

https://www.youtube.com/watch?v=mtiyFYj1pGI

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/ddce692f060f10c7f7f34d60ffea89ef65c6c72c
