### ISSUE TITLE
build queue ghost staying on top of an already built unit 

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/Beyond-All-Reason#77]
Not sure how to recreate, but it seems to happen often with a queue done with the initial queue widget. 

Attached a screenshot

the ghost disappears after a while, eg. when something is built next to that building. 
![2020-09-20 12_44_13-Beyond All Reason test-14208-a3e41b3 (Spring 104 0 1-1553-gd3c0012 maintenance)-min](https://user-images.githubusercontent.com/29601271/93709675-748b8200-fb40-11ea-9e41-d708b7427cb9.png)

**Comment by Ruwetuin** [comment]
i bet it is cleared when you give a cmd to the commander without shift, thus removing the queue

**Comment by Ruwetuin** [comment]
i guess the initial queue hasnt got the right grid applied, then there is a little offset in position and thus not clearing the ghost cause the positions dont match

**Comment by Ruwetuin** [comment]
is this still happening?
