### ISSUE TITLE
Metal spots font visibility at high resolutions bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#770]
![изображение_2022-01-30_155548](https://user-images.githubusercontent.com/89547444/151700602-9681d78f-2b48-4866-ae94-1b24cf1138bb.png)
https://www.youtube.com/watch?v=dyTwhhhc_KU
[Font] Warning: Texture limit reached! (try to reduce the font size and/or outlinewidth)

**Comment by lhog** [comment]
TODO: Bump up `CFontTexture::atlasAlloc` dims.

**Comment by Ruwetuin** [comment]
i limited fonsize scaling for this widget in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/527e18d69280e6fe49162fc3a187c121cd3787bc
