### ISSUE TITLE
Ubuntu appimage installation error: Error in curl Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by keithphw** [beyond-all-reason/Beyond-All-Reason#772]
Hi,
Installation isn't working for me on ubuntu 18.04 using the appimage installer. 
I ran 'apt-get install ca-certificates' but it reported that it was already up to date.
I also tried running as root user with './Beyond-All-Reason-1.1351.0.AppImage --no-sandbox'  and it produced the same error.
Thanks for your help.
Cheers,
Keith

[Mon Jan 31 2022 22:34:11 GMT+1100 (Australian Eastern Daylight Time) info] Including extension: ././exts//random_background.js...

[Mon Jan 31 2022 22:34:11 GMT+1100 (Australian Eastern Daylight Time) info] Including extension: ././exts//videoplayer.js...

[Mon Jan 31 2022 22:34:11 GMT+1100 (Australian Eastern Daylight Time) error] Failed to load exception: TypeError: Cannot set property 'src' of null

[Mon Jan 31 2022 22:34:14 GMT+1100 (Australian Eastern Daylight Time) info] Step: {
    "name": "launcher_update"
}

[Mon Jan 31 2022 22:34:14 GMT+1100 (Australian Eastern Daylight Time) info] Checking for launcher update

[Mon Jan 31 2022 22:34:14 GMT+1100 (Australian Eastern Daylight Time) info] Checking for update

[Mon Jan 31 2022 22:34:16 GMT+1100 (Australian Eastern Daylight Time) info] Update for version 1.1351.0 is not available (latest version: 1.1351.0, downgrade is disallowed).

[Mon Jan 31 2022 22:34:16 GMT+1100 (Australian Eastern Daylight Time) info] No update available.

[Mon Jan 31 2022 22:34:16 GMT+1100 (Australian Eastern Daylight Time) info] Step: {
    "name": "game",
    "item": "byar:test"
}

[Mon Jan 31 2022 22:34:17 GMT+1100 (Australian Eastern Daylight Time) info] Download started: byar:test

[Mon Jan 31 2022 22:34:17 GMT+1100 (Australian Eastern Daylight Time) info] pr-downloader 0.7-603-g31a5070 (linux64)

[Mon Jan 31 2022 22:34:17 GMT+1100 (Australian Eastern Daylight Time) warn] [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:468:processMessages():CURL error(1:77): Problem with the SSL CA cert (path? access rights?) 0 (https://repos.springrts.com/repos.gz)

[Mon Jan 31 2022 22:34:19 GMT+1100 (Australian Eastern Daylight Time) info] [Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:188:setWritePath():Using filesystem-writepath: /home/megan/Documents/Beyond All Reason
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:178:DownloadSetConfig():Free disk space: 431985 MB
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:62:DumpVersion():libcurl 7.73.0 OpenSSL/1.1.1i
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'openssl' (ID: 1)

[Mon Jan 31 2022 22:34:19 GMT+1100 (Australian Eastern Daylight Time) warn] [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Rapid/RapidDownloader.cpp:189:ParseFD():Broken /home/megan/Documents/Beyond All Reason/rapid/repos.springrts.com/repos.gz: 0

[Mon Jan 31 2022 22:34:19 GMT+1100 (Australian Eastern Daylight Time) warn] [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

[Mon Jan 31 2022 22:34:19 GMT+1100 (Australian Eastern Daylight Time) error] byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

PS: Thanks for the hard work of the devs and everyone who has made this a fantastic game. Incredible work

**Comment by lhog** [comment]
So, do you have the file in `/etc/ssl/certs/ca-certificates.crt` ? Is it accessible by your user account?

**Comment by keithphw** [comment]
Hi,
Thanks for your reply. 
Yes it's a default ubuntu 18 installation and the file exists and is readable and writable by the root user:
ls -l /etc/ssl/certs/ca-certificates.crt
-rw-r--r-- 1 root root 0 Oct  7 19:38 /etc/ssl/certs/ca-certificates.crt

I tried doing 'chmod 777 /etc/ssl/certs/ca-certificates.crt' and then starting the installer as root with './Beyond-All-Reason-1.1351.0.AppImage --no-sandbox' but it gave similar errors:



Log file: /root/Beyond All Reason/spring-launcher.log
Beyond-All-Reason - 1.1351.0
App path: /tmp/.mount_BeyondYDDPzQ/resources/app.asar
pr-downloader path: /tmp/.mount_BeyondYDDPzQ/bin/pr-downloader
Write path: /root/Beyond All Reason
Launcher configs:
[
    {
        "package": {
            "platform": "linux",
            "portable": false,
            "display": "Alpha",
            "id": "manual-linux"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": false,
        "no_start_script": true,
        "load_dev_exts": false,
        "route_prd_to_nextgen": false,
        "github_log_repo": null,
        "config_url": null,
        "silent": true,
        "downloads": {
            "games": [
                "byar:test",
                "chobby:test",
                "byar-chobby:test"
            ],
            "maps": [],
            "engines": [],
            "resources": [
                {
                    "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-739-ga241485/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable.7z",
                    "destination": "engine/105.1.1-739-ga241485 bar",
                    "extract": true
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/altored_divide_bar_remake_1.55.sd7",
                    "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/boulder_beach_v1.sd7",
                    "destination": "maps/boulder_beach_v1.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/dsdr_4.0.sd7",
                    "destination": "maps/dsdr_4.0.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/quicksilver_remake_1.24.sd7",
                    "destination": "maps/quicksilver_remake_1.24.sd7",
                    "extract": false
                },
                {
                    "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/trefoil_remake_2.20.sd7",
                    "destination": "maps/trefoil_remake_2.20.sd7",
                    "extract": false
                }
            ],
            "nextgen": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "rapid://byar-chobby:test"
            ],
            "engine": "105.1.1-739-ga241485 bar"
        },
        "title": "Beyond All Reason"
    },
    {
        "package": {
            "platform": "linux",
            "portable": false,
            "display": "Dev Lobby",
            "id": "dev-lobby-linux"
        },
        "isolation": true,
        "auto_download": false,
        "auto_start": false,
        "no_downloads": true,
        "no_start_script": true,
        "load_dev_exts": false,
        "route_prd_to_nextgen": false,
        "github_log_repo": null,
        "config_url": null,
        "silent": true,
        "downloads": {
            "games": [],
            "maps": [],
            "engines": [],
            "resources": [
                {
                    "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-739-ga241485/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable.7z",
                    "destination": "engine/105.1.1-739-ga241485 bar",
                    "extract": true
                }
            ],
            "nextgen": []
        },
        "launch": {
            "start_args": [
                "--menu",
                "BYAR Chobby $VERSION"
            ],
            "engine": "105.1.1-739-ga241485 bar"
        },
        "title": "Beyond All Reason"
    }
]
Default config:
{
    "package": {
        "platform": "linux",
        "portable": false,
        "display": "Alpha",
        "id": "manual-linux"
    },
    "isolation": true,
    "auto_download": false,
    "auto_start": false,
    "no_downloads": false,
    "no_start_script": true,
    "load_dev_exts": false,
    "route_prd_to_nextgen": false,
    "github_log_repo": null,
    "config_url": null,
    "silent": true,
    "downloads": {
        "games": [
            "byar:test",
            "chobby:test",
            "byar-chobby:test"
        ],
        "maps": [],
        "engines": [],
        "resources": [
            {
                "url": "https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR105%7D105.1.1-739-ga241485/spring_bar_.BAR105.105.1.1-739-ga241485_linux-64-minimal-portable.7z",
                "destination": "engine/105.1.1-739-ga241485 bar",
                "extract": true
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/altored_divide_bar_remake_1.55.sd7",
                "destination": "maps/altored_divide_bar_remake_1.55.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/boulder_beach_v1.sd7",
                "destination": "maps/boulder_beach_v1.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/dsdr_4.0.sd7",
                "destination": "maps/dsdr_4.0.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/quicksilver_remake_1.24.sd7",
                "destination": "maps/quicksilver_remake_1.24.sd7",
                "extract": false
            },
            {
                "url": "https://github.com/beyond-all-reason/Maps/releases/download/1.0/trefoil_remake_2.20.sd7",
                "destination": "maps/trefoil_remake_2.20.sd7",
                "extract": false
            }
        ],
        "nextgen": []
    },
    "launch": {
        "start_args": [
            "--menu",
            "rapid://byar-chobby:test"
        ],
        "engine": "105.1.1-739-ga241485 bar"
    },
    "title": "Beyond All Reason"
}
(node:13378) DeprecationWarning: file property is deprecated and will be removed in v5.
bridge: listening on port: 127.0.0.1:43785
Including extension: ./exts/bridge_download.js...
Including extension: ./exts/dev_extension_loader.js...
Including extension: ./exts/map_parser.js...
Including extension: ./exts/open_file.js...
Including extension: ./exts/replay_handler.js...
Including extension: ./exts/start_new_spring_handler.js...
Including extension: ./exts/track_files.js...
Including extension: ./exts/upload_log.js...
(node:13378) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:13378) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(beyond-all-reason:13378): libappindicator-WARNING **: 16:40:24.093: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(beyond-all-reason:13378): LIBDBUSMENU-GLIB-WARNING **: 16:40:24.093: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
Including extension: ././exts//random_background.js...
Including extension: ././exts//videoplayer.js...
Failed to load exception: TypeError: Cannot set property 'src' of null
Step: {
    "name": "launcher_update"
}
Checking for launcher update
Checking for update
Update for version 1.1351.0 is not available (latest version: 1.1351.0, downgrade is disallowed).
No update available.
Step: {
    "name": "game",
    "item": "byar:test"
}
Download started: byar:test
pr-downloader 0.7-603-g31a5070 (linux64)

[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:468:processMessages():CURL error(1:77): Problem with the SSL CA cert (path? access rights?) 0 (https://repos.springrts.com/repos.gz)

[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/FileSystem/FileSystem.cpp:188:setWritePath():Using filesystem-writepath: /root/Beyond All Reason
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/pr-downloader.cpp:178:DownloadSetConfig():Free disk space: 431530 MB
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:62:DumpVersion():libcurl 7.73.0 OpenSSL/1.1.1i
[Info] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/CurlWrapper.cpp:42:GetTLSBackend():SSL backend #0: 'openssl' (ID: 1)


[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Rapid/RapidDownloader.cpp:189:ParseFD():Broken /root/Beyond All Reason/rapid/repos.springrts.com/repos.gz: 0

[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs)
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:196:search():Error downloading https://springfiles.springrts.com/json.php?category=game&springname=byar:test 
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:196:main():No game found for byar:test
[Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/main.cpp:241:main():Error occurred while downloading: 1

**Comment by lhog** [comment]
Try and follow suggestions here: https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url

**Comment by keithphw** [comment]
Thanks for the suggestions. I tried the top solution in https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url
mkdir -p /etc/pki/tls/certs
cp /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

This had no effect on the error unfortunately. But that might be expected since the program only looks for the file ca-certificates.crt in /etc/ssl/certs/

One thing I noticed just today is that the file ca-certificates.crt has **zero size**. Not sure if this is a problem or not? This was the output running apt-get install ca-certificates which appears to show everything updated, so a bit strange that the file is empty?
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20210119~18.04.2).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-161 linux-headers-4.15.0-161-generic
  linux-image-4.15.0-161-generic linux-modules-4.15.0-161-generic
  linux-modules-extra-4.15.0-161-generic shim
Use 'apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 19 not to upgrade.


I think I'll give up at this stage and just continue having fun with the windows version of the game until it's out of alpha and beta. Thanks very much for your help lhog.

**Comment by lhog** [comment]
> One thing I noticed just today is that the file ca-certificates.crt has zero size

It shouldn't be empty.
Do `sudo apt install --reinstall ca-certificates`. The file should contain a plenty of public keys.

**Comment by keithphw** [comment]
Thank you lhog, that fixed it! 
Very kind of you to help me with this. 
The program updated successfully and I reached the 'start' button.

Unfortunately I ran into another error, but I'll investigate further and if I can't resolve it I'll post up another bug report. 
Thanks again.
