### ISSUE TITLE
Empty AllyTeam (Startbox without a team) causes victory condition to not trigger

### ISSUE THREAD

**Issue by Damgam** [beyond-all-reason/Beyond-All-Reason#778]
The 0 units allyteam isn't considered dead i suppose.

**Comment by 6AKU66** [comment]
Duplicate of https://github.com/beyond-all-reason/Beyond-All-Reason/issues/563?

**Comment by sprunk** [comment]
Duplicate of #563

**Comment by 6AKU66** [comment]
P.S I will rename my ticket, Damgam's title more good than mine.
