### ISSUE TITLE
Corapt3 model AO plate bug

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#784]
![изображение_2022-02-11_234814](https://user-images.githubusercontent.com/89547444/153667881-e8148292-6f2f-4063-abbf-464a6e9cd872.png)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/bde4cf59174ff582bb1c4424cc94c690b98b73cf
