### ISSUE TITLE
Radar not showing 1/4 of the screen on mini map when using fog of war disabled

### ISSUE THREAD

**Issue by Logicaster** [beyond-all-reason/Beyond-All-Reason#787]
Radar not showing 1/4 of the screen on mini map when using fog of war disabled
Recently, about a week ago both friends and foes units on the mini map stopped being shown. Some units are being shown but most of them on the screen are not being shown.

**Comment by 6AKU66** [comment]
It's looks like this?
https://cdn.discordapp.com/attachments/549282926596980738/941076529268551690/2022-02-09T180115444401420-0300.png

**Comment by 6AKU66** [comment]
It's looks like this?
![2022-02-09T180115444401420-0300](https://user-images.githubusercontent.com/89547444/153772035-385cd640-0827-44ea-8943-60c531c3a644.png)

**Comment by Logicaster** [comment]
Yes this is the exact problem that is going on

**Comment by KyleAnthonyShepherd** [comment]
Due to above comment, closing issue
