### ISSUE TITLE
Loot box option not working with 2 human players or more on multiplayer

### ISSUE THREAD

**Issue by Logicaster** [beyond-all-reason/Beyond-All-Reason#788]
Loot box option not working with 2 human players or more on multiplayer
Recently, about a week ago the loot box button stopped working on multiplayer with 2 human players and 1 or two Barbarian AI and during the entire game (about 45 minutes) no loot boxes spawned.

**Comment by SethDGamre** [comment]
very old issue and from my testing has been resolved
