### ISSUE TITLE
Reclaiming paralyzed metal storages leads to negative metal values

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#789]
1. Paralyze metal storage.
2. Reclaim paralyzed metal storage.

https://youtu.be/lRA0sXNHpcA

P.S Energy storages immune to that.
![изображение_2022-02-14_032928](https://user-images.githubusercontent.com/89547444/153782352-2f6c14d9-c7ac-416a-9096-ca3c1356a662.png)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f2a91426b51307037ea006b10dcbba88bd29a0cd

**Comment by icexuick** [comment]
That was quick! Nice find!
