### ISSUE TITLE
Paralyzed seconds counter goes negative (2)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#791]
Paralyzing building structure lead to paralyze counter goes negative
https://youtu.be/lC4HhDeArBk
![изображение_2022-02-15_072532](https://user-images.githubusercontent.com/89547444/153992427-760f1fad-86da-4294-b29f-59a847c6a71c.png)

**Comment by 6AKU66** [comment]
@Born2Crawl I stole your title

**Comment by Born2Crawl** [comment]
We had a similar issue before, when paralysing a unit and then carrying it with a transport, it did not unparalyze while being carried, and the counter went to zero and then negative.

**Comment by Beherith** [comment]
Healthbars GL4 should not have this bug any more, we will be switching to them soon.
