### ISSUE TITLE
Scavenger boss stop walking to D-gun's target

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#793]
https://youtu.be/pls4d3Nvc1Q
https://www.beyondallreason.info/replays?gameId=97ad0a628d66c17fcd1fd85146107bad

**Comment by Damgam** [comment]
Lol that's new.

**Comment by icexuick** [comment]
I just watched review and yes, was weird.
He had order of DGUN on enemy, too far away.

**Comment by SethDGamre** [comment]
The boss has since been replaced this issue is outdated
