### ISSUE TITLE
Projection highlighting not working for paralyzed objects

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#794]
https://youtu.be/Z6IdNV8qs-A
![Снимок](https://user-images.githubusercontent.com/89547444/153999949-cc963fcd-0397-463d-bd15-fef6e403c4c7.JPG)
![Снимок2](https://user-images.githubusercontent.com/89547444/153999953-696a45b9-8e6e-4688-8675-e76c61922cf5.JPG)

**Comment by Beherith** [comment]
fixed, thx for reporitng
