### ISSUE TITLE
RenderUnitDestroyed not getting called for all widgets

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#796]

**Comment by Beherith** [comment]
its called for airjets, but none of the others.

**Comment by SethDGamre** [comment]
Is this still an issue? Is there a communicable way for somebody else to be able to fix this?

**Comment by saurtron** [comment]
I can't really reproduce it, although don't see many widgets using this, I tried adding the callin to a few ones and seems to work fine.

What I noticed is the unit_death_animations.lua gadget doesn't get it, but I think it's because it has the handler on the synced part and it's an unsynced message (I think so, but not totally sure about the internal mechanisms).

**Comment by Beherith** [comment]
All effects that depend on this have been moved to use the unit tracker api, making this one effectively moot

**Comment by saurtron** [comment]
In that case maybe uses of RenderUnitDestroyed should be removed? cus_gl4, gfx_airjets_gl4 and unit_death_animations still using.

Anyways, whatever I think it works anyways, but unit_death_animations is using it wrong, that use should be either fixed or removed imo, to cleanup the code.

**Comment by Beherith** [comment]
> In that case maybe uses of RenderUnitDestroyed should be removed? cus_gl4, gfx_airjets_gl4 and unit_death_animations still using it.
> 
> Anyways, whatever, I think it works anyways, but unit_death_animations is using it wrong, that use should be either fixed or removed imo, to cleanup the code.

To provide some context: when a unit dies, then unit destroyed gets called for it. However, crashing aircraft and units running their death animations are dead, but still get drawn, hence renderunitdestroyed.

**Comment by Beherith** [comment]
Dying raptors and fighter testing air fighters show this

**Comment by saurtron** [comment]
I mean,  unit_death_animations has the handler on the synced part and it's an unsynced message so I think it doesn't get called . It doesn't have a visible effect because it just uses that to free the key from the array.
