### ISSUE TITLE
Data in info (gui_info) is not updating

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#798]
https://youtu.be/JMgWMy6mW-Y
![изображение_2022-02-18_111051](https://user-images.githubusercontent.com/89547444/154643541-cbc0576d-40a1-4f0d-ba91-8b7ff26d0b18.png)

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/5331286a7eb1f595a178bb08536a138ca2d680e7
