### ISSUE TITLE
Fusion ball visible beyond of LOS

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#799]
Reproduce:
1. Team 1 build advanced fusion.
2. Team 2 command units to scout reactor (reach LOS).
3. Team 3 now can see fusion balls via map beyond LOS.
https://youtu.be/MRWYe7HGE2I

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/37c2d657e872e64bc39df8af1bcb6ffe555920ac
