### ISSUE TITLE
Projections of metal extractors/geothermal powerplant can lead to low FPS

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#801]
Example with metal extractor
https://youtu.be/UDOWcyN6qlg

Example with geothermal powerplant
https://youtu.be/gc4yG4R8Hh4

![Projections of powerplant mp4_snapshot_00 02_ 2022 05 21_15 57 11](https://user-images.githubusercontent.com/89547444/169652570-93b54b7c-5a07-4cb8-b876-65fe50433596.jpg)
![Projections of powerplant mp4_snapshot_00 07_ 2022 05 21_15 57 21](https://user-images.githubusercontent.com/89547444/169652578-cd4bbb03-f0f3-4dc6-afef-e3c0275ca72c.jpg)

![Снимок](https://user-images.githubusercontent.com/89547444/169652890-f8cc215a-7b10-4183-a2b8-0fe8927def64.PNG)
![Снимок2](https://user-images.githubusercontent.com/89547444/169652892-6a7fbc22-aea5-429c-a190-31d479728467.PNG)

150 FPS to 14 FPS with 30 constuction units when projecting powerplant.

**Comment by Beherith** [comment]
With sane numbers of constructors (100) it was ok, i'm not tracking down bugs with /given 1000 cons :D

**Comment by 6AKU66** [comment]
With 100 FPS dropping from 220 to 64

**Comment by 6AKU66** [comment]
I updated this thread @Beherith

**Comment by Ruwetuin** [comment]
this has been fixed a few months ago
