### ISSUE TITLE
Sometimes units have no walk animation

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#802]
Reproduce steps unknown.

Timestamp 34:08. Bugged unit Archangel.
https://youtu.be/dKJ6Z6CjMIs

[20220212_201810_Archsimkats_Valley_V1_105.1.1-861-ge8bf8a9 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8095893/20220212_201810_Archsimkats_Valley_V1_105.1.1-861-ge8bf8a9.BAR105.zip)

![Снимок](https://user-images.githubusercontent.com/89547444/154655894-90942752-349c-428f-b57f-fa568b833328.JPG)

**Comment by Born2Crawl** [comment]
I saw this, too. However, it happens with other unit types as well, ages ago I reported a constructor that lost his animation after being hit, and then healed and recovered later.

**Comment by Born2Crawl** [comment]
https://youtu.be/0TJmJKfW-JQ

**Comment by Beherith** [comment]
fixed armaak, the armck one is due to a race condition, where a unit gets multiple start and stopmoving calls on the same frame, not really fixable, but extremely rare.
