### ISSUE TITLE
Commander can trap itself in building

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#803]
Reproduce:
1. Start game as player.
2. After commander spawned pick building and start build it on itself.

https://youtu.be/4v4V7mEjqHU

**Comment by 6AKU66** [comment]
I blame IceXuick

**Comment by Beherith** [comment]
Note, this is reproducible with old engines down to 104 1977 with latest BAR
Latest barengine with BA10 does not repro bug.

**Comment by Beherith** [comment]
In fact, BAR 18132 doesnt repro bug either

**Comment by Beherith** [comment]
Its caused directly by this: 
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/34fd6642829ee0dae83aed7589bd341c62d2c1ff/luarules/gadgets/game_initial_spawn.lua#L285

@Ruwetuin  anything against removeing the movectrl stuff?

**Comment by Beherith** [comment]
Removing movectrl fixes it. The bug can be seen and reproduced by not moving the commander at start and queueing up a solar above it. The dollars yard map will not become yellow until the unit moves.

**Comment by WatchTheFort** [comment]
That added for the Commander warp-in effect

**Comment by Beherith** [comment]
> That was added for the Commander warp-in effect

Yes, I know that, but why was it added? What does it achieve besides not allowing the comm to move for 3 secs?

**Comment by Damgam** [comment]
> Yes, I know that, but why was it added? What does it achieve besides not allowing the comm to move for 3 secs?
Exacly the reason i added it... to not let it move for 3 seconds.

**Comment by Beherith** [comment]
Ok ill remove movectrl tomorrow then

**Comment by badosu** [comment]
@Beherith Do you have an idea if this movectrl change fixes it without negative side effects? Otherwise the PR above fixes this in buildmenu itself (for pregame phase).
