### ISSUE TITLE
Grounded bombers ignore area attack command

### ISSUE THREAD

**Issue by BAR-eL-bArTo** [beyond-all-reason/Beyond-All-Reason#805]
I've only tried this with T1 bombers and don't currently know if this affects any other bombers.

## Repro Steps:

- Select a T1 bomber that is not in flight.
- Click on the `Area Attack` button in the UI.
- Click and drag to expand the attack area somewhere on the map.
- The bomber will ignore the command.

This also occurs if selecting multiple bombers. If any of them are not inflight already they will ignore the command. Just adding this info here in case it turns out to be useful.

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/aaa3f9bf-db97-4dcd-b21c-5b65915cfe4c)
Can confirm this issue.
Although I barely know what the Area Attack ui button does, or what it is supposed to do

**Comment by SethDGamre** [comment]
yep, still exists

**Comment by SethDGamre** [comment]
Looks like spunk thinks this to be an engine issue. Looks like it to me as well.
