### ISSUE TITLE
Sim:Gameframe unknown source of lag 

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#807]
Timestamp 11:20 and 12:45 
https://youtu.be/6MPqPLlSrtY
[20220220_141022_Flats and Forests Remake 1_105.1.1-861-ge8bf8a9 BAR105.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8105905/20220220_141022_Flats.and.Forests.Remake.1_105.1.1-861-ge8bf8a9.BAR105.zip)

**Comment by Beherith** [comment]
The period of that seems to be one second. To see if lua gadgets are calling this, type ```/luarules profile```, its very useful compared to just alt+b view only.

**Comment by 6AKU66** [comment]
Oh wow, i didn't knew about this. I knew only about widget profiler.

**Comment by 6AKU66** [comment]
Fisrt candidate for lag
![Снимок](https://user-images.githubusercontent.com/89547444/154935444-f2a70181-020b-41cf-b625-4590ebab712b.PNG)

**Comment by Damgam** [comment]
What the fuck

**Comment by Beherith** [comment]
Yes, indeed it was a huge drop of rezzers getting tons of orders for scavs. Maybe @Damgam wants to investigate? But imo its ok-ish

**Comment by Beherith** [comment]
![screen00025](https://user-images.githubusercontent.com/109391/154936415-2dbf4513-e96c-4498-a687-c17ff1dff305.jpg)
![screen00026](https://user-images.githubusercontent.com/109391/154936423-7c6c6471-1c73-4cae-bae3-631c930b623f.jpg)

**Comment by Damgam** [comment]
Well, rezzers won't roam like wild on the back anymore so there's that.

**Comment by 6AKU66** [comment]
12:45 seems have another issue, i found that on 11:00-12:00

**Comment by Beherith** [comment]
2% is fine

**Comment by Damgam** [comment]
> 2% is fine

kBps though

**Comment by sprunk** [comment]
maybe add a `collectgarbage()` inside the gadget so the 2% also measures the GC load

**Comment by SethDGamre** [comment]
Very old and resolved issue.
