### ISSUE TITLE
Paralyze Effect widget crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#811]
Widget crashed when i started spectate for player

1: popElementInstance  @LuaUI/Widgets/Include/instancevboidtable.lua:269 Locals:(iT={myName:paralyzedDrawUnitVBOTable, primitiveType:4, VAO:<userdata>, numZombies:1, indexVBO:<userdata>, }[#23]; instanceID=17304; noUpload=nil; oldElementIndex=569; lastElementIndex=570; lastElementInstanceID=25252; iTStep=12; endOffset=6828; oldOffset=6816; myunitID=25252)
2: StopDrawParalyzedUnitGL4  @LuaUI/Widgets/gfx_paralyze_effect.lua:366 Locals:(unitID=17304)
3: ??
4: pcall  @=[C]:-1 Locals:()
5: UnitLeftLos  @LuaUI/barwidgets.lua:611 Locals:(w={uploadAllElements:<function>, LUAUI_DIRNAME:LuaUI/, VFS:<table>, tostring:<function>, gcinfo:<function>, }[#78]; (*temporary)={}[#0])
6: ??
7:   @=(tail call):-1 Locals:()

[t=00:21:21.431000][f=0034626] false
[t=00:21:21.431000][f=0034626] Error in GameFrame(): [string "LuaUI/Widgets/gfx_paralyze_effect.lua"]:443: gl.SetUnitBufferUniforms() Invalid Unit id (11023)
[t=00:21:21.431000][f=0034626] Removed widget: Paralyze Effect

**Comment by Beherith** [comment]
It crashed when you entered spectator mode? Or when you were using the playerTV camera and went from fullview spectator to spectating only that player?

**Comment by 6AKU66** [comment]
I was watching replay and it's happened when i double click on player's nickname.
