### ISSUE TITLE
Building wire-frame model have wrong color (simple team colors)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#814]
Steps to reproduce:
1. Select player
2. Enable simple team colors
3. Pick enemy team
4. Building wire-frame model have wrong color

![изображение_2022-02-21_084952](https://user-images.githubusercontent.com/89547444/154896871-9176b60b-6e69-4fcb-ae69-ee7602eb317a.png)

https://youtu.be/Y0wXgtNCo4Y

**Comment by Beherith** [comment]
See #815

**Comment by SethDGamre** [comment]
Building shaders have been completely reworked, being that this issue is also old on top of that I think it's safe to close it for now and wait for other bug reports.
