### ISSUE TITLE
Fusion balls missing at enabling simple team colors

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#816]
1. Make sure builed advanced fusion reactor exist
2. Enable simple team colors
3. Fusion balls gone
![изображение_2022-02-21_090003](https://user-images.githubusercontent.com/89547444/154897826-0fd23c4c-a901-44f3-9d8d-6df9aeb54505.png)

https://youtu.be/7XhrPq2Lm7E

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/5136f6de6cb6193f3025d2662b30a3dcac19622d
