### ISSUE TITLE
Build queue via space+alt+shift may cause ghost building

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#817]
https://youtu.be/1hXJdvAhZwE

**Comment by SethDGamre** [comment]
still exists
![image](https://github.com/user-attachments/assets/1f5e809d-4cd9-48d4-9c33-b4caad721abd)
not as commonly, but I still get ghost structures sometimes

**Comment by SethDGamre** [comment]
Unclear what is causing this bug or how to proceed. Requesting peer review.

**Comment by Ruwetuin** [comment]
probably that last convertor couldnt be build due to ground height changes and was dropped.... but ofc the ghost should also dissapear when no builder has it in their queue anymore

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/049555f893a55be489aca0e730028858bce87ea8
