### ISSUE TITLE
Gui_healthbars_gl4 nil value

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#821]
Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=ProjectileCreatedReloadHB trace=[Internal Lua error: Call failure] [string "LuaUI/Widgets/gui_healthbars_gl4.lua"]:1325: attempt to perform arithmetic on field '?' (a nil value)

I was a spectator

**Comment by Sovgut** [comment]
i think this is fixed

https://github.com/beyond-all-reason/Beyond-All-Reason/commit/cc9d7747f95c766f2e7a686e0cb66cab5b840a33
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/c92bc12e70be826ff523e39d88102add01abc143
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/cf85d0d620aea45569226d083aa16d2a7d5a57a1

**Comment by 6AKU66** [comment]
I don't think so, i'm on recent version 19006

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/987e3a9d7140a4c730945552ae59cff59766a556
