### ISSUE TITLE
Highlight GL4 widgets crash

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#823]
[t=00:06:28.868000][f=0035373] [SpecTeamAction] local client 5 now spectating team 0 and allyteam 0
[t=00:06:29.068000][f=0035380] Invalid unitID, 776, at, 15, during resizing, highlightUnitVBOTable
[t=00:06:29.074000][f=0035380] Error in Shutdown()
[t=00:06:29.074000][f=0035380] false
[t=00:06:29.074000][f=0035380] Error in Shutdown(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [65]
[t=00:06:29.074000][f=0035380] Removed widget: Highlight Selected Units GL4
[t=00:06:29.074000][f=0035380] false
[t=00:06:29.074000][f=0035380] Error in SelectionChanged(): [LuaUtils::GetDrawIndicesImpl] Non-existing UnitID (776) is supplied
[t=00:06:29.074000][f=0035380] Removed widget: Highlight Selected Units GL4
[t=00:06:29.152000][f=0035382] Unable to remove what you wanted in StopHighlightUnitGL4, 7289
[t=00:06:29.152000][f=0035382] false
[t=00:06:29.152000][f=0035382] Error in Update(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [95]
[t=00:06:29.153000][f=0035382] Removed widget: Highlight Unit GL4
[t=00:06:29.222000][f=0035385] Error in Shutdown()
[t=00:06:29.222000][f=0035385] false
[t=00:06:29.222000][f=0035385] Error in Shutdown(): [string "LuaUI/Widgets/Include/instancevboidtable.lu..."]:319: table index is nil
[t=00:06:29.222000][f=0035385] Removed widget: Under Construction gfx GL4
[t=00:06:29.222000][f=0035385] false

Is this same?
[t=00:06:53.912000][f=0011974] Speed set to 1.5 [AKU]
[t=00:06:59.052000][f=0012206] Invalid unitID, 21452, at, 1, during resizing, highlightUnitVBOTable
[t=00:06:59.052000][f=0012206] Error in Shutdown()
[t=00:06:59.052000][f=0012206] Error in Shutdown(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [22]
[t=00:06:59.052000][f=0012206] Removed widget: Highlight Unit GL4
[t=00:06:59.052000][f=0012206] Error in Update(): [LuaUtils::GetDrawIndicesImpl] Non-existing UnitID (21452) is supplied
[t=00:06:59.052000][f=0012206] Removed widget: Highlight Unit GL4
[t=00:06:59.406000][f=0012222] Unable to remove what you wanted in StopHighlightUnitGL4, 7026
[t=00:06:59.406000][f=0012222] Error in UnitFinished(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [22]
[t=00:06:59.406000][f=0012222] Removed widget: Under Construction gfx GL4
[t=00:06:59.912000][f=0012244] Error in Shutdown()
[t=00:06:59.912000][f=0012244] Error in Shutdown(): [string "LuaUI/Widgets/Include/instancevboidtable.lu..."]:319: table index is nil
[t=00:06:59.912000][f=0012244] Removed widget: Highlight Selected Units GL4
[t=00:06:59.912000][f=0012244] Error in Update(): [LuaVAOImpl::RemoveFromSubmission] wrong submitCmds index [3]
[t=00:06:59.912000][f=0012244] Removed widget: Highlight Selected Units GL4

**Comment by SethDGamre** [comment]
this appears very old with no recreation steps and nobody referencing it as a persistent issue. Close until it resurfaces?
