### ISSUE TITLE
Chicken_spawner_defense table index is nil

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#826]
Warning: [LuaHandle::XCall] tried to cross-call unlinked Script.LuaUI.ChickenEvent()
Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/chicken_spawner_defense.lu..."]:1194: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/chicken_spawner_defense.lu..."]:1194: in function 'updateSpawnQueen'
	[string "LuaRules/Gadgets/chicken_spawner_defense.lu..."]:1483: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:858: in function <[string "LuaRules/gadgets.lua"]:856>
	(tail call): ?
	
It's was scavs and raptors match

**Comment by Damgam** [comment]
Chicken UI and Scav UI clashing with each other?
Could be the case if i forgot to cut off or rename something on scav version.

**Comment by Ruwetuin** [comment]
i assume this has been dealt with by now
