### ISSUE TITLE
Aggravator wreckage offset

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#828]
![Снимок](https://user-images.githubusercontent.com/89547444/155172591-6a2f6fd9-7988-4a3b-984e-ce09de3d7abd.JPG)

**Comment by Ruwetuin** [comment]
this end up like this because when it dies, its death animation makes it fall forward.

i cant think of how to correct it easily

**Comment by SethDGamre** [comment]
still an issue.

Fixing this would require changing the origin point around which the unit collapses in the death animation. Doesn't seem fun to me.

**Comment by SethDGamre** [comment]
being that this has been around for 3 years with 0 interest, I'll call this "good enough leave as is". Will re-open issue if anybody expresses interest in working on it
