### ISSUE TITLE
Thug wreckage offset

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#829]
![Снимок2](https://user-images.githubusercontent.com/89547444/155172650-d0b7e6e6-7e1d-4e34-bddb-b9457be45bef.JPG)

**Comment by simeonpfeiffer** [comment]
Seems like the widget Health Bars GL4 does not consider 3d objects that are off center. Centering the 3d object is not as simple as it sounds, because then the death animation wouldn't fit. A different death animation would require changes to the 3d object.
