### ISSUE TITLE
Marader wreckage offset

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#831]
![Снимок](https://user-images.githubusercontent.com/89547444/155192295-72b1fa1c-a5d6-4e94-b1c8-8f797fb34e98.JPG)

https://youtu.be/wGYjdTKctuA

**Comment by 6AKU66** [comment]
Here problem may be different:
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/833
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/832
Since when i'm trying ressurect it nanoparticles seems not offsetted.

**Comment by Beherith** [comment]
fixed this one
