### ISSUE TITLE
Duck unit don't have proper wreckage

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#832]
Duck unit upon destroy leaving derbis (name wreckage) only.
![Duck wreckage mp4_snapshot_00 04_ 2022 02 22_21 10 59](https://user-images.githubusercontent.com/89547444/155193320-f75b305d-6410-4fac-b3c5-95f75c683ee9.jpg)

https://www.youtube.com/watch?v=2V-mcQiaeQk

**Comment by 6AKU66** [comment]
Rename to heaps for avoid confusion?

**Comment by Beherith** [comment]
I think the 'heap'/'wreck' automatically gets appended to the names

**Comment by sprunk** [comment]
Make the automated system detect that this is a heap (no wreck level below it, not rezzable) and call it appropriately

**Comment by WatchTheFort** [comment]
Doing the wreck/heap names was such a headache, because there is nothing in the code that makes something a wreck vs. a heap. The logic is that progressively killing a unit goes unit -> wreck -> heap, but this is just a convention.

@Beherith Are you sure this was done intentionally for balance reasons, and wasn't just an oversight?

**Comment by Beherith** [comment]
Im 100% this is a leftover 'balance' reason from BA, but I have no attachment to it. @Ruwetuin what do you think ?  @Zecrus2  too?

**Comment by Zecrus2** [comment]
I know that a few units intentionally don't leave wrecks (decoy comm, commando, crawling bombs, spies, pyros), but I can't think of any reason why duck would be on that list.

**Comment by Ruwetuin** [comment]
Me neither

**Comment by Beherith** [comment]
> I know that a few units intentionally don't leave wrecks (decoy comm, commando, crawling bombs, spies, pyros), but I can't think of any reason why duck would be on that list.  

Why pyros though?

**Comment by Zecrus2** [comment]
Same reason as crawling bombs, it explodes on death so the wreck isn't intact.

**Comment by WatchTheFort** [comment]
I'll need to implement an alternate solution to assign wreckage vs heap names for units, it looks like I can use the `category` tag inside the feature def.

**Comment by WatchTheFort** [comment]
This is a bit more complicated than anticipated, as `category` is not present in the featuredef at the time captions are loaded.
