### ISSUE TITLE
Fiend unit don't have proper wreckage

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#833]
Fiend unit upon destroy leaving derbis (name wreckage) only.
![Fiend wreckage mp4_snapshot_00 04_ 2022 02 22_21 10 51](https://user-images.githubusercontent.com/89547444/155193521-12e42815-962f-41bc-9f46-9abdb0b34543.jpg)

https://www.youtube.com/watch?v=Q8aZgsXXw98

**Comment by Beherith** [comment]
fixed, thx

**Comment by Beherith** [comment]
reopen, wrong ticket closed:
pyro's wreck is actually not resurrectable (heap only)

**Comment by SethDGamre** [comment]
Fiend will never have a corpse and isn't intended to leave behind any scrap anyways. Closing this as unplanned.
