### ISSUE TITLE
Self-D all units in shared control resigning all players/bots

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#835]
https://youtu.be/FxikyIL4n_8

[t=00:00:59.359000][f=0000541] Wasp has bowed out
[t=00:00:59.363000][f=0000541] [EOH::DestroySkirmishAI(id=0)]
[t=00:00:59.415000][f=0000541] [Game::ClientReadNet] local skirmish AI "bot5" (ID: 0) being removed from team 0

**Comment by badosu** [comment]
This is not a bug, it's intended behavior.

If intended behavior is not the correct behavior is a separate matter perhaps.

Can be closed.

**Comment by 6AKU66** [comment]
If players have shared control it's resign all players

**Comment by badosu** [comment]
I see, what is suggested behavior?

**Comment by 6AKU66** [comment]
@badosu Resign only the player that commanded self-D to all units, but not whole team that have shared control.

**Comment by SethDGamre** [comment]
Now we have a resign button for when the game is ongoing. Self-destructing your units is discouraged, even though there is a gadget if I remember right that catches a self-destruct order of all your units and instead resigns.

Shared unit control has been talked about but currently is not a planned feature. Given the lack of interest, and the age of this issue I'm going to close it as unplanned
