### ISSUE TITLE
Only Top-right quadrant of minimap works

### ISSUE THREAD

**Issue by hoijui** [beyond-all-reason/Beyond-All-Reason#838]
![2022-02-26-12-26-33-area](https://user-images.githubusercontent.com/42907/155841535-1485bdba-db2b-4b93-b366-435033906b8c.png)

```
[t=00:00:00.005504]   Spring Engine Version: 105.1.1-861-ge8bf8a9 BAR105
[t=00:00:00.005510]       Build Environment: gcc libstdc++ version 20210408
[t=00:00:00.005515]        Compiler Version: gcc-10.3.0
[t=00:00:00.005522]        Operating System: Linux 5.15.0-3-amd64 #1 SMP Debian 5.15.15-2 (2022-01-30) (x86_64)
[t=00:00:00.022169]         Hardware Config: AMD Ryzen 5 PRO 4650U with Radeon Graphics; 23326MB RAM
[t=00:00:00.022201]        Binary Word Size: 64-bit (native)
[t=00:00:00.022214]           Process Clock: std::chrono::high_resolution_clock
[t=00:00:00.022226]      Physical CPU Cores: 6
[t=00:00:00.022241]       Logical CPU Cores: 12
```

**Comment by 6AKU66** [comment]
It's fixed in not released engine update

**Comment by 6AKU66** [comment]
@badosu True?

**Comment by badosu** [comment]
Yes, fixed in next engine release by https://github.com/beyond-all-reason/spring/commit/a12f8b02c6f29559282883456d6f5dd61a69804c

**Comment by badosu** [comment]
Also, nice i3/sway :-)

**Comment by hoijui** [comment]
wow, that was a fast response... thank you guys! :-)

(@badosu good catch! :D it is `xmonad`... basically the same)

**Comment by badosu** [comment]
> (@badosu good catch! :D it is xmonad... basically the same)

Hah, I deleted my comment cause it was not relevant. xmonad was my second tiling wm after ratpoison, the best multimonitor experience I had to this date
