### ISSUE TITLE
Game freezing on fedora 34

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [beyond-all-reason/Beyond-All-Reason#856]
As soon as I click the big green start button (in the menu, not the launcher) the whole game just freezes. I was able to replicate this issue twice.

I have an NVIDIA GT 730M on a Lenovo thinkpad t540p

nouveau drivers

edit:-installed through flatpak

**Comment by Beherith** [comment]
Can I see a full infolog.txt please?
