### ISSUE TITLE
air units self D has counter stuck at 1 when turned into wreck

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/Beyond-All-Reason#873]
![screen00050](https://user-images.githubusercontent.com/75929927/159461945-95d6e3e3-0e74-454f-b72f-08e6f97a40e0.jpg)
![screen00047](https://user-images.githubusercontent.com/75929927/159461952-7b2cc390-37f5-4a0c-bfc3-447518f90726.jpg)
![screen00048](https://user-images.githubusercontent.com/75929927/159461955-33e790d0-353c-42f1-97fd-e908cec126bf.jpg)
![screen00049](https://user-images.githubusercontent.com/75929927/159461960-3e48d45c-7610-41db-ae14-c859ce5d9d0c.jpg)

**Comment by 6AKU66** [comment]
Also control group number still showed when air unit is dying. 
And if someone guard dying unit it's following that dying unit.

**Comment by Ruwetuin** [comment]
fixed both selfd/group# cases in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/1210888b54e1d80aea55a8153b0c0403b09cbf4b
