### ISSUE TITLE
means to see reclaim on the map with a button press

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/Beyond-All-Reason#890]
relevant discord thread
https://discord.com/channels/549281623154229250/959520949005320214/959520950729183252

**Comment by SethDGamre** [comment]
broken link, old, still an issue?

**Comment by SethDGamre** [comment]
ahh, archeologist role. 
This appears to be resolved with reclaim field highlight widget. I'd say this issue is resolved.

**Comment by drivver44** [comment]
this issue has been resolved since the reclaim field widget has been added to the base game of bar
