### ISSUE TITLE
Multiple Tactical Missiles will deform the ground, getting units stuck (see gif)

### ISSUE THREAD

**Issue by Randiom** [beyond-all-reason/Beyond-All-Reason#896]
In this example, 16 tactical missile launchers where used:
https://gyazo.com/a81b3307008b52f9eb8f778b4caa7048

Just seems wierd as there where the most expensive experimental Juggernauts, and they got stuck in place after getting hit

**Comment by Beherith** [comment]
Yep, pretty much par for the course, you can nuke holes and craters in BAR (constructors can restore terrain quickly though)
