### ISSUE TITLE
GameInfo: Issue with missing translation 

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#902]
```
[t=00:40:20.337503][f=0065504] Error in Update(): [string "LuaUI/Widgets/gui_info.lua"]:1516: attempt to concatenate local 'newTooltip' (a nil value)
[t=00:40:20.337528][f=0065504] Removed widget: Info
```

Happens here: https://github.com/badosu/Beyond-All-Reason/blob/fd10d2f20866873f6675f1b1a01fabeb5db4e3fb/luaui/Widgets/gui_info.lua#L1509

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f309d0b0b20b594c3485dbf79c084363674f2931

**Comment by WatchTheFort** [comment]
@badosu Which unit's wreck/heap were you mousing over when this happened? I thought I caught all the unitdefs whose features were missing `category` tags, but it looks like I missed one.

**Comment by badosu** [comment]
@WatchTheFort Don't remember to be honest
