### ISSUE TITLE
Hotkeys Fix buildfacing

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/Beyond-All-Reason#921]
These buildfacing bindings dont work because they are shaded by other commands.
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/b5b5c42efae8e756f705013d9494971cfab02119/luaui/Widgets/cmd_bar_hotkeys.lua#L335-L338
Delete these bindings:
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/b5b5c42efae8e756f705013d9494971cfab02119/luaui/Widgets/cmd_bar_hotkeys.lua#L69-L72

**Comment by badosu** [comment]
Fixed on https://github.com/beyond-all-reason/Beyond-All-Reason/pull/932
