### ISSUE TITLE
Unit build drag tolerance 

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#925]
When placing units to build in a queue (with shift held), it's super easy to accidentally drag multiple of a unit when only 1 was desired. This is especially problematic with units like LLT and mexes and is common to see happen:

![image](https://user-images.githubusercontent.com/1434248/162620052-bf9b16a6-8754-4052-8799-7ab9908588fe.png)

Maybe some minimum drag tolerance threshold could alleviate this?

**Comment by lolsteamroller** [comment]
I don't think this is issue, @Jazcash adjust your LTT spacing for cases where you would actually drag the ltts (you would never build ltt's with no gap). 

If you change drag tolerance, then it will likely introduce delay for cases when you actually want to quickly place some buildings.
