### ISSUE TITLE
Building Prefab Templates for BAR

### ISSUE THREAD

**Issue by LordSolaireAstora** [beyond-all-reason/Beyond-All-Reason#934]
So basically anyone who has played supcom FA will know exactly what im referring to. Having the ability to save build templates for your commander/engineer will help improve the pace at which a base/defenses can be set up. I know I am not the only one who is playing the game and as they continue to capture more ground or at the start of the game need to quickly set up a defensive line to hold the sector or quickly setup a new base.

With building templates, this will allow you to save a select amount of structures under a single tab, with the last selected structure being the picture for the building template. After you save said templates, this will allow you to quickly select an engineer either T1 or T2 and then click into the building template tab and select the template you quickly want to build. You can then place said template down where you want it and the engineer will move to build all buildings in said template.

This of course will save you precious time whilst playing the game for you will no longer have to spend time cycling through all the structures you want to build and manually placing them for any given moment as long as you have the template you want to build saved.

**Comment by icexuick** [comment]
Quick answer:
Has been talked about between various people.
Likely will not get in any time soon.

**Comment by SethDGamre** [comment]
This has been implemented in the blueprints feature
