### ISSUE TITLE
No Commander Appears

### ISSUE THREAD

**Issue by JayRugMan** [beyond-all-reason/Beyond-All-Reason#935]
When I start the game, select a location, and click "Ready," it appears as though the game has started, but my commander does not appear. I know the game is not frozen because I can click, move the screen, and zoom. I've restarted the game a few times and the issue repeats. This happens in multi and single player. In multiplayer, other player have no issue and even see my commander sitting idle in the spot I selected before clicking ready, but I still don't see it and cannot control it. 

Here are my specs:
OS: Linux Mint 20.1 x86_64 
Host: Inspiron 3521 A11 
Kernel: 5.4.0-107-generic 
Packages: 2664 (dpkg), 6 (flatpak) 
Shell: bash 5.0.17 
Resolution: 1366x768 
CPU: Intel i3-3227U (4) @ 1.900GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller
Memory: 7375MiB / 11849MiB 

I have BAR installed with flatpak - which installed with no issues. 

Let me know which log(s) is/are useful and I'll upload them.

**Comment by Ruwetuin** [comment]
GPU: Intel 3rd Gen Core processor Graphics Controller
thats the problem, even if we get it to work, the experience would be too horrible to enjoy.

**Comment by Beherith** [comment]
Does this issue still show up?

**Comment by JayRugMan** [comment]
Yup. But it's the computer, so we use a different computer.

**Comment by cdplayer** [comment]
Having same issue. Select zone and begin. Commander does not 'teleport' into the spot in the starting zone you selected. The game ticks over, but you do not have any real interaction as nothing to select. The number of commanders in icon at top, is faded as it knows there are zero.

**Comment by Damgam** [comment]
@cdplayer logs! :D

**Comment by cdplayer** [comment]
[Sat Jun 11 2022 15:38:28 GMT+1000 (Australian Eastern Standard Time) info] User wants to upload?  Yes (Upload)

[Sat Jun 11 2022 15:38:28 GMT+1000 (Australian Eastern Standard Time) info] Uploading...

[Sat Jun 11 2022 15:38:29 GMT+1000 (Australian Eastern Standard Time) error] Failed to upload log, copy and upload the log manually.
Reason: HTTPError: Response code 503 (Service Unavailable).

[Sat Jun 11 2022 15:38:29 GMT+1000 (Australian Eastern Standard Time) error] HTTPError: Response code 503 (Service Unavailable)
    at Request.<anonymous> (/app/main/resources/app.asar/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Damgam** [comment]
lol.
in "log" folder you have infologs
send one created when your commander did not appear

**Comment by cdplayer** [comment]
Resolved by doing update of the launcher itself (ie not the update listed in game panel).
For me the launcher was a flatpak installation on linux where auto updating was not active. Corrected by manual running
```
flatpak update
```
Suggest there be a way of seeing if your 'launcher' is out of date.
