### ISSUE TITLE
god mode selection issue

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/Beyond-All-Reason#938]
![screen00110](https://user-images.githubusercontent.com/75929927/164215507-e330c3b0-d31c-4c5a-89b0-794eb4c1dff8.jpg)

this is done with the reclaim widget that lexon made but its not the widget afaict as ive turned it off and this still pops up

## replication ##
1. zoom out far and turn on god mode
2. with builders as separate selection option on

when attempting to select the commander the game will refuse to select the commander with box select

**Comment by drivver44** [comment]
forgot to add 
this issue pops up at certain levels of zoom

**Comment by WatchTheFort** [comment]
Godmode causes box select to fail when there is a critter inside the selection box

**Comment by Ruwetuin** [comment]
fixed in: https://github.com/beyond-all-reason/Beyond-All-Reason/commit/f77b456591788dd25334ddfab762f6ac7f07692d
