### ISSUE TITLE
 Incomplete display of Chinese characters

### ISSUE THREAD

**Issue by overtimemaster** [beyond-all-reason/Beyond-All-Reason#940]
when screen resolution is 1920x1080 , everything is ok. but when screen resolution is biger ,like 3840x2160, Chinese characters display incomplete.
this is 1920x1080
![1920x1080](https://user-images.githubusercontent.com/100030220/164265712-c136b9ed-8752-4a51-809e-48954d83791c.png)

and this is 3840x2160
![3840x2160](https://user-images.githubusercontent.com/100030220/164265726-87084a3b-eabf-4ed4-9655-8cdef2dad167.png)

**Comment by WatchTheFort** [comment]
The engine pre-renders all font glyphs into an 8,000px×8,000px texture, so if the letter A is needed in three different sizes, there will be three A's in the texture. It looks like what is happening is that at larger resolutions, the texture is running out of room for all the required glyphs.

@lhog Does my hypothesis look correct?

**Comment by lhog** [comment]
It could be the case. IIRC the fonts texture is significantly smaller than 8k x 8k.
@overtimemaster will need infolog.txt when after this has happened.

**Comment by Beherith** [comment]
I dont know how many glyphs there are in the chinese language, but im pretty sure there are more than fits the atlas.

**Comment by overtimemaster** [comment]
> It could be the case. IIRC the fonts texture is significantly smaller than 8k x 8k. @overtimemaster will need infolog.txt when after this has happened.

here is infolog.txt
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8531630/infolog.txt)

**Comment by lhog** [comment]
Indeed:
```
[t=00:02:16.829602][f=-000001] [Font] [LoadCustomFonts] loaded fonts "Exo2-SemiBold.otf" and "Exo2-SemiBold.otf"
[t=00:02:16.927217][f=-000001] [Font] Warning: Texture limit reached! (try to reduce the font size and/or outlinewidth)
[t=00:02:17.246451][f=-000001] [~ScopedOnceTimer][EventHandler::ViewResize] 578ms
```

So yeah it doesn't fit into the atlas.

I'm not at the PC capable of running spring engine to check the actual limits, but from the code it looks like it's 2k by 2k. We can probably bump this value to `MaxTextureAtlasSizeX`/`MaxTextureAtlasSizeY`, which are 8192 currently.

**Comment by WatchTheFort** [comment]
I'm not sure even an 8k atlas will handle all characters in an Asian language. Does chat use the font atlas?

**Comment by overtimemaster** [comment]
> I'm not at the PC capable of running spring engine to check the actual limits, but from the code it looks like it's 2k by 2k. We can probably bump this value to `MaxTextureAtlasSizeX`/`MaxTextureAtlasSizeY`, which are 8192 currently.

When I chat with chinese in lobby , All Chinese characters can be displayed completely.

**Comment by lhog** [comment]
Each font has its own atlas to store all glyphs ever requested to be drawn with this font.
Chat font could use smaller font size or less amount of glyphs so they all fit.

**Comment by overtimemaster** [comment]
@lhog Thank you, I know the cause of this bug now,Should I close this issues and wait for someone fix this?

**Comment by lhog** [comment]
Your issue is legit no need to close it.
I'm quite constrained in what I can do a.t.m, otherwise I'd release you a binary with possible fix to see how it goes.
In any case if you use Discord go to BAR server #engine section and tag me there(I go by ivand nickname), I'll see what I can do.

**Comment by overtimemaster** [comment]
@lhog thank you ,I will contact you with Discord when I have problem in the future.

**Comment by lhog** [comment]
I've committed a tentative fix to the engine: https://github.com/beyond-all-reason/spring/commit/74a989328f5f185b4499df4fc1d7963f46f6a2fa

The most easy way is to wait until new engine is deployed. The cadence used to be every couple of weeks, but now you'll probably need to wait a bit more.

**Comment by overtimemaster** [comment]
> I've committed a tentative fix to the engine: [beyond-all-reason/spring@74a9893](https://github.com/beyond-all-reason/spring/commit/74a989328f5f185b4499df4fc1d7963f46f6a2fa)
> 
> The most easiest way is to wait until new engine is deployed. The cadence used to be every couple of weeks, but now you'll probably need to wait a bit more.

Thank you , I will wait .no need to rush. @lhog

**Comment by SethDGamre** [comment]
> I've committed a tentative fix to the engine: [beyond-all-reason/spring@74a9893](https://github.com/beyond-all-reason/spring/commit/74a989328f5f185b4499df4fc1d7963f46f6a2fa)
> 
> The most easiest way is to wait until new engine is deployed. The cadence used to be every couple of weeks, but now you'll probably need to wait a bit more.

Are you happy closing this thread as resolved?

**Comment by SethDGamre** [comment]
@lhog

**Comment by lhog** [comment]
For some reason the commit I referenced is no longer in the git's history. Let's hope it did the trick.
