### ISSUE TITLE
Flatpak using Nvidia 510 driver

### ISSUE THREAD

**Issue by FelixTheTBone** [beyond-all-reason/Beyond-All-Reason#943]
Hello there, I hope this is the right place:

I noticed when using Flatseal to offload BAR to my Nvidia GPU, the updater starts, but doesn't render.
This does not change even when waiting for a long time, so I can currently only use my Intel GPU.

If it helps, here is what I used for Flatseal Variables:
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia

Let me know if you need more relevant system info:
5.17 Kernel, X11, GTX 1650 Ti mobile and Nvidia 510.60.02 driver

Cheers

**Comment by hollowaykeanho** [comment]
Same case with AppImage.

System:
5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux

**Comment by A-childs-encyclopedia** [comment]
logs

**Comment by Beherith** [comment]
Yes,please post your data/infolog.txt after an error

**Comment by hollowaykeanho** [comment]
@A-childs-encyclopedia , ahh, to whom you're requesting or should I open a new issue? Issue topic is flatpak.

@Beherith , sure, let gather the data and upload here once the question above.

**Comment by Hi-Timofey** [comment]
Same of Manjaro linux 
System:
Linux 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11  x86_64 GNU/Linux
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9414386/infolog.txt)
I have hybrid system with both intel and nvidia mx150 gpu. Same issue with render while using optimus. And working ok with Intel gpu

**Comment by p2004a** [comment]
I believe this is obsolete, please comment if that's not the case

**Comment by curt-wise** [comment]
> I could not run it with the nvidia drivers until I tried running the executable directly with the env variables set:
> 
> ```shell
> __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia  /home/larionov/.var/app/info.beyondallreason.bar/data/engine/105.1.1-1767-gaaf2cc3\ bar/spring --write-dir /home/larionov/.var/app/info.beyondallreason.bar/data --isolation --menu rapid://byar-chobby:test
> ```
> 
> But now it runs correctly on the nvidia.

This is a real pain

**Comment by curt-wise** [comment]
> Same of Manjaro linux System: Linux 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 x86_64 GNU/Linux [infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/9414386/infolog.txt) I have hybrid system with both intel and nvidia mx150 gpu. Same issue with render while using optimus. And working ok with Intel gpu

Me 2 i am using Manjaro and having several problems including low FPS with Veloren and Airshipper not running at all.
