### ISSUE TITLE
ships being unable to move

### ISSUE THREAD

**Issue by ancientCabbage** [beyond-all-reason/Beyond-All-Reason#947]
How to reproduce:
- start a game
- save the game
- load the game
- build a shipyard and watch how the build ship will be unable to move out of the factory

Tested on:
engineVersion: 105.1.1-902-g34d2eb7 BAR105
gameVersion: test-19652-f2ce731
OS: Archlinux 64bit & Windows10 64bit

This is a bug, that happened to me multiple times while playing (offline). The state of the game appears to get corrupted upon loading a savegame, which causes all ships being unable to move. Movement orders get canceled. Entering traverse-ability mode with F2 reveals that all water has become non-traversable for all ships. Seems to me like the state of the map/terrain gets corrupted. This happened on various maps.

Corrupted save example:
[savefile.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/8564519/savefile.zip)

**Comment by Beherith** [comment]
Maybe @ashdnazg knows more?

**Comment by Beherith** [comment]
Were you using any custom waterlevel settings in these games?

**Comment by ancientCabbage** [comment]
> Were you using any custom waterlevel settings in these games?

Nope, I remember this happening on the following maps:
- Quicksilver Remake 1.24
- Neurope a7 v3 (from the Wolrd War XXV scenario)
- Supreme Crossing V1 (not 100% sure about this one)

**Comment by ashdnazg** [comment]
did it always happen after loading a saved game?

**Comment by ancientCabbage** [comment]
> did it always happen after loading a saved game?

No, it just happens while playing, saving/loading does neither cause not solve the issue. I frequently use pause/unpause and the occasional alt+tab, but I can't say if any of this causes it because I don't necessarily notice the bug immediately.

**Comment by ancientCabbage** [comment]
Ok, I just did some more testing. It indeed only seems to happen after loading a safegame(at least in the newest version, i could swear this was not the case previously). Tested on Windows (different drive, otherwise same hardware) too, same thing. Updated the main post.

**Comment by Beherith** [comment]
Could you please verify that this is indeed fixed with the latest engine updates?

**Comment by ancientCabbage** [comment]
> Could you please verify that this is indeed fixed with the latest engine updates?

Will check this weekend

**Comment by ancientCabbage** [comment]
Looks fixed to me 👍
