### ISSUE TITLE
Mouse doesn't work properly after toggling Fullscreen mode

### ISSUE THREAD

**Issue by RedOrbTalon** [beyond-all-reason/Beyond-All-Reason#960]
To reproduce the issue: Use Alt+Backspace to change the game from borderless (where the Windows taskbar is visible on the bottom of the screen) to fullscreen. The mouse disappears, and moving the mouse moves the camera. It behaves very similar to a first-person shooter; the mouse isn't visible but it's still used.

**Comment by SethDGamre** [comment]
looks like this is no longer the case
