### ISSUE TITLE
Explosion ground scar visual glitch

### ISSUE THREAD

**Issue by MasterBel2** [beyond-all-reason/Beyond-All-Reason#971]
![screen00273](https://user-images.githubusercontent.com/39206414/169072455-be613467-ff20-4d32-9e37-23fd87c35bbf.jpg)

Steps to reproduce: 
Self-destruct corsktl on Quicksilver, zoom in on the ground scar

**Comment by lhog** [comment]
Yep it is a known issue, it is ticketed somewhere as well.
