### ISSUE TITLE
Dying air constructor keep building while body exist

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#975]
![изображение_2022-05-21_154554](https://user-images.githubusercontent.com/89547444/169652076-496758b9-8306-4271-8d34-1861f1b1c59d.png)

https://youtu.be/AqHSHadRAzM

**Comment by MasterBel2** [comment]
Should this be addressed engine-side or lua-side?

**Comment by MasterBel2** [comment]
Construction continuing, as far as I can tell. Had to watch the video a few times to be sure.

**Comment by 6AKU66** [comment]
> progressing

actually progressing

**Comment by sprunk** [comment]
Fix this Lua-side, or at least keep this available as an option if going via the engine, because ZK wants some dying gunships to keep active while falling unless explicitly disabled.

**Comment by Ruwetuin** [comment]
probably fixed by adding a stop command in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/eeed1ec95534a6e27db83e3fb22b4d982cdaff9f
