### ISSUE TITLE
Weapon range is not shown for units in factories

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#976]
![screen00501](https://user-images.githubusercontent.com/89547444/169653090-77a27b60-199e-4780-9d0c-2814663d477c.jpg)
![screen00502](https://user-images.githubusercontent.com/89547444/169653093-6c3e156d-0da7-4159-abf3-891a62ffb4d7.jpg)

**Comment by Beherith** [comment]
Ty MasterBel!

**Comment by 6AKU66** [comment]
Range in factories still not shown for units

**Comment by 6AKU66** [comment]
@Beherith
