### ISSUE TITLE
Dragon unit leaving yellow occupated spots in placement grid

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#977]
![изображение_2022-05-21_162839](https://user-images.githubusercontent.com/89547444/169653821-2d1b3406-9525-458a-ad75-30141108f28f.png)
https://youtu.be/ggzs6-An5Yk

It's floating bug. I'm not sure exact steps for reproduce.

**Comment by MasterBel2** [comment]
if can't reproduce, replay file would be a great help

**Comment by SethDGamre** [comment]
I was unable to reproduce this issue either.
