### ISSUE TITLE
UI display wrong state of parameters for some buttons

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#978]
![изображение_2022-05-21_163844](https://user-images.githubusercontent.com/89547444/169654228-f424bec2-5a15-411b-bbe5-cad3f2e53876.png)
![Снимок](https://user-images.githubusercontent.com/89547444/169654231-13cd7c82-551e-4a83-af41-7ad791b1bcc4.PNG)

https://www.youtube.com/watch?v=aaq84g9nbkY

Looks like states changed via hotkeys avoid this bug

**Comment by Ruwetuin** [comment]
fixed the lag for most state toggles... https://github.com/beyond-all-reason/Beyond-All-Reason/commit/3cfb9a36d57267ec0bf9a3a1e01d0f6e368762f1

I couldnt manage to fix the On/Off toggle being there for unfinished buildings. The engine just provides the commands, its just that the on/off cmd doesnt work for unfinished buildings.

**Comment by Ruwetuin** [comment]
Submitted an issue at the engine repo that links to this issue here
https://github.com/beyond-all-reason/spring/issues/307

**Comment by SethDGamre** [comment]
Looks like the fix for this is engine side, and there is an open issue there for it.
