### ISSUE TITLE
Sound and music sliders is not easy accessible in some conditions

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#979]
Steps:
1. Start game via chobby
2. Go to skirmish and start game without bots and without being log-in
3. Sound and music sliders have offseted clickbox

https://youtu.be/64ct-qRRz0U

**Comment by MasterBel2** [comment]
This appears to be the case ONLY if the advplayerlist is ONLY showing the player; no ais and no empty "enemies" team (as AKU described :joy: )
Making this note because it took me hours to realise. :facepalm:

**Comment by MasterBel2** [comment]
So likely what's happening is that advplayerlist is eating the keypresses

**Comment by Beherith** [comment]
Ty Bel!
