### ISSUE TITLE
Weapon range for some units don't give any useful information for players

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#981]
For units like anti-nuke, nuclear missle silo, juno better be use coverage parameter instead.
![Снимок2](https://user-images.githubusercontent.com/89547444/169657320-d780a0e8-c320-4adf-9fa7-c480eb3ed4af.PNG)
![Снимок](https://user-images.githubusercontent.com/89547444/169657318-b724a0b5-9e92-4508-aa2c-2a83bcb0d918.PNG)

**Comment by MasterBel2** [comment]
Seems the `coverage` attribute isn't exposed to Lua.

**Comment by MasterBel2** [comment]
Okay, I was mistaken. Fix should be on its way.

**Comment by Ruwetuin** [comment]
implemented as such in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/cfb7738fea59e7981b35e4f0a92a0e5a8caebcd1
