### ISSUE TITLE
Music is not playing in pre-game stage

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#985]
1. Set music in game 49%, close game
2. Start game again, in pre-game there's no will be music because game time is not flow.
https://youtu.be/VeareMpdVVc

**Comment by 6AKU66** [comment]
In pre-game stage seems yes. But also music refuse to play when i pause the game (by entering in menu) and disable and enable OST: then it's only start when i unpause the game.

**Comment by Damgam** [comment]
Ok i'll take a look, thanks. :)

**Comment by Damgam** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/e72ca8ceb993a1ee8a54664d6cbaa2f36205db6a
That seems to be fixing it.
