### ISSUE TITLE
Resource bar can go out of scale

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#986]
It's happening when you overflow resourse while losing storage
https://youtu.be/qqWs1903p6g
![изображение_2022-05-24_201442](https://user-images.githubusercontent.com/89547444/170094067-38e52c7b-e010-4e31-8c57-476629db9fac.png)

**Comment by MasterBel2** [comment]
Could you provide a replay file to test with? I seem to be unable to replicate this one.

**Comment by Ruwetuin** [comment]
fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/b98e498ed793f2fc74075a5f248f3cd576165405
