### ISSUE TITLE
Wasting energy/metal sign blocking values

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#990]
![Снимок](https://user-images.githubusercontent.com/89547444/170291880-8d5b50a6-77b0-48f9-8a6a-9dbf90993ad3.PNG)

**Comment by Ruwetuin** [comment]
i didnt see this as a real issue, you are at max storage capacity and your current value represents that too. All you need to know is that you either need to spend real quick or make additional storage

**Comment by 6AKU66** [comment]
> i didnt see this as a real issue, you are at max storage capacity and your current value represents that too.
Yeah, i agree.
