### ISSUE TITLE
Fade in effect apply to music track when game have been started

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#993]
Fade in effect apply to music track when game (exited pre-game stage) have been started
https://youtu.be/l35gb2QBOUc

**Comment by Damgam** [comment]
Thanks for report. Indeed, it's broken.

**Comment by 6AKU66** [comment]
> Thanks for report. Indeed, it's broken.

You're welcome, here additional report for you #994!

**Comment by MasterBel2** [comment]
@6AKU66 ty for the report, I've found a fix and it's just waiting on review / final code cleanup :) (#1035)

**Comment by Ruwetuin** [comment]
seems fixed
