### ISSUE TITLE
SimpleDefender does nothing on a Watermap ? Update : is it a problem with Nine Island map?

### ISSUE THREAD

**Issue by Averellx** [beyond-all-reason/Beyond-All-Reason#995]
Hi Team,

I was playing a single skirmish against a SimpleDefender AI.
The map was : Nine Island Metal

And AI did nothing. Is that foreseen? 

Kind Regards,
Damien

**Comment by Averellx** [comment]
Hi, 

Additional info : 

Looks like it is not limited to SimpleDefender AI but also for Simple AI and SimpleCheater AI

This might be usefull as well : 

STAI looks to do something (I disabled fog of war and I can see something). However, as a player the first click leads to a crash. 
I sent the logs :  https://bar-infologs.s3.amazonaws.com/spring-launcher_1653819229410.log

Will try to reproduce it on another map ;)

Kind Regards, 
Damien

**Comment by Averellx** [comment]
I confirm that all simple AI looks inactive on this map STAI is playing. (I used spectator mode to see it)

**Comment by Damgam** [comment]
SimpleAI requires metal spots to function. So yea. It doesn't work on metal or metalless maps
